### ISSUE TITLE
Make props async and add ability to pass function to props()

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1000]
Currently props is synchronous but it'd be good if it had the same semantics as setting props normally and allowed a function to be passed to it so that you could calculate your next set of props from the previous one in a predictable manner, like in React.

The previous prop values are recorded using a symbol, so those props can be retrieved and passed into the user-defined function as the previous props.

See https://medium.com/@shopsifter/using-a-function-in-setstate-instead-of-an-object-1f5cfd6e55d1#.bfgyrbjud for more information for those who may not be aware of the pitfalls of async rendering and calculate next props.

**Comment by Hotell** [comment]
Why is this needed? I mean setState in React is async, props() in skate is not AFAIK?

**Comment by treshugart** [comment]
@Hotell updated the issue.

Setting props normally is async and `props()` is sync. So we have this problem (with no way to get the previous props) when setting properties normally, forcing the component author to have to render sync, which isn't ideal if you have multiple calls to it. Additionally, I think it'd be better for them to have the same semantics, thus needing a standard way to retrieve the previous state.

**Comment by Hotell** [comment]
thanks for clarification. yup totally makes sense 🍺

**Comment by alexlafroscia** [comment]
Is the plan to support either an object _or_ a function? Or only a function?

**Comment by treshugart** [comment]
The PR changed quite a bit. In retrospect, there's no foreseeable reason to support a function as property values reflect immediately, renders are queued. So no need for a function. There's now a `props` getter / setter. See the PR for more details.
