### ISSUE TITLE
Question: use pragma h vs. prefix vdom 

### ISSUE THREAD

**Issue by andreawyss** [skatejs/skatejs#1001]
@treshugart code from ak-icon/src/icon.js:             
```
      <Root size={elem.size}>
            <Content>
                 <Glyph role="img" label={label} />
             </Content>
      </Root>
```
A) using babel-plugin-incremental-dom with prefix vdom the output is correct.
```
                        ['incremental-dom', {
                            components: true,
                            hoist: true,
                            prefix: 'vdom',
                        }],

      <div...>
         <span...>
             <svg... ></svg>
         </span> 
     </div>
 ```
b) using babel-plugin-transform-react-jsx with pragma h the output is not correctly nested.
```
                        ['transform-react-jsx',
                            {
                                pragma: 'h',
                            },
                        ],

      <svg... ></svg>
      <span... ></span>
      <div... ></div>
```
Is there a way to get this to work with option B?
Or when using components one needs to use the babel-plugin-incremental-dom?

**Comment by treshugart** [comment]
B should just work. See http://www.webpackbin.com/N18e21OHf. I think ak-icon might be built using the old vdom way.

**Comment by andreawyss** [comment]
B doesn't work. 
See: http://www.webpackbin.com/4kth22OSf

**Comment by treshugart** [comment]
When using `h`, you don't call `children` as a function. When using old `vdom`, you do. This is because calls to `h` return functions, whereas `vdom` calls incremental-dom directly. See: http://www.webpackbin.com/4y4aeL5Sf.

**Comment by andreawyss** [comment]
Thank you! 
That is something to be aware when converting code from vdom to h.
