### ISSUE TITLE
Add static "is" property to constructor instead of having to specify name to define()

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1004]
### Rationale

The purpose of the `define()` function is to add convenience on top of the native `customElements.define()` method. A common pattern, when defining a component, is to use a static `is` property to define the component:

```js
const MyElement extends HTMLElement {
  static is = 'my-element'
}

customElements.define(MyElement.is, MyElement);
```

To simplify this, we can use this property in `define()` automatically:

```js
const MyElement = define(class extends HTMLElement {
  static is = 'my-element';
});
```

*Note: you can pass a vanilla custom element to `define()`.*

#### Additional use case

Another use case for specifying an `is` attribute, that is somewhat orthogonal to using it in `define()`, is being able to consume a component that uses the property in other libraries. For example, React:

```js
const MyElement = skate.define(class extends HTMLElement {
  static is = 'my-element'
});

const MyReact = () => (
  <MyElement.is />
);
```

There is a [react integration library](https://github.com/webcomponents/react-integration) for this, but that might be overkill if you're not exporting the result of reactification. For example, a web component app that might use [react-storybook](https://github.com/storybooks/react-storybook) for developing its components.

### Behaviour

- It overrides the deprecated `name` argument.
- If `is` has already been registered, a unique name is generated, just as with the deprecated `name` argument.
- The `is` property should be set on the passed constructor so that can be made consistent with the name it was registered with

### Other changes

- The `name` argument to `define()` should be deprecated.
- Refactoring of deprecated calls to `define()` in tests.
- The vdom module should use `is` if it's available, but cache using the previously used `$name` symbol.

**Comment by Hotell** [comment]
I would rather say that common pattern is to use static is property `static get is()`. It makes it immutable, of course can be overwritten by Object.defineProperty but regular user won't easily mutate the is name by some mistake if it's just a getter

**Comment by treshugart** [comment]
@Hotell either one works, really. I think it'd be desirable for it to reflect the unique value, if generated. WDYT? For example, if someone specifies:

```js
class MyElement extends HTMLElement {
  static is = 'my-element'
}
```

But that is already registered, what should it do? Skate currently allows this to avoid naming conflicts between multiple versions. Global names is something a lot of people have been vocal against (a +1 for React et al).

What it does in this pr is try and set `is` to the unique value. It feels dirty, but I think it's more desirable to have it in sync than to not.

**Comment by Hotell** [comment]
yeah I understand your reasoning behind this ( I did review of PR you submitted ) but what about this situtation:

- I created a web-component ( let's say `sk-datepicker` )
- A consumer installs it from npm, and adds it to it's app (SPA, classic server rendered, whatever app ) like this ( according to that element docs) :
```html
<script src="node_modules/web-components/polyfill.min.js"></script>
<script src="node_modules/sk-datepicker/index.min.js"></script>
<form>
  <div>
   <label>When?</label>
   <sk-datepicker></sk-datepicker>
  </div>
  <button>call me</button>
</form>
```
- now I released a BC of that component. Consumer wants to use both version 1 and version 2. And now here comes the problem, because Skate will generate random unique name for the version 2, which the user is unable to determine and can't declaratively use within it's html because it could be `<sk-datepicker123></sk-datepicker123>`  or any other name
```html
<script src="node_modules/web-components/polyfill.min.js"></script>
<script src="node_modules/sk-datepicker/index.min.js"></script>
<script src="node_modules/sk-datepicker@2/index.min.js"></script>
<form>
  <div>
   <label>When?</label>
   <sk-datepicker></sk-datepicker>
  </div>
  <button>call me</button>
</form>
```

how can we solve this situation?

**Comment by treshugart** [comment]
@Hotell see the last suggestion on https://github.com/skatejs/skatejs/pull/1005#discussion_r95090174. I think this would be the ideal scenario (maybe) where you'd have to explicitly not pass any identifier for it to make the custom element autonomous. It'd still do what it normally did with the `name` argument, of course, but when that's removed, there's simpler semantics with the `static is` property.

**Comment by Hotell** [comment]
sounds good!
