### ISSUE TITLE
You should be able to return a string (or array of) from renderCallback()

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1011]
```js
renderCallback ({ name }) {
  return `Hello, ${name}!`;
}
```

Or

```js
renderCallback ({ name }) {
  return ['Hello', ' ', name, '!'];
}
```

**Comment by thepian** [comment]
or an array of strings?

**Comment by treshugart** [comment]
Yeah that'd be good, too. Cheers :)

**Comment by marcoms** [comment]
Is this to be used with incremental DOM? From the example there is only basic text content and no elements, so I'm unsure if this could be used with idom or without, since idom can't parse from a string but I suppose it could construct a basic `Text` node from the return value of `renderCallback`.

**Comment by treshugart** [comment]
Related to #811.

**Comment by treshugart** [comment]
This will be subject to whatever will be used underneath the hood in the future. Preact will soon be the default renderer, so whatever it does here will be what's done.
