### ISSUE TITLE
Remove framework / library comparisons in the docs

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1021]
Related to #857.

There's a new framework or library everyday. It would consume a significant amount of time to compare other libraries and frameworks, and I think detracts from Skate's focus. It might just be worth answering questions on a case-by-case basis, or blog about it instead.

**Comment by matthewp** [comment]
I agree 👍

**Comment by Hotell** [comment]
basic usage of how to use with framework/lib XYZ is definitely a must not just from PR perspective -> this will also broaden "knowledge" about WebComponents in general, because skate is just WC :)

**Comment by Hotell** [comment]
so yes for no comparison docs, must have for integration docs

**Comment by morewry** [comment]
I agree with @Hotell; integration docs are essential. Helps make the case for WC and skate, helps authors of skate components who may not use all the same frameworks as their users.

**Comment by Hotell** [comment]
yup @morewry  also we can reference just https://custom-elements-everywhere.com/ as a start for advanced devs ( they can look at the tests for usage :P )

**Comment by morewry** [comment]
Oh, nice! I haven't seen this yet, thanks for sharing.

**Comment by treshugart** [comment]
Yeah I think this has transformed quite a bit over time. Definitely need integration docs, but may not need "comparison" docs. Maybe for Polymer / X-Tags? But not sure if that's the best thing to focus on and have to maintain. I'll close this for now and add a task or integration docs on the website issue.
