### ISSUE TITLE
ie11+win7 broken

### ISSUE THREAD

**Issue by pbuzdin** [skatejs/skatejs#1025]
![image](https://cloud.githubusercontent.com/assets/1329807/22156606/16da60d8-df45-11e6-8525-28516a041865.png)
what is going on here?
http://skatejs.github.io/

**Comment by Hotell** [comment]
That page is not much maintained anymore AFAIK ( right @treshugart ? ). 
Instead try this https://skatejs.gitbooks.io/skatejs/content/docs/examples/#counter as a reference point of workable demo.

The issue with the site is not skatejs bug. The culprit are webcomponents polyfills, which are not including all required ES6 features, although they are using them... :(

for reference:
- ShadyDom https://github.com/webcomponents/shadydom/issues/51
- ShadyCss:
  - https://github.com/webcomponents/shadycss/issues/29 ( Object.assign )
  - https://github.com/webcomponents/shadycss/issues/36

If you don't have any more question pls fell free to close this issue

Cheers!

**Comment by Hotell** [comment]
Closed by https://github.com/skatejs/skatejs.github.io/issues/16
