### ISSUE TITLE
Skate + ShadyCSS application different than with Raw WC

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#1028]
this is rather a question than an issue.

If I use skate + skate-web-components,** ShadyCSS** is applied in browsers without nativeShadow dom, by adding `style-scope <name-of-custom-element>` class to every root element within shadowRoot, although if I create WebComponent by native API ( without skate ) nothing is applied. 

I was skimming through skate source, but didn't found anything about applying `ShadyCSS.applyStyle` . So I'm just curious how is the described behaviour possible?

DEMO: http://codepen.io/Hotell/pen/dNWjvY?editors=1010

![skate-shady-css-not-work-with-raw-wc](https://cloud.githubusercontent.com/assets/1223799/22185474/8e3933e6-e0e6-11e6-9b17-4800cf21424b.gif)

cheers!

**Comment by treshugart** [comment]
Just released https://github.com/skatejs/web-components/tree/v5.0.2. It was using very old versions. See https://github.com/skatejs/web-components/issues/33#issuecomment-274362552. try with the updates. There's no special code to cater to the ShadyCSS polyfill in Skate, so this would be happening simply by including it, which makes me thing it's just a version mismatch causing the anomaly you're seeing.

**Comment by Hotell** [comment]
Hmm as I've mentioned (https://github.com/skatejs/web-components/issues/33#issuecomment-274364694) the "shadyCSS" behaviour persist, skate components have the generated classes, but `custom-style` is now not transforming it contents, so now I'm really confused where is the problem :D 🗡 

![image](https://cloud.githubusercontent.com/assets/1223799/22186762/1c4704ba-e0fb-11e6-8d3f-8e2445314d60.png)

**Comment by treshugart** [comment]
Fixed in in resolving https://github.com/skatejs/web-components/issues/33.
