### ISSUE TITLE
Cannot export TypeScript typing definitions for Skate-extended components

### ISSUE THREAD

**Issue by mattdsteele** [skatejs/skatejs#1031]
Using TypeScript 2.1.5, Skate 4.6.2.

When defining a component, if you have `declaration: true` set in your TypeScript compiler config, setting `static get props()` throws a compiler error:

```
[ts] Return type of public static property getter from exported class has or is using name 'PropOptions' from external module "c:/project/skatepark/node_modules/skatejs/src/ts-typings/api" but cannot be named.
```

To reproduce, clone the [blaze-elements](https://github.com/wc-catalogue/blaze-elements) repo, and add `"declaration": true` to `tsconfig.json`'s `compilerOptions`. Then run a build and it will fail.

/cc @Hotell, I'm not well-versed enough in TypeScript to debug where this needs resolved, but I think it's an issue with the type definitions?

**Comment by treshugart** [comment]
@Hotell has been refining those lately. He'd probably know right off the bat what the issue might be.

**Comment by Hotell** [comment]
hey @mattdsteele interesting. I'm core memberof that repo. That is probably some problem within blaze-elements setup which needs to be addressed.

When you try [skate starter](https://github.com/Hotell/skate-starter) and add `declaration: true` to `tsconfig.json` no errors at all

**Comment by Hotell** [comment]
Oh yes I remember now. We saw that error when we were pairing with @elmariofredo at work.

The error is occurring because we are not exporting that `PropOptions` so form compiler perspective, that's an error if you wanna produce public definitions ( he cannot create them properly if all needed interfaces, props are not exposed )

**Comment by elmariofredo** [comment]
yup and there is issue for that https://github.com/wc-catalogue/blaze-elements/issues/126 we will address it soon in [blaze-elements](https://github.com/wc-catalogue/blaze-elements) repo

**Comment by mattdsteele** [comment]
Thanks for the info. So if my understanding is right, there's still work to do here; we should export `PropOptions` from `src/index.d.ts` to fix this? I can submit a PR if needed. Or is there another approach I should take?

**Comment by Hotell** [comment]
not from ambient definition, that's generated stuff.

What needs to be done is this ( for instance in Alert component )
```diff
+export type AlertProps = Props & EventProps;
-type AlertProps = Props & EventProps;
+export type Props = {
-type Props = {
  color?: ColorType,
  isOpen?: boolean,
}
+ export type EventProps = {
-type EventProps = {
  onAlertClose?: ( ev: CustomEvent ) => void,
}
export class Alert extends Component<AlertProps> {
// ...
}
```

then tweak tsconfig
```
{
  declaration: true
}
```

**Comment by mattdsteele** [comment]
Hmm, VSCode is showing the same error on the `props` getter even after exporting the types:
![image](https://cloud.githubusercontent.com/assets/389077/22254951/9b3e4550-e21b-11e6-8fa1-4b53b10c1361.png)

**Comment by Hotell** [comment]
aha! right!

So compiler needs to be explicit because he cannot infer everything, which is good thing. Maybe we can try to improve generics within skate that inference would work.

Current fix is to strictly annotate return of props like this:

```diff
import { 
 h, Component, prop, 
+ComponentProps
 } from 'skatejs';

+export type AlertProps = Props & EventProps;
-type AlertProps = Props & EventProps;
+export type Props = {
-type Props = {
  color?: ColorType,
  isOpen?: boolean,
}
+export type EventProps = {
-type EventProps = {
  onAlertClose?: ( ev: CustomEvent ) => void,
}
export class Alert extends Component<AlertProps> {
static get is(){ /*...*/ }
+ static get props(): ComponentProps<Alert,Props> {
- static get props() {
    return {
      color: prop.string({
        attribute: true
      }),
      isOpen: prop.boolean({
        attribute: true
      })
    }
  }
// ...
}
```

**Comment by mattdsteele** [comment]
Setting `ComponentProps<Alert, Props>` gave me this error:
```
[ts] Type '{ color: PropOptions<any, string>; isOpen: PropOptions<any, boolean>; }' is not assignable to type 'ComponentProps<Alert, Props>'.
       Types of property 'color' are incompatible.
         Type 'PropOptions<any, string>' is not assignable to type 'PropOptions<Alert, "brand" | "info" | "warning" | "success" | "error">'.
           Type 'string' is not assignable to type '"brand" | "info" | "warning" | "success" | "error"'.
```

Changing to `ComponentProps<Alert, any>` lets the compiler run, which is good enough to let me move forward. Happy to close this if you want to handle better generics in another ticket.

**Comment by Hotell** [comment]
right the error is there because Alert uses `string literals` as type for `color` property to get proper autocomplete within JSX. 

That type doesn't match of course to `props.string()` which returns `string` and `string` !== `brand | primary`.

Once again TS is right and forces us to write type safe code!

What needs to be done is to create custom `prop` helper for `colors`, which will also validate run time property mutation. 

Here is a contrived example how it should look like:
```ts
import { h, Component, prop, ComponentProps } from 'skatejs';

// our lookupHelper for 'foo' | 'bar'
const lookupProp = prop.create<Lookup>({
  default: '' as Lookup,
  coerce: toNullOrString,
  deserialize: toNullOrString,
  serialize: toNullOrString,
  // run time validation yay!
  set(elem,data){
    const validValue = ['foo','bar'].filter(key=>key===data.newValue).length;
    if(!validValue){
      throw new Error(`${data.newValue} is not supported. Api allows 'foo' or 'bar'`)
    }
  }
})

export type Lookup = 'foo' | 'bar';
export type Props = {
  counter: number,
  lookup: Lookup,
}
export class App extends Component<Props> {
  static get is() { return 'my-app' }
  static get props(): ComponentProps<App,Props> {
    return {
      counter: prop.number(),
      lookup: lookupProp(),
    }
  }
  renderCallback() {
    return [
      <div>Hello</div>
    ]
  }
}

export  function isEmpty (val:any): val is null|undefined { return typeof val === 'undefined' || val === null; }

function toNullOrString<T extends Lookup>(val:T){ return isEmpty(val) ? null : String(val) as T };
```

Result is fantastic! 💃 

![skate-runtime-validations](https://cloud.githubusercontent.com/assets/1223799/22268880/7de398f2-e289-11e6-971c-9d49a274c9b9.gif)

**Comment by Hotell** [comment]
auto inference of `static get props()` just isn't possible in TS (generics cannot be used with properties and we cannot reference generic of instance within static method/prop) so you need to always explicitly use `ComponentProps` which is a good thing ( full type safety ).

![skate-static-props-as-generic](https://cloud.githubusercontent.com/assets/1223799/22269324/3784e940-e28b-11e6-98b1-8be97808fc4a.gif)

**Comment by Hotell** [comment]
So if there are any more question, feel free to close this ;)

**Comment by mattdsteele** [comment]
Thanks!

**Comment by Hotell** [comment]
no, thank you! thanks to this, missing "puzzle" to super powered type safe skate web components has been explored.

cheers! 🍺
