### ISSUE TITLE
Move initialising prop definitions from the constructor to the prototype

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1033]
See https://github.com/skatejs/skatejs/blob/master/src/api/component.js#L57

This is breaking as it removes support for Safari < 10.

**Comment by thepian** [comment]
So original iPad and iPhone 4/4S. Sad, but I think that reflects the common consensus for mainstream sites.

**Comment by treshugart** [comment]
Yeah, I thought about that. There's so many problems with Safari <= 9, though and I think that's why so many have said they just support "latest".  If you have any further thoughts on this, I'm happy to discuss.

**Comment by thepian** [comment]
I think the direction of turning most things into mixins is the best, it allows making legacy browser variants that don't hold back new functionality. Of course it is more work and likely to atrophy without a larger number of maintainers. So in this case I would lean towards moving forward.

**Comment by Hotell** [comment]
I would be cautious about moving everything to mixins as it creates long prototypal chains, which may hit performance ( maybe, have no numbers yet )...

**Comment by treshugart** [comment]
I'm also concerned about perf here. Every upgrade has to walk all the way from your top chain to HTMLElement. This should be optimised by the browser if using native, but ES5 transpiled code uses setPrototypeOf. Maybe a non-issue in the future.

**Comment by treshugart** [comment]
To be clear, mixins are great, and whatever can be modularised probably should be. I still prefer the idea of having a pre-built base class for an all-in approach for the simplest use case. For example, I use most features in most components, so it makes sense to not have to piece everything together every time for that.

**Comment by treshugart** [comment]
Done in #1098.
