### ISSUE TITLE
Smplfy prop / attr / event setting

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1037]
We should follow simple rules when setting each one:

- If an `attrs` prop is passed, set everything as attributes (removing ones that weren't specified)
- If an `events` prop is passed, set everything as event listeners (removing ones that weren't specified)
- Set everything else as props
- Remove all code that handles special cases for everything else, except:
  - key
  - ref
  - skip

UPDATE

Spike: https://gist.github.com/treshugart/2fb509a8828adf7fee5245bfa2a54ba7

**Comment by Hotell** [comment]
Can you specify some example how will this look like? thanks

**Comment by treshugart** [comment]
- iDOM issue: https://github.com/google/incremental-dom/issues/316
- Will look similar to -> docs for implementation of `h` in `skatejs-dom-diff`: https://github.com/skatejs/dom-diff#hname-props-childrenortext

**Comment by treshugart** [comment]
Might be nice to have a `prop.event()` for setting events as properties, if consumers want to be able to do that. So, something like:

```js
static get props () {
  return {
    onclick: prop.event
  };
}
```

**Comment by treshugart** [comment]
Ended up creating https://github.com/skatejs/val as a lib that does this for all `h()` style vdom libs. We now are simply using default Preact behaviour.

**Comment by Hotell** [comment]
@treshugart 
> We now are simply using default Preact behaviour.

This means that we can do following?

```js
import {h,Component, define} from 'skatejs';

@define
class App extends Component {

    handleOnFoo = (data) => { console.log( data ) }
    renderCallback(){
       return (
         <div>
            <MyComponent onFoo={this.handleOnFoo} />
         </div>
       );
    }
}

@define
class MyComponent extends Component {

    static get props(){
      return {
        onFoo: {}
      }
    }

    renderCallback({onFoo}){
       return (
         <div>
            <button onClick={()=>onFoo('wooof!')} >Click me</button>
         </div>
       );
    }
}
```

**Comment by treshugart** [comment]
@Hotell I think Preact would bind that as a `CustomEvent`. You might have to specify as just `foo={this.handleFoo}`.
