### ISSUE TITLE
Remove complex iDOM wrapping code

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1038]
We wrap *A LOT* around Incremental DOM. The notable parts are:

- We try and make skipping more intuitive, as in you can turn it off and on selectively. This probably doesn't need to be done anymore if they now don't empty trees that have never had virtual nodes declared, but have DOM in them.
- Stateless functional components can be done by passing a function as a tag name. This forces us to have to wrap every function so we can buffer calls, and "build up" a tree which we can pass a `children` argument to. We probably don't need to do this if we return functions for everything.

Skipping isn't really necessary, especially if Incremental DOM now ignores trees that never had any nodes in the first place.

Stateless functional components are more complex. We should consider simplifying this as much as possible, even if it makes the API change a little.

- [ ] prove Incremental DOM ignores trees with no virtual nodes declared (use `ref` to update the node and do several renders)
- [ ] ensure you can still do stateless functional components in a similar manner (probably calling a function rather than passing a function to a tag name

**Comment by thepian** [comment]
Sounds great. It is really hard to extend the iDOM functionality.

**Comment by treshugart** [comment]
Replaced Preact with iDOM. See referenced PR for details.
