### ISSUE TITLE
vdom.text wrapper

### ISSUE THREAD

**Issue by thepian** [skatejs/skatejs#1042]
How is the idomWrapper working for the text function

```
function wrapIdomFunc (func, tnameFuncHandler = noop) {
  return function wrap (...args) {
    args[0] = resolveTagName(args[0]);
```

It seems that the resolve call would mess with the text to render.

**Comment by treshugart** [comment]
It just wraps it so that it can be buffered in case it's being called within a function helper. I'm hoping we can remove a lot of this stuff in #1038.

**Comment by thepian** [comment]
But the `args[0] = resolveTagName(args[0]);` line makes no sense for text

**Comment by treshugart** [comment]
It's a noop as `resolveTagName()` just returns what's passed in. Possibly better ways to do that, but it's going to get a rewrite soon anyways. Let me know if you have anymore questions about it. I'm going to close this now, but reopen if I haven't answered your question.
