### ISSUE TITLE
test coverage nested custom elements

### ISSUE THREAD

**Issue by thepian** [skatejs/skatejs#1043]
Is there a test to see if multiple rendering of two custom elements inside each other works?

```html
<x-outer><x-inner>inner</x-inner></x-outer>
```

Where `x-outer` renders `x-inner` which renders "inner".

I think that on the second render of `x-outer` it will render `x-inner` without any content. At least that is what I see in Chrome and Safari.

**Comment by Hotell** [comment]
you probably need to re-project that value. can you create a codepen or jsbin reproduction of that behaviour pls?

**Comment by thepian** [comment]
It is know behaviour, you need to build a new render system for regular DOM .... WiP
