### ISSUE TITLE
Fix Static is property for Component class

### ISSUE THREAD

**Issue by jmenestr** [skatejs/skatejs#1044]
https://github.com/skatejs/skatejs/blob/master/src/api/component.js#L102

```js
export default class extends HTMLElement {
  static get is = ''
```

This line throws a syntax error when importing `skatejs/src`. 

This needs to be changed to a static getter method. Should be changes as follows:
```js
export default class extends HTMLElement {
  static get is() { return ''; }
```

**Comment by treshugart** [comment]
I'm assuming you closed this because you found a workaround?

To clarify, `src/` isn't API and in importing it, your subject to the stage of the ES spec we choose to write it in. In this case, this would be stage 2, I believe. If you simply `import { Component } from 'skatejs'` you should be fine.
