### ISSUE TITLE
prop.node() for consuming DOM nodes, or nodes from other frameworks (preact et al)

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1056]
```js
import { Component, prop } from 'skatejs';

class Test extends Component {
  static props = {
    tbody: prop.node()
  }
  renderCallback ({ tbody }) {
    return <table>{tbody}</table>;
  }
}
```

The React node sniffing should move from vdom functions and into the prop function. We should also consider putting this in a separate `skatejs/vdom` lib that is a consolidation of both https://gist.github.com/treshugart/2fb509a8828adf7fee5245bfa2a54ba7 and the prop. We could then add support for other virtual DOM libraries' `createElement()` functions and a prop that will convert their vnodes into something Skate can understand.

**Comment by treshugart** [comment]
References #1055.

**Comment by Hotell** [comment]
Brilliant !!!

**Comment by treshugart** [comment]
Closing as I haven't had a need for this to date. Also, if you use lit-html, it works with real DOM, which is exactly what this use case is for. I think down the line there maybe a need for this in the react / preact renderers to consume children, but I'd prefer to just flesh it out at that point in time as some of the information here is stale.
