### ISSUE TITLE
Prop coerce() callback should accept an Error() as its return value 

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1057]
If an `Error` is returned, then the prop will throw it in dev mode or ignore it in prod mode. It should also be updated to accept the same arguments as `set` used to:

- `elem`
- `{ name, oldValue, newValue }`

**Comment by Hotell** [comment]
just for reference, it will work like this:

```js
function minLen(len){
  return (val) => (len && len.length) ? len.length >= len : new Error(`you need to provide at least ${len} chars dude!`)
}

class User extends Component {
   static get is(){ return 'skate-user' }
   static get props(){ return {
     return {
       name: prop.string({
          coerce(elem,{name,oldValue,newValue)){
             return minLen(3)(newValue);
          },  
       }),
     }
   }}
   renderCallback({name}){
     return (
       <div>Owner of this skate is {name}</div>
     )
   }
}

define(User)
```

**Comment by treshugart** [comment]
@Hotell that looks about right. Do you think there should be a separate `validate` callback instead?

**Comment by Hotell** [comment]
Hmm hard to say. As you've said previously it would do the same thing as `coerce` does. From API and naming perspective `validate` would be definitely nicer for consumer.

**Comment by treshugart** [comment]
Yeah. To me it's like, if you can coerce return the value. If you can't, return an error. This doubles as validation. I can see arguments for both, though. If you have validate and coerce, does it make sense? I'm not so sure. Will keep as is for now, but worth keeping in the back of our minds.

**Comment by Hotell** [comment]
yup. 100% agree

**Comment by treshugart** [comment]
I was thinking about this last night and returning from `coerce` doesn't work if you want to completely eliminate the checking and throwing using `process.env.NODE_ENV` as you still want to `coerce`, but generate an error.

I'm wondering what the best solution here is:

1. Throw in dev and prod, keeping `return new Error()`.
2. Move these checks to a `validate` callback that gets eliminated in prod.
3. Move to a `validate` callback that throws in prod, keeping `coerce`.
4. Completely remove `coerce` in favour of checking with something like `validate`. Still up in the air whether or not to throw in prod or not.

**Comment by Hotell** [comment]
I vote for hybrid of `2. and 3.`

so `Move these checks to a validate callback that gets eliminated in prod. + keeping coerce`

**Comment by Hotell** [comment]
`coerce` is important in situations like datepicker implementation, where you wanna provide attribute API via date string so it will get coerced to `Date` instance

**Comment by Hotell** [comment]
huh nevermind about that `coerce`, just realised that `deserialize` is used for that 
https://github.com/wc-catalogue/blaze-elements/blob/master/packages/calendar/Calendar.tsx#L64

**Comment by treshugart** [comment]
I'm thinking that it might be best to have a separate `validate` callback that returns an `Error` if the value isn't valid.

Open questions:

- Should validation be removed in prod?
- Should we also have a separate `required` option?

**Comment by treshugart** [comment]
I haven't come across a use case for this yet, so closing.
