### ISSUE TITLE
Can I use JSX to pass an object to an attribute?

### ISSUE THREAD

**Issue by jashworth** [skatejs/skatejs#1058]
I can write a React component that receives a preferences object from a consumer:

```

const ReactExtensibleGreeting = ({ name, preferences, children }) => {
        return (
            <div>
                Hello, <span id="name">{name}</span>
                <p>Your favourite framework is {preferences.framework}.</p>
                {children}
            </div>
        );
    };


// consumer

        this.state = {
            name: 'Julian',
            preferences: {
                framework: 'React'
            }
        }

    render() {
        return (
            <ReactExtensibleGreeting name={this.state.name} preferences={this.state.preferences}>
                <p>This greeting was brought to you by React and Web Components.</p>
                <p>Enjoy your day, {this.state.name}!</p>
            </ReactExtensibleGreeting>
        );
    }

```

Can I do this in SkateJS?

I tried

```
customElements.define(
    'skate-extensible-greeting',
    class extends Component {
        static get props() {
            return {
                preferences: {
                    attribute: true,
                    deserialize: function (value) {
                        // value is "[Object object]" :(
                    }
                },

                name: { attribute: true }
            };
        }

        // nice top-down data flow using JSX; no nasty imperative stuff

        renderCallback() {
            const styles = `
                #name {
                    color: magenta
                }
            `;

            return (
                <div>
                    <style>{styles}</style>
                    Hello, <span id="name">{this.name}</span>
                    <p>Your favourite framework is {this.preferences.framework}.</p>
                    <slot />
                </div>
            );
        }
    }
);

// consumer

<skate-extensible-greeting name={this.state.name} preferences={this.state.preferences}>
    <p>This greeting was brought to you by React and Web Components.</p>
    <p>Enjoy your day, {this.state.name}!</p>
</skate-extensible-greeting>

```

but the value I received, unsurprisingly, was a string "[Object object]".

My example is simple, but it's not difficult to imagine wanting to pass quite complex state to a component and doing that through a string seems far from ideal.

Perhaps I should be thinking about this in a different way?

I realize the issue may not lie with SkateJS but I'd still like to know if it's being tackled.

thanks

**Comment by Hotell** [comment]
hey @jashworth  great question. so here is the thing:

> My example is simple, but it's not difficult to imagine wanting to pass quite complex state to a component and doing that through a string seems far from ideal.

This is mostly a bad architectural decision. Reusable web components should be very simple and do one thing mostly, which comes to simple API ( mostly primitives, in edge cases there can be array or simple object ).

But yes you might use complex structures if you using WebComponents or skate for whole app data flow.

Also preferred API for WC is to not use attribute reflection ( attributes are slow and always converted to string in HTML -> I'm pointing on { `attribute:true` } ). Instead preferred API is just using props ( like React does for example ):
If you need that attribute support, consider using it one way ( not 2 way ) via `{ attribute:{source:true} }`

### now about your example:

you are consuming your component via HTML interpretation of IDOM so under the hood, your node is created from string via:
 `h('skate-extensible-greeting',{name: this.state.name, preferences: this.state.preferences}, children )`
which passes attributes as attributes, not as props.

if you wanna pass it as props you need to use Component class:
```js
import {h,Component,prop} from 'skatejs';

export class ExtensibleGreeting extends Component {
  static get is(){ return 'skate-extensible-greeting' }
  static get props(){ 
   name: prop.string(),
   preferences: prop.object(),
  }
  renderCallback({name,preferences}){
    const styles = `
                #name {
                    color: magenta
                }
            `;

            return (
                <div>
                    <style>{styles}</style>
                    Hello, <span id="name">{name}</span>
                    <p>Your favourite framework is {preferences.framework}.</p>
                    <slot />
                </div>
            );
  }
}

customElements.define(ExtensibleGreeting.is, ExtensibleGreeting );

// consumer 

import {h, Component} from 'skatejs';

class App extends Component {
 renderCallback(){
   return (
    <ExtensibleGreeting name={this.state.name} preferences={this.state.preferences}>
      <p>This greeting was brought to you by React and Web Components.</p>
      <p>Enjoy your day, {this.state.name}!</p>
    </ExtensibleGreeting>
    )
  }
}
```

**Comment by jashworth** [comment]
Thanks for a super-comprehensive answer. On a Saturday afternoon too.

Lots of things to explore now!

**Comment by Hotell** [comment]
always man! happy hunting :) don't hesitate to ask further questions. cheers!

**Comment by treshugart** [comment]
Hey @jashworth, @Hotell, I just want to clarify a few things here. Part of it will reiterate what @Hotell said, but I also want to clarify a few points.

### Re bad architecture / design

Passing complex data structures to a web component isn't inherently bad design, nor is making a component composed of complex behaviours.

> This is mostly a bad architectural decision. Reusable web components should be very simple and do one thing mostly, which comes to simple API ( mostly primitives, in edge cases there can be array or simple object ).

I want to emphasise that building complex components that take complex data structures isn't bad design and web components are perfectly suited for doing so, especially with Skate. You can do everything that you can do in React (and more, such as deferred upgrades because it's built into the platform).

### React is culprit

To your points about expecting React to do the right thing here, that's not the case at the moment. See:

- https://github.com/facebook/react/issues/7901
- https://github.com/facebook/react/issues/7249

I don't think my proposal is being taken too seriously. It's unfortunate because the only true way to have the most robust DOM integration is to give the consumer full control over what they want to set: properties, attributes or events. Relying on checks is problematic especially if you don't know when a custom element will be defined.

Using [that gist](https://gist.github.com/treshugart/2fb509a8828adf7fee5245bfa2a54ba7) will give you expected and robust behaviour from `React.createElement()` while falling back to the original behaviour, so it's backward compatible.

There's also https://github.com/webcomponents/react-integration that sort of does the same thing, but it does it from the other perspective: it creates a React component from a web component. The more I think about it, I prefer the gist method as there's less indirection and it works with both custom elements and standard DOM elements better.

Fortunately, alternatives like Preact do the right thing (for the most part). However, they don't go the full 9 yards and give the user complete control; there's still checks they do that can be problematic in some scenarios, mostly around deferred custom element upgrades.

### Clarifying attribute reflection

> Also preferred API for WC is to not use attribute reflection

This is mostly true. That said, to have a true HTML API, you must at least do `{ attribute: { source: true } }`. We're considering making the default behaviour as there's no overhead if you're using props but it still allows the attribute to affect a prop, thus enabling the HTML API.

**Comment by Hotell** [comment]
well written @treshugart 🍺 thanks

**Comment by jashworth** [comment]
@treshugart: I completely get what you're saying.

In fact, I think you nailed it on [this thread](http://www.2ality.com/2015/08/web-component-status.html) where you say

> Just because web components don't have an opinion about immutable state and declarative templating doesn't mean that you can't very easily take that approach.

That was golden. It was that thread and that quote that got me looking at SkateJS.

I now have a "Rosetta Stone" of &lt;plain-extensible-greeting&gt;, &lt;skate-extensible-greeting&gt; and ReactExtensibleGreeting, plus React and Preact consumer code, which I hope will prove valuable to folks I work with.

thanks again

**Comment by Hotell** [comment]
@jashworth If you have further question, shoot, otherwise feel free to close this issue. cheers mate! 🍻

**Comment by treshugart** [comment]
@jashworth if you are able to share that code, it might prove useful to others, too :)

**Comment by treshugart** [comment]
Closing as it seems we've addressed the main point. That said, it'd be great to share that code :). Thanks again for your question!

**Comment by jashworth** [comment]
My day job keeps getting in the way.

There's not much code so I'm posting it inline.

Here's the basic **React Component**:

```
const ReactExtensibleGreeting = ({ name, preferences, children }) => {
        const styles = `
            #name {
                color: magenta
            }
        `;

        return (
            <div>
                <style>{styles}</style>
                Hello, <span id="name">{name}</span>
                <p>Your favourite framework is {preferences.framework}.</p>
                {children}
            </div>
        );
    };

export default ReactExtensibleGreeting;
```

Now the **plain/vanilla Web Component**:

```
class PlainExtensibleGreeting extends HTMLElement {
    constructor() {
        super();

        const root = this.attachShadow({ mode: 'open' });

        root.innerHTML = `
            <style>
                #name {
                    color: magenta
                }
            </style>

            Hello, <span id="name"></span>
            <p id="preferences"></p>

            <slot />
        `;
    }

    static get is() {
        return 'plain-extensible-greeting';
    }

    set name(value) {
        this.shadowRoot.getElementById('name').textContent = value;
    }

    set preferences(value) {
        this.shadowRoot.getElementById('preferences').textContent =
            `Your favourite framework is ${value.framework}`;
    }
};

customElements.define(PlainExtensibleGreeting.is, PlainExtensibleGreeting);
```

Now the **SkateJS Web Component**:

```
import { Component, h, prop } from 'skatejs';

/** @jsx h */

// nice top-down data flow using JSX; no nasty imperative stuff

class SkateExtensibleGreeting extends Component {
    static get is() {
        return 'skate-extensible-greeting';
    }

    static get props() {
        return {
            name: prop.string(),
            preferences: prop.object()
        };
    }

    renderCallback({name, preferences}) {
        const styles = `
            #name {
                color: magenta
            }
        `;

        return (
            <div>
                <style>{styles}</style>
                Hello, <span id="name">{name}</span>
                <p>Your favourite framework is {preferences.framework}.</p>
                <slot />
            </div>
        );
    }
}

customElements.define(SkateExtensibleGreeting.is, SkateExtensibleGreeting);

export default SkateExtensibleGreeting;
```

Here's the React **application code** to drive all three together:

```
import React from 'react';
import { render } from 'react-dom';

import ReactExtensibleGreeting from 'react-extensible-greeting';
import SkateExtensibleGreeting from 'skate-extensible-greeting';
import 'plain-extensible-greeting';

class App extends React.Component {
    constructor(props, context) {
        super(props, context);

        this.state = {
            name: 'Julian',
            preferences: {
                framework: 'React'
            }
        }
    }

    changeTarget() {
        return {
            name: 'Manish',
            preferences: {
                framework: 'Angular'
            }
        };
    }

    componentDidMount() {
        // set the web component props manually
        this.setWebComponentProps(Object.assign({}, this.state));

        setTimeout(() => this.setState(this.changeTarget), 2000);
    }

    componentDidUpdate() {
        // set the web component props manually
        this.setWebComponentProps(Object.assign({}, this.state));
    }

    setWebComponentProps(state) {
        this.plainExtensibleGreetingNode.name = state.name;
        this.plainExtensibleGreetingNode.preferences = state.preferences;
        this.skateExtensibleGreetingNode.name = state.name;
        this.skateExtensibleGreetingNode.preferences = state.preferences;
    }

    render() {
        return (
            <div>
                <h3><b>React only</b></h3>
                <ReactExtensibleGreeting name={this.state.name} preferences={this.state.preferences}>
                    <p>This greeting was brought to you by React and Web Components.</p>
                    <p>Enjoy your day, {this.state.name}!</p>
                </ReactExtensibleGreeting>
                <hr />
                <h3><b>skate</b>-extensible-greeting</h3>
{/*
                <SkateExtensibleGreeting.is name={this.state.name} preferences={this.state.preferences}>
                won't work because React doesn't care about web components (yet)
*/}
                <SkateExtensibleGreeting.is ref={node => this.skateExtensibleGreetingNode = node}>
                    <p>This greeting was brought to you by React and Web Components.</p>
                    <p>Enjoy your day, {this.state.name}!</p>
                </SkateExtensibleGreeting.is>
                <hr />
                <h3><b>plain</b>-extensible-greeting</h3>
{/*
                same thing applies here
*/}
                <plain-extensible-greeting ref={node => this.plainExtensibleGreetingNode = node}>
                    <p>This greeting was brought to you by React and Web Components.</p>
                    <p>Enjoy your day, {this.state.name}!</p>
                </plain-extensible-greeting>
            </div>
        );
    }
}

render(
    <App />,
    document.body
);
```

And finally, using **Preact** to drive the **SkateJS Web Component**:

```
import { h, render, Component } from 'preact';

/** @jsx h */

import SkateExtensibleGreeting from 'skate-extensible-greeting';

class App extends Component {
    constructor(props, context) {
        super(props, context);

        this.state = {
            name: 'Julian',
            preferences: {
                framework: 'React'
            }
        }
    }

    changeTarget() {
        return {
            name: 'Manish',
            preferences: {
                framework: 'Angular'
            }
        };
    }

    componentDidMount() {
        setTimeout(() => this.setState(this.changeTarget), 2000);
    }

    render() {
        return (
            <div>
                <h3><b>skate</b>-extensible-greeting with Preact</h3>
                <SkateExtensibleGreeting.is name={this.state.name} preferences={this.state.preferences}>
                    <p>This greeting was brought to you by React and Web Components.</p>
                    <p>Enjoy your day, {this.state.name}!</p>
                </SkateExtensibleGreeting.is>
                <hr />
            </div>
        );
    }
}

render(
    <App />,
    document.body
);
```
