### ISSUE TITLE
feat( decorators ): decorator implementation for flawless TS integration

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#1059]
Just wanna brainstorm here and also ask if we wanna have this as a part of core skate or rather separate package under skatejs  organization.

WDYT @treshugart ?

## Implementation

```ts
// skatej-decorators.ts
import { emit as skEmit } from 'skatejs';
 
export class EventEmitter {
    origin: Component<any>;
    eventName: string;
    emit(conf?:EventConfig) {
        return skEmit(this.origin,this.eventName,conf)
    }
}

export function customElement(name: string) {
    return function (cls) {
      customElements.define(name || cls.is, cls);  
    }    
}

export function prop(config?: PropConfig) {
   // IMPL
  //  it will create static get props(){} under the hood
}

export function event(nameAlias?: string) {
 // IMPL
 //  it will set origin and eventName on eventEmitter instance
 // also the event name will be taken from property name if not aliased
}

type PropConfig = {
    attributes?: boolean | string | Object,
    coerce?(elem, {name,oldValue,newValue}): any,
    serialize?(): any,
    deserialize?(): any,
}

type EventConfig = {
    bubbles?: boolean,
    composed?: boolean,
    cancelable?: boolean,
    detail?: Object
}
```

## Usage

```ts
// app.tsx

import { h, Component } from 'skatejs';
import { customElement, prop, event, EventEmitter } from 'skatejs-decorators';

interface UserProps {
    name: string,
    doKickflip: (ev: EventConfig)=>boolean
}

@customElement('skate-user')
class User extends Component<UserProps> implements UserProps {
    @prop() name: string;
    @event() doKickflip = new EventEmitter();

    renderCallback({name}) {
        return (
          <div>
            <div>This skater name is {name } </div>
            <button onClick= {(ev)=>this.doKickflip.emit()}>do kickflip</button>
          </div>
        )
    }
}


class App extends Component<void>{

    renderCallback({skaters}) {
        return (
            <div>
              <User name={'Tony Hawk'} onDoKickflip= {()=>console.log('this dude just hit kickflip')}/>
            </div>
        )
    }
}
```

**Comment by treshugart** [comment]
TS is great, but I'm not a fan of designing core features around a language superset. IIRC they're implemented in the same way, though, and since decorators are at stage 2 in tc39, I think we should probably propose this in the context of that.

I think decorators might work well as a separate package; they feel like they'd augment what the core gives you

**Comment by Hotell** [comment]
yup exactly. juste wanted to double check with you. So can I create new repo for that under skate org ?

thanks!

**Comment by treshugart** [comment]
Sure. I'm wondering if it'd be good to have a single repo that has extensions like this? I've actually considered using [Lerna](https://github.com/lerna/lerna) and just having everything skate related in a single repo :p

**Comment by treshugart** [comment]
Go ahead and create it and we can bikeshed a name before publishing.

**Comment by Hotell** [comment]
> Sure. I'm wondering if it'd be good to have a single repo that has extensions like this? I've actually considered using Lerna and just having everything skate related in a single repo :p

Lerna is awesome. Let's do it!

**Comment by treshugart** [comment]
Sure, Lerna it up!
