### ISSUE TITLE
prop.* overhaul

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1073]
- remove `create()`
- make each prop type a frozen object rather than a function
- update docs
- consider making default `array` and `object` a shared frozen array / object (we should somehow communicate this and encourage immutability and more functional constructs like `concat()` and spread

**Comment by thepian** [comment]
why can't props be objects and functions? Are you just trying to keep the codebase small?

**Comment by treshugart** [comment]
@thepian yeah. Functions and `create()` were convenience that is really unnecessary if you have `Object.assign()` or spread (`{ ...prop.array, ...customOptions }`). It doesn't reduce the code size too much, but it reduces complexity. If there's a compelling use case, I'd be happy to consider keeping it.

**Comment by thepian** [comment]
Interesting idea with the spread notation, it gives flexibility. I assumed that you were moving closer to the React notation which might make static analysis easier. However I guess autocomplete/docs could easily load the class and inspect the props. It might even be a better solution for analysis to load the actual code over just parsing it.

Nope, I have no requests for backwards compatibility.

**Comment by treshugart** [comment]
> However I guess autocomplete/docs could easily load the class and inspect the props.

Yeah, that's not the main purpose of this, but definitely a nice benefit of doing so. The main benefit here is the simplicity that comes with less API and less code.
