### ISSUE TITLE
New compilation requirements

### ISSUE THREAD

**Issue by thepian** [skatejs/skatejs#1078]
I'm a bit surprised by the aggressive move forward with source syntax. Source code dependency on CJS/requirejs/Typescript has been big pains in the past for open source JS. Now it is becomming much easier with the widespread adoption of ES 2015.
Skate already relies on being compiled with Babel (tried rollup which seems to not do the HTMLElement extension properly). Recent changes relies on static initialisers `static is = ''`. Isn't it a bit premature?

If not could you document the build requirements, I tried using the same babelrc that you have, but it doesn't seem to work.

**Comment by treshugart** [comment]
The `src/` is not API, thus not supported as a consumption method. Even if we followed strict ES2015, we wouldn't expose it is directory structure would be API. We should be free to experiment and use whatever we see fit for our source without affecting our consumers. For posterity, these are also known as [class public fields](https://github.com/tc39/proposal-class-public-fields) and are in stage 2.

In https://github.com/skatejs/skatejs/issues/992 we'll probably transpile to es2015 in `dist/` and transpile to the latest stable es spec. More implementation details there.
