### ISSUE TITLE
Where should we put extra stuff that doesn't fit into core?

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1079]
- An `extras` repo?
- Each on in a separate repo?
- NFI

**Comment by Hotell** [comment]
My suggestions:

- skatejs/warehouse - Lerna repo
- skatejs/griptape - Lerna repo
- each extra in separate repo project

Downsides:
- via Lerna ( decorators package will be written with TS, others authored by @treshugart probably vanilla JS ). I guess it can be solved, but have to try
- separate projects ( maintenance problems ? )

**Comment by thepian** [comment]
What is the downside of having an extras folder?

1) longer build time
2) more dist files

The good thing is that they stay in sync. It is easier for people that use the extras but an overhead for people that just use the core.

**Comment by treshugart** [comment]
@Hotell ES decorators are at stage 2 and have the same characteristics as TS. I think I want to keep most things in Vanilla so it keeps the barrier low for anyone to contribute.

**Comment by Hotell** [comment]
You know my opinion, vanilla js sucks and there is zero overhead ( even better for smaller codebases ) to using type annotations within code instead of JSDoc and also keeps the docs up to date + many other benefits ( auto generating type definitions -> TS and Flow )

TS gives us another powerful feature - design type reflection, so it can infer from compile time Types what type of variable are you using.

for instance:

```ts
import {h, Component} from 'skatejs';
import {customElement, prop} from 'skate-grip-tape';

type Props = {}
class User {
 name: string;
 email: string;
}

@customElement('x-hello')
class Hello extends Component<Props>{
  @prop() greet: string;
  @prop() user: User;
}
```

typescript and Reflection will gives us design types, which can be leveraged for creating appropriate props API even with `proposed validations api` under the hood.

so the code will "transform" to:

```js
import {h, prop, Component} from 'skatejs';

class Hello extends Component {
  static get props(){
    return {
      greeting: prop.string(),
      user: prop.object({
        validate(value){
          return value instanceOf User || throw new Error('this is not a user')
        }
      }),
    }
  }
}

customElements.define('x-hello', Hello );
```

**Comment by Hotell** [comment]
So "I'm afraid" that I will "have to" create skate decorators library outside of this project, which is ok I guess :D

**Comment by alexlafroscia** [comment]
I like the idea of putting extras in a separate repo, although maybe a repo for each additional thing makes more sense than one big repo, just to keep things easy.  I personally also like the convention that Ember and Angular have taken recently of putting official packages under a `@__library_name__` namespace on NPM, so you'd do something like

```
import { Component } from 'skate';
import StyledMixin from `@skate/shady-css`

class Foo extends StyledMixin(Component) {
  ...
}
```

**Comment by Hotell** [comment]
Yup scoping is indeed great idea and having extras under separate repo is flawless victory with Lerna.

 Angular has also everything under one mono repo for instance although they don't use lerna or webpack rather old school maintenance gulp hell ...

**Comment by alexlafroscia** [comment]
What would the benefit be of putting them all in one repo via Lerna? I feel like keeping things separate makes more sense for things like error tracking and versioning. Nothing wrong with a small repo!

**Comment by treshugart** [comment]
I like the idea of separate repos because it functionally separates out each bit. It also makes it simpler to use TS / Flow / Vanilla in each one without affecting the tooling of the other. The difficult part is build duplication. For that we have skatejs-build. However, maintaining that kinda sucks and [nwb](https://github.com/insin/nwb) is pretty great.

And, fuck it, let's just use TS.

**Comment by treshugart** [comment]
> And, fuck it, let's just use TS.

Turns out they don't support Semver. I'm not sure how comfortable I am with that. Any minor version has the possibility of breaking us. I'd reference the clarification of that, but I don't want to induce extra chatter here.

Is Flow / Vanilla really that bad!?

**Comment by trajedy** [comment]
What is this Typescript discussion about? Rewriting the core of Skate in TS? What benefits will that provide component authors? Is it merely for decorators / mixins? Would much prefer Vanilla with Flow TBH.

**Comment by treshugart** [comment]
Currently we're doing this in separate repos and using [conartist](https://github.com/treshugart/conartist) to manage duped configs. Will close for now.
