### ISSUE TITLE
How to plug in to renderCallback LC ?

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#1080]
I wanna implement `Style` decorator for "compiling" component styles via `ShadyCss` so we get encapsulation and which will add styles automatically to the DOM.

Thing is I didn't find a way how to plug in `renderCallback` and add `<styles>{compiledStyles}</styles>`  to user component `RC` LC hook.

Any suggestions @treshugart ?

here is how it would look like:

```js
class Deck extends Styled(Component){
   static get is(){ return 'x-deck' }
   
   get css(){
     return {
       :host{ display: 'block' }
       .div { color: tomato }
     }
   }

   renderCallback(){
      return (
        <div class="div">Birdhouse</div>
      )
   }
}
```

at this moment I have to do 

```js
class Deck extends Styled(Component){
   static get is(){ return 'x-deck' }
   
   get css(){
     return {
       :host{ display: 'block' }
       .div { color: tomato }
     }
   }

   renderCallback(){
      return [
        this.renderCss(),
        <div class="div">Birdhouse</div>
      ]
   }
}
```

**Comment by treshugart** [comment]
That's what I do, currently, but I've been wanting to do something [like this](http://codepen.io/treshugart/pen/ZLVXPG?editors=1010) with decorators.

**Comment by Hotell** [comment]
turns out, that it's also possible directly via mixin:

```js
class Deck extends Styled(Component){
   static get is(){ return 'x-deck' }
   
   get css(){
     return {
       :host{ display: 'block' }
       .div { color: tomato }
     }
   }

   renderCallback(){
      return [
         ...super.renderCallback(),
        <div class="div">Birdhouse</div>
      ]
   }
}

function Styled( Base ){
  return class extends Base {
      get renderCss(){
          return applyShadyCss(this.css);
      }
      renderCallback(){
          return [
            h('style',this.renderCss),
            ...super.renderCallback()
          ]
      }
  }
}
```

As I dig more and more into mixin patterns ( https://github.com/wc-catalogue/blaze-elements/blob/mh/mixins-with-new-ts/packages/_helpers/mixins.ts#L51 ) I'm really starting to hate them, super long prototype chain, complicated constructs within Super class ( by calling `super` all the time ). I rather prefer simple Decorators ( which have only downside from Typescript perspective - they don't enhance Super class property definitions, so user has to manually define them.

**Comment by treshugart** [comment]
+1 decorators are awesome. Maybe it's not worth spiking decorators in #927 instead? Going to close this now as it seems that the question is answered. Feel free to reopen if need be.
