### ISSUE TITLE
Official Gitbook seems to have broken rendering

### ISSUE THREAD

**Issue by thepian** [skatejs/skatejs#1082]
The Gitbook linked by the repo is very limited and flakey. Whenever I navigate the links the page blanks out, making it very hard to read the documentation. It also seems there is a second gitbook with more information, but the URL for it escapes me. I guess nothing can be done about this, but perhaps it's something simple that will go away by some configuration or URL change for the deployed book.

**Comment by Hotell** [comment]
can you elaborate more pls? maybe some gif and version in which browser are you experiencing this behaviour would be helpful. 

In Chrome everything works fine.

thx

**Comment by thepian** [comment]
[Skate docs fail.mp4.zip](https://github.com/skatejs/skatejs/files/769638/Skate.docs.fail.mp4.zip)

**Comment by Hotell** [comment]
next time maybe you can use Licecap to create gif like a boss :) http://www.cockos.com/licecap/

Once again I have no idea which safari are you using. Works fine on my machine ( Safari Version 10.0.3 (12602.4.8) )

![skate-gitbook-safari-view](https://cloud.githubusercontent.com/assets/1223799/22866166/c94e4228-f171-11e6-9e21-2c4e4061c484.gif)

**Comment by treshugart** [comment]
Interesting. I've tried in my Safari and everything seems to work ok. What version of Safari are you using, @thepian?

**Comment by thepian** [comment]
Sorry, same version. Perhaps it's something with the graphics driver.

**Comment by treshugart** [comment]
Are you using any extensions in Safari that might be doing something to cause this?

**Comment by paulwan** [comment]
I was had same issue for gitbook in safari.but when I disable "JSONView" extension in Safari perferences,the page content diaplay is normally. hope this tip can help.

**Comment by treshugart** [comment]
All docs are on https://skatejs.netlify.com now, anyways :)
