### ISSUE TITLE
Add ability to specify contexts

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1089]
Still not sure whether this is core or addon, but it kinda feels core-ish. It'd be nice to have a way to use contexts like in, you guessed it, React.

See https://gist.github.com/treshugart/fbc37ab7d19028b9fe22311bd1b634f4 for more details.

**Comment by Hotell** [comment]
implemented in 5.x, closing

**Comment by treshugart** [comment]
One thing to test here is if a component has a different `renderRoot` (like portals in react`, is if it's host still gets context. It should because the host would still be in the standard component / document flow, just the content would be rendered somewhere else. This means that descendant content probably wouldn't get the context, though, unless it was manually carried from the host to the content in the render root (unless we had a way around this built-in).
