### ISSUE TITLE
Boolean attributes as strings

### ISSUE THREAD

**Issue by alexlafroscia** [skatejs/skatejs#1091]
What's the best way to handle `boolean` attributes that are passed around as strings? For example, I have a component that needs to pass an attribute down to a child component. Something like this:

```js
define(class extends Component {
  static is = 'parent'

  static props = {
    foo: prop.boolean({ attribute: true })
  }
  
  renderCallback() {
    const { foo } = props(this);

    return [
      <child foo={foo}></child>
    ]
  }
});

define(class extends Component {
  static is = 'child'

  static props = {
    foo: prop.boolean({ attribute: true })
  }
  
  renderCallback() {
    ....
  }
});
```

what's the best way to handle passing the attribute around? I want to be able to pass the attribute like I am in that `renderCallback`

```js
<child foo={foo}></child>
```

but this ends up passing it as a string, which is then always `true`. Is there some way to do this, but pass it as a boolean instead?

**Comment by alexlafroscia** [comment]
It seems like you can set the `true` state correctly...

```js
<child foo={foo ? 'foo' ? ...}></child>
```

but how do you model the `false` state? Should the `...` above be `undefined`

**Comment by alexlafroscia** [comment]
Never mind. Using `undefined` for `false` seems to work. The syntax isn't ideal but it does work.

**Comment by treshugart** [comment]
What's not ideal about the syntax?

**Comment by alexlafroscia** [comment]
I'd love to be able to just pass it a Boolean directly:

```jsx
<child foo={foo}></child>
```

instead of having to pass it like this:

```jsx
<child foo={foo ? 'foo' : undefined}></child>
```

but that's not a big deal.

**Comment by treshugart** [comment]
@alexlafroscia Skate follows standard HTML behaviour for string and boolean attributes. For example, true boolean attributes work just fine: http://www.webpackbin.com/4JDv3FdtM. If you need to represent a boolean as a string, you'll need to write a custom prop for that that uses `coerce` / `serialize` / `deserialize` to check specific values you're wanting to represent falsy and truthy.

**Comment by alexlafroscia** [comment]
Yeah, totally makes sense 😄  I was confused because it works differently than React, but once I read up more on how real HTML attributes work, I was able to answer my own question. Thanks!

**Comment by alexlafroscia** [comment]
Hmm

**Comment by alexlafroscia** [comment]
Thanks for that example by the way, I didn't realize that you _can_ just pass the property directly like that. When I was encountering the issue with them coming through as strings, I was using `.setAttribute` from outside the component to set the values, and I think that that was turning it into a string as the follow was set in the DOM. It's great to know that within the components, you can just pass the values directly, like your example shows.

**Comment by rsimsek** [comment]
Hi
I am having some problems passing boolean values when i create the custom elements.

I have a ColumnLayout component from Material UI.
ColumnLayout has container and item as boolean values. 
I created my custom element and specified my props for container and item as skateProps.bool
When i try to use it in an example, lets say
```
<column-layout container spacing=24>
    <column-layout item xs=12>
      <div>some value</div>
    </column-layout>
    <column-layout item xs=12>
      <div>some value</div>
    </column-layout>
</column-layout>
```
If i try to pass the container and item values like that, they are always undefined. 
If change the skateProps type to string and pass the values as 
```
<column-layout container=true spacing=24>
    <column-layout item=true xs=12>
      <div>some value</div>
    </column-layout>
    <column-layout item=true xs=12>
      <div>some value</div>
    </column-layout>
</column-layout>
```
It works like that but React gives warning because it expects a bool type but it receives as string.
How can pass the bool value? 

Thank you.
