### ISSUE TITLE
Use Preact as default rendering pipeline

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1094]
Incremental DOM is great, but we've had to wrap a lot of code around it. Preact embodies most of the opinions we've had to write around the iDOM wrapper, which means we can remove the bloat and offload those opinions to someone else. The first step in making renderers a first class citizen is to move most of the opinions over to the rendering pipeline.

Things we need to consider in this move:

- `h` / JSX now use the Preact API, thus lose the ability to use a custom element constructor (@developit can you confirm?) as the tag name.
- Need to document how to use https://github.com/skatejs/val with renderers.
- Documenting renderers.
- Finding out a good way forward how we should build / release custom renderers.

**Comment by developit** [comment]
@treshugart not sure if I quite follow the stateless functions thing, but in Preact 8 (actually been sitting done for a while) stateless functional components get coerced into full-fledged Components at instantiation time.   Is there a place I could look to check where the custom element constructors work in Skate today?

**Comment by treshugart** [comment]
Hey sorry, @developit, I poorly worded that point. Basically what you can do currently is do `<CustomElementCtor />`. I wanted to confirm if this is, or is not, possible in Preact. I couldn't find anything on it, but I probably didn't search well enough.

**Comment by developit** [comment]
@treshugart hmm - does that get mapped back to a `createElement()` call, or is it invoked with `new`?

**Comment by treshugart** [comment]
@developit 

> hmm - does that get mapped back to a createElement() call, or is it invoked with new?

We were using the constructor to [look up](https://github.com/skatejs/skatejs/blob/d02a62a85e0462b7d2d12ea59e29dc8ed6e80632/src/api/vdom.js#L141) the local name of the custom element by constructing it and then caching the localName value. We'd then just pass the name into Incremental DOM. The way we're doing it in https://github.com/skatejs/val is more performant because we override `customElements.define()` and store the map.

From the sounds of it, Preact doesn't do this yet. It's no biggy, just wanted to get clarification :)

**Comment by Hotell** [comment]
sorry for unrelated comment:

> not sure if I quite follow the stateless functions thing, but in Preact 8 (actually been sitting done for a while) stateless functional components get coerced into full-fledged Components at instantiation time. Is there a place I could look to check where the custom element constructors work in Skate today?

Nice that will make things much easiear @developit , currently I'm writting enzyme-preact-lite and I have to explicitly wrap stateles components ( functions ) to `Component` to make things work ( access to props etc )

**Comment by developit** [comment]
ooh - clever idea to override define and store it.  You can inject a hook to do this btw:

```js
import { options } from 'preact';

let old = options.vnode;
options.vnode = vnode => {
  let name = vnode.nodeName;
  if (typeof name==='function' && ctorToNameMap.has(name)) {
    vnode.nodeName = ctorToNameMap.get(name);
  }
  if (old) old(vnode);
};
```

This would enable anything using preact with that lookup.  Alternatively, just wrapping `h()` would work if it only needs to be done internally.

**Comment by treshugart** [comment]
@developit ahh great. I think `@skatejs/val` will be fine for this as it isolates the behaviour. As custom elements stabilise, is this something you'd consider putting into core? Being able to use valid DOM constructors instead of string names feels like something that vdom libs should consider.

**Comment by developit** [comment]
@treshugart potentially. I'm kinda confused how the API doesn't explicitly allow for it already - it seems like it would have been an obvious choice.

**Comment by treshugart** [comment]
Ahh right, you mean `document.createElement(CustomElementCtor)`. I have no idea, but it seems like something that would fit a good proposal. It'd be simple to polyfill, too.

**Comment by developit** [comment]
Wonder if it was decided on because it would be polymorphic..
