### ISSUE TITLE
How to unregister already registered Web Component

### ISSUE THREAD

**Issue by wellermiranda** [skatejs/skatejs#1095]
I can define a new tag, but I can't  undefine". We need it because my app needs to destroy components which are not in use. Thanks.

**Comment by treshugart** [comment]
The spec doesn't offer an API for this, so it's not possible. Can you elaborate on why this is needed?

**Comment by treshugart** [comment]
Hey @wellermiranda, I haven't received a response in a few days, and seeing as this isn't allowed by the native APIs, I'm going to close this. Feel free to provide your use case and I can do my best to help you out.
