### ISSUE TITLE
refactor(ts-typings): update definitions to match skate 5.x

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#1102]
5.x introduces BC to the API

@treshugart already updated ts-definitions, but we should review if everything is up to date

Also Preact definitions needs some love before we can proceed
- issue https://github.com/developit/preact/issues/639
- depends on https://github.com/developit/preact/pull/621

**Comment by treshugart** [comment]
I don't think I added them for the `when*` mixins or separation of the `props()` function into `setProps()` and `getProps()`.

**Comment by freeman** [comment]
Also missing: prop.string, prop.number, etc. should become propString, propNumber, etc.

**Comment by Hotell** [comment]
yeah that's gonna actually change in #1100

**Comment by treshugart** [comment]
Yeah, `using props.*` (plural) actually makes more sense especially since the convenience of importing a single namespace outweighs the benefits of tree-shaking (object properties don't shake out).

**Comment by freeman** [comment]
I've seen the fix in #1100. Thanks.

Also now that skate is using preact, shouldn't it rely on preact's type definitions for the JSX part instead of redeclaring it ?

**Comment by Hotell** [comment]
That will need to be refactored. Preact typings are not in very good shape at the monent. I'll work on it soon

**Comment by treshugart** [comment]
> Also now that skate is using preact, shouldn't it rely on preact's type definitions for the JSX part instead of redeclaring it ?

Yeah, I think that's probably a good idea. Would this be possible if forwarding the export from `with-props.js` like we're doing now?

**Comment by Hotell** [comment]
> Also now that skate is using preact, shouldn't it rely on preact's type definitions for the JSX part instead of redeclaring it ?

NOPE. as I've said:

> That will need to be refactored. Preact typings are not in very good shape at the monent. I'll work on it soon

**Comment by treshugart** [comment]
Ahh right. At least that will benefit Preact!

**Comment by freeman** [comment]
@treshugart are you confident on the automated generation of TS typings from the flow source ? 

Or should we still invest in making the manual TS definitions complete ? (some thing are missing like the `prop` function and `props.any` for which I can make a PR)

**Comment by treshugart** [comment]
@freeman I would still invest in making the TS definitions complete. There's still some work that needs to be done in the converter.

**Comment by Hotell** [comment]
Since 5.beta we have no default renderer, so all specific preact typings needs to be moved to renderer-preact and skate defs needs to be updated as well. Everything is ready here https://github.com/Hotell/reactive-typesafe-webcomponents/pull/1

will submit PR's soonish ! ;)
