### ISSUE TITLE
lost props when creating multiple instance of a component simultaneously

### ISSUE THREAD

**Issue by freeman** [skatejs/skatejs#1111]
When creating multiple instance of a given component in 1 shot through this kind of code: 
```js
var host = document.querySelector('#container');
host.innerHTML = '<x-hello-world name="first"></x-hello-world>' +
  '<x-hello-world name="second"></x-hello-world>';
```

Only the second one will render with the right name props. The first one will have an undefined name props during render.

**Comment by Hotell** [comment]
Closed by https://github.com/skatejs/skatejs/pull/1110
