### ISSUE TITLE
enable easier debuggability by using symbol descriptions

### ISSUE THREAD

**Issue by freeman** [skatejs/skatejs#1112]
The `Symbol` function allows passing description which is then visible in object inspectors. This would probably ease debuggability in case such as #1111 .

Would you mind a pull request modifying the sym() function to allow it to use such an argument ?

I would probably make it mandatory and change every usage of it but if you'd rather not tell me and I would make it optionnal.

**Comment by treshugart** [comment]
I think optional is best, as this reflects the built in `Symbol()` function. I think it should append / prepend the descriptor to the unique id so that even if the same key is used, it's kept unique.

**Comment by freeman** [comment]
Closing as #1116 is merged in `5.x`
