### ISSUE TITLE
Template string support

### ISSUE THREAD

**Issue by matthewp** [skatejs/skatejs#1132]
I'm just thinking-out-loud here, so feel free to ignore this. I'm wondering if there should be anything done to make using template strings a little bit easier in 5.x. I guess with Preact using hyperx should be as simple as:

```js
import { h } from "preact";
import hyperx from "hyperx";

const hx = hyperx(h);

hx`
  <div>Hello world</div>
`
```

Is it worth doing anything about this?

**Comment by matthewp** [comment]
Like, if there were a hyper-preact this could be simplified to:

```js
import hx from 'hyper-preact';
```

But I'm not sure this is worth the savings.

**Comment by treshugart** [comment]
You should just be able to plop that in `renderCallback()`:

```js
import { Component, h } from 'skatejs';
import hyperx from 'hyperx';

const hx = hyperx(h);

class MyElement extends Component {
  renderCallback() {
    return hx`<div>Hello World</div>`;
  }
}
```

**Comment by matthewp** [comment]
Yeah, my only issue was that it is lame to have to write `const hx = hyperx(h)` in every component file. But, nothing that Skate should be concerned with, so closing.

**Comment by Hotell** [comment]
or you can build your own renderer 

https://github.com/skatejs/project/blob/master/meetings/2017/04-07.md#renderer-api

**Comment by matthewp** [comment]
Oh! Can I attend the next one of those meetings?

**Comment by Hotell** [comment]
yes sir !
