### ISSUE TITLE
TodoMVC style example?

### ISSUE THREAD

**Issue by curioustechizen** [skatejs/skatejs#114]
Is there an end-to-end example that showcases skatejs? Something along the lines of todomvc? If not, would you accept a pull request?

I'm evaluating frameworks that would help me implement my relatively small web app following the principles of web components. Polymer is just too big for this particular use case. I would like to give skatejs a try. The documentation and the talk at SydJS are pretty detailed, but it would be best to look at an end-to-end example to figure out what it involves.

**Comment by shenrunfu** [comment]
My question might not be relevant to the topic of this thread, but I wonder how it handles the IE8/9 users as I know Atlasssian has used this library in production. Thanks.

**Comment by treshugart** [comment]
@shenrunfu We support IE9 but no longer support IE8. If you want IE8 support you need to polyfill mutation events yourself (it's doable) but I can't guarantee that Skate's code will run in IE8's non ES5 compat engine.

**Comment by treshugart** [comment]
We've submitted an issue to the TodoMVC repo for adding Skate.

https://github.com/tastejs/todomvc/issues/1306

**Comment by arthurvr** [comment]
As an FYI for anybody looking here, we said that a PR was welcome :) https://github.com/tastejs/todomvc/issues/1306#issuecomment-105055798

**Comment by treshugart** [comment]
Forked TodoMVC. Will start work in about a week. cc @alexreardon

**Comment by alexreardon** [comment]
#### TodoMVC contribution guidelines:
https://github.com/tastejs/todomvc/blob/master/contributing.md

#### Base app template
https://github.com/tastejs/todomvc-app-template

**Comment by alexreardon** [comment]
Branch created with our work on this one:
https://github.com/skatejs/todomvc

**Comment by arthurvr** [comment]
Forgot to say: feel free to ping me if you need any help or have any questions.

**Comment by alexreardon** [comment]
This is making good progress. The application itself is finished, just fleshing out the tests

**Comment by alexreardon** [comment]
Skate has undergone some significant changes in the last 1-2 weeks. It would be worth reevaluating our current implementation and whether it could be done differently in light of the changes. /cc @treshugart

**Comment by treshugart** [comment]
It definitely could be done simpler now. I have some unpublished changes that I'm working on against master, at the moment. I say we don't PR back to TodoMVC until 0.14 or 1.0.

**Comment by treshugart** [comment]
For posterity: 

- https://github.com/skatejs/todomvc/tree/skatejs/examples/skatejs
- https://github.com/skatejs/todomvc/tree/skatejs/examples/skatejs-dom-diff

They've both been called out in the `README` and we'll hopefully be submitting them once we get a chance to run them through the automated tests and fix any outstanding items.

I'll close this now as those examples are pretty close to what they should be and are now browsable by anyone.

Let me know if you have any questions.
