### ISSUE TITLE
Create an es-latest build

### ISSUE THREAD

**Issue by matthewp** [skatejs/skatejs#1142]
This build will be to support ES2016 environments.

**Comment by treshugart** [comment]
I'd say that the criteria for this is that you should technically be able to load `skatejs/es-latest` in Safari TP and everything should work. The only blocker for this is dependencies. For example, if you use `Component` or `withComponent`, it tries to `import ... from 'preact'';` which will break it. What's the best way to solve this? cc @justinfagnani (I just saw your issue in Incremental DOM :))

**Comment by matthewp** [comment]
Does @justinfagnani have some super-secret build of Chromium or did he build from source himself? I had to test with this: https://github.com/matthewp/do-modules-work and not in Canary yet.  Safari though!

To answer your question @treshugart, we would need a babel plugin that rewrites the module identifiers to their full paths. So that 

`import './with-module';` becomes `import './with-module.js';`

And 

`import 'preact';` becomes `import '../node_modules/preact/preact.js';`

**Comment by treshugart** [comment]
There must be a babel plugin for that.

**Comment by Hotell** [comment]
Good article to es2016 raw environments

https://www.contentful.com/blog/2017/04/04/es6-modules-support-lands-in-browsers-is-it-time-to-rethink-bundling/

**Comment by matthewp** [comment]
I added a build in 3984e4f064ea3005d27e907d49d79f038c5226a9. Going to check it against my fritz and see if it works. Also going to give the babel plugin idea a shot.

**Comment by matthewp** [comment]
I can confirm that fritz builds and runs fine with this change. So its just a matter of seeing if we can get this to run in Safari.

Conceptually this babel plugin is very similar: https://github.com/unpkg/babel-plugin-unpkg-rewrite/blob/master/modules/index.js . Except that we'll be resolving to the module's path, instead of using a CDN. So I'll use that a basis.

**Comment by matthewp** [comment]
Got it working locally!  Not quite PR ready.

![screen shot 2017-04-25 at 10 50 41 am](https://cloud.githubusercontent.com/assets/361671/25391873/3b9a14c2-29a5-11e7-872c-864436b24785.png)

**Comment by treshugart** [comment]
Exciting!

**Comment by matthewp** [comment]
The one downside is that it needs to copy over preact to `es-latest/preact` because preact is not web-compatible and must go through the same babel plugin. I filed https://github.com/developit/preact/issues/670 to see if they are open to having a web-compat build too.  If so then we could point skatejs to that during out own build.

**Comment by matthewp** [comment]
This is mostly ready on my end. Waiting to see if there's feedback on https://github.com/developit/preact/issues/670.  If so, I'll create a PR there first.  Otherwise will have to change the build in skatejs so that preact is copied into `es-latest/preact`.

**Comment by treshugart** [comment]
I wonder if the tool you're building can have two modes:

1. transform path to point to existing directory
2. copy target to relative path and rewrite to that

**Comment by matthewp** [comment]
Well, to be clear I'm not building a "tool", just a couple of babel plugins. I don't think we need to create any tool for copying the target.  I think the way the plugins works makes that case easy:

```json
         [
           "modules-map",
            {
              "preact": "preact/dist/preact.esm"
            }
         ],
         "modules-web-compat"
```

This maps "preact" over to the ESM build that I submitted as a PR to preact.  If that doesn't get accepted for some reason we can just copy preact to the `es-latest/` folder, and change that map to point to `./es-latest/preact/dist/preact.esm` or whatever is needed. Just an extra npm script probably.

**Comment by treshugart** [comment]
Cool, that looks awesome!

**Comment by treshugart** [comment]
Discussed with @matthewp yesterday via hangout:

It looks like we'll change `es` to publish ES latest code instead of ES5 + ESM like NWB does by default.

**Comment by matthewp** [comment]
Currently blocked waiting for https://github.com/developit/preact/pull/675 to be merged/released.

@treshugart, I can't remember, did we decide to not use nwb for this build (since we couldn't figure out how to get it not to set default presets/plugins)?

**Comment by treshugart** [comment]
@matthewp I think we should *try* to use `babel-preset-env` with NWB. If that doesn't work, we can pass an option that we detect in the NWB config and turn on the ES build with different options and turn off the UMD build.

**Comment by Hotell** [comment]
maybe I'm too biased (a @treshugart  would say :D ) but this config via nwb/babel plugs looks like shooting yourself in the foot.

With TS it's just one config https://github.com/Hotell/typescript-lib-starter/blob/master/tsconfig.json
and one liner in npm scripts https://github.com/Hotell/typescript-lib-starter/blob/master/package.json#L22

just saying [whistling] :) :D

**Comment by matthewp** [comment]
I'm pretty sure TypeScript doesn't replace module specifiers with full paths [like described here](https://github.com/skatejs/skatejs/issues/1142#issuecomment-295805604) though.

**Comment by treshugart** [comment]
We'll stick with the Babel stack for now.

This should be fairly trivial to implement by switching out Babel configs. The extra config / code we'd have to write will suck, but I'm not sure using TypeScript and Babel together is any better - two configs, two separate transpilers and push code between the two. At least with this method, everything is still contained within Babel and NWB.

Our prepublish should look something like:

```bash
nwb build && nwb build --es
```

In the config we do something like:

```js
const { es } = yargs().argv;

module.exports = {
  esModules: es,
  babel: es ? esConfig : umdConfig
}
```

**Comment by treshugart** [comment]
Will be fully fixed up in #1181.

**Comment by treshugart** [comment]
Going to raise a separate issue for making stuff web compat.

**Comment by treshugart** [comment]
Created #1189.
