### ISSUE TITLE
Consider adding decorators for properties mapping  in 5.*

### ISSUE THREAD

**Issue by majo44** [skatejs/skatejs#1146]
I think much more readable and simple way for declare the mapping between properties and attributes (or adding 'obsevable' properties is to use decorators like where property decorator factory is taking optionally PropertyOptions: https://github.com/skatejs/skatejs/blob/master/src/ts-typings/api.d.ts#L61

Compassion of current and proposed solutions

```
// with props static 
 class A extends skate.Component<{ name: string; }> {
    name: string;
    static get props() {
      return {
        name: { attribute: true }
      };
    }
    renderCallback() {
      return skate.h('div', `Hello, ${this.name}`);
    }
  }
 
// with decorator
 class A extends skate.Component<{ name: string; }> {
    @property({ attribute: true })
    name: string;

    renderCallback() {
      return skate.h('div', `Hello, ${this.name}`);
    }
  }

**Comment by treshugart** [comment]
Hey, definitely not opposed to this, but I think this would qualify as a non-core feature. @Hotell is working on an accessory repo which could facilitate this.

@majo44 Could you please update the description and add a comparison to how you'd normally do this so that there is a point of comparison? Thanks!

**Comment by majo44** [comment]
@treshugart Maybe this will be no bad idea to separate this to some add-on package.

**Comment by Hotell** [comment]
Heyo! Yes it will be in separate repo. We already use it for blaze elements   https://github.com/wc-catalogue/blaze-elements/blob/master/packages/common/decorators.ts used like     https://github.com/wc-catalogue/blaze-elements/blob/master/packages/select/Select.tsx   which uses skate 4., I'm on Vacation till May 8th so I'm won't be able to do anything till that time :D 

Lemme know if you'll have any further questions. Thx

**Comment by treshugart** [comment]
I've been thinking a lot about this lately. I really like this approach as it gives you the ability to declare typed properties and links from attributes at the same time. I feel this is possibly one of the only ways to do this. Maybe it's worth having a `prop()` function exported from `WithProps()` that works like a decorator in core?

**Comment by treshugart** [comment]
All of this works now:

```js
import { Component, prop, props } from 'skatejs';

class MyComponent extends Component {
  static props {
    foo: props.any
  }

  @props.array
  bar: array

  @prop({ ...props.string, ...{ attribute: true })
  baz: string
}

MyComponent.props = {
  qux: prop({ ...props.string, ...prop({ attribute: true }) })
};
```

This retains the existing functionality, but also brings back a similar style as before that enables the simple decorator / typing approach.
