### ISSUE TITLE
Publish 5.0 prerelease?

### ISSUE THREAD

**Issue by jescalan** [skatejs/skatejs#1148]
Any chance you could publish a prerelease of 5.0 so I can start tinkering with it? Pulling directly from github means I can't get the built source. 💖

**Comment by treshugart** [comment]
Yeah, good point. @matthewp you were talking about doing this. Did you want to do it?

**Comment by Hotell** [comment]
https://img.memesuper.com/a749ca9109d14af6cf467ccba01f0528_just-do-it-shia-labeouf-just-do-it-memes_960-540.jpeg

**Comment by matthewp** [comment]
I can publish an alpha based on the current 5.x if that works for everyone.

**Comment by treshugart** [comment]
Alpha sounds good!

**Comment by matthewp** [comment]
<img width="605" alt="screen shot 2017-04-25 at 12 54 35 pm" src="https://cloud.githubusercontent.com/assets/361671/25397464/59f354a4-29b6-11e7-9347-abe1eab9ce45.png">
