### ISSUE TITLE
Skate doesn't initialise elements on registration for IE9

### ISSUE THREAD

**Issue by cyberdash** [skatejs/skatejs#115]
When `skate()` is called, normally this initialises elements that already exist on the page.

This does not occur when the `skate()` call is in the `<head>`, as the DOM is not ready.

It usually works in Chrome and other browsers due to the `debounce()` function's `setTimeout`, but this behaves inconsistently in IE9 (it usually runs debounced function before the DOM is ready.)

**Comment by treshugart** [comment]
Fixed in #116.
