### ISSUE TITLE
build: choose between clang/prettier/semistandard for linting

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#1158]
as discussed previously https://github.com/skatejs/skatejs/pull/1118#discussion_r112497202 we should consider prettier vs clang or just stay with semistandard

**Comment by treshugart** [comment]
We'll probably have to have some level of linting no matter what to catch potential perf pitfalls etc. This is stuff that prettier cannot do for you. That said, I ran Skate through Prepack yesterday and it worked just fine. The output came out a bit big, and I ran into some friction when trying to enable minification on the output. This has something to do with how NWB passes plugins to Webpack and how Webpack 2 automates minification for a prod build.

**Comment by Hotell** [comment]
I was thinking that prettier replaces eslint ?

If not we should proabably stick with what we have now and we can close this.

Or clang is a good alternative -> works for js, ts

**Comment by treshugart** [comment]
Prettier would take the burden off of us having to worry about formatting. ESLint forces the user to make the changes etc. There's an eslint plugin, though!

Happy to just close. Can revisit if we start having formatting issues, but configurationless semistandard is 🆒

**Comment by Hotell** [comment]
yup yup, agreed
