### ISSUE TITLE
5.x alpha npm package is missing types.

### ISSUE THREAD

**Issue by freeman** [skatejs/skatejs#1168]
The `src` folder is not included in the package. I'd say bundle everything from src but you might keep only the `d.ts` files also.

**Comment by treshugart** [comment]
In the [flow-ts branch](https://github.com/skatejs/skatejs/blob/flow-ts-support/package.json#L57) both Flow and TS def files get pushed to the `umd` folder. Is this sufficient? I'm also assuming we'll need to publish them to the `es` folder, too, if bundlers decide to take that over `umd`.

**Comment by freeman** [comment]
The folder in which they are pushed does not really matter as long as:
* the `types` `package.json` key points to the right file (the type description of the skatejs package as a whole)
  * this does not seem correctly configured yet on your branch
* and they are included in the `files` key

In the mean time would you mind pushing a new alpha with the types included ?

**Comment by treshugart** [comment]
@freeman can you have a look at #1173, please?

**Comment by treshugart** [comment]
Published skatejs@5.0.0-alpha.4.

**Comment by treshugart** [comment]
I ended up just publishing `src/` for now.

**Comment by Hotell** [comment]
types are published just once, referenced by entrypoint from `"typings": "path/to/index.d.ts"` we should move it to `types` folder or so

**Comment by treshugart** [comment]
Yep, but just waiting to see what happens with the generation. Was simpler to not have to move stuff around.
