### ISSUE TITLE
docs/chore: what online tool should we use for starters/demos

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#1172]
This issue is just to brainstorm/come to common conclusion what to use.

currently -> we use jsbin for demos in git-book

after #1118 is merged -> we will use codepen

Trey is using webpackbin a lot, I've started to use recently https://codesandbox.io/ ( which is great for non-trivial examples )

feel free to discuss folks @treshugart @matthewp

**Comment by treshugart** [comment]
CodeSandbox looks awesome 👍. Lol at how it markets itself via React but will work for anything, though. WebpackBin is my second choice due to the simplicity of imports and transpiler options.

**Comment by Hotell** [comment]
LOL exactly CodeSandbox  -> right, It's kinda annoying that you have to `import {Foo} from './Foo.jsx'` and add `@jsx h` in every file. otherwise very nice tool

**Comment by treshugart** [comment]
Let's stick with webpackbin for now, if that's cool.
