### ISSUE TITLE
5.x + ts: Property 'slot' does not exist on type 'JSX.IntrinsicElements'

### ISSUE THREAD

**Issue by mattdsteele** [skatejs/skatejs#1174]
I'm in the process of migrating a project (TypeScript, with JSX) from 4.x to 5.x. I think I have most of the changes in, but I'm getting compiler errors with code like this:

    renderCallback() {
        return (<slot></slot>);
    }

The error I'm seeing is: `[ts] Property 'slot' does not exist on type 'JSX.IntrinsicElements'.`

Using skatejs@5.0.0-alpha.4, typescript@2.3.2, preact@8.1.0

I see an [open TypeScript issue](https://github.com/developit/preact/pull/621) on the Preact repo, is that related perhaps? Should I hang back on using 5.x with a TypeScript project for a while?

/cc @Hotell

**Comment by Hotell** [comment]
yup that's definitely related + definitions in 5.x are generated with one problem -> the generator is not generating jsx definitions which should be mitigated by preact. BUT! yup preact has not good jsx definitions.

I don't now how quick will this be resolved on preact side as they stopped my PR.

We have working definitions at work -> private repo which are overriding preact's defs so we can work without hassle

**Comment by Hotell** [comment]
As a quickfix you can extend missing Intrinsic Attributes. Typescript is extendable like a boss

create `global.d.ts` in your root
```
declare namespace JSX {
     interface IntrinsicElements {
         slot: HTMLProps<HTMLSlotElement>;
     }
}
```

although your bug is strange because latest Preact typings define `slot`
https://github.com/developit/preact/blob/master/src/preact.d.ts#L688

**Comment by mattdsteele** [comment]
Yes, that looks like it was caused by this bit of code:

```
declare global {
    namespace JSX {
        interface IntrinsicElements {
            'up-groupbox-heading': GroupboxHeadingProps & Partial<HTMLElement>
        }
    }
}
```

Removing it fixes the `slot` binding (and don't need to add the global for Slot either).

But, that breaks when I try to use the component elsewhere:

    // in groupbox.tsx:
    import GroupboxHeading from './groupbox-heading';

    renderCallback(): any {
        return ([
            <slot name="heading">
                <GroupboxHeading>{this.heading}</GroupboxHeading>
            </slot>,
            <div class="groupbox-content">
                <slot></slot>
            </div>,
            <slot name="footer"></slot>
        ]);
    }

With the error `[ts] JSX element type 'GroupboxHeading' is not a constructor function for JSX elements.
  Property 'state' is missing in type 'GroupboxHeading'.`

I'm kind of cargo-culting my way through this, so I might be doing multiple things wrong!

**Comment by Hotell** [comment]
right,

- so first thing that may cause issues is that Preact uses obsolete pre TS 2.x era style of TS modules 

just via `declare`

so this may be clashing with the compiler 

```ts
declare global {
    namespace JSX {
        interface IntrinsicElements {
            'up-groupbox-heading': GroupboxHeadingProps & Partial<HTMLElement>
        }
    }
}
```

try using just 
`declare namespace JSX {` in your custom `my-components.d.ts` file

- second

I assume `import GroupboxHeading from './groupbox-heading';` that `GroupboxHeading ` is skate component? 

If yes, this won't work 
- It's on of 5.x  BREAKING CHANGEs. You have to use  just html like native WC signature ( we discussed this with @treshugart , I don't remember if he submitted PR to Preact so Preact knows that constructors/functions are WC and renders them appropriately )
- next BC is that Preact doesn't support arrays as return from render function so you have to wrap in it root VNode ( although React 16.x will allow this, maybe future versions of Preact @developit ? )

- so you need to do :
```ts
import {h,Component,define} from 'skate'
import './groupbox-heading';

export class MyComp extends Component<void>{

static get is(){ return 'my-comp' }

renderCallback(): any {
    return (
       <div>
        <slot name="heading">
            <GroupboxHeading>{this.heading}</GroupboxHeading>
        </slot>,
        <div class="groupbox-content">
            <slot></slot>
        </div>,
        <slot name="footer"></slot>
       </div>
    );
}
}

export default define(MyComp)
```

Pls correct me if I'm wrong @treshugart 

thx!

**Comment by developit** [comment]
@Hotell I wonder if there's something that can be done to get that PR merged?  People only seemed hesitant because of the size, it definitely looked like an improvement when I read through it.

**Comment by Hotell** [comment]
> I wonder if there's something that can be done to get that PR merged? People only seemed hesitant because of the size, it definitely looked like an improvement when I read through it.

Yeah I know @developit , will re-evaluate and will try to create new ones in smaller pieces although as I've said, it's already chunked in atomic commits...

**Comment by developit** [comment]
Yeah. Personally I'm fine with commits, but I guess it makes discussion a little more difficult? I'm not the best with Git in the first place haha

**Comment by mattdsteele** [comment]
Thanks for your help. I've got my component upgraded, so I'll close this one out and let y'all work through the more general work on the Preact PR.

Let me know if there's anything I can do to help move it forward. Thanks!
