### ISSUE TITLE
feat: functional stateless web-components support

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#1184]
This is an idea for discussion. If agreed I will implement it

There are use cases where user doesn't need anything else just `renderCallback` + maybe some props. For these use cases it would be more convenient to be able use just function, like P(r)eact does. 
Implementation should be straightforward

---

**Updated** after review during https://github.com/skatejs/project/blob/master/meetings/2017/06-01.md

---

```jsx
import { define, props } from 'skatejs'

const Button = ({color,type}) => {
  const className = someLogic(color, type)
  return (
      <button class={className}><slot/></button>
  )
}

// this is optional as we generate unique Id's
Button.is = 'my-btn'

// this is needed only if your web component needs to have custom API properties
Button.props = {
 type: props.string, 
 color: props.string
}

// generic define that consumes both functions or classes
export default define(Button)
```

which would transform in runtime to:

```jsx
class Button extends Component {
   static is = 'my-btn'
   static get props(){ return { color: props.string, type: props.string } } 

  renderCallback({color,type}) {
    const className = someLogic(color, type)
    return (
      <button class={className}><slot/></button>
    )
  }

}
```

cmp usage:

```html
<my-btn type="sucess">Done</my-btn>
```

**Comment by treshugart** [comment]
I think this is a matter of subjectivity. Personally, I'd much prefer to write the class approach; incorporating `is` and `props` in the class definition is arguably cleaner because you're not setting them out of context.

If you want to write SFCs, you can simply write them as Preact (or whatever renderer you're using) SFCs. Am I missing something objective?
