### ISSUE TITLE
Only the first dashed attribute is managed when defining my own property type

### ISSUE THREAD

**Issue by linsolas** [skatejs/skatejs#1186]
Hello everyone,

I'm currently using skatejs `5.0.0-alpha.9`.

I'm trying to define a new type of attribute, which is almost the same as the `props.object` but with a slight difference (i.e. it can parse JSON written with simple quotes instead of forcing the usage of double quotes).

My component is as follow:

```ts
import { h, Component } from 'skatejs';

type MyProps = {
  foobar: any;
  bazbaz: any;
}

class MyComponent extends Component<MyProps> {
  static get props() {
    return {
      foobar: Object.freeze({
        source: true,
        attribute: true,
        default: Object.freeze({}),
        serialize: JSON.stringify,
        deserialize: (obj: any) => {
          console.log('deserialize 1', obj);
          return JSON.parse(obj);
        }
      }),
      bazbaz: Object.freeze({
        source: true,
        attribute: true,
        default: Object.freeze({}),
        serialize: JSON.stringify,
        deserialize: (obj: any) => {
          console.log('deserialize 2', obj);
          return JSON.parse(obj);
        }
      })
    };
  }

  constructor() {
    super();
  }

  renderCallback({foobar, bazbaz}: MyProps) {
    console.log('foobar', foobar);
    console.log('bazbaz', bazbaz);
    return (
      <div>
      </div>
    );
  }
}

customElements.define('my-component', MyComponent);
```

And its usage is:

```html
<my-component foobar='{"foo": "bar"}' bazbaz='{"baz": "baz"}'>
</my-component>
```

It works as expected, the JS console is displaying the following information:

```
deserialize 1 {"foo": "bar"}
deserialize 2 {"baz": "baz"}
foobar Object {foo: "bar"}
bazbaz Object {baz: "baz"}
```

Now, I want to use dash-separated names for these properties. The component is exactly the same, except for the name of the attributes which are now camelCased.

```ts
type MyProps = {
  fooBar: any;
  bazBaz: any;
}

class MyComponent extends Component<MyProps> {
  static get props() {
    return {
      fooBar: Object.freeze({
        source: true,
        attribute: true,
        default: Object.freeze({}),
        serialize: JSON.stringify,
        deserialize: (obj: any) => {
          console.log('deserialize 1', obj);
          return JSON.parse(obj);
        }
      }),
      bazBaz: Object.freeze({
        source: true,
        attribute: true,
        default: Object.freeze({}),
        serialize: JSON.stringify,
        deserialize: (obj: any) => {
          console.log('deserialize 2', obj);
          return JSON.parse(obj);
        }
      })
    };
  }

  constructor() {
    super();
  }

  renderCallback({fooBar, bazBaz}: MyProps) {
    console.log('foo-bar', fooBar);
    console.log('baz-baz', bazBaz);
    return (
      <div>
      </div>
    );
  }
}

customElements.define('my-component', MyComponent);
```

And its usage is:

```html
<my-component foo-bar='{"foo": "bar"}' baz-baz='{"baz": "baz"}'>
</my-component>
```

Only the first attribute is managed (in that case `foo-bar`, but it can be `baz-baz` if the latter is defined before the other attribute in HTML).
The console log now shows:

```
deserialize 1 {"foo": "bar"}
foo-bar Object {foo: "bar"}
baz-baz Object {}
```

I think the issue is mainly on how I define my property, since if I set the properties as direct `props.object`, it works:

```ts
class MyComponent extends Component<MyProps> {
  static get props() {
    return {
      fooBar: props.object,
      bazBaz: props.object
    };
  }
  // ....
}
```

and in console:

```
foo-bar Object {foo: "bar"}
baz-baz Object {baz: "baz"}
```

Is it a bug, or is something wrong in the definition of my property type (sorry, the official documentation still rely on v4, and this part seems to have been changed).

Thanks in advance.

**Comment by Hotell** [comment]
Hey thx 4 report!

first of, you are using wrong api,

there is no `source` allowd on property object

Here is your example working and fixed

https://codesandbox.io/s/Kr8pp1Y3J

problem is when you use `attribute:true` which is not recommended ( perf reasons -> 2 way property attribute reflection ), so maybe we have bug in that use case @treshugart  ?

**Comment by treshugart** [comment]
If we can confirm that `attribute: true` is a problem, then yeah, it'd be a bug.

**Comment by Hotell** [comment]
yup my example confirms that

**Comment by linsolas** [comment]
Thanks you all for the details

**Comment by sugendran** [comment]
Tried to repo the issue, but I'm not sure if I've mis-understood the bug.

https://github.com/sugendran/skatejs/commit/c4f2fa40095cffe457c5cc643ce3b5b7abf4ccd4

**Comment by treshugart** [comment]
Here's a simplified reproduction: https://codesandbox.io/s/oqy3oozx9z.

**Comment by treshugart** [comment]
What's interesting, though, is when I write this test for it, it works:

```js
// @jsx h

import { define, name, props, withComponent } from 'skatejs';
import { mount } from '@skatejs/bore';
import { h } from '@skatejs/val';

const Elem = define(
  class extends withComponent() {
    static is = name();
    static get props() {
      return {
        aB: { ...props.string, ...{ attribute: true } },
        cD: { ...props.string, ...{ attribute: true } }
      };
    }
    render({ aB, cD }) {
      return `
        <div>
          <p>${aB}</p>
          <p>${cD}</p>
        </div>
      `;
    }
  }
);

test('https://github.com/skatejs/skatejs/issues/1186', () => {
  const elem = mount(<Elem />);
  elem.node.setAttribute('a-b', 'test 1');
  elem.node.setAttribute('c-d', 'test 2');
  return elem.wait(() => {
    expect(elem.has(<p>test 1</p>)).toBe(true);
    expect(elem.has(<p>test 2</p>)).toBe(true);
  });
});
```

**Comment by treshugart** [comment]
As a side note, however, we generally consider two-way attribute reflection an anti-pattern. There's some use-cases for accessibility and styling, but you can usually work around not needing it even in those cases. I think it's worth continuing to investigate this, but your properties will work so long as you use the default one-way.

**Comment by treshugart** [comment]
This shouldn't be an issue in `@skatejs/element` anymore.
