### ISSUE TITLE
Make esnext output web compat

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1189]
References #1142, https://github.com/matthewp/babel-plugin-modules-web-compat/pull/4.

The `exnext` build works in well in Node and bundlers, but won't work in a browser because they're not relative paths.

**Comment by justinfagnani** [comment]
I'm very interested in what your solution here is, especially for importing external modules like Preact. Our current plan is to assume all packages are siblings and import like '../preact/...'. Some tools aren't ready for that though.

**Comment by matthewp** [comment]
Same here, becomes messy with scoped package names though.

**Comment by matthewp** [comment]
@treshugart  is the es-latest folder the place to do this? Or do you want another one?

Also, given that https://github.com/developit/preact/pull/675 hasn't been accepted, would you be open to a stopgap solution where we copy preact to es-latest/preact (running it through the web-compat babel plugin)?  The downside is that we get the version of preact we have installed locally when publishing.

**Comment by treshugart** [comment]
@matthewp we've renamed it to `esnext` to match the option of the same name in the `package.json`.

> The downside is that we get the version of preact we have installed locally when publishing.

Yeah, that's a toughie. We place a peer dependency on preact, so it wouldn't be installed by default, but the other downside is that we choose (and bundle) the version for them which may not be ideal, especially if they want to dedupe their own (correct me if I'm speaking from the bum).

What would it look like if we didn't do anything about Preact yet?

**Comment by justinfagnani** [comment]
This just wouldn't work without a bundler, which would be unfortunate. Is there anything holding up on the Preact end? I didn't see any objections.

**Comment by treshugart** [comment]
That's what I thought.

Do browsers tree shake this stuff yet? Like if I import Skate but don't want to use Preact, it will still download it even if I'm not referencing any code from it, right?

**Comment by matthewp** [comment]
No, browsers don't do that. They can't, really, tree shaking requires examining the entire dependency tree. Rollup does "load" unused deps, it just doesn't include them into the final bundle.

So yeah, the only options are to bring Preact in (since its src/ code is not web compat we'd have to run it through the babel plugin) or wait for the ES module build to be released there. I have no problem waiting.

**Comment by matthewp** [comment]
Preact released 8.2 with an ES build, so I can take this on now.

**Comment by matthewp** [comment]
@treshugart one of [these presets](https://github.com/skatejs/skatejs/blob/5.x/package.json#L68) is converting to CommonJS, any idea which one it could be?

**Comment by treshugart** [comment]
@matthewp no idea. I've looked at all the corresponding plugins for the presets and nothing really makes sense.

- https://babeljs.io/docs/plugins/preset-react/
- http://babeljs.io/docs/plugins/preset-es2016/
- http://babeljs.io/docs/plugins/preset-es2017/
- http://babeljs.io/docs/plugins/preset-stage-0/
- http://babeljs.io/docs/plugins/preset-stage-1/
- http://babeljs.io/docs/plugins/preset-stage-2/
- http://babeljs.io/docs/plugins/preset-stage-3/

**Comment by matthewp** [comment]
Yeah, it's weird, i'll stick a debugger and see what is going on.

**Comment by matthewp** [comment]
This is done.

**Comment by treshugart** [comment]
I think I may have broken this recently. I'll look into it.

**Comment by kito99** [comment]
FYI, I was able to get the esnext build working in Chrome by adding a ".js" extension to all of the imports.

**Comment by treshugart** [comment]
@kito99 cheers for that. I've just fixed this in d255fbf11c9d54ead31cbabf78a3688e07b43b89.
