### ISSUE TITLE
Add option to render synchronously on every prop set

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1191]
References #1190.

It would simplify usage in certain environments (tests / ssr) to render sync after every prop set / on connected so that there doesn't have to be any deferred code.

This is done for performance reasons (see #1190 for rationale), so we would retain the sane defaults we currently have and allow it to be overridden at the risk of the consumer.

The way I propose to do this is by using a getter / option in the `WithProps` mixin that sync renders if it is truthy. Implementors would then write a base class or patch at the global level as they see fit.

We could discuss environment checking and render sync in certain environments, but I feel that this could lead to more unexpected issues.

**Comment by matthewp** [comment]
Asynchronous rendering is one of the unspoken nice things about web components. Frameworks with their own component model have to put a lot of work into scheduling rendering; it's easy to do with custom elements + shadow dom as you have *real* encapsulation

I don't see a great reason to have synchronous rendering. It might encourage bad practices like outside consumers of a component depending on implementation details (such as what happens inside of `.shadowRoot`.

As long as props change synchronously the component *should* appear synchronous from the outside. What is happening inside of the shadowRoot shouldn't be relevant, imo.

**Comment by treshugart** [comment]
I've always shared @matthewp's viewpoint here but just wanted to open this up as a discussion point in light of the other issue. I don't have any motivation to ever implement this but if someone has a valid use case, feel free to comment.

**Comment by majo44** [comment]
Hi, back to topic. I see , and clearly understand your pint. But As I know I always able to overwrite default impl by 
```
class CE extends Component {
    constructor() {
        super();
        this._updateDebounced = this._updateCallback.bind(this);
    }
}
```
so maybe you can consider to made this a 'public' api ?

**Comment by matthewp** [comment]
That sounds reasonable to me.

**Comment by treshugart** [comment]
Maybe the `withProps()` mixin can provide a getter for turning it off, or something.
