### ISSUE TITLE
Immutability of data structures in SkateJS

### ISSUE THREAD

**Issue by fredyagomez** [skatejs/skatejs#1192]
How does SkateJS control immutability when changing data structure inside a skatejs component? To change internal state in skatejs, I do skate.props then mutate the respective value.

I would love to do something that does not change the value but creates a new element although don't know if there is a real benefit of doing so.

**Comment by treshugart** [comment]
By default Skate does a shallow reference check, so mutation won't queue a render, if that's what you were wondering. If you want to reassign an object, you can do something like:

```js
elem.someProp = Object.assign({}, { newValue }, elem.someProp);
```

Or use object spread:

```js
elem.someProp = { ...{ newValue }, ...elem.someProp);
```

**Comment by treshugart** [comment]
Hey Fredy, thanks for posting that from the email. I converted my response to a comment so it could be official :). Closing now as it seems you have gotten the answer you needed. Cheers!
