### ISSUE TITLE
Best way to assign initial state to a variable from a prop

### ISSUE THREAD

**Issue by fredyagomez** [skatejs/skatejs#1194]
I have a prop object which I want to assign as an initial state of a variable inside a web component. 

In React, I usually use this to assign this initial value from a prop.
```
constructor(props){ 
    super(props); 
    this.state={ initialValue: props.value }
} 
```

I tried below for any reason I can't reach my prop. Any other approach I missed in the documentation?

```
static get props () {
    return {
      initialValue: {
        initial (elem, data) {
          return elem.__SKATE_DATA.props.value;
        }
      }
    };
  }
```

**Comment by treshugart** [comment]
The `initial` option is being removed in 5.0. You can do exactly the same thing you're doing with React:

```js
constructor () {
  super();
  Object.assign(this, whateverYouWant);
}
```

**Comment by fredyagomez** [comment]
Make sense but here is where I get stuck because `whateverYouWant` is a value coming from outside the webcomponent as a prop.  I am trying to find where my props are stored, and it looks like this one has them -> __SKATE_DATA.props, but when I assign this value, it does not get assigned as I was expecting.

```
constructor () {
  super();
  console.log(Object.keys(this));
  Object.assign(this, newValue: this.__SKATE_DATA.props.data.internalValue);
}
```

**Comment by treshugart** [comment]
If it's coming from outside the component and being set on it, then you shouldn't have to re set it. I'm not sure what you're trying to accomplish.

**Comment by fredyagomez** [comment]
I wanted to assign the value only when **it mounts** so I can update it later. I do get your point about resetting the value though so txs for the info.

**Comment by treshugart** [comment]
Okay, I just wasn't sure what this was trying to do. Feel free to reopen if you have any further questions :)
