### ISSUE TITLE
UMD asks for Preact via CommonJS require

### ISSUE THREAD

**Issue by bedeoverend** [skatejs/skatejs#1195]
Seems the UMD in latest 5.0.0 build (alpha-10) tries to load in Preact via `require`. When loading skate UMD into the browser (using [unpkg](https://unpkg.com/skatejs@5.0.0-alpha.10/umd/skatejs.js) - rogue require statement is down the bottom) it throws `required is not defined`. It'll still try to `require` even if `preact` is available on the global object before loading in the script.

**Comment by DanDeMicco** [comment]
Was playing around with jsfiddle and noticed this too. https://jsfiddle.net/azt8q1db/

**Comment by treshugart** [comment]
Yeah, this is definitely an issue rn. I'll investigate.

**Comment by treshugart** [comment]
I've published `5.0.0-beta.14` which should fix this. It moved the bundling to Rollup because `webpack-externals-plugin` was generating the `require()` and I had no idea how to not do that. We get a 600 byte reduction too! Let me know if this is still an issue.

**Comment by bedeoverend** [comment]
Yup works a treat 👍 thanks! +1 for using Rollup and saving bytes, so good.

Only thing to note is it'll fail unless preact is already globally available, but this is expected yeah?

**Comment by treshugart** [comment]
Yeah, expected. I wish there was a better way around it. Don't need preact if importing files directly from `es`, `esnext` or `node`.

**Comment by bedeoverend** [comment]
I think that's fair, just a caveat of using UMD's - feel like they're usually just for testing / playing around anyway.

**Comment by treshugart** [comment]
It might be okay if we don't export Preact's `h` directly as then it would be lazily used in `Component` only.

**Comment by treshugart** [comment]
Another thing we could do is have a `@skatejs/renderer-preact` and just advise on using that by default.

**Comment by bedeoverend** [comment]
Would this potentially be a stepping stone to splitting out renders as mixins...? FWIW I'd be very keen for that

**Comment by treshugart** [comment]
Created #1217 for splitting it out. We'll still recommend Preact as the default and the docs examples will be written with it.
