### ISSUE TITLE
Let's build a skatejs website 🤘

### ISSUE THREAD

**Issue by matthewp** [skatejs/skatejs#1202]
This issue is meant for discussion of what a skatejs website might look like and entail. One thing @treshugart and I discussed is if there was some editable code. https://emotion.sh/ does that. Another is the format, we might just start with a single page with a "why SkateJS" section and a "Getting started" with some code samples. I did something similar with https://fritz.work/.

I'm going to mock up an idea or two and drop them in here.

---

EDIT by Trey: some things we need to make sure we cover:

- [x] Tag line?
- [x] <strike>Use lit-html for the website renderer</strike> <- we'll do this later. Keep Preact for now.
- [x] <strike>Should be statically rendered using skatejs/ssr (try using no JS for rehydration to dogfood it).</strike> <- while this would be amazing, there'd be quite a bit of yak shaving here. I've done much of it already, but since we're using webpack loaders, pushing it through node is impossible (and loaders are so convenient). What we'll do here is write a webpack plugin to pre-render certain pages.
- [x] integration / renderer docs
- [x] <strike>examples should be written in every major renderer, but the usage should be the same HTML, thus highlighting the benefits of CEs and SD.</strike> <- this is a lot of work and not every example needs a renderer. Having examples within each renderer doc would be nice, though. Not necessary for v1.
- [ ] Write docs for utilities: define, emit, link and shadow (new).
- [ ] Get CSS encapsulation working in Polyfill land (SSR did this for us 😅).

**Comment by fredyagomez** [comment]
@matthewp @treshugart Will this site contain a section to showcase examples? Following the approach from other libraries (Reacts, Polymer) a section where anybody can display applications with source code about cool web component examples will help enormously to implement the library.

**Comment by treshugart** [comment]
@matthewp following our discussion, what you've proposed sounds great. I look forward to seeing what you come up with.

@fredyagomez yeah, so @matthewp's suggestion about using emotion or something like that would help cover that I think. We'll see as it evolves.

**Comment by matthewp** [comment]
I haven't started on this yet, but hope to soon.

**Comment by matthewp** [comment]
A way too early version:

![screen shot 2017-09-02 at 1 32 46 pm](https://user-images.githubusercontent.com/361671/29997518-47ca652c-8fe3-11e7-85c2-a199ba3f42c1.png)


Note that I spent 1 minute coming up with the subtitle, let's brainstorm on a better one. What is the *essence* of what skatejs is?

# Layout

I was thinking, with the direction being skatejs as a set of mixins for constructing components and an emphasis on working with different renderers, to have different sections that show using skatejs with Preact, React, Vue, lit-html, etc.

# Cool tech stuff

* This uses `<script type=module>`. It would be cool if we could have this in production and fallback to a bundle for non-supporting browsers (which you can easily do using the `nomodule` attribute).
  * Would want to use H2 PUSH most likely (or at least Link preload headers).
* It therefore doesn't use JSX, but instead uses lit-html. Could have used Preact with raw `h()` calls.
* I know that @treshugart will want to use `@skatejs/ssr`, I'll need help getting that set up.

**Comment by treshugart** [comment]
Tag lines:

- Inclusive web components
- Web components for *everyone*
- ...

Other stuff:

- +1 on using lit-html. I <3 Preact but Lit definitely feels better suited for this.
- SSR is a must, I think. What you'll need should be https://github.com/skatejs/ssr#static-site-generation. However, this is already set up [here](https://github.com/skatejs/skatejs/blob/5.x/package.json#L74). `npm run site` builds the site and `npm run dev` runs it in watch mode. It's already configured to run on Netlify.

**Comment by treshugart** [comment]
> I was thinking, with the direction being skatejs as a set of mixins for constructing components and an emphasis on working with different renderers, to have different sections that show using skatejs with Preact, React, Vue, lit-html, etc.

I really like this idea. Each example should be done in the major renderers and where you use it is all just HTML, so that wouldn't change (possibly highlighting what web components were designed for).

**Comment by matthewp** [comment]
I'm going to convert the site I've worked on over to the `site/` folder and get an initial PR in. This way everyone can help iterate on it and its not blocked by my slowness.

**Comment by Hotell** [comment]
> its not blocked by my slowness.

there is no such a thing in OSS, just not enough of time  :D ! cheers @matthewp  :)

**Comment by matthewp** [comment]
Hey @treshugart, does `npm run site` not run Babel on code inside of node_modules?  I get this error message:

```
> ./node_modules/@skatejs/ssr/bin/index --babel config/babel.node --out public --no-rehydrate --src site/*.js

/Users/matthew/skatejs/node_modules/lit-html/lit-html.js:22
export function html(strings, ...values) {
^^^^^^
SyntaxError: Unexpected token export
```

lit-html doesn't have an ES5 version. I looked at `config/babel.node.js` but it doesn't exclude node_modules or anything. Is that something that skatejs/ssr does by default?

**Comment by treshugart** [comment]
@matthewp Yeah, I ran into that issue when testing the renderer. I just updated the build in b1a514f3c94b6542497b68e4c75dea1774b8dd2e and then fixed the site build in ba55779c0eb546c8bd5609671702c7c691d96f87.

**Comment by treshugart** [comment]
I've ticked off a couple items. I don't want to force us to use Lit right off the bat (thought it's awesome and we should try at some point). I also don't want to write the examples with every renderer (not every example needs one either).

The site is mostly done now. I'll update the main comment with the tasks necessary to consider it done.

**Comment by treshugart** [comment]
<img width="1012" alt="screen shot 2017-11-07 at 9 41 46 am" src="https://user-images.githubusercontent.com/136556/32467791-ea3adb4e-c39f-11e7-81ed-276eb474b32c.png">

@matthewp design hasn't changed much! 😄 

Right now it's sitting at a Lighthouse score of 95. It was 100, but then I added the polyfills. If we didn't have to conditionally load these (es5 shim only in native etc) we could keep it to 1 request when booting, giving us 100, even with the polyfill weight. However, we can't do that because we have to conditionally load certain ones and only then we can load the App and mount it.

**Comment by obedm503** [comment]
since this issue is still ongoing, it seems like a good place to report that links to the renderer docs are broken, for example preact docs link to http://skatejs.netlify.com/renderers/react instead of http://skatejs.netlify.com/renderers/with-react same for the other 2
![screenshot](https://i.imgur.com/WOA71YW.png)

**Comment by treshugart** [comment]
Thanks @obedm503, fixed!

**Comment by blikblum** [comment]
http://skatejs.netlify.com/ gives "Page not found" error.

**Comment by treshugart** [comment]
@blikblum cheers, it's broken right now because of Netlify. Some dependency can't be found when installing Yarn. Trying to fix.

**Comment by treshugart** [comment]
Ok, it's fixed now: http://skatejs.netlify.com/. I'm closing this as the site is pretty much complete in terms of a MVP for docs.

**Comment by blikblum** [comment]
Thanks.
Wondering the reason to switch from preact to lit-html

**Comment by treshugart** [comment]
@blikblum mostly to really test out what doing something with it on a larger scale would feel like in terms of DX. It accepts real DOM as parts (`${dom}`) so it's simpler when passing around custom elements as opposed to converting them to / from vdom, but that's a bit edgy. I love preact, so it was more out of interest.

**Comment by blikblum** [comment]
Visiting http://skatejs.netlify.com/, an "Uncaught TypeError: Cannot read property 'rest' of undefined" occurs. Just open devtools to see it. The site seems to work fine

**Comment by treshugart** [comment]
Yeah, that's because prismjs is being passed an empty, or incorrect value for the `lang` from inside the code component.
