### ISSUE TITLE
Missing dist at unpkg.com

### ISSUE THREAD

**Issue by MichaelBergquistSuarez** [skatejs/skatejs#1205]
The README mentions https://unpkg.com/skatejs/dist/index-with-deps.min.js.

It redirects to [https://unpkg.com/skatejs@5.0.0-alpha.12/dist/index-with-deps.min.js](https://unpkg.com/skatejs@5.0.0-alpha.12/dist/index-with-deps.min.js), which is missing.

Getting `Not found: file "/dist/index-with-deps.min.js" in package skatejs@5.0.0-alpha.12`.

If is has deprecated, the link should be removed from the README, otherwise the dist should be made available

**Comment by treshugart** [comment]
I think it just needs to be updated to point to skatejs@4. The 5.x alphas are currently latest.

**Comment by treshugart** [comment]
@MichaelBergquistSuarez did my last comment help?

**Comment by kylecordes** [comment]
BTW, the example in the documentation:

https://skatejs.gitbooks.io/skatejs/content/docs/examples/#counter

... currently does not run, I think because of this issue.

**Comment by treshugart** [comment]
Yes, that is because of this.

**Comment by treshugart** [comment]
Readme was updated awhile back and things now have proper fields in the package.json.
