### ISSUE TITLE
Can't use component constructors directly in 5.x

### ISSUE THREAD

**Issue by matthewp** [skatejs/skatejs#1206]
Want to make sure this is a bug, but I thought previously you could do this, no?

```js
import { Component, h } from 'skatejs';
import Header from './header.js';

class extends Component {
  renderCallback() {
    return h(Header);
  }
}
```

Where `Header` is another skate component. Or am I just wrong here?

**Comment by treshugart** [comment]
We had to hack this into the iDOM wrapper for 4.x and I've opened up a PR to Preact (https://github.com/developit/preact/pull/715) to enable this there (`h` is a direct export of Preact). To do what you want, you'd have to wrap `h` with https://github.com/skatejs/val.

**Comment by matthewp** [comment]
Ok, let's see where the Preact PR goes.

**Comment by treshugart** [comment]
Do you think it's worth not re-exporting `h` from Preact and to make the consumer do that directly?

**Comment by Hotell** [comment]
my proposal:
- preact is adopting new features way to slow ( ts defs tweaks, @treshugart PR )
- let's monkey patch preact's `h` within skate renderer package for preact

WDYT folks ?

**Comment by matthewp** [comment]
I think we're going to have to wrap with val for renderer-react, so why not also do so for renderer-preact?

**Comment by treshugart** [comment]
Yeah, might be a good idea to just export an `h` for both that is wrapped with `val`. Need to make sure tree shaking works with however we do it. I think generally many might just use the exports directly from the libraries themselves. Also need to make sure val API is what we want. Always catches me up that you have to do `attributes: {}`. Maybe it's not a big deal as long as we are very clear about what does what.

**Comment by treshugart** [comment]
I also mean what I say when I say `h` for both. I want to be consistent even if React does `React.createElement()`. If they want to use React directly, then they adjust the JSX pragma.

**Comment by chrisdarroch** [comment]
Potentially dumb question: Now that the renderer for Skate is split in to separate repositories (e.g., @skatejs/preact-renderer), does it even make sense for Skate to export an `h` function at all? What would its default behaviour be?

Perhaps this change is resolved by making the appropriate wrapped `h` in that preact-renderer repo, and not exporting `h` from skatejs at all?

**Comment by Hotell** [comment]
@chrisdarroch 
![image](https://user-images.githubusercontent.com/1223799/30782205-870f4382-a12d-11e7-9c59-1b7ef78dfc1d.png)

**Comment by treshugart** [comment]
Yeah, y'all are right. I'll close this. Can someone (I'm on phone and about to hit the sack) please raise an issue to discuss there? I'm hesitant to do this but would be better to discuss over there.
