### ISSUE TITLE
Shadow slot event listeners

### ISSUE THREAD

**Issue by cary-smith** [skatejs/skatejs#1207]
So I have a question which I have a workaround for but am interested in your thoughts:

Using skatejs 5.x and the power of preact, I am curious when I might be able to add a 'slotchange' listener to a shadowDOM slot element? I want to avoid accidentally adding multiple listeners, but be sure to reattach them if the slot element is replaced from a render. I thought about detaching and reattaching them per `renderCallback`, but that seemed excessive. 

Any thoughts? Maybe there is already a hook?

**Comment by alexlafroscia** [comment]
You should be able to bind an event to `slotchange` just like any other event in Skate's JSX -- was there a reason you were concerned about this approach?  I was able to debug `slotchange` events using the following (in Skate 5):

```javascript
import { Component, define, h } from 'skatejs';

import style from '../util/style.js';
import css from './styles.scss';

function log(event) {
  console.debug(event);
}

export default class SlotChangeEvent extends Component {
  /**
   * @property {string} is defines the component as slot-change-event
   */
  static get is() {
    return 'slot-change-event';
  }

  renderCallback() {
    return (
      <div>
        { style(this, css) }
        <p class="text">
          Hello, world! I am slot-change-event!
          <slot onSlotchange={log}></slot>
        </p>
      </div>
    );
  }
}

define(SlotChangeEvent);
```

**Comment by cary-smith** [comment]
DOH! I knew it was probably easier than I was thinking. This completely boils down to me not being as familiar with preact/react methodology as I should be.

Thanks @alexlafroscia !

**Comment by alexlafroscia** [comment]
No worries! Happy to help.
