### ISSUE TITLE
Skate 5: Using Props

### ISSUE THREAD

**Issue by alexlafroscia** [skatejs/skatejs#1208]
I've been fiddling with this for a long time now and just can't figure out how to set props on an Element.

My code currently looks something like this:

```javascript
import { Component, define, h } from 'skatejs';

import style from '../util/style.js';
import css from './styles.scss';

export default class MyComponent extends Component {
  static get is() {
    return 'my-component';
  }

  static get props() {
    return {
      value: { }
    };
  }

  renderCallback() {
    return (
      <div>
        { style(this, css) }
        <p class="text">
          This is the value: { this.value }
        </p>
      </div>
    );
  }
}

define(MyComponent);
```

Setting `value` on the component (in my case, through the Storybook setup in `generator-skatejs`) just doesn't produce any `value` on the component. I've tried every combination of `prop` and `props.string` I can think of but I've just had no success. How are you supposed to use this API now? 

The docs all mention things like `propString` and `propNumber` but I don't think those are actually in the source anymore.

I was expecting to be able to use something like this (similar to Skate 4):

```javascript
import { Component, define, h, props } from 'skatejs';

import style from '../util/style.js';
import css from './styles.scss';

export default class MyComponent extends Component {
  static get is() {
    return 'my-component';
  }

  static get props() {
    return {
      value: props.string()
    };
  }

  renderCallback() {
    return (
      <div>
        { style(this, css) }
        <p class="text">
          This is the value: { this.value }
        </p>
      </div>
    );
  }
}

define(MyComponent);
```

but that function needs to take some arguments that feel pretty funky to me, and @treshugart mentioned that that's not how to use it. Do you need to use `prop` _and_ `props.string` together in some way?

**Comment by alexlafroscia** [comment]
Okay, so I looked over the tests to try to get a handle on the syntax, and noticed that they all use the class property syntax (which isn't actually part of JS just yet). I installed that Babel plugin and suddenly it works!

```
import { Component, define, h } from 'skatejs';

import style from '../util/style.js';
import css from './styles.scss';

export default class MyComponent extends Component {
  static get is() {
    return 'my-component';
  }

  static props = {
    value: {}
  }

  renderCallback() {
    return (
      <div>
        { style(this, css) }
        <p class="text">
          This is the value: { this.value }
        </p>
      </div>
    );
  }
}

define(MyComponent);
```

How would one do this without the transform, though?

**Comment by bedeoverend** [comment]
@alexlafroscia so since #1146, I believe the `static get props` syntax is no longer supported - you'll need to use one of the method listed [here](https://github.com/skatejs/skatejs/issues/1146#issuecomment-310916054). IMO class properties (`static props = {...}`) is the cleanest, but will require a [babel plugin](https://babeljs.io/docs/plugins/transform-class-properties/). Otherwise just `MyComponent.props = {...}` after declaration ought to do it 👍 

You're right in using `props.*`, you don't need to call a function - that's only to support decorators I think. So a complete example:

```js
import { Component, define, h, props } from 'skatejs';

import style from '../util/style.js';
import css from './styles.scss';

export default class MyComponent extends Component {
  static get is() {
    return 'my-component';
  }

  static props = {
      value: props.string
  }

  renderCallback() {
    return (
      <div>
        { style(this, css) }
        <p class="text">
          This is the value: { this.value }
        </p>
      </div>
    );
  }
}

define(MyComponent);
```

**Comment by bedeoverend** [comment]
Ha - how's that for timing?

Without the transform:

```js
import { Component, define, h, props } from 'skatejs';

import style from '../util/style.js';
import css from './styles.scss';

export default class MyComponent extends Component {
  static get is() {
    return 'my-component';
  }

  renderCallback() {
    return (
      <div>
        { style(this, css) }
        <p class="text">
          This is the value: { this.value }
        </p>
      </div>
    );
  }
}

MyComponent.props = {
  value: props.string
};


define(MyComponent);
```

**Comment by alexlafroscia** [comment]
Gotcha. Thanks for that info, I appreciate it.

My gut reaction was that it's a little unusual to force non-standard syntax to use the library. Class properties are still [only in the proposal stage](https://github.com/tc39/proposal-class-fields). However, seeing the second example @bedeoverend kindly provided, where

```javascript
MyComponent.props = {
  value: props.string
};
```

also works, removed the requirement of the Babel plugin I suppose.

**Comment by treshugart** [comment]
@alexlafroscia @bedeoverend I also thought that it's kinda weird not to work with `static get props`, however using that requires a lot of work around memoising the "getting" and massaging of values when the first instance is created. Changing to this method to work with a setter means that we can just do it once outside of instance creation without any cache checking. It also enables working with decorators and types easier:

```js
class Hello extends Component {
  @props.string
  name: string;
}
```

As opposed to:

```js
class Hello extends Component {
  static get props () {
    return {
      name: props.string
    };
  }

  name: string;
}
```

**Comment by alexlafroscia** [comment]
I'm really excited for decorators... might look into using that instead. Should it work with both Babel and TypeScript decorators?

**Comment by treshugart** [comment]
So long as it follows the spec, it will work. I'm not sure about TypeScript, but I think they do.

**Comment by alexlafroscia** [comment]
Sweet. I'll try that out.

Thanks for the help, @treshugart and @bedeoverend!

**Comment by bedeoverend** [comment]
@alexlafroscia FWIW class fields have now reached stage 3, so they're pretty much guaranteed into the spec 🎉

**Comment by alexlafroscia** [comment]
Yeah, I saw that too! Makes me feel better about that being the official API in Skate 5
