### ISSUE TITLE
5.x - Props + Composition

### ISSUE THREAD

**Issue by deini** [skatejs/skatejs#1210]
With the new changes to props, I'm not entirely sure whats the best approach for handling props when composing/extending a component.

With the getter function I was able to do something like:
```js
static get props () {
  return {
    ...super.props,
    ...{ color: props.string }
  }
}
````

Not sure whats the best approach after the changes. Can't use `super` in a class property.

**Comment by treshugart** [comment]
You can do something like:

```js
// or static props = ...
ChildComponent.props = {
  ...ParentComponent.props
  ...{ color: props.string }
};
```

**Comment by deini** [comment]
Thanks @treshugart that makes sense 👍
