### ISSUE TITLE
Counter example doesnt work on ipad

### ISSUE THREAD

**Issue by staabm** [skatejs/skatejs#1215]
The jsfiddle mentioned in https://skatejs.gitbooks.io/skatejs/content/docs/examples/#counter renders a white page... seems the component doesnt work at all on ipad

Tested on iOS 10.3.3

**Comment by treshugart** [comment]
Interesting. I'll categorise it as a bug.

**Comment by Loilo** [comment]
Additional info:

The example doesn't seem to work anywhere. Tested Chrome on Android, Chrome, Firefox and Safari on macOS. It states that "skate is not defined".

**Comment by treshugart** [comment]
Yeah, I tried it too. It seems to be because the example is pulling latest but using code from 4.x. The bin should be pulling from latest `^4.0.0`.

**Comment by fredyagomez** [comment]
@treshugart I was playing with skatejs using the URLs provided to upload the library and can't find skatejs anywhere.

Here my experiment, what am I missing?

https://jsfiddle.net/fredygomez/hgLb0j2j/1/

**Comment by blikblum** [comment]
Try using https://unpkg.com/skatejs@4.6.7/dist/index-with-deps.js

Unpkg defaults to latest v5 release that does not have a proper dist file

See https://jsfiddle.net/L1otg3Lb/91/ for a working version

**Comment by treshugart** [comment]
@blikblum is correct here. That's the best solution for now. We're reworking the docs and will have this guaranteed working when they're done. I'll keep this open until then.

**Comment by obedm503** [comment]
the linked fiddle is broken, i'm guessing due to versioning again

**Comment by treshugart** [comment]
Closing this as the old sites have been decommissioned and the new site is up with working examples (https://skatejs.netlify.com). Native only for now. We'll implementing the shady CSS polyfill shortly (or using something simpler like css-in-js, for encapsulation).
