### ISSUE TITLE
Split out preact into @skatejs/renderer-preact

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1217]
After using Skate 5 alpha for awhile, I tend to like experimenting with other renderers. The downside to doing this is that, unless you import specific mixins, Skate is going to try and load Preact.

Moving Preact out into it's own renderer makes this very trivial. Renderers can then co-exist quite easily and follow a simple convention of `import { Component, h } from 'whatever-renderer'`.

**Comment by matthewp** [comment]
Does that mean you'll never really import anything from skatejs (unless you are building your own component from mixins?

**Comment by chrisdarroch** [comment]
As a library that is meant to help people author web components, it makes sense to me that out of the box, it'd help achieve that goal. The renderer probably doesn't matter all that much to first-timers, but matters a whole lot to more experienced devs.

In that capacity, I think it would make sense to:

* Bundle a default renderer in the dist of skate, and
* Allow more experienced devs to provide their own renderer.

The main question is: do you want to allow those more experienced devs to provide that renderer at build-time, or runtime?

**Comment by chrisdarroch** [comment]
the API we're thinking of going with would look something like this:

```
import { withProps, withUnique } from 'skatejs';
import { withPreactRenderer } from '@skatejs/renderer-preact';

const PreactComponent = withUnique(withProps(withPreactRenderer()));

class MyHello extends PreactComponent {
  renderCallback(data) {
    // this will be rendered via the Preact engine.
  }
}
```

Of course, Skate itself will still expose both a default `Component` that composes a no-dependency renderer, and the functions to compose your own renderer. The latter is what `renderer-preact` and friends would use under the hood.

**Comment by matthewp** [comment]
nit: I think `@skatejs/renderer-preact` should export a `withRenderer` function, not `withPreactRenderer`. Preact is redundant here, it's already in the package name. And since you're unlikely to be importing multiple renderers in the same file, there's no need to make the function names distinct (and there's import renaming if you need that).

**Comment by treshugart** [comment]
Opened #1218 as a WIP for this so we can contribute / discuss separately / async.

**Comment by treshugart** [comment]
I'm thinking renderers should conventionally export a mixin function and a base class where the base class. So like:

```js
import { withRender, Component } from '@skatejs/renderer-preact';
```

Where `Component = withRender()`.

I'm also thinking of renaming Skate's `withRender` to `withRenderer` because that's kinda what it is. It has no renderer yet, so can't "render".

**Comment by bedeoverend** [comment]
With the above proposal, would the exported `Component` bundle the `withUnique`, `withProps` etc? i.e. all the mixins that form the base Skate component apart from `withRender` mixin?

If it does, does that mean `withRender` includes them too? Basing that off:

> Where Component = withRender(

Also +1 for `withRenderer` 👍

**Comment by treshugart** [comment]
I'm actually thinking now that we don't export a pre-baked class. Consumers can do that if they want to. Maybe? Yay? Nay?

After thinking about the options, if renderers create pre-baked classes (i.e. `Component`) they they must place, *at least*, a peer dependency on Skate so they can load it and extend Skate's base. We'd have to do this if we wanted to make extending Skate's base a default, too. So what I think is to make renderers simply have a HoF that returns a class that extends `HTMLElement` by default. This makes the surface area super-minimal. Using it then becomes:

```js
import { h } from 'preact';
import { withComponent } from 'skatejs';
import { withPreact } from '@skatejs/renderer-preact';

class MyComponent extends withComponent(withPreact()) {}
```

If we wanted to take this the extra mile to give consumers a safe default, we could make `skatejs`  a composition of `@skatejs/core` and `@skatejs/renderer-preact`.

Just floating around ideas.

**Comment by bedeoverend** [comment]
My vote is for the former. Not much other than it just feels a lot cleaner, and personally that's what I prefer - though realise it might be annoying for people wanting to get up and running quick.

Though think it's fair to bundle and export `h` from `renderer-preact`, at least the option, and also the option to use `h` directly from Preact, so:

```js
import { h, withRender } from '@skatejs/renderer-preact';
import { withComponent } from 'skatejs';

class MyComponent extends withComponent(withRender()) {}
```

Agree with @matthewp that `renderer-preact` should export `withRender`, not `withPreact` given that implies from the package. People can alias when importing if needed

**Comment by treshugart** [comment]
> Agree with @matthewp that renderer-preact should export withRender, not withPreact given that implies from the package. People can alias when importing if needed

Fair. I also agree with "the former". I wonder how the Skate docs will look then. I guess we could just do that all the time and just show Preact by default everywhere?

**Comment by matthewp** [comment]
I say don't prebake a `Component` for the reasons you stated. If you really want to make it user-friendly you could then create `@skatejs/preact` that wires together skatejs and skatejs/renderer-preact. Would be a pain to maintain though!  

I feel like this might be a case of do what your gut tells you and wait for people to complain before changing it.

**Comment by chrisdarroch** [comment]
In my view, I'd want to pursue the "`skatejs` is a composition of `@skatejs/core` and `@skatejs/renderer-<sensible-default-lib>`".

I don't think the average punter wanting to get in to web components will care as much about the functional composition aspects as we do. They'll just want to get up and running with "skate", and the following things will be "weird" to newcomers:

* The setup takes longer and more pieces. You can't get started like some other component libraries by pulling in just the library -- e.g., this won't work:
    ```sh
    npm install skatejs
    touch my-component.js
    ```
    ```js
    import { Component } from 'skatejs';

    class MyComponent extends Component {
    }
    ```
    You need to pull in at least one other package -- a renderer for skate (which itself pulls in the templating lib). This leads to the second "weird" thing:
* The pattern for component creation "looks odd" compared to React/Preact/Polymer. We're mixing patterns of "classical inheritance" with functional composition. I mean, it works, but it's aesthetically odd and potentially confusing.

The newcomer's experience with Skate is as important as the flexibility of implementation. I'm a fan of giving that flexibility when it's needed, but having sensible defaults until that point in time.

**Comment by chrisdarroch** [comment]
Mmkay, setting the default behaviour of `skatejs` itself aside, it sounds like the consensus so far is:

* we create a new series of `@skatejs/renderer-<templatelib>` repos + npm packages.
    * these shouldn't depend on `skatejs` itself.
    * these will export a `withRenderer` function, and an `h` pragma function.
    * these will _not_ export a `Component` class.
* `skatejs` itself would expose a `withComponent` function.
* `skatejs` itself would not have a `Component` class, because it would couple the base with a specific renderer.

Let's follow this and see where it goes.

**Comment by treshugart** [comment]
Done! Done done done!!!

**Comment by Hotell** [comment]
whaaat now I have to redo my whole talk in 1 day 🗡 :D

this is awesome btw!
