### ISSUE TITLE
How access children and their props in parent component

### ISSUE THREAD

**Issue by keyvan-m-sadeghi** [skatejs/skatejs#1219]
I have a nested component:

```html
<top-level>
    <child-first order="1"></child-first>
    <child-second order="2"></child-second>
</top-level>
```

How can I access `order` for `child-first` and `child-second` in `top-level`'s definition?

To elaborate more, I have a hierarchy that describes some data and `top-level` should draw the whole thing in a canvas (PixiJS).

**Comment by treshugart** [comment]
In this use case specifically, you should probably use document order to determine order, as opposed to a property.

**Comment by keyvan-m-sadeghi** [comment]
Hi @treshugart, I don't have an `order` property in my actual component, just wanted to give an example. The actual nested components have properties like `x-offset`, `y-offset` and so on, `top-level` needs to iterate over them, extract these properties and paint them. Thank you very much.

**Comment by keyvan-m-sadeghi** [comment]
It's more like the below example:

```html
<top-level>
    <rectangle xoffset="200" yoffset="300" width="400" height="50">Some Text</rectangle>
    <rectangle xoffset="100" yoffset="200" width="300" height="50">More Text</rectangle>
</top-level>
```

**Comment by treshugart** [comment]
There's a few things you can do here in order of preferred methodology.

## 1. Use properties and arrays of objects

This is a prominent pattern in React but it's not limited to it. The idea here is that you provide an array of objects that describe each element and internally in the `top-level` component, you render them out.

```js
class TopLevel extends Component {
  static props = {
    items: props.array
  }
  renderCallback({ items }) {
    return (
      <div>
        {items.map(item =>
          <x-rectangle
            xoffset={item.xoffset}
            yoffset={item.yoffset}>{item.content}</x-rectangle>
        )}
      </div>
    );
  }
}

<TopLevel items={[{
  content: 'Some text',
  xoffset: 1,
  yoffset: 2
}, {
  content: 'Some text',
  xoffset: 1,
  yoffset: 2
}]}
```

## 2. Create a render function for rendering the objects

You can expand the previous example if you need to dynamically render each item:

```js
class TopLevel extends Component {
  static props = {
    items: props.array
  }
  renderItem(item) {
    return <x-rectangle
      xoffset={item.xoffset}
      yoffset={item.yoffset}>{item.content}</x-rectangle>;
  }
  renderCallback({ items, renderItem }) {
    return (
      <div>
        {items.map(renderItem)}
      </div>
    );
  }
}

<TopLevel items={[{
  content: 'Some text',
  xoffset: 1,
  yoffset: 2
}, {
  content: 'Some text',
  xoffset: 1,
  yoffset: 2
}]}
```

## 3. `assignedNodes()`

You can traverse the assigned nodes of a slot by calling `slot.assignedNodes()` on it. You have to be careful here not to mutate the child nodes. Elements should never mutate each other as this can break expectations of other parts of your component tree.

The problem here is that you need a way of triggering a callback whenever the assigned node tree changes. You can listen to the `slotchange` event on `<slot />` nodes but it doesn't get fired for the initial render sometimes so you end up having to do your work both in `connectedCallback()` *and* on `slotchange`. This isn't idea.

You can use something like this to listen to all light DOM children changing and perform some work on the next microtask: https://gist.github.com/treshugart/6bb7093a709b5cf1d52bc67a89c70709.

Your implementation might look like:

```js
class ChildrenChanged extends Component {
  connectedCallback () {
    super.connectedCallback();
    if (this.childrenChangedCallback) {
      const mo = new MutationObserver(this.childrenChangedCallback.bind(this));
      mo.observe(this, { childList: true });
      this.childrenChangedCallback();
    }
  }
}

class TopLevel extends ChildrenChanged {
  static props = {
    items: props.array
  }
  childrenChangedCallback() {
    // This causes a re-render.
    this.items = Array.from(this.children);
  }
  renderCallback({ items }) {
    return (
      <div>
        {/* traverse items here */}
      </div>
    );
  }
}
```

**Comment by keyvan-m-sadeghi** [comment]
Great! Thanks. I wasn't aware that `this.children` exists, i.e. `skate.Component` extends `HTMLElement` (I actually skimmed through the `skate.Component` code, clumsy me). And thanks for the detailed examples (didn't know about `MutationObserver` either).

**Comment by fredyagomez** [comment]
@treshugart I was playing today with version 4 skatejs and did something similar to what you guys did in this conversation except that I was updating the items object internally by pushing new objects.

Something similar to this:

```
class TopLevel extends Component {
  static props = {
    items: props.array
  }
  _onClick(){
    let { items } = this
    let newItems = items
   let object = {
      content: 'Some text',
      xoffset: 1,
      yoffset: 2
    }
    newItems.push(object)
    props(this, {items: newItems})
  }
  renderItem(item) {
    return <x-rectangle
      xoffset={item.xoffset}
      yoffset={item.yoffset}>{item.content}</x-rectangle>;
  }
  renderCallback({ items, renderItem }) {
    return (
      <div>
        {items.map(renderItem)}
        <button onClick={this._onClick.bind(this)}>Add new item</button>
      </div>

    );
  }
}

<TopLevel items={[{
  content: 'Some text',
  xoffset: 1,
  yoffset: 2
}, {
  content: 'Some text',
  xoffset: 1,
  yoffset: 2
}]}
```

The outcome is really interesting though. Initially, I can see my first two items, but as I start aggregating new items with the button, only the first skatejs element shows up, the rest does not render even though they appear in the DOM. In other words, they get inserted successfully but the browser only displays the first item, the other ones act like the tag was undefined.

```
<x-rectangle xoffset=3 yoffset=4>content1</x-rectangle>
<x-rectangle xoffset=3 yoffset=4>content1</x-rectangle>
<x-rectangle xoffset=3 yoffset=4>content1</x-rectangle> --> Only this one renders on the screen
```

**Comment by treshugart** [comment]
@fredyagomez Interesting. I'd recommend upgrading to Skate 5. It's very likely that you can just drop in the Preact renderer without doing much work. Check out the fantastic [migration guide](http://skatejs.netlify.com/migrating) written by @Hotell.

Something that you and @keyvan-m-sadeghi may also be interested in, is the ability to use the [`withChildren()` mixin](http://skatejs.netlify.com/mixins/with-children). It can probably do what both of you need here.
