### ISSUE TITLE
Break property debouncing into a separate mixin

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1222]
The mixin should:

- Contain the existing debouncing functionality.
- Override layout accessors (i.e. `offsetHeight`) so that it can sync render before retrieving and returning the overridden value. This means that when they're used they return the correct value.
- Possibly provide a way to turn off the debouncing functionality (this is up for debate because consumers could just compose their own mixins leaving this out).

The `withProps` mixins should retain:

- All `props.*` related logic, just with the debouncing part moved into the new mixin.

**Providing a way to sync render as API would be very useful here.**

**Comment by blikblum** [comment]
Wondering if will be any performance impact and/or increase in code complexity to sync the work done between each mixin (currently counting 4 to build default component class).

> Possibly provide a way to turn off the debouncing functionality (this is up for debate because consumers could just compose their own mixins leaving this out)

If an option to disable debounce is implemented, this proposed mixin no longer makes sense. It would be better add the option to withProps mixin.

**Comment by treshugart** [comment]
@blikblum I've added this functionality back into the, now, `withUpdate` mixin (renamed from `withProps` because it contains the idea of `state`, too).
