### ISSUE TITLE
build: don't compile classes for /es build

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#1223]
`/es` build output classes are compiled, so when someone want's to use webpack to bundle/chunk for evergreen browsers he has to explicitly include WC es5-shim polyfill. 

Is there any particular reason why we ship es/ this way ? I think it should be consumer responsibility to compile what he imports ( for both tree shaking and compile output )

**TL;DR:**

es/ should include similar output like esnext/ except for relative paths to preact and `.js` suffixes in imports

**Comment by Hotell** [comment]
Oh I completely missed "new Readme"

> If you want to deliver native classes, you can configure Webpack to pull in a version of Skate that's been transpiled to the latest ES specification. More about this approach is detailed in this blog post.

I don't like that explicit churn within webpack config but I guess that's best we can get as of today. Maybe some tiny function as npm module could be neat so users don't have to go through that article ceremony everytime ? Just thinking out loud here :)

anyway Closing

**Comment by treshugart** [comment]
I've since updated the 5.x build. It's now a bit more clear. It has specific babel configs for both es and esnext, where esnext is untranspiled classes and es is only import / export + es5.

**Comment by Hotell** [comment]
esnext is untranspiled everything not just classes right ?

**Comment by treshugart** [comment]
It will transpile everything to es2015. So you can use es2016 and es2017 and have a consistent target.

**Comment by Hotell** [comment]
yup, basically allows running skate + html-lit without ZERO build step

**Comment by treshugart** [comment]
Yeah, but I need to work out if I broke web compat imports in #1189 :p.

**Comment by Hotell** [comment]
whoops! :D
