### ISSUE TITLE
Multiple websites

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1225]
Hey hey, seems like there's three sites that need to be consolidated into one:

- http://skatejs.github.io/ (say docs are coming soon, but...)
- https://skatejs.gitbooks.io/skatejs/content (... there's docs)
- http://skate.js.org/ (And that's just 404)

'Twould be nice to have `skate.js.org` shows the content from `skatejs.github.io`, and the docs link go to the gitbook.

I know maybe you thought about it, but better now than later, so it's not difficult to find stuff on Google.

**Comment by Hotell** [comment]
heyo!, gitbook served us well and it's going bye bye :(

There is already plan for website https://github.com/skatejs/skatejs/issues/1202

**Comment by trusktr** [comment]
Oh, okay, great! Looking forward. :]

**Comment by treshugart** [comment]
Gitbook has served us very well, but there's two things I want to get out of a website:

1. Dogfooding. Need to use our code in anger.
2. Marketing. It's a good look to have a flashy, non-cookie-cutter docs site.

**Comment by trusktr** [comment]
> Dogfooding. Need to use our code in anger.

There's nothing better than inspecting a website and seeing the non-minified example code. :}
