### ISSUE TITLE
suggestion: Let's not stringify attributes, let's let setAttribute do that.

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1226]
https://github.com/skatejs/skatejs/blob/6783120020738b3f4f807be0e4f3758891b8e9c5/src/util/with-props.js#L81

^ That's passing a stringified version of a prop into setAttribute.

It is possible nowadays for Custom Elements to override or extend `setAttribute`. Libraries like A-Frame allow attributes to be non-string values in order to boost performance (rather than having to always convert strings back to numbers).

This is useful for 3D element, for example:

```
node.setAttribute('rotation', [20, 30, 50]) // x, y, z rotation
```

If libraries like Skate or React simply pass the raw values, Custom Elements can take advantage of the `setAttribute` API.

See:

- https://github.com/ngokevin/aframe-react/issues/101
- https://github.com/facebook/react/issues/10070

**Comment by treshugart** [comment]
I'm not a fan of doing this because everyone should just be using props. Outside of that, if you're writing HTML, you have to be using strings anyways and Skate will convert those to props that are linked.

If you want this, you could easily create a mixin for it:

```js
const withComplexAttributes = (Base = HTMLElement) =>
  class extends Base {
    getAtribute(name) {}
    setAttribute(name, value) {}
  }
```

And use it like:

```js
import { withComponent } from 'skatejs';

class MyComponent extends withComponent(withComplexAttributes()) {}
```

**Comment by bedeoverend** [comment]
I echo @treshugart's thoughts here. Changing the behaviour of `setAttribute` feels like an anti-pattern, where instead you should promote props for passing complex data.

Regardless of your stance on that though, shouldn't be baked - IMO it's just too opinionated for wide adoption.

**Comment by Hotell** [comment]
can this be closed ?

**Comment by timwis** [comment]
> Changing the behaviour of setAttribute feels like an anti-pattern, where instead you should promote props for passing complex data.

Could you elaborate on what you mean by props here? How would you set a prop if not via HTML attribute? Or do you mean instance properties, ie. `instance.propName = x` rather than skate's `static get props()` ?

**Comment by treshugart** [comment]
@timwis instance properties :)

Many DSL's and view libraries prefer props such as Preact, LitHTML (using lit-extended). Vue has a syntax for it, etc.

**Comment by timwis** [comment]
Ah, so it sounds like those view libraries somehow know to set a property on the instance rather than simply set a dom attribute. Interesting.

```html
<custom-element dataset={largeArrayOfObjects}></custom-elements>
```
Results in:
```js
customElementInstance.dataset = largeArrayOfObjects
```
Hope that's right. Thanks for taking the time to explain.

**Comment by treshugart** [comment]
Yep!

**Comment by trusktr** [comment]
> Changing the behaviour of setAttribute feels like an anti-pattern, 

Although that may or may not be true, perhaps it's better for the Custom Element author to decide that. It's about freedom. A CE author can easily make `setAttribute` accept non-strings (for whatever reason), so it'd be nice to "just pass values along" and let people decide what to do.

This isn't to say that instance propertied aren't preferred. I like those more, and I think it's cleaner to use those when possible, but not all view libraries follow that rule (there's at least hundreds of them).

**Comment by treshugart** [comment]
This can also be done via a mixing. Though, I'm unclear as to how it plays in with `attributes.someattr.value` and `attributeChangedCallback`. Feels like a lot of patching. This is my main reasoning for not doing this in core. A userland mixin might be a good place for it.
