### ISSUE TITLE
LitHTML vs HyperHTML

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1227]
HyperHTML seems to have wider browser support, maybe it's a good idea to use that?

See this table: https://gist.github.com/WebReflection/fadcc419f5ccaae92bc167d8ff5c611b

**Comment by treshugart** [comment]
I'm happy to have both. If you feel like writing a renderer for one, we're more than happy to receive a contribution. Hard part is creating a repo, but having a gist or something we can refer that's written in the same style of the lit html one would be a good place to start :)

**Comment by trusktr** [comment]
Yeah, managing another repo adds a lot of maintenance work. What about just having a folder for renderers in the main repo, but still publishing them as separate packages (perhaps even using something like [Lerna](https://github.com/lerna/lerna))?

**Comment by treshugart** [comment]
@trusktr we have a monorepo in skatejs/skatejs now, so it could just go there. More than happy to accept a contrib.
