### ISSUE TITLE
add to hnpwa?

### ISSUE THREAD

**Issue by tycho01** [skatejs/skatejs#1232]
Thanks for the library, looking forward to giving it a try!
Not sure if this is the right place for suggestions like this, but to give the project further exposure, I think it would be useful to provide an implementation for TodoMVC successor [HNPWA](https://hnpwa.com/). :)

**Comment by Hotell** [comment]
hmm, interesting Idea idea
- Me as PR guy - definitely we need to do this
- Me as Webcomponents evangelist - I dunno, like WC are awesome for reusable widgets not that much for whole apps ( yet ? ), for sure with skate, you can build whole apps without hassle, bud still 

👍  :D

**Comment by tycho01** [comment]
Yeah, going over that list I definitely got curious about how sizable the framework-WC gap really is. What I've managed to make out, comparing from an Angular background:
- change detection to minimize re-renders for performance: useful, but I've no idea how WCs compare here. orthogonal? different per WC library (skate, polymer, stencil)?
- state/route management: probably desirable, but even frameworks delegate these to external libs
- stuff I'm seeing in Angular:
  - http module: replaceable with rxjs observable http handling
  - i18n module: was worse than JS-based solutions anyway
  - form module: useful, I think
  - animations module: [allegedly](https://stackoverflow.com/a/43942861/1502035) they'd split this out, probably in a decade; in React I guess they just used CSS in JS, in WCs I don't even know. then again, first-world problem.

**Comment by treshugart** [comment]
> change detection to minimize re-renders for performance

 Skate does do this. There's a lifecycle hook called `propsChangedCallback()` that's like `shouldComponentUpdate()`. Why make this a thing when other libraries already do it? So that no matter what renderer you use, you can minimise the impact of unimportant property sets.

> state/route management: probably desirable, but even frameworks delegate these to external libs

Yup. I've been using [mobx quite a bit lately](https://github.com/treshugart/moolah/tree/c588cc49f84168efb88a048525b9da70a766986f).

I think a HNPWA definitely needs to be done. I disagree with @Hotell - it's a rarity! - here that web components aren't ready for full apps. The only difference between this and something else is you're offloading to a primitive component model that can be augmented, and you're adding native encapsulation. You're likely to see a performance boost as a result.

Sure, you generally need libraries if you're building web components, but that's a composite layer of abstraction. I think we're always going to want to use *something* at some point.

The only thing to worry about here is the rendering layer. Since Skate doesn't provide this, only hooks and pre-built integrations, we're subject to the performance characteristics of whatever we choose to build it with. When doing this, we need to make clear that we offload that aspect.

So, we should definitely do one. The question is, who in their spare time wants to do it 😛?

**Comment by Hotell** [comment]
**change detection:** 
- there is no such an overkill like angular does
- only source of truth are `props` like in React ( we also batch re-renders so it has even better perf == async pipeline )
- Stencil is doing basically the same what we do in term of rendering with one huge difference -> you can use only their implementation of VDOM ( hello locking in ! )

**state/route management:**
- I think @treshugart build already something tiny, again no rocket science like angular or so 👍 
- what's super powerful is that you can just use the platform (`import()`) for dynamically loading stuff without any nuclear bomb blowing off like angular or similar "solutions" does

**http**
- you can use what you want, I would go with `fetch` as it's baked within the platform, RxJs for doing Get is 🗣 🔫  :D

**DI**
- easily doable via mixins :)  ( react like principle of HOC ) again baked within the platform

**i18n**
- there are many existing tools, what I prefer nowadays is [i18next](https://www.i18next.com/)

**forms**
- doable 

**animations**
- WC is just javascript so doable as well :)

**Comment by Hotell** [comment]
>  I disagree with @Hotell - it's a rarity! - here that web components aren't ready for full apps.
@treshugart  😭  :D you are right dude ofc!

I'm up to do it! best way to dog food ( because currently we are not using skate at work :( ) + great topics for conference talks etc

**Comment by treshugart** [comment]
> I'm up to do it!

You're a legend as always, @Hotell! I'm happy to help here, too, I'm just not sure if I'll be able to do it all.

**Comment by Hotell** [comment]
> You're a legend as always, @Hotell! I'm happy to help here, too, I'm just know we're all really busy :)

haha thanks dude, but nah I'm just a person that is very interested in skateboarding not only in real life but also within the browser :D. All of this is happening thanks to your idea/vision 🍻 ;)

Sure I'm counting on it as a team effort but first things first, 5 stable out, PR, blogposts.... :P

**Comment by tycho01** [comment]
The above points sound pretty reasonable to me.

Angular did go all-in on Observables, yeah. This was part of their change detection strategy: any state (state lib, router) would be exposed through these, so the app could know it'd only need to update on new events from these or on manual triggers.

Or at least, that was the idiomatic way, as opposed to the free but less performant default (components can't know when to update so they have to keep checking).

**Comment by chrisdarroch** [comment]
I started building hnpwa in Skate, but ran in to setup problems, and ended up falling down the rabbit hole of learning "allthethings" about the web component polyfills :P 

@Hotell I'll race you toward having a completed app ;)

**Comment by chrisdarroch** [comment]
As an update to this request, I'm close to having a PWA built using Skate and lit-html. You can see the source here: https://github.com/chrisdarroch/skate-hnpwa/
 
App-wise, last few things I need to do are: proper routing, relative times, comment collapsing, and... well, actually add the service worker to it :P

Deployment-wise, I need to decide where I'll push it. Might use a trial Amazon thing. I could potentially push to Netlify if I re-use a CORS-friendly hackernews API and stop using back-end caching.

When I next get some spare time, I'll add the service worker and get some production-looking code ready to deploy somewhere.

**Comment by tycho01** [comment]
@chrisdarroch since it's just static assets, you could just use Github Pages like HNPWA Vue. :)

**Comment by treshugart** [comment]
No plans to do a nwpwa at this point, but may in the future.
