### ISSUE TITLE
How do we use this in IE10?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1233]
What's your recommendation on using transpiled-to-es5 elements in IE10 or 11?

**Comment by treshugart** [comment]
Most of the browser support information will come from https://github.com/webcomponents/webcomponentsjs#browser-support. We internally use `MutationObserver` to batch prop updates, but it will fallback to `setTimeout` if it's not available. Other than that it should work fine so long as the poly fills will work fine.

I'll come this as there's really no action from it, but happy to continue answering questions if you have them.
