### ISSUE TITLE
Skate 5: Questions

### ISSUE THREAD

**Issue by donifer** [skatejs/skatejs#1234]
👋  I have a couple of 5.x questions not sure where to ask them, feel free to close if this is not the right place:

1. Why does the `props` helper doesn't have a `function` type? Not exactly sure how to declare a prop (of type function) other than using `props.any`

2. Can someone explain me why/how is that if I define a prop called lets say `name`, why is `this.name` and `this.props.name` pointing to the same thing? Is this expected? If so, what should I be using? Setting/Reading directly from `this.name` or `this.props.name`?
Seems like sometimes if I set thing using `this.props.name` doesn't pick it up but when I do `this.name` directly it does, super confused with this one.

3. How can I define a property in the constructor (not as a prop) but when it changes, trigger the `renderCallback()`? Currently I can't make it trigger `renderCallback` unless I make it a prop. Usage: I have a "private" property that I don't really want to "expose" (I know that everything is exposed anyway) but I would like whoever uses my components to just read trough the props and expect those to be passed down (kinda like reading docs) and I don't want to confuse them having that "private" state property.

4. To avoid ^ I tried defining a prop using a Symbol as a name, but everything crashed, is there a way to do this?

5. Is there any docs on how to setup some basic testing with Jest?

**Note:** Using preact renderer if that matters

PS: Thanks so much for these mixins, I'm so happy using them.

**Comment by treshugart** [comment]
1. It might be a good idea to have this. We're definitely open to a discussion / PR here. I'm wondering if values should be "undefinable" or "nullable"?

2. `props` is a getter that returns an object of names / values for all `props` that are defined on the element. It's also a setter itself, but the object it returns doesn't react to changes, so you must set (`elem.props = {}`).

The second part to this is that when you want to get the names of all the props (own and inherited up the chain) you have to write a lot of code to go up the proto chain using getOwnPropertyNames etc. Using `props` you can just do something like `Object.keys(this.props)`.

Public API to the consumer is properties on the element (`elem.name`). However, internal to the component, feel free to use `props`.

We're also likely to introduce a concept of `state` so it can be tracked and used separately from `props`. It would simply be a `props` entry, but is great for tracking internal state.

3. This is the reason I want to introduce an idea of `state`. Currently you have to make it part of `props`.

4. This is a bug. Symbols should work and this is the ideal way to do it.

5. See https://github.com/skatejs/ssr#running-in-jest. If you have any questions feel free to ask them in that repo if it's unrelated to Skate.

> PS: Thanks so much for these mixins, I'm so happy using them.

That's so great to hear.

Let us know what you think about using a `state` prop.

**Comment by donifer** [comment]
>It might be a good idea to have this. We're definitely open to a discussion / PR here. I'm wondering if values should be "undefinable" or "nullable"?

Expanding this question, whats the current "best approach" for this? I'm guessing just not defining the prop but just setting it directly in the component?
Since I would love for my users to just read my defined props and know what to send, it would be ideal to have a function type. 

Can you explain to me about values should be "undefinable" or "nullable"? Do you mean like what should be the default value if the user doesn't pass anything to it? like if it should be null or noop?

>We're also likely to introduce a concept of state so it can be tracked and used separately from props. It would simply be a props entry, but is great for tracking internal state.

This in combination with Symbols would be ideal in my use case, would love to keep a bit of separation between internal / props.

**Comment by treshugart** [comment]
> https://extranet.atlassian.com/pages/viewpage.action?pageId=3506394081

Yes, exactly this. Also, If they pass null, should it also be coerced to a noop?

> This in combination with Symbols would be ideal in my use case, would love to keep a bit of separation between internal / props.

The thing about this is that if we use `state`, then it's public. If we use a symbol, it's not really any different than a consumer doing the same thing. I guess except that we might have it included with a base mixin, but is abstracting that away worth it? Maybe as it would illustrate best practice by having it included in the lib.

**Comment by donifer** [comment]
Interesting, I was actually referring about having `state` and then me as a consumer setting state names with symbols, not that all state should be symbols.

But now that you mention it being part of a mixing ... it might be useful, that would abstract away creating the symbols and assigning them to state keys. Not sure if the abstraction is worth it but it would be a nice to have. Maybe an opt-in mixin?

**Comment by treshugart** [comment]
I was talking about state being a symbol itself:

## Theoretical implementation

export const state = Symbol();
export const withState = (
  Base: Class<HTMLElement>
): Class<HTMLElement> => class extends Base {
  static props = {
    [state] = props.object
  }
}

## Theoretical usage

import { state, withComponent } from 'skatejs';

// withComponent would automatically mixin withState
export default class extends withComponent() {
  static props = {
    name: props.string
  }
  renderCallback() {
    const name = this.state.name || this.props.name;
    return <div>Hello, ${name}!</div>;
  }
}

**Comment by donifer** [comment]
>I was talking about state being a symbol itself:

Thats even better, I like this a lot.

The only difference I see is that we would have to use it with `this[state].name` if I'm understanding this correctly.

**Comment by treshugart** [comment]
> The only difference I see is that we would have to use it with this[state].name if I'm understanding this correctly.

Yep.
