### ISSUE TITLE
Concept of state as an internal props

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1237]
I've spoken to a few people lately and it seems that it'd be worthwhile to add the concept of internal "state" to components.

Since state is tied closely to the concept of props, I'm thinking we could just add this functionality to the `withProps()` mixin.

## Usage

The following describes the current state of `props` along with the new `state`.

```js
import { state, withState } from 'skatejs';

export default class extends withState() {
  constructor() {
    super();

    // This represents the public API.
    this.name = 'Trey';

    // This is identical to the above.
    this.props = { name: 'Trey' };

    // These are all the same.
    this.props = { [state]: { name: 'Trey' } };
    this.props[state] = { name: 'Trey' };
    this[state] = { name: 'Trey' };

    // These have no effect in terms of triggering a propsChangedCallback().
    this.props.name = 'Trey';
    this.props[state].name = 'Trey';
    this[state].name = 'Trey';
  }
}
```

## Implementation

The implementation can simply be a symbolised prop. Consumers can do this by themselves quite easily, but it requires them to provide boilerplate and have their own opinion. We have an opportunity to streamline this for them so they don't have to think about it.

```js
import { props } from './with-props';

// We don't use symbols yet, so we'd have to account for older browsers.
function sym(id) {
  return typeof Symbol === 'function' ? Symbol(id) : `__skate_${id}`;
}

// Should we prefix this with something (i.e. $/_)?
export const state = sym('state');

export const withState = (
  Base?: Class<HTMLElement> = HTMLElement
): Class<HTMLElement> =>
  class extends Base {
    static props = {
      [state]: props.object
    }
  }
```

It's likely that this isn't useful without the `withProps()` mixin anyways, so it might be better to simply include it as part of that.

## Related

We introduced a `props` setter because that used to be the way to update state all at once. While you could have done an `Object.assign(elem.props, {})` somewhere, it sort of made sense to have a counterpart to the getter. However, with the introduction of `state`, it doesn't make as much sense.

The `props` getter is definitely useful because then you don't have to merge prototype chains, however, I don't think the setter has much use if we introduce state because public props are for external APIs. Maybe it's worth doing:

- `props` becomes a symbol and has only a getter (maybe not?)
- `state` has both a getter and a setter

Thoughts welcome. This isn't a super drastic change, but I'm wary of making a breaking change on a beta.

## Bikeshedding

- Should we use a symbol?
- If so, should we have a naming convention?
- If not, does a pre-defined `state` prop work?

## Other

- Is this implementation too simple (are we not thinking of something)?

**Comment by Hotell** [comment]
As we discussed on twitter previously, when I showcase skate to devs they have really hard time to understand re-render concepts by triggering it via setting a prop. ( huh prop is mutable? what? )

**having separate API for state is a must**


I'm not ok for using symbols for this at this moment, again as we discussed, it is not type safe and currently  not able to type by any existing JS type systems
- just making it public prop on class instance for now, until private class properties hit Ecma specification and type systems implement it as well

> props becomes a symbol and has only a getter (maybe not?)
- just getter - totes
- symbol - nope because of reason mentioned above

> state has both a getter and a setter
- again this may be mind fuck for React devs, but otherwise it's better and easier to reason about as we don't get into issues like react when setting state etc. So 👍 

> This isn't a super drastic change, but I'm wary of making a breaking change on a beta.
bah It's beta you can do what you want until it's not RC nor sable :)

**Comment by treshugart** [comment]
> it is not type safe

Type systems are going to need to buck up for Symbols sooner or later, but that's a fair argument. This is why I converted symbolised props to underscored in the mixins.

> again this may be mind fuck for React devs

I'm not a fan of following another's API just for the sake of it. Getters and setters as props align better as an API. It's odd to have a `state` getter and a `setState()` function.

**Comment by treshugart** [comment]
This has been [implemented](http://skatejs.netlify.com/mixins)!
