### ISSUE TITLE
docs: migration from 4 -> 5

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#1239]
**Current behavior**

there is no public document about migration path from skate 4 -> 5

**Expected/New behavior**
create Migration.md 

I've already started this https://gist.github.com/Hotell/c100bd7b84a5297651c5ed5a9287385b

If you're ok I will add it to skate repo.

WDYT? @treshugart

**Comment by treshugart** [comment]
Yeah, add it to the website. Maybe branch of off @chrisdarroch's work and add it to the website.

**Comment by chrisdarroch** [comment]
Just merged #1230, so go nuts \o/

**Comment by chrisdarroch** [comment]
Having quickly skimmed what you've written @Hotell, it looks like we could write some codemods to ease the migration from 4 to 5. I'm happy to write the codemods based on the diffs you've provided :)

**Comment by treshugart** [comment]
> I'm happy to write the codemods based on the diffs you've provided :)

\o/

**Comment by treshugart** [comment]
@Hotell I've taken the migration guide you wrote up and landed it at: http://skatejs.netlify.com/migrating, with some minor alterations. Thanks again for writing that up. If anyone has anything to add / update, PR to the site. Cheers!
