### ISSUE TITLE
Try using sweet-changelogs / standard-version

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1241]
Commitizen and semantic release were nice, but it's really not that hard to bump and release yourself. Maintaining the changelog is what's difficult. I'm proposing we look at using https://github.com/Thinkmill/sweet-changelogs for maintaining them.

**Comment by Hotell** [comment]
I've been using [standard-version](https://github.com/conventional-changelog/standard-version) for all the things. top notch.

**Comment by treshugart** [comment]
I have not seen that. Looks awesome, Thanks! Will try.

**Comment by treshugart** [comment]
Will probably end up using `np` or `pika` in the future.
