### ISSUE TITLE
Skate 5 beta doesn't seem to work - Failed to construct 'HTMLElement'

### ISSUE THREAD

**Issue by madou** [skatejs/skatejs#1243]
## Bug report

- Skate version 5.0.0-beta.3
- Affected browsers (and versions): Chrome + ?

### Current behaviour

See: https://www.webpackbin.com/bins/-KxqpMvLkUXJMKfOTd3o

Error is thrown:
```
Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at GreetingComponent._class2 (dll.js:1923)
    at GreetingComponent._class2 (dll.js:1862)
    at GreetingComponent._class2 (dll.js:1692)
    at GreetingComponent._class (dll.js:1403)
    at new GreetingComponent (main.js:21)
    at Object.<anonymous> (main.js:48)
    at __webpack_require__ (bootstrap 09314f5d6dd10820f7bc:19)
    at bootstrap 09314f5d6dd10820f7bc:65
    at main.js:69
```

### Expected behaviour

Would expect it to work. Let me know if there anything wrong in the basic setup, but I was essentially just trying to copy the example in the readme. Does v5 need polyfills in Chrome?

---

Edit:

Reading: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Custom_Elements, looks like it says `Custom elements require using the class syntax introduced in modern versions of JavaScript.`. Perhaps this isn't working because babel is compiling it down to constructor functions. Will have a play.

**Comment by deini** [comment]
>Perhaps this isn't working because babel is compiling it down to constructor functions. Will have a play.

You are right!
Quoting the webcomponentsjs repo:
>According to the spec, Custom Elements must be ES6 classes.

Option 1:
There is a [custom-elements-es5-adapter](https://github.com/webcomponents/webcomponentsjs#custom-elements-es5-adapterjs) that you can use so you can still target es5.

Added it to your webpack bin example: https://www.webpackbin.com/bins/-Kxrl8AH_uKHUyk1EaK2

An important note is that the adapter must not be compiled and should only be loaded on browsers that support custom elements natively. 

Option 2: 
Don't compile to es5 and use skate's `esnext`build.
https://www.webpackbin.com/bins/-KxryR0cabcQ1QV0JAvI

--------------
@treshugart Not sure whats the best way to make it easier for newcomers, maybe a link to a working webpackbin for each example?

**Comment by madou** [comment]
@deini cool thanks man, will close this now.

would be good to mention these quirks somewhere in the readme :-) for newbies of course.

**Comment by treshugart** [comment]
> would be good to mention these quirks somewhere in the readme :-) for newbies of course.

I think you're right. It's called out pretty explicitly in the polyfill documentation, but I can see a major benefit in documenting it here, too. I'll raise an issue for it.
