### ISSUE TITLE
Give an opportunity to the renderer to perform clean when disconnected

### ISSUE THREAD

**Issue by freeman** [skatejs/skatejs#1244]
Not sure if it is a bug or a feature request ...

### Current behaviour

When a custom element if removed from the DOM, the `disconnectedCallback` is properly called but this does not cascade to the preact components below. This means the `componentWillUnmount` lifecycle method is never called in those.

This can lead to memory leaks as for example any subscription taken in the `componentDidMount` lifecycle will not be released properly when the custom element is removed from the DOM.

### Expected behaviour

skatejs  should notify the renderer so that the proper lifecycle methods of the renderer can be correctly triggered.

**Comment by Hotell** [comment]
Hmm interesting, thanks for report! maybe this should be opened directly on [renderer-preact](https://github.com/skatejs/renderer-preact) ?

**Comment by freeman** [comment]
You are right. Done. Feel free to close this one.

**Comment by freeman** [comment]
Since the monorepo migration, I am not sure the fix that happened in the previous repository has been ported back. Maybe we should reopen this issue ?

**Comment by treshugart** [comment]
Good point, @freeman. I think this can be done by providing a `disconnectedCallback()` in the renderer class. We should always be calling back to it anyways, and the default `withComponent()` implementation will automatically.

**Comment by treshugart** [comment]
This is starting to make me wonder if there should be a base `renderer-reactalike` for all things that follow the same component "spec".

**Comment by treshugart** [comment]
Using `@skatejs/element` you can now hook into the `disconnectedCallback()` to do this for all renderer subclasses.
