### ISSUE TITLE
Clarify the main skate.js site

### ISSUE THREAD

**Issue by kito99** [skatejs/skatejs#1245]
It's hard to figure out which site is the _official_ Skate.js site (besides the github site).

* The docs (https://www.gitbook.com/@skatejs) mention http://skate.js.org, which doesn't exist
* The git repo mentions http://skatejs.netlify.com/ which appears to be out of date
* http://skatejs.github.io appears to be the correct site, but it doesn't even point to the docs at https://www.gitbook.com/@skatejs.

**Comment by treshugart** [comment]
Yep, good point. To add some lol to this, the Netlify site is the future one.

**Comment by treshugart** [comment]
I've:

- Deleted the GitBook site (we still have the markdown docs in master)
- Redirected the github.io site to the Netlify site.

Thanks!
