### ISSUE TITLE
Call out polyfill / transpiled quirks

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1246]
References #1243.

We need to call out the issues when using transpiled classes. These are called out in the polyfill docs, so we could just list out the issues and link off to them.

**Comment by IamNotUrKitty** [comment]
Hello @treshugart , i think we can make skatejs working with es5, without adapter out of box, using this babel [plugin](https://github.com/WebReflection/babel-plugin-transform-builtin-classes) to build es version.

I made simple [demo](https://stackblitz.com/edit/es5-without-adapter) using skatejs version builded that way, pls check it. If you interested check this commit https://github.com/IamNotUrKitty/skatejs/commit/cc230875c899d3f4093685a893a4b05d50481b9c.
I think it's better than use adapter. Thank you.

**Comment by treshugart** [comment]
@IamNotUrKitty 

Interesting. I've never been able to get that to work. Maybe that's because I was building the consuming app with that transform as opposed to building Skate with it, which now makes sense!

What's the `Base` global in there for?

I'm happy to accept a PR for that. Would be great to call this out in the docs as well as the quirks and related stuff.

Would you be open to PR'ing the build fix as well as the docs? I'm happy to help with the docs aspect, as I'm aware that might be a harder thing for some to contribute to right now if they're not super familiar with the platform.

It might be good, for now, to just document this under [the Guides section](http://skatejs.netlify.com/guides) and call it out from the README. WDYT?

**Comment by IamNotUrKitty** [comment]
@treshugart 

> What's the Base global in there for?

Related to https://github.com/WebReflection/babel-plugin-transform-builtin-classes/issues/6 , We have two ways, on the advice of the plugin author to make the code "intent statically analyzable", or if in our context we always know class must be patched called Base, specify this in the plugin settings (I'm not sure what will be more correct).

> Would you be open to PR'ing the build fix as well as the docs?

For sure,I think for now we can specify in the documentation that the library works out of the box without having  the adapter, and then link to webcomponents to read more?

**Comment by treshugart** [comment]
Regarding `Base`, does that mean that it places the requirement on consumers to call things `Base`, or just us? I'm a little outside of my familiarity zone here, with that, so I apologise. If not, then I think it's a good idea to take that case into consideration.

> For sure,I think for now we can specify in the documentation that the library works out of the box without having the adapter, and then link to webcomponents to read more?

Yep! I think that's a great idea. Cheers!

**Comment by treshugart** [comment]
Current docs call out:

> For more information on the polyfills, see the web components polyfill documentation, emphasis on the caveats.
