### ISSUE TITLE
skatejs.netlify.com fails to load on Safari 11

### ISSUE THREAD

**Issue by roxeteer** [skatejs/skatejs#1247]
## Bug report

- Skate version: *unknown*
- Affected browsers (and versions): *Safari/macOS 11.0.1 (12604.3.5.1.1)*

The SkateJS website only shows a blank page on Safari 11.

### Current behaviour

The site doesn't load because of a JavaScript error:

```
[Error] TypeError: Constructor requires 'new' operator
	(anonymous function) (main.js:1:69053)
	c (main.js:1:69053)
	t (main.js:1:57184)
	t (main.js:1:55449)
	t (main.js:1:51620)
	t (main.js:1:47264)
	t (main.js:1:45770)
	t (main.js:1:48844)
	t (main.js:1:3594)
	t (main.js:1:73415)
	(anonymous function) (main.js:1:69538)
	t (main.js:1:106)
	(anonymous function) (main.js:1:1304)
	Global Code (main.js:1:1313)
```

This block throws the error mentioned above:

```javascript
function c() {
    return t(this, c), n(this, (c.__proto__ || Object.getPrototypeOf(c)).apply(this, arguments))
}
```

**Comment by treshugart** [comment]
Should be good now. Fills were loading async while app was trying to boot. Race condition. Try now. Thanks!

**Comment by roxeteer** [comment]
Works for me. Great job!
