### ISSUE TITLE
codebase: flow errors

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#1249]
## Bug report
- Skate version: *5.x*
- Flow version: 0.59
- OS: Windows 10
- Flow: 0.59

### Current behaviour
When `flow` is run multiple flow errors occur - within `/site` `/tests` and also within `/src`

![image](https://user-images.githubusercontent.com/1223799/32986880-82eaa4c6-cd2f-11e7-9dee-1cf18f6c4de0.png)

### Expected behaviour

no Flow errors

**Comment by treshugart** [comment]
We haven't Flow typed `tests` or `site` yet. I'm assuming this is why you might be getting errors withing `src`? Also, what version are you using?

**Comment by Hotell** [comment]
> We haven't Flow typed tests or site yet. 

so we have flow not configured correctly, it consumes all files ( that use // @flow ) which you use in various files in both /site and /tests, so we have invalid javascript :) ( one of "features" I really hate on Flow :P

> Also, what version are you using?
updated in description -> latest 0.59

**Comment by treshugart** [comment]
> one of "features" I really hate on Flow :P

I'm not sure I understand your point here. We don't have invalid JavaScript, just that only some files in site and all of src are Flow typed. Might just be a mis-configuration on my part.

**Comment by Hotell** [comment]
when you write type annotations to a javascript file, it's not valid javascipt ( unless you add `// @flow ` annotation ). It's just babel plugin "magic" that those types and annotations are striped . That's what I meant

**Comment by Hotell** [comment]
https://github.com/skatejs/skatejs/pull/1254#issuecomment-347489783
