### ISSUE TITLE
Use customElements.whenDefined() to set up props and add hooks

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1252]
We had ordering issues with `props` due to using a setter. One way to get around this would be to use `customElements.whenDefined()` to set up props.  In order to do this, we'd need to do the following:

1. Continue defining a getter and a setter
2. Simply set an internal prop with the value when setting `props`
3. `whenDefined` we get `props` and set them up with what's currently doing it in the setter

The problem with this is that in the `withProps` mixin, we have absolutely no idea what the tag name will be. To work with this, we might have to have a dependency on `withUnique`. I'm not sure this is the best idea because you can use components without that mixin, or bypass it entirely.

*I think this is a poor design choice in the spec, to have to use a name with `whenDefined`. It'd be much better to have `static defined()` callbacks.*

It'd be great, if we can work around this to then define custom lifecycle callbacks for `defined()`.

Does anyone have any ideas around this? cc @Hotell @chrisdarroch @matthewp 

If we can work around this limitation, then we should:

1. Fix setting up props so we can use a getter
2. Add a hook for `static defined()`

**Comment by chrisdarroch** [comment]
My rough thoughts... which I haven't really shit-tested with code:

Perhaps we can split `withProps` in to a curried mixin for creating the props and leaving a placeholder for the element's name, then turn `withProps` in to a combination of that mixin and `withUnique` by default?

We could then provide an alternative, synchronous `withProps` variant for those who know what they're doing, but `withProps` (and thus `withComponent`) will work out of the box as according to the spec, which will likely be the expected behaviour.

**Comment by treshugart** [comment]
> We could then provide an alternative, synchronous withProps variant for those who know what they're doing, but withProps (and thus withComponent) will work out of the box as according to the spec, which will likely be the expected behaviour.

Building on that idea, what if we just made `withUnique` define a `static defined()` callback. therefore it's 100% going to get called when defined. Then we could make `withProps` define a `static defined()`, so when it's used with `withUnique` it just works. We might also just be able to do this in the `constructor`. I remember having a difficult time with that in Skate 4, but maybe I'm just being silly now and over thinking it.

**Comment by Hotell** [comment]
So you have created the behaviour via `static defined()` within `withUnique` 
https://github.com/skatejs/skatejs/commit/7a413a77467fafbb213860f82a6cadbf08126f77

but 

> Then we could make withProps define a static defined(), so when it's used with withUnique it just works

is missing. is this desired behav or you forgot to implement it ? thx

**Comment by Hotell** [comment]
Also what do you mean by 
> We had ordering issues with props due to using a setter 
?

**Comment by treshugart** [comment]
@Hotell 

> is missing. is this desired behav or you forgot to implement it ? thx

I didn't implement the `withProps` definition for it yet. The `withUnique` implementation seems solid, I just want to think about the other one a bit more, I think.

> what "ordering" issues do you have in mind ?

The `renderer-react` package requires an order so that `children` gets properly defined.

**Comment by matthewp** [comment]
I don't quite understand the problem unfortunately. I've also never used whenDefined(). My understanding is that it is so that you can lazy-load element definitions and set props on them after they've loaded. I'm not quite sure the use-case in library code though..

**Comment by treshugart** [comment]
We now do this in `observedAttributes` as this is called right when it's defined and it's only called once.
