### ISSUE TITLE
types are not included in the latest release

### ISSUE THREAD

**Issue by cronon** [skatejs/skatejs#1253]
## Bug report

* Skate version: _5.0.0-beta.4_

package.json file says that types should sit in `src/index.d.ts`, but this file is not included in the latest release

**Comment by treshugart** [comment]
Bah! You're right. I'll see what I can do about that tonight. Are you able to ignore it for now?

**Comment by cronon** [comment]
Yes, I can wait a bit, thanks

**Comment by treshugart** [comment]
I'm wondering if we should be publishing types to a separate `types/` folder, or something. We'll have to do this for flow, too.

**Comment by treshugart** [comment]
I've pushed things into a `ts/` folder. Tests and `index.d.ts` files are in there for now.

**Comment by treshugart** [comment]
Hey @cronon, I've decided to remove the TS types for the foreseeable future. It's a pain having to maintain them along side a source not written with them. I'm happy if someone wants to take the types from git history and maintain them in definitely-typed, though. Unfortunately, I don't have time to continue maintaining them. If you have any questions, feel free to ask away.
