### ISSUE TITLE
devDeps: add flow-bin

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#1256]
### Current behaviour
- contributor needs to install flow globally without any restriction to flow version from our side

### Expected behaviour
- having exact flow version as dev dependency so every contributor uses the same version
- also adding explicitly flow version to .flowconfig via `[version] x.x.x`

if you're ok with this @treshugart I'll submit PR , thanks

**Comment by treshugart** [comment]
Fixed in 926fcaf :)
