### ISSUE TITLE
question: is it possible to return array of nodes from render()

### ISSUE THREAD

**Issue by cronon** [skatejs/skatejs#1266]
As title says. Is it possible to return array of nodes from render(). I'm building my own system of components, and my renderer can handle the case when several nodes are returned from render() method. So the question is, if skatejs would be fine with this behavior?

**Comment by treshugart** [comment]
Yes, there is no restriction on what you can return, so long as your renderer can handle it.

**Comment by cronon** [comment]
thank you @treshugart
