### ISSUE TITLE
@skatejs/ssr doesn't work with Jest@22

### ISSUE THREAD

**Issue by trescenzi** [skatejs/skatejs#1285]
## Bug report

@skatejs/ssr doesn't work with Jest@22 even with the addition of `setup` and `teardown` due to the dependency on `jest-enviroment-node@21`. This is because `expect(<mock>).toHaveBeenCalled` now calls `getMockName` which isn't defined in Jest@21. You can see this call [here](https://github.com/facebook/jest/blob/efe65d4d7b265e328f069df57661ba67594d5f9f/packages/expect/src/spy_matchers.js#L64).

* Skate version: @skatejs/ssr@0.18.0

### Current behaviour

`expect(<mock>).toHaveBeenCalled` throws `received.getMockName is not a function` when using with Jest@22.

### Expected behaviour

Honestly not sure. I'm fine with `@skatejs/ssr` not working with Jest@22 but currently it seems like it's half supported so I wanted to document that. Willing to contibute whatever is decided here but I'm certain if sticking with Jest@21 was the plan or upgrading was.

**Comment by treshugart** [comment]
Thanks for reporting. We should make it compatible with Jest 22, for sure. Happy to accept a PR if you have one in flight.

**Comment by trescenzi** [comment]
There's a few different ways it could be done not sure if you have a preference. We could update the dep on `jest-enviroment-node` to be `@22` which would probably be a breaking change if that matters. Or we could update `jest-environment-node` to be `^21 || ^22`. That probably makes the most sense if we want to keep compatibility with `21`. I _think_ that would work as expected.

I've been working with the `ssr` package to add `cloneNode`(for templates) and am close to a PR. I could add whatever you think makes sense for this to that PR which I hope to have up tomorrow morning.

**Comment by treshugart** [comment]
> I've been working with the ssr package to add cloneNode(for templates) and am close to a PR. I could add whatever you think makes sense for this to that PR which I hope to have up tomorrow morning.

That sounds sensible to me :). Thanks for hacking on it!
