### ISSUE TITLE
Improve documentation/site 

### ISSUE THREAD

**Issue by Javiani** [skatejs/skatejs#1287]
Hi, 

I was just looking for something just like this, this project seems to be going in the web standards direction which is a really good thing. However, It seems that documentation lacks sort of information and I think you could improve organization for better adoption and understanding.

I tried to do exactly the same as per documentation in order to generate the static site, and I get  always an error :

```
require('@skatejs/ssr/register');
const render = require('@skatejs/ssr');

class Hello extends HTMLElement {
  connectedCallback () {
    const shadowRoot = this.attachShadow({ mode: 'open' });
    shadowRoot.innerHTML = '<span>Hello, <x-yell><slot></slot></x-yell>!</span>';
    Promise.resolve().then(() => {
      const shadowRoot = this.attachShadow({ mode: 'open' });
      shadowRoot.innerHTML = '<strong><slot></slot></strong>';
    });
  }
}
class Yell extends HTMLElement {
  connectedCallback () {
    Promise.resolve().then(() => {
      const shadowRoot = this.attachShadow({ mode: 'open' });
      shadowRoot.innerHTML = '<strong><slot></slot></strong>';
    });
  }
}
customElements.define('x-hello', Hello);
customElements.define('x-yell', Yell);

const hello = new Hello();
hello.textContent = 'World';

render(hello).then(console.log);

```

```
TypeError: Promise resolver #<Hello> is not a function
    at new Promise (<anonymous>)
    at module.exports (/Users/earagao/Sites/webcomponents/front/node_modules/@skatejs/ssr/index.js:46:10)
    at Object.<anonymous> (/Users/earagao/Sites/webcomponents/front/components/x-button/index.js:24:1)
    at Module._compile (module.js:635:30)
    at loader (/Users/earagao/Sites/webcomponents/front/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/earagao/Sites/webcomponents/front/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

I could find some part of cli documentation in medium, and the same part in skatejs/ssr which says that is migrated to skatejs repository, but in the skatejs repository does not have any subject  regarding ssr on readme.md file... so it's kinda confusing....

I had to search in the site some minimal setup in order to create a web component without any dependencies, maybe preact could be in a secundary section instead of bringing it in the front page... I don't know...

It's kind of hard to do a baby-step approach following documentation as it is today... I'm not sure if I will get the SSR working just by reading documentation.

**Comment by treshugart** [comment]
Hey @Javiani, those are some fair points.

As for your problem, I can't figure out why it's not working. Make sure you're running 0.18 as the first argument to render there is the node (defaulting to `document`) and the second arg is the resolver it's complaining about.

**Comment by treshugart** [comment]
No response for over a year and we're working on a different approach to SSR anyways.
