### ISSUE TITLE
[idea] Writing Web Components using Vue component definitions.

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1289]
Continuing from ideas in https://github.com/skatejs/skatejs/issues/1220, it'd be super nice to be able to write Custom Elements using Vue single-file-component format.

For an example of what I mean, check out [vue-custom-element](https://github.com/karol-f/vue-custom-element), which allows us to write a custom element by writing a simple Vue components, then defining a Custom Elements with it in a really simple way.

This workflow is AWESOME and minimal!

At the moment, vue-custom-element [doesn't support nesting of their custom elements](https://github.com/karol-f/vue-custom-element/issues/74), while SkateJS does support this (each SkateJS element has a shadow root in which a specific renderer (like Vue) is used to define content, which makes composing SkateJS elements naturally possible with native `<slot>` elements).

It'd be nice if there were a workflow for creating custom elements defined by the developer using Vue single-file-components, then some API in SkateJS can create the custom elements.

For example:

```js
import AwesomeButton from './awesome-button.vue'

const AwesomeButtonElement = SkateJS.elementClassFromVue(AwesomeButton)

customElements.define('awesome-button', AwesomeButtonElement)
```

There might be some nice features that we can extend from too, f.e.

```js
import AwesomeButton from './awesome-button.vue'

class AwesomeButtonElement extends SkateJS.elementClassFromVue(AwesomeButton) {
  // extend some stuff, maybe add public methods to the element that can
  // provide access to private parts of the Vue component.
}

customElements.define('awesome-button', AwesomeButtonElement)
```

It would be possible to make a loader that can automagically load up the class, so we can do this:

```html
<!-- awesome-button.vue -->
<template>
  <button>...</button>
</template>
<style> button {color: red} </style>
<script>export default { methods: {...} }</script>
```

```js
// imports an HTMLElement class made with SkateJS:
import AwesomeButton from './awesome-button.vue'

console.log(AwesomeButton.vueDefinition) // in case access to the vue definition is needed, or something.

customElements.define('awesome-button', AwesomeButton)
```

---

Bonus:

When composing components, it may be desirable to skip native element defining, so the loader can be configured so that when a `.vue` file is imported into another `.vue` file, the definition will be used as a regular Vue component instead of a custom element. This would result in the element not appearing in the element inspector, there not being a DOM API for that element to use after querying, but would increase performance. In this case, the only custom element we may see in the DOM is the root-most one, all others having been used as pure-Vue components and only their ultimate template content manifesting inside the DOM. This last idea would be a bonus, but may be tricky to implement, and will surely have edge cases.

**Comment by trusktr** [comment]
THe prospect of this workflow seems REALLY COOL for people who want to publish Custom Elements but who want the power of a simple layer like Vue.

**Comment by trusktr** [comment]
Maybe this can be implemented as an entirely separate package to Vue. I'll give it a go...

**Comment by treshugart** [comment]
@trusktr I've been messing around with this idea in https://github.com/skatejs/wc-parser. I don't think you'd use Vue's parser, but you'd probably use a custom combination of a SFC parser (like wc-parser, or something else) that could possibly use Vue as a backend.

**Comment by trusktr** [comment]
wc-parser is interesting. There's I couple things I noticed:

1. it auto-names the final custom elements. I'd rather import something, then give it name I want, or let another user name it. I need this flexibility.
1. The names that it gives the elements are not the actual names (prepended with `x-`) so it can be unexpected to see other names in the inspector. I understand there's opportunity here to prevent name collisions. However if we have the ability to name things after importing them we can also manually fix name collisions.

I really like Vue because of the SFC dev experience that it has. It uses Vue.compile.

What I'm imagining with something like `SkateJSFromVue(AwesomeButton)` is that it would take the already `Vue.compile`d component definition, then just create a class with `rendererCallback` that mounts the component.

**Comment by trusktr** [comment]
I'm giving it a go, at the moment, but I'm not sure when to use `withComponent` or `withRenderer` based on the docs.

So far, this is what I'm trying:

```js
import Vue from 'vue'
import App from './App.vue'
import { withRenderer } from 'skatejs'

function mountVueComponent( Component, container ) {

  // `tmp` gets replaced by the DOM generated from the component
  const tmp = document.createElement('div')
  container.appendChild(tmp)

  vueInstance = ( new ( Vue.extend( Component ) ) )
    .$mount( tmp )
}

function VueElement( Component, ElementClass = HTMLElement ) {
  return withRenderer(class VueElement extends ElementClass {
    renderer( root, render ) {
      mountVueComponent( App, root )
    }
  })
}

const AppElement = VueElement( App )

customElements.define('app-element', AppElement)

// finally, test the element!
setTimeout(() => {
  const appRoot = document.querySelector( '#app' )
  appRoot.appendChild( document.createElement( 'app-element' ) )
}, 1000)
```

but I'm having issues because I'm using a Webpack environment configured by vue-cli, and it compiles classes to regular function constructors, so I am getting errors like

```
Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
```

or if I change my example to just

```js
import Vue from 'vue'
import App from './App.vue'
import { withRenderer } from 'skatejs'

Object.assign(window, {
  Vue,
  App,
  withRenderer,
})
```

then run the rest of the code in the browser console I get an error like

```
Uncaught TypeError: Class constructor VueElement cannot be invoked without 'new'
```

which shows that some other code in Vue is being compiled to non-classes and tripping it up. Darn build systems and native classes having to be called with `new` !

**Comment by trusktr** [comment]
> which shows that some other code in Vue is being compiled to non-classes and tripping it up

Actually, the error is coming from a SkateJS file, that seems to be passing through Webpack:

![screenshot 2018-01-04 at 4 58 21 pm](https://user-images.githubusercontent.com/297678/34591188-9ed05d10-f170-11e7-9f7c-934bc4355617.png)

**Comment by trusktr** [comment]
Oh, that file is pre-compiled and shipped with SkateJS. This might trip some people up when they try to just plug SkateJS into their app. What can we do about that?

**Comment by treshugart** [comment]
> but I'm not sure when to use withComponent or withRenderer based on the docs

Most of the time you should just use `withComponent`. Using the separate mixins is helpful when you want to explicitly include only the parts you want, for whatever reason.

> Oh, that file is pre-compiled and shipped with SkateJS. This might trip some people up when they try to just plug SkateJS into their app. What can we do about that?

Try using `skatejs/dist/esnext`. Otherwise you need to use the [ES5 adapter](https://github.com/webcomponents/webcomponentsjs#custom-elements-es5-adapterjs).

**Comment by trusktr** [comment]
Alright, got it working. The following code shows how to write a helper function, `VueElement` that takes a Vue component definition as imported from a `.vue` file, and generates a Custom Element with fully-working shadow root and everything. The only problem at the moment is that `<style>`s generated by Vue are placed in the `<head>`, so styling won't have any effect on the component content. I file a new [Vue issue](https://github.com/vuejs/vue/issues/7385) about it. 

```js
import Vue from 'vue'
import App from './App.vue'
import { withComponent } from 'skatejs'

function mountVueComponent( Component, container ) {

  // `tmp` will get replaced by the DOM generated from the component
  const tmp = document.createElement('div')
  container.appendChild(tmp)

  const vueInstance = ( new ( Vue.extend( Component ) ) )
    .$mount( tmp )
}

function VueElement( Component, ElementClass = HTMLElement ) {
  return class VueElement extends withComponent( ElementClass ) {
    renderer( root, render ) {
      mountVueComponent( App, root )
    }
  }
}

const AppElement = VueElement( App )

customElements.define('app-element', AppElement)

// a hack class used so we don't conflict with Vue's builtin <slot> component.
class RealSlot extends HTMLElement {
  connectedCallback() {
    this.innerHTML = '<slot></slot>'
  }
}

customElements.define('real-slot', RealSlot)

// finally, test the element, and you can also nest them (take a look at the
// element inspector)
document.body.innerHTML = `
  <app-element>
    <app-element>
    </app-element>
  </app-element>
`
```

where `App.vue` looks like:

```html
<template>
  <div id="app">
    <img src="./assets/logo.png">
    <h1>{{ msg }}</h1>
    <real-slot>
    </real-slot>
  </div>
</template>

<script>
export default {
  name: 'app',
  data () {
    return {
      msg: 'Welcome to Your Vue.js App'
    }
  }
}
</script>

<style scoped>
  ...
</style>
```

Output (notice the elements are nested in the inspector, as expected, and we see the output twice on the screen):

![screenshot 2018-01-04 at 6 43 14 pm](https://user-images.githubusercontent.com/297678/34593596-af9db75e-f180-11e7-8d9f-ad72bdf3b77f.png)

**Comment by trusktr** [comment]
I really really like this!! It's awesome. I feel like this is my favorite way to make custom elements (aside from styling not working...), thanks to SkateJS' `renderer` method feature. I wonder how to fix that styling issue.

**Comment by trusktr** [comment]
I'm still a bit confused between `withComponent` and `withRenderer`.

If I take the above example, and use `withRenderer` instead of `withComponent` as described in the "Hooking it up" section of https://skatejs.netlify.com/renderers, so that my `VueElement` function becomes:

```js
function VueElement( Component, ElementClass = HTMLElement ) {
  return class VueElement extends withRenderer( ElementClass ) {
    renderer( root, render ) {
      console.log('this is never logged')
      mountVueComponent( App, root )
    }
  }
}
```

then nothing happens, the `renderer` method is never called. If I simply change back to `withComponent`, it all works again, but not based on what the `renderers/Hook it up` doc told me to do, so it isn't clear what to do from the docs.

**Comment by treshugart** [comment]
@trusktr You need something that calls out to the renderer on update, which is why if you imperatively call `updated()` (`withRenderer()` implements this), things will work. The `withUpdate()` mixin calls that when props update, so you could probably do `withRenderer(withUpdate(withVue()))`.

It'd be fantastic if others wanted to help out with the docs. I'm far too close to the code to write great docs (can't see the forest from the trees and all), though, I can help with domain knowledge.

**Comment by trusktr** [comment]
Alright, this is what I came up with. It uses `withRenderer`'s `renderer` callback only to set up the initial Vue instance, but other than that all rendering is left up to Vue rather than the Skate component controlling the render. Attributes/props are just propagated to the underlying Vue instance, which triggers it to update the DOM:

https://github.com/trusktr/vue-web-component

If you've any thoughts on any SkateJS usages that I could improve, please do let me know!

The only real caveat at the moment (listed in the README) is that it's not possible to map all possible Vue prop types to SkateJS prop types, in part due to the attributes-as-strings problem. So out of the box things may not work that would otherwise work with pure Vue components.

F.e. props with type `Function` can't be (de)serialized. Instance properties have to be used, extra steps to take.

**Comment by trusktr** [comment]
Any thoughts on how I'm mapping from [Vue-style prop types](https://vuejs.org/v2/guide/components.html#Prop-Validation) to SkateJS prop types?:

https://github.com/trusktr/vue-web-component/blob/8d06150b39834892d31351892c2c80d73d2a84ee/src/index.js#L145-L191

The `vueProps` arg is a object containing stuff like like in the Vue doc example.

**Comment by treshugart** [comment]
> So out of the box things may not work that would otherwise work with pure Vue components.

But if you use `props`, things just work, right?

> Any thoughts on how I'm mapping from Vue-style prop types to SkateJS prop types?

I think what you're doing there is sane in terms of attempting to map them as close as possible. If we could have something like:

```js
props: {
  someProp: props.oneOf(props.number, props.string)
}
```

This might be able to help. This would require some way to validate for props, though, so maybe a `validate` callback on each prop definition?

I'm just spitballing, though. I'm wary of putting too much process in here as I've built some pretty complex things and have never needed that much control over things. The more we add to props, the more complexity we add to the logic and it is exponential when placed at that level.

**Comment by trusktr** [comment]
> But if you use `props`, things just work, right?

If by that you mean using a renderer that can pass things to props, then I suppose so. Which libs allow you to define which attributes (as in JSX attributes) map to props? React [doesn't yet](https://github.com/facebook/react/issues/11347).

For example, some custom elements might only work with attributes, not with props, so a renderer that always passes values to instance props will cause an error. By default, I assume that renderers use `setAttribute` because normally HTML elements are supposed to have attributes.

Which of SkateJS' renderers lets me explicitly specify which data should be passed as instance props? Can you write a short example of that?

Or, are you assuming that all elements should have an instance prop associated with every attribute, and they'd otherwise break?

> `props.oneOf(props.number, props.string)`

I think let's just leave it alone unless we or someone runs into the situation where they need it.

> so maybe a validate callback on each prop definition?

Right now, nothing is actually validated. `withUpdate` is only (de)serializing and coercing. For example, doing something like `foo="blah"` for a `props.number` attribute just results in `NaN` rather than a type error.

If we wanted to specify a custom constructor as a type, f.e. in Flow:

```js
import Foo from './Foo'
type Props = {
  foo: Foo
}
```

how can we express that with SkateJS props? What's the pattern for serializing and deserializing? I suppose it'd be

```js
foo: {
  serialize() {
    return a string
  },
  deserialize(value) {
    // interpret the string
    const foo = new Foo(___)
    foo._______ = _______
  }
}
```

but in this case it's not possible to automatically map from Vue types to SkateJS prop types, as far as attributes go, right? Maybe for these cases I have to write custom serialize/deserialize. Does the object require anything else besides those two methods?

---

In my case, since I'm using Vue, I'm not yet sure how to tell it to send data to instance properties, so I'm waiting to here back [here](https://forum.vuejs.org/t/how-do-we-pass-values-to-elements-as-instance-properties/26077).

**Comment by treshugart** [comment]
> If by that you mean using a renderer that can pass things to props, then I suppose so. Which libs allow you to define which attributes (as in JSX attributes) map to props? React doesn't yet.

https://github.com/skatejs/val can do this.

> For example, some custom elements might only work with attributes, not with props, so a renderer that always passes values to instance props will cause an error. By default, I assume that renderers use setAttribute because normally HTML elements are supposed to have attributes.

HTML uses attributes only because it's the only way to represent data in the HTML string. However, the DOM has a property for every attribute that it supports, sometimes has properties with no corresponding attribute and in some instances, it will force you to prefer the property. For example, calling `setAttribute` for `value` doesn't work for `input` elements after the value becomes "dirty", but the property will still change value.

Something that I, @rob_dodson and many others have been trying to advocate is to prefer props, but to have a corresponding, one-way (attribute to property), attribute where possible, even if it means deserialising from the attribute value to the property value. This also enables it to play well with SSR.

I think it's a common fallacy that attributes are the defacto way to apply data to DOM elements. The limitations HTML attributes have with complex data types and situations where properties *must* be used over attributes should serve as compelling evidence of this.

> Or, are you assuming that all elements should have an instance prop associated with every attribute, and they'd otherwise break?

As I've stated, preferring props and having attributes where possible is something many of us are trying to advocate, and it's definitely something that Skate will continue to try and enforce through its API.

> but in this case it's not possible to automatically map from Vue types to SkateJS prop types, as far as attributes go, right? Maybe for these cases I have to write custom serialize/deserialize. Does the object require anything else besides those two methods?

Yeah, that is the correct API and doesn't require anything else. You only need the serialise method if you're supporting a two-way attribute binding, which I wouldn't recommend for both performance as well as refraining from mutating the host.

In terms of mapping properties from Vue to DOM properties, check out the Vue section for @rob_dodson's https://custom-elements-everywhere.com. There's an explicit syntax to tell Vue to set a property using a leading colon (`:`).

**Comment by trusktr** [comment]
> I think it's a common fallacy that attributes are the defacto way to apply data to DOM elements.

Apparently the spec authors seem to encourage that because they haven't provided any way to react to property changes, only to attribute changes (`setAttribute` with `attributeChangedCallback`).

> As I've stated, preferring props and having attributes where possible is something many of us are trying to advocate, and it's definitely something that Skate will continue to try and enforce through its API.

I think this is a good thing to advocate. It would just help if specs weren't focused entirely on attributes. And because the specs are, new people making custom elements will naturally start focusing on attributes because that's the API that they are given with Custom Elements.

> There's an explicit syntax to tell Vue to set a property using a leading colon (:).

It turns out the `:` just makes the property dynamic. f.e. `foo="1"` is to `foo={1}` in React as `foo="1"` is to `:foo="1"` in Vue. `foo={1}` in React is literally equivalent to `:foo="1"` in Vue when you see the compiled output. But I learned that Vue supports `.prop` modifier, so `:foo.prop="1"` will pass the value to the `.foo` instance property due to the appended `.prop` modifier (with a really neat `.foo="1"` syntax [coming soon](https://github.com/vuejs/vue/issues/7582)!

**Comment by treshugart** [comment]
> Apparently the spec authors seem to encourage that because they haven't provided any way to react to property changes, only to attribute changes (setAttribute with attributeChangedCallback).

Wouldn't getters / setters be the way to do that?

> I think this is a good thing to advocate. It would just help if specs weren't focused entirely on attributes. And because the specs are, new people making custom elements will naturally start focusing on attributes because that's the API that they are given with Custom Elements.

I think why it seems the specs are focused on that as the entry point is because of the whole `setAttribute()` and `attributes.something.value` being separate ways to set an attribute and the author needs a way to react to that change in a consistent manner (probably to set props).

**Comment by trusktr** [comment]
> Wouldn't getters / setters be the way to do that?

Is there something in the spec that maps attributes to properties? I haven't seen anything that says `some-attribute` maps to `someAttribute` or similar, so there's nothing enforcing that. `setAttribute` and `observedAttributes` are spec'd, and officially the way that HTML elements receive data.

People learning to "program" for the first time, with HTML "code", know only attributes.

**Comment by trusktr** [comment]
> (probably to set props).

Yes, but also not necessarily. it's completely optional, and not spec'd.

**Comment by treshugart** [comment]
> People learning to "program" for the first time, with HTML "code", know only attributes.

There's two API entry points: HTML and DOM. Attributes didn't have a built-in way for that before `attributeChangedCallback()`. For DOM, there's getters and setters.

> Yes, but also not necessarily. it's completely optional, and not spec'd.

Not sure what there is to spec. You can react to a change simply by defining a setter and doing your thing. 

> Is there something in the spec that maps attributes to properties?

This would be too opinionated for the spec because this would lead into having to think about what Skate does with `withUpdate()` and how things are transformed between the two. When you start implementing that, you become opinionated; you're no longer a primitive API meant for building abstractions.

**Comment by treshugart** [comment]
I think this issue has gotten a little off track, and it's closed now. I'd love to see a Vue renderer inspired from this as part of #1220, though!
