### ISSUE TITLE
Something like withRequiredProps and withDefaultProps

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1316]
I'm looking at Vue's [props validation](https://vuejs.org/v2/guide/components.html#Prop-Validation) feature.

Vue props can be required.

It might be neat to have a mixin like `withRequired` or `withRequireProps` or similar to somehow be able to specify that some props are required.

Or maybe just `withUpdate` could be updated to somehow accommodate this.

**Comment by trusktr** [comment]
Vue also supports default values, and OR types.

For OR types, if we wanted `[String, Number]` (the prop can be a string or a number as per Vue's syntax), then maybe it would boil down to requiring that the attribute have some sort of explicit hint. For example, a string: `some-prop="'2'"`. And a number: `some-prop="2"` without the inner quotes.

**Comment by trusktr** [comment]
If https://github.com/skatejs/skatejs/issues/1317 became reality, OR types would not have to parse string values in the non-string case.

**Comment by treshugart** [comment]
Are there valid use cases for having OR types in the context of components? If you have  `string | Array<string>`, I'd just cast it to the latter (`props.array` does this). If `string | number`, why not be explicit and just require `number`?

We support default values already, so there's that. For required props, you can use type systems to require these if necessary.

**Comment by trusktr** [comment]
- [ ] mention default props in the docs, for `withUpdate`

**Comment by treshugart** [comment]
> How do we apply this to HTML?

HTML doesn't have the concept of required. This is why I would always choose good defaults. In React, most times we require a prop, but provide a default prop. If we can lay out clean semantics in how required props behave and there's no weird cases like between the time the element is created and something sets an attr / prop, then it might be worth considering (or be clear you have to provide a default in this case). However, for attributes, if you require them, your host mutates itself. I don't like this. I'd much rather make the concept of "required" props only, if considered.

Re "or" types, I'm wondering if you had a multi-typed prop type, you could prefer the one that's specified first in the array. I'm still unclear as to how this would look in Skate, though. I'd also want to make it compatible with https://github.com/skatejs/babel-plugin-transform-skate-flow-props.

**Comment by trusktr** [comment]
> HTML doesn't have the concept of required. This is why I would always choose good defaults

You're right. After thinking about it, the whole notion of require props is unnecessary with the use of `default`s.

I think the only thing we'd add to make props "required" is to throw an error to console if an element is created and it doesn't have the "required" attribute. Other than this, there's not much to do if the props have defaults.

We can say that having no default makes them not required.

So, really that's the only reason I think we'd want this: making certain attributes explicitly required to be on the element during parsing, which may not be worth adding.

**Comment by treshugart** [comment]
In `v6-trey` there's now a `changed` prop callback. Could use that to log etc.

**Comment by trusktr** [comment]
Well, now in `v6-trey` there's neither `default` nor a `required` feature, which means we'd need the feature of this issue. Before, `default` handled the case. I'd say let's add `default` back in.

Note, I'm not using a type system, and I would still like to benefit (f.e. like how React provides an optional `PropTypes` runtime utility for users with no type system).

**Comment by treshugart** [comment]
Default has been added back in. I'm not opposed to adding a required option, but this is something you could easily implement by throwing if `default` is invoked in how it's currently implemented in that branch.
