### ISSUE TITLE
withReferences or withNonStrings mixins

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1317]
Something cool might be to allow attributes to accept non-strings.

For example, in A-Frame you can run

```js
element.setAttribute('foo', { bar: 5 }) // the element uses this non-string, avoiding string conversion for performance.
```

and the element will react to that literal object instead of a string.

It would be neat to be able to have this feature in a generic way, so that any element made with SkateJS, perhaps using something called `withNonStrings` or similar, can receive and react to non-string values.

This would mean some trickery would be needed with `attributeChangedCallback`, as all my tests show that no matter what you pass into `setAttribute`, the value is **always** converted into a string, and the browser will always call `attributeChangedCallback` with a string value.

A possible way to make this work is to override `setAttribute` on the element class, so that it only calls `super.setAttribute` for strings.

```js
setAttribute(attr, val) {
  if ( typeof val == 'string' )
    super.setAttribute(attr, string) // eventually triggers attributeChangedCallback with a string value
  else
    // ... call attributeChangedCallback manually, with the non-string value, (possibly in the future to be similar to the native version) ...
}
```

**Comment by trusktr** [comment]
Aha, I see if we are using `withUpdated`, then inside of attribute changed callback we can access the coerced value on `this.props`:

```js
    attributeChangedCallback(attr, oldVal, newVal) {
      super.attributeChangedCallback(attr, oldVal, newVal)

      // pass the value along to the Vue component
      this.vue_instance[attr] = this.props[attr]
    }
```

(in my case I'm still perfecting my vue-to-skate-element converter, so I want to pass the non-string value to the Vue instance)

To test this, I am calling `setAttribute` on the element, and if I log the value, I still see a string though:

```js
    attributeChangedCallback(attr, oldVal, newVal) {
      super.attributeChangedCallback(attr, oldVal, newVal)

      console.log(typeof newVal) // this is still a string

      // pass the value along to the Vue component
      this.vue_instance[attr] = this.props[attr]
    }
```

It would be really great to be able to call

```js
el.setAttribute('message', 123)
```

and completely avoid the number-to-string-to-number conversion, and just pass the number argument directly to `attributeChangedCallback`.

So, even though I can get the coerced value from `this.props`, it doesn't solve the performance problem.

**Comment by treshugart** [comment]
Why can't you just set properties? This is the defacto way to do this with the DOM and I haven't seen any compelling evidence against it. The fact that A-frame allows you to do this is worrying. It's non-standard behaviour and requires some heavy-handed patching to the DOM.

If you need to write HTML-like syntax something like https://github.com/skatejs/val can help you do that while setting props.

I'm going to close this as it's not something that will ever make it into core. Don't let that stop you from creating your own mixin if you really want this behaviour, though.

**Comment by trusktr** [comment]
I'll give a mixin for that a go. 👍 

It's just that, at this rate, who knows what will really be standard. If my custom elements can accept non-strings for `setAttribute` as well as with instance properties, then they will be ready for whatever people do with them, because right now there's so many libraries out there and making everyone follow exactly the same convention right now seems nearly impossible.

It's just easier for my elements to work in all the cases.

I sympathize with you on the desire for everyone to do it one way (f.e. with instance properties which are clean) but not everyone is doing it one single way (yet).

**Comment by treshugart** [comment]
> because right now there's so many libraries out there and making everyone follow exactly the same convention right now seems nearly impossible.

That's fair. My main reasoning here is I don't want to do patching at the native method level, which would be required for this. That and I have questions around how setting `attribute.someattr.value` handles these sort of things. I've had trouble in the past getting both that and the attribute methods working consistently.

**Comment by trusktr** [comment]
> I've had trouble in the past getting both that and the attribute methods working consistently.

Hmmmm. Noting that I should consider this when I [get to it](https://github.com/trusktr/infamous/issues/115#issuecomment-366644643).

**Comment by trusktr** [comment]
Maybe this would work in most cases:

```js
setAttribute(attr, val) {
  const propName = this.constructor._attributeToPropertyMap &&
    this.constructor._attributeToPropertyMap[attr]
  if (propName)
    this[ propName ] = val
  else
    super.setAttribute(attr, val)
}
```
