### ISSUE TITLE
How to know which props changed with withUpdated?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1318]
I'm trying to use `withUpdated`, and like with `attributeChangedCallback`, I'd like to know which prop was updated.

Should I just use attributeChangedCallback then?

I think if I do,

```js
attributeChangedCallback(attr, oldVal, newVal) {
  super.attributeChangedCallback(attr, oldVal, newVal) // triggers withUpdate sync

  // check `attr` here
}
```

then I can check which prop was changed, and I think `updated` should've already been called at that point right?

But then I feel like I'm side stepping the API a little. It'd be nice if we knew what changed in the updated API.

**Comment by treshugart** [comment]
The `attributeChangedCallback` will sync props, thus queuing a call to `updating`, `shouldUpdate` and `updated`, in that order. They are invoked once in a micro task to batch changes. I recommend using `updated` for capturing all changes and `updated` for rendering to the DOM. All methods receive `prevProps` and `prevState` as arguments.

**Comment by trusktr** [comment]
> All methods receive prevProps and prevState as arguments.

This means I have to diff it myself to find what changed.

I'm making that tool I mentioned in another thread to generate elements from Vue components, and I want to update only the Vue instance's props that have changed. This is important because it means the implementation can withstand future updates to Vue APIs (f.e. re-rendering only parts of a template based on which props have changed).

This is simple to do with attributeChangedCallback, because I know which prop to update.

I'll post the tool here when finished, so you can see what I mean, almost done...

---

Maybe the changed attributes can he recorded in a `Set`, and passed to `updated`

**Comment by treshugart** [comment]
> This means I have to diff it myself to find what changed.

There's plenty of libraries out there that can easily do this and then you can just do `diff(this.props, prevProps)`. This is really all you'd need to do, though:

```js
const diff = Object.keys(this.props).reduce((prev, curr) => {
  if (this.props[curr] !== prevProps[curr]) prev.push(curr);
  return prev;
}, []);
```

If Skate did this on every render just in case you needed the, it would cause an unnecessary performance hit. It's better if users opt-in to doing things like this.

**Comment by trusktr** [comment]
We could make it easier with something like a list created without a loop:

> the changed attributes can he recorded in a `Set` [inside `attributeChangedCallback`], and passed to `updated`

and the idea is here: https://github.com/skatejs/skatejs/pull/1321 (not tested yet).

It doesn't involve a loop, the user can optionally iterate on it. What do you think about this?

**Comment by trusktr** [comment]
Plus, if the `_changedProps` list can be shorter than the full list of props, so optionally iterating on it can often be shorter than iterating on all props.

**Comment by trusktr** [comment]
For now I'm doing this to avoid iterating twice (once in the diff, once after):

```js
function forChangedProps(oldProps, newProps, action) {
    for ( const oldKey in oldProps ) // not checking for own props. That okay?
        if ( oldProps[ oldKey ] !== newProps[ oldKey ] )
            action( oldKey, oldProps[ oldKey ] )
}

forChangedProps(prevProps, this.props, (name, oldVal) => doSomethingWithChangedProp(name, oldVal))
```
