### ISSUE TITLE
[feature] reactive props

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1320]
## Feature request

When using `withUpdate`, make `this.props` reactive similar to properties on Vue instances.

### Use case(s)

I can currently trigger an update by soing `el.setAttribute('foo', 45)`, and if the prop type for foo is props.number, then it sets `this.props.foo` to the number `45` as expected.

But I was also hoping that I could do something like `this.props.foo = 123` and that that would also trigger an update.

If you have an instance of a Vue component, you can do `instance.foo = 123` and it triggers a re-render of the component.

I haven't tried this with `this.state`, but I am only testing `this.props` because that is the public interface, and in Vue props are also the public interface and they are reactive, which I really like.  (Vue doesn't have an additional `state`, only `props` which are directly on the instance).

This would be cool feature!

**Comment by trusktr** [comment]
I see in the docs:

> Attribute binding is one-way: attribute updates affect the property, but not the other way around.

I think that confirms that using `setAttribute` is the only way to supply new values via JavaScript (which includes the [`number-to-string-to-number` problem](https://github.com/skatejs/skatejs/issues/1317)).

**Comment by trusktr** [comment]
Hmmm, the "Guide" section of the docs says

> `withUpdate` -- the generated element will react to changes on their props or HTML attributes.

This seems to imply that I can change either the attribute **or** the props, but in my experience changing values inside of `elem.props` isn't doing anything, only `setAttribute` is working, so I'm not sure if this is a feature request or a bug report. Which one might it be?

**Comment by treshugart** [comment]
If you have:

```js
import { props, withComponent } from 'skatejs';

class MyComponent extends withComponent() {
  static props = {
    foo: props.number
  }
}
```

You can:

1. `element.foo = 123;`
2. `element.props = { foo: 123 };`
3. `element.setAttribute('foo', '123');`

Where it says:

> Attribute binding is one-way: attribute updates affect the property, but not the other way around.

This means that property updates don't affect attributes. This is intentional because if you mutate an attribute, it might mess with any state a parent renderer has over the host element. This is consistent with DOM props that maintain internal state such as `value` on inputs.

You can enable two-way binding if you want by specifying `{ attribute: true }` to your `props`:

```js
import { props, withComponent } from 'skatejs';

class MyComponent extends withComponent() {
  static props = {
    foo: { ...props.number, attribute: true }
  }
}
```

If you have access to the element instance, I don't recommend using `setAttribute()`. You should use the standard property to do so. this is the defacto way to do it with DOM elements and it's also much faster in microbenchmarks, which can add up at this level of abstraction.

**Comment by treshugart** [comment]
I'm going to close this as I think option 1 solves your use case as this is exactly how Vue behaves, and you also have option 2 and option 3 to fallback to.

**Comment by trusktr** [comment]
Option 1 isn't working for me, which is what prompted me to open this. Maybe I'm causing it to break though.

I've got something like follows in my class (piece left out). Do you see anything that I may have done to break option 1 from working?

```js
  return class VueWebComponent extends withUpdate( withRenderer( ElementClass ) ) {

    renderer( root, render ) {
      if (this.id == 'test')
        console.log(' ----------- RENDERER ', this._shadowRoot)

      // mount the component
      this.vue_mountComponent( root )

      // bring in the global styling
      requestAnimationFrame(() => this.vue_applyStyle( root ))
    }

    static get props() { return vuePropTypes }

    updated(...args) {
      super.updated(...args)

      // nothing here, we use attributeChangedCallback instead because we need
      // to know which attribute was modified and Skate doesn't tell us here.
      // See https://github.com/skatejs/skatejs/issues/1318
    }

    attributeChangedCallback(attr, oldVal, newVal) {
      super.attributeChangedCallback(attr, oldVal, newVal)

      // pass the value along
      this.vue_instance[attr] = this.props[attr]
    }
```

I'm not calling `super` in `renderer`, maybe that breaks it?

**Comment by treshugart** [comment]
It would be best to start from a simple example and work your way into the code that you've written. Option 1 definitely works as it's tested in the tests.

**Comment by trusktr** [comment]
Ah, we both missed my obvious mistake in the OP: I was doing `this.props.foo = 123` instead of just `this.foo = 123`. That works!

When do we want to use `this.props.foo` vs just `this.foo`? Maybe we generally never want to touch `this.props`, and that's just a buffer for `withUpdate`?

**Comment by treshugart** [comment]
> When do we want to use this.props.foo vs just this.foo? Maybe we generally never want to touch this.props, and that's just a buffer for withUpdate?

Yeah, mutating `props` is not supported. If you want to do that you just do `this.props = { foo: 123 };`.

**Comment by trusktr** [comment]
The `withUpdate` page in the docs actually never mentions anything about setting props on an instance, so actually I was just guessing, and I turns out I guessed wrong!

It'd be great to stick what you said earlier, so people can make the connection as to how modifying a prop causes the HTML to update:

> You can:
> 
> 1. `element.foo = 123;`
> 1. `element.props = { foo: 123 };`
> 1. `element.setAttribute('foo', '123');`

**Comment by treshugart** [comment]
Good idea. If you have time to push a PR to the website, I'll happily merge it :)

**Comment by trusktr** [comment]
👍
