### ISSUE TITLE
Computed properties.

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1334]
## Feature request

Vue has a ["computed properties"](https://vuejs.org/v2/guide/computed.html) feature, where computed properties are functions that have dependencies on `data` (where `data` is to Vue as `props` are to SkateJS).

Due to Vue's reactivity system, computed property functions are only re-ran when their dependencies have changed.

Maybe it would be neat to have a feature like this in SkateJS?

### Use case(s)

_Explain the rationale for this feature._

Computed properties only need to be calculated when their dependencies change. At the moment, someone will use `props` in their `render` method, and they might compute values from those props to use in rendering. If so much as one prop updates, all computations in the render method are redone. Computed properties is a way to prevent unnecessary recomputation.

**Comment by treshugart** [comment]
It would seem to me that every time a dependent property changes, a re-render would occur, thus you could just have a getter on the prototype that computes the value of whatever changed in `render()`, no?

**Comment by trusktr** [comment]
> It would seem to me that every time a dependent property changes, a re-render would occur, thus you could just have a getter on the prototype that computes the value of whatever changed in render(), no?


Not exactly, because then every time that `render()` is called it will call the getter, every time, and run the computation every time.

The purpose of this feature would be that a cached value is used in `render()`, so that the computation does not need to be re-ran, only the existing value used. This could prevent looping and other performance heavy operations that might happen in computing a getter.

**Comment by trusktr** [comment]
One way to do this, so that the details are completely magic for the end user, is to override the old getter on the class prototype with a new getter that can return a cached value if no dependencies have changed?

**Comment by obedm503** [comment]
It might be worth looking at [aurelia's `computedFrom` getter decorator](http://aurelia.io/docs/binding/computed-properties#introduction) which aims to do exactly this to get inspitation

**Comment by treshugart** [comment]
Why not just use [memoization](https://github.com/alexreardon/memoize-one)?

**Comment by trusktr** [comment]
Well, if that's what happens behind the scenes and it avoids things from being re-computed, I'm good with it. Basically then, Skate could take the computed properties and memoize them, cache them, or do whatever it needs to do to avoid re-computation.

**Comment by treshugart** [comment]
> EDIT: I guess the computation can be memoized, and only invalidated if any deps have changed.

Yeah, this is the idea of memoization. It would take in the dependent values as args and memoize based on them. I'd prefer to follow the model of "innocent until proven guilty" for performance here as that's sort of a theme with React, Skate and other libs.

I feel the idea of computed properties is already inherently available, trivial to optimise and adds a lot of complexity if it were a "custom thing", so I'd prefer to leave it out for now.

**Comment by trusktr** [comment]
About computed properties, I'm doing something like this now:

```js

    static: {
        type: 'material',
        props: {
            color: props.THREE.Color,
            opacity: { ...props.number, default: 1 },
        },
    },

    async updated( oldProps, oldState ) {
        if (! ( await Super( this ).elementIsMesh() ) ) return

        this.updateMaterial(oldProps, 'color')

        if (this.updateMaterial(oldProps, 'opacity')) {
            this.updateMaterialNoCheck('transparent')
        }

        Super( this ).updated && Super( this ).updated( oldProps, oldState )
    },

    get transparent() {
        if ( this.opacity < 1 ) return true
        else return false
    },

    updateMaterial( oldProps, propName ) {
        if ( oldProps[ propName ] !== this[ propName ] ) {
            this.updateMaterialNoCheck(propName)
            return true
        }
        return false
    },
```

where `transparent` is the computed property, and clearly a dependent of `opacity`. The value isn't cached though.

Maybe I can make a mixin at some point for defining computed props that are cached and invalidated only when their dependencies change. Vue's are nice and easy: in Vue we'd only have to write the equivalent of my `transparent` getter, all other stuff is behind the scenes.

**Comment by trusktr** [comment]
Maybe we can use [`S.js`](https://github.com/adamhaile/S) to implement a mixin for this. I may try it at some point.
