### ISSUE TITLE
Thoughts on the catch phrase.

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1343]
The slogan,

> Effortless custom elements for modern view libraries

reads as if Skate lets us make custom elements _for_ other view libraries.  I'm don't think you meant that.

Maybe

> Effortless custom elements powered by modern view libraries

would be reflect the idea better because it is more aligned with the fact that Skate makes it easy to _use_ React/Preact/LitHTML/etc as the rendering mechanisms for elements that are made with Skate.

I really like Skate, so I'm just sharing what I thought about it, and that I hadn't really thought hard about the slogan before, but when I did then this was what I realized.

**Comment by treshugart** [comment]
I like that. Happy for you to update the relevant parts and I can do the GitHub one once it's done.
