### ISSUE TITLE
Instance properties with special formats.

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1347]
(not sure if this is a feature request yet)

On my custom elements, I can do this:

```js
el.rotation = {x:30, y:30, z:30}
```

This corresponds to the `props.object` type, which means we can do

```html
<i-box rotation="{x:30, y:30, z:30}">
```

which will deserialize the string into an object and set the property similarly.

I'm just wondering, if it would be worth somehow restricting the the object format? Maybe that's too much overhead? But presumably, attributes should only be deserialized on initial page load and after that instance properties should be used always.

On my elements we can also do

```js
el.rotation.y = 30
```

So I'm wondering if it's possible to do something like

```html
<i-box rotation.y="30">
```

and have that value passed to the sub-property. Does that seem doable? If so, could it be typeable with `props.*`?

**Comment by treshugart** [comment]
> But presumably, attributes should only be deserialized on initial page load and after that instance properties should be used always.

In #1348 this will be enforced with the only escape hatch being using `updated()` to reflect back to attributes.

> and have that value passed to the sub-property. Does that seem doable? If so, could it be typeable with props.*?

Dot-notation as attributes would be a bit of work and overhead, and would go against the immutability convention of props, where the prop must pass an equality check to update (mutations to the sub-object don't queue a render).

In terms of being typeable, you can do:

```js
class MyEl extends withComponent() {
  props: {
    rotation: {
      x: number,
      y: number,
      z: number
    }
  }
}
```

You can actually translate that automatically to a prop, if you're using Flow, using https://github.com/skatejs/babel-plugin-transform-skate-flow-props.

**Comment by trusktr** [comment]
> ```js
> class MyEl extends withComponent() {
>   props: {
>     rotation: {
>       x: number,
>       y: number,
>       z: number
>     }
>   }
> }
> ```

Do you have an example of that? The one you linked is just one level deep:

```js
  props: {
    code: string,
    lang: string,
    title: string
  };
```

> You don't get the "shape" validation at runtime, but type systems can statically analyze it on the consumer's end.

A type system isn't available in my case.

**Comment by trusktr** [comment]
#1493 (and related PR #1509) solves lots of problems including this one! I think #1509 is really worth considering.

**Comment by treshugart** [comment]
To be clear, `this` would be the prop definition. I don't want to alter the context of the function. That said, passing the element is handy to callbacks that happen at runtime, though I'm not sure things like serialize and deserialize need it.

**Comment by trusktr** [comment]
👍 I really like the use of `this` for prop type instance and `elem` for the element, even more flexibility.

> You know you can use Flow comment types that require no build step, right?

I know I can, but as a library author, I still want to provide runtime types, at least in "dev" mode, for end users. I can figure out how to disable it in prod mode as a bonus optional feature (for performance).
