### ISSUE TITLE
`wrap` export is missing in react-renderer build

### ISSUE THREAD

**Issue by hoodwink73** [skatejs/skatejs#1352]
## Bug report

Skate version: ^5.1.1
```
   ├─┬ @skatejs/renderer-react@0.2.1
   │ └── skatejs@5.1.1  deduped
   └── skatejs@5.1.1 
```

### Current behaviour

```
   import { wrap } from '@skatejs/renderer-react';
```

says `wrap` is not defined.

While I can see it GitHub source files, I cannot spot the `wrap` in the built code.

<img width="1290" alt="screenshot 2018-02-05 21 12 29" src="https://user-images.githubusercontent.com/1285699/35813388-8064f310-0ab9-11e8-9d60-552cbc9bafb3.png">

**Comment by treshugart** [comment]
This isn't exported anymore in the newer renderers.
