### ISSUE TITLE
SSR and withRenderer

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1356]
I'm a little confused about what the SSR package is for.

If my SkateJS-based element makes it's own shadow root (because it uses withRenderer), will that conflict with the `__ssr()` stuff that the `ssr` package sends to the client?

I mean, the custom element will be defined, then when the element gets updraded it will use `shadow(this)` to create a shadow root, which will conflict with `_ssr()`, won't it?

**Comment by trusktr** [comment]
I mean, f.e., the output HTML (from the server) might be like this:

```js
<script src="/x-hello.js"></script>
<script src="/x-yell.js"></script>

<script>function __ssr(){var a=document.currentScript.previousElementSibling,b=a.firstElementChild;a.removeChild(b);for(var c=a.attachShadow({mode:"open"});b.hasChildNodes();)c.appendChild(b.firstChild);}</script><x-hello><shadow-root><span>Hello, <x-yell><shadow-root><strong><slot></slot></strong></shadow-root><slot></slot></x-yell><script>__ssr()</script>!</span></shadow-root>World</x-hello><script>__ssr()</script>
```

based on the README example, and so it seems like both the custom element definitions AND the ssr script will both attempt to create shadow roots. Isn't that a problem? Or I'm not clear on what exactly ssr does.

I always thought that SSR with Custom Element would be only a matter of sending raw HTML, then, for example, `withUpdate`/`skate.props` in a SkateJS component would be the mechanism responsible (in this case of SkateJS-based elements) for parsing attributes into data for instance properties.

**Comment by treshugart** [comment]
Yeah, the ssr aspect is still being fleshed out. Previously it would rehydrate the render() state but there's some conflicting proposals happening for it, so it's still in flux here. The most useful part about the ssr package is the node DOM integration that allows you to run tests in Jest and render on the server.

In terms of conflicting shadow roots, Skate will check to ensure a shadow root needs to be created before creating one. Otherwise it uses the existing one and just renders to it. I think it'd be useful to try and bring back the full tree rehydration we used to have and split that node dom stuff out into a separate implementation to make the package distinctive.

**Comment by trusktr** [comment]
> In terms of conflicting shadow roots, Skate will check to ensure a shadow root needs to be created before creating one.

What if the component author want ls a closed root?

**Comment by trusktr** [comment]
wants*

**Comment by trusktr** [comment]
What about elements that set their own content, without a root, just this.innerHTML? I suppose on the client the regular content or shadow content may get overriden by setting this.innerHTML or this.root.innerHTML, which would cause a bunch of unloading and reloading stuff.

**Comment by trusktr** [comment]
F.e., all the DOM created from the SSR payload may get recreated unnecessarily. Is that what you were solving before when you mention the previous rehydration?

**Comment by treshugart** [comment]
> What if the component author wants a closed root?

I'm of the opinion that closed roots don't solve anything. But to solve this if we needed to, we could serialise the type of root to create on the server, and then create it like that on the client.

> What about elements that set their own content, without a root, just this.innerHTML? I suppose on the client the regular content or shadow content may get overriden by setting this.innerHTML or this.root.innerHTML, which would cause a bunch of unloading and reloading stuff.

I'm of the opinion that if you set your own content, you *must* use a shadow root. Those that don't are opening themselves up for integration issues, which defeats the purpose of a web component in the first place.

> F.e., all the DOM created from the SSR payload may get recreated unnecessarily. Is that what you were solving before when you mention the previous rehydration?

Yes. Until there's declarative shadow DOM, there's no way around this.
