### ISSUE TITLE
What are projector and bolt used for?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1359]
https://github.com/skatejs/skatejs/blob/57a6dbb11094effcf0a1e708665830e5cf518ce2/package.json#L116

I see that `prepare` script runs `bold build`. After looking at bolt, I see that without the `bolt ws` command, it just runs in the root, which is effectively the same as `yarn build` if I understand. And in the `projector.js` I don't see anything special besides `getWorkspaces` for getting the path to each sub-package.

So, I'm wondering,

1. what is projector for? Because I see there's nothing about the `projector.js` file that seems like I'd need projector to run. In other words, what goal does projector accomplish by just running the file directly?
2. If not using any feature of `bolt` other than `getWorkspaces` (and `bolt build` which if I understand correctly can be just `yarn build`), would just using Lerna be simpler and easier?

Have I missed a feature of bolt or projector that maybe isn't obvious?

**Comment by treshugart** [comment]
> Oh, about Projector, I see, it's just a task runner, where the name of the task is the name of an export, and that export should be a function. Somewhat of like a Gulp alternative, but more general purpose and without all the tools?

Yep! Much simpler and async friendly out of the box.

> Still don't see the utility that Bolt offers though.

Bolt wraps Yarn, but provides a fantastic monorepo workflow. It's responsible for linking and managing dependency versions across the monorepo packages. That's why it's required for dev.
