### ISSUE TITLE
Implement public API for server-side rendering.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#136]
It'd be nice to have a way to render components server-side while only having their behaviour bound on the client side.

Currently you are able to add the "resolved" attribute to your element and it will not template it. However, this may not be the best way to do it as "resolved" is reserved for preventing FOUC.

I suggest we need to prove that "resolved" is not the best API for this and to come up with a better way. If not, we should ensure that we want to continue using this and document it accordingly.

**Comment by alexreardon** [comment]
Any update on this one?

**Comment by treshugart** [comment]
I've been thinking about it. Could just be another attribute. Currently the resolved attribute should work if you urgently need it.

Any thoughts?

**Comment by alexreardon** [comment]
I suppose the actual implementation of this would be dependent on the template solution chosen (eg `handlebars`).

My main concern would be reducing any duplication of independent templating logic across the server and client. Ideally it would be good to use the same template function across server and client but I supposed this would be up to individual implementation. 

Just throwing ideas around:
Would you consider implementing a `node` compatible module of `skate` in order to have a `toString` function (similar to that of `React`:  `React.renderComponentToString`). This would be different to the current `template` function which sets the `element.innerHTML`. Perhaps this is stepping outside of the boundaries of this library? Not sure.

**Comment by treshugart** [comment]
I would definitely consider it given the need but my thinking is that it can be simpler.

Since the `template` callback is only there to ensure that templating happens at a consistent point in the element lifecycle, if you bypass it, it assumes that it either doesn't need to be done or that it's already being handled by something else and everything else happens as normal. This means that all you should need to do is use your templates server-side to output your element and all Skate will do is bind behaviour to your pre-templated element.

I'd say actually going further to have an opinion on templating would be out of the scope of Skate itself, but it's worth discussing how it can facilitate this. What are your thoughts on my suggestion above?

**Comment by AmitKumarDas** [comment]
Not sure if you guys have checked out http://skitjs.com/

Would it be worth to try Skate with Skit before trying out an independent node module for skate ?
Note - Skit is a very young library. However its core focus seems to be promising.

**Comment by alexreardon** [comment]
It seems like Skit does some things that Skate does not (server side rendering). However, it also touches on a number of concerns that Skate does (element life cycle, event binding). I would think a good match would be a solution that allowed one consistent template across server and client while also allowing for intelligent rendering (not just smashing `.innerHTML` of a root element).

**Comment by alexreardon** [comment]
Just got to meet up with @treshugart. Thanks for that. Here is a summary of things we talked about:

h2. Server side rendering

The `resolved` attribute currently tells stake to skip the template step. This facilitates agnostic server side rendering. Still pending: whether to formalise this into the api

h2. Re-render

There currently exists no *framework* way to cause an element to call `template` again. It is a *one time call*. After that point mutations to the dom need to be done manually. This might not be ideal for a few reasons:

1. initial render controller by template function but ongoing changes are manual (duplication of concerns?)
2. Additions would be simple (adding a new element) but modification to existing data sets could involve complicated dom access logic.

Techniques were discussed that would give the ability for an element to call it's template function again. /cc @treshugart

**Comment by treshugart** [comment]
Yeah that's probably a good location for that. Will create an issue.

**Comment by treshugart** [comment]
After thinking about it, I think it would be best to create a separate flag that the developer can set to skip the template callback. As @alexreardon has stated `resolved` does indeed do this, but `resolved` is reserved for FOUC prevention. If the developer sets this before the element is initialised there will be FOUC if anything happens in the created callback. Probably best to keep these separate as they're purpose is different.

**Comment by treshugart** [comment]
I'm going to close this as I've created a more specific issue to discuss the details of the attribute.

**Comment by alexreardon** [comment]
@treshugart any thoughts on the *re-render* concern?

**Comment by treshugart** [comment]
@alexreardon created this: https://github.com/skatejs/skatejs/issues/172. Feel free to expand with your thoughts.
