### ISSUE TITLE
QUESTION: Using React Context With SkateJS

### ISSUE THREAD

**Issue by slipmat** [skatejs/skatejs#1365]
### Use case(s)

I want to pass the React context down from one React Component to another.
via WebComponents.

```
<react-web-component-parent>
    <react-web-component-child/>
</react-web-component-parent>
```

React passes context to the "react-web-component-child" component via the constructor.
[React Context Reference](https://reactjs.org/docs/context.htm)

SkateJS's withContext, passes context from one WebComponent to another but it not related to React Context. 

I believe it's because a new root is created when you call ReactDOM.render, so the previous parent React context is not known by the React child. 

Is there an example of using React context with SkateJS or some helpful pointers.
(If I get something working, I'll post an update)..

**Comment by treshugart** [comment]
I haven't used React context across separate render trees. Which version are you using? I don't suspect it to work, regardless, though.

Do you need the context passed via react, or can you use the web component context from skate to pass props into the react components?

**Comment by slipmat** [comment]
We are using React 16. 

We wrote a set of React wrappers for Material UI’s React Components. 
[https://material-ui-next.com]

The MUI components pass the Theme through to React child components, via context.  

React depends on a common root, for context, unless you are using Portals or unstable_renderSubtreeIntoContainer. I tried both these approaches with Skate and the context was still getting reset by React. 

I solved it by wrapping every rendered component in a MuiThemeProvider to give each Custom Element, it’s own context. I then used emit to dispatch an event, that is caught by a Custom Element called ThemeProvider, which then gives the theme back to the child Custom Element. This bypasses the issue, for now. 

( Hopefully this post gives folks some ideas, if they run into a similar issue )

BTW, great job! 
I’ve used a few of your repos now and have been really impressed with quality and effort you’ve put in.

**Comment by treshugart** [comment]
@slipmat 

> I solved it by wrapping every rendered component in a MuiThemeProvider to give each Custom Element, it’s own context. I then used emit to dispatch an event, that is caught by a Custom Element called ThemeProvider, which then gives the theme back to the child Custom Element. This bypasses the issue, for now.

That's a neat approach. An alternative I was thinking of would be to wrap the provider in a custom element. You can then grab a ref of the component, get the context and then set that as the custom element context, which then could be read by all custom elements down the tree. This might get around you having to wrap every custom element in a theme provider.

> BTW, great job! I’ve used a few of your repos now and have been really impressed with quality and effort you’ve put in.

Those are super kind worlds. Thank you!
