### ISSUE TITLE
ID set on element is overwritten

### ISSUE THREAD

**Issue by jadedsurfer** [skatejs/skatejs#137]
Great library but I've run into an issue during my evaluation.

If I create a component like this:

```
<my-component id="myid"></my-component>
```

I get this in the DOM after I have initialized the component.

```
<my-component id="my-component" resolved></my-component>
```

Notice how the id I had set is overwritten with the component id. This leads to duplicate ids and broken selectors in my code. 

I couldn't find in the src where it was happening.

I know I can use still use a class selector but I would prefer to have the ability to still use getElementById.

**Comment by treshugart** [comment]
That is definitely a bug. What branch / tag are you using?

**Comment by treshugart** [comment]
After writing a test for this, I can't seem to reproduce it. See https://github.com/skatejs/skatejs/commit/dd260ba08f4777f9dcc54d2062a10e6f3f0208ca. Are you able to reference the code that this is happening to?

**Comment by treshugart** [comment]
@jadedsurfer I'm closing now (no response and unable to reproduce) but please reopen if you get to it and can send the code that is reproducing it.

Thanks!
