### ISSUE TITLE
Where's @skatejs/bore?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1376]
I'm trying to write my first test using @skatejs/bore. I noticed that the repo saysit was moved into skatejs monorepo, but I don't see a `bore` folder in `packages`.

**Comment by trusktr** [comment]
Ah, I see it in the `v6` branch. Maybe it was moved too early.

**Comment by treshugart** [comment]
Yeah, could have been archived a bit too early. But people can still raise issues in the skate repo. Shouldn't be too long for v6 now.
