### ISSUE TITLE
How to test Web Component with @skatejs/bore?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1377]
Theskatejs/bore README says

> Enzyme-like testing utility built for the DOM and Web Components, that works both on the server and in browsers.

But, when I try making a test like this:

```js
import { mount } from '@skatejs/bore'
import { h } from '@skatejs/val'
import VueWebComponent from '.' // uses `customElements.define()`

test('testing works', () => {
    expect(VueWebComponent).toBe(VueWebComponent)
})
```

the test fails with 

```
> jest --config ./config/jest.config.js
 FAIL  src/test.js
  ● Test suite failed to run

    ReferenceError: customElements is not defined

      142 |     }
      143 | }
    > 144 | customElements.define('real-slot', RealSlot)
      145 |
      146 | function makeVuePropTypes( vueProps ) {
      147 |     if (! vueProps ) return {}

      at Object.<anonymous> (src/index.js:144:1)
      at Object.<anonymous> (src/test.js:3:9)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.969s, estimated 1s
Ran all test suites.
```

So it seems @skatejs/bore didn't set up the environment for testing Web Components!

It appears we have to make sure we have some sort of DOM polyfill loaded first, but based on what the README advertised, I was hoping we didn't have to do that!

How do you recommend setting this up?

**Comment by trusktr** [comment]
Ah, I see further down the README says:

> To test your web components in Node or Jest, you'll have to use @skatejs/ssr. More information there.

**Comment by trusktr** [comment]
Importing only `@skatejs/ssr/register` in my test files wouldn't work, but when I configured `Jest` to use the provided testEnvironment, then it worked.

Why won't it work without the environment if I import `@skatejs/ssr/register` directly?

**Comment by trusktr** [comment]
Oh! Because Jest's environment is by default `jsdom`, so using importing `@skatejs/ssr/register` in my test file was conflicting with that. So, using `@skatejs/ssr/jest` for `testEnvironment` worked!

**Comment by treshugart** [comment]
Yeah, you have to explicitly use the test environment for that reason. Glad you figured it out!

**Comment by mnicic** [comment]
I have something similar... I want to test with Jest my Web component developed in Angular Elements. My `test.spec.js` file has:

```JavaScript
require('@skatejs/ssr/register');

describe("Embeded myElement", () => {
  beforeAll(() => {
    var script = document.createElement("script");
    script.src = "./scripts/my-element.js";
    document.body.appendChild(script);

    var elem = document.createElement("my-element");
    myElement.apptitle = "asdfasdf";
    document.body.appendChild(myElement);
  })

  it("create", () => {
    // some testing
  })
})
```

And `jest.conf.js`:

```JavaScript
module.exports = {
  preset: "jest-preset-angular",
  testEnvironment: "@skatejs/ssr/jest",
  setupTestFrameworkScriptFile: "<rootDir>/jest.ts",
  ...
}
```

I'm getting the error with Zone.js:

```bash
  ● Test suite failed to run

    ReferenceError: Zone is not defined

      at node_modules/zone.js/dist/zone.js:646:1
      at Object.<anonymous>.FUNCTION (node_modules/zone.js/dist/zone.js:9:65)
      at Object.<anonymous> (node_modules/zone.js/dist/zone.js:12:2)
      at Object.<anonymous> (node_modules/jest-preset-angular/setupJest.js:5:1)
```

Any idea?

**Comment by treshugart** [comment]
@mnicic it sounds like Zone might be doing something odd with with environment detection, or something. Happy to fix on this side if it's a problem with our test env.

**Comment by mnicic** [comment]
@treshugart Actually, I'm not reporting an issue. I'm just asking about how to implement it. Any suggestion? Or example?
