### ISSUE TITLE
I see 5.1.1 on NPM, but no tag in the repo?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1379]
I was trying to investigate some code in node_modules, but it differs from what I see here in the repo. I see that I have `skatejs` 5.1.1 installed, but I don't see that tag here in the repo. Where's it at?

**Comment by trusktr** [comment]
I don't see it in the GitHub releases either.

**Comment by trusktr** [comment]
Ah, this is in the v6 branch too! I spent too much time reading the old code, loaded up node_modules version to find it was totally different. 😆

**Comment by treshugart** [comment]
Yeah, I've done a few releases from there. I'm still getting used to the monorepo.
