### ISSUE TITLE
No more dash-cased props to attributes?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1380]
https://github.com/skatejs/skatejs/blob/f5de3c95e169067c50df30f3d091717e501a9192/packages/skatejs/src/with-update.js#L30

No more dash-case? Why so? I like the camelCase <-> dash-case.

`someLongProp` becomes `somelongprop` which may  not be as readable as `some-long-prop`.

**Comment by treshugart** [comment]
I think what will happen here is that we'll end up providing a function for the `attribute` option and default it to this method. That way you can go back to dash-casing if you really want.

**Comment by treshugart** [comment]
Will close this for now since there's no real action for it, but still happy to discuss.

**Comment by trusktr** [comment]
> That way you can go back to dash-casing if you really want.

Sounds good, if it's configurable then people have freedom to choose. 👍
