### ISSUE TITLE
Pleeeeease, don't remove prop-to-attribute mapping.

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1381]
This is a good feature that I'm relying on, and the [removal of it](https://github.com/skatejs/skatejs/commit/4c3212d7b8b70cff187b80d6751b41dc3f98daa6#r27633516) (see the comment there) means we have to side-step SkateJS API to achieve it. EDIT: oops, I may have commented in the wrong place there, but I see the latest version of `with-update` in the `v6` branch does not have the prop-to-attribute feature any more. I believe that is a really good feature, because it is needed sometimes, and the previous API makes it really easy to automate.

**Comment by treshugart** [comment]
Yeah, I removed it to see what it actually felt like and I think it's going to have to go back as an opt-in to sate those that need that behaviour.

**Comment by treshugart** [comment]
What the API will probably end up looking like is:

```js
type PropConfig = {
  attribute: string => string,
  deserialize: string => any,
  serialize: any => string
}
```

**Comment by blikblum** [comment]
IMO property to attribute reflection should be kept

Some actual use case: https://github.com/morbidick/bootstrap-webcomponents/issues/1

Also LitElement is getting this feature as part of its [redesign](https://github.com/Polymer/lit-element/pull/132)

**Comment by treshugart** [comment]
Reflecting properties to attributes will be kept. That said I’m unsure if
name mapping is necessary at this point. Keep in mind v6 is still very much
a playground for me but keep giving feedback for sure.

**Comment by trusktr** [comment]
> Reflecting properties to attributes will be kept

I noticed. Yaaaay. 👍 

I think this can be closed now.

**Comment by trusktr** [comment]
> so don't be too alarmed if you see this in experimental branches in the future, but totes keep feeding back.

👍 

Yep, I saw it gone in `v6` branch, but back in `v6-trey`.

Just like `PropTypes` in React is an optional feature, it'd be great to also have runtime type stuff in Skate as an optional feature.
