### ISSUE TITLE
Question around async triggerUpdate

### ISSUE THREAD

**Issue by deini** [skatejs/skatejs#1392]
* Skate version: _5.1.1_

### Current behaviour
Today I stumbled into what I believe is a corner case. To be honest I'm not entirely sure if this is a bug or just something to take into consideration.

Since `triggerUpdate` is async, if you change props/state before `updated` is called it will run `triggerUpdate` again but since the `_updating` flag is true it will return early, causing it to not re-render with the latest props/state.

Here is an example:
https://codesandbox.io/s/m4no32nr7y

There is a Parent and a Child component, parent listens to a `disconnected` event on the child.

There are 2 state properties on the parent `showChild` and `isChildDisconnected`.

When you press the "disconnect child" button it sets `showChild` to `false ` triggering state's setter which calls `triggerUpdate` setting the `_updating` flag. When its re-rendering the `disconnected` event from the child is being triggered which again udpates the state but when it gets to `triggerUpdate` since its already updating it will return early.

To work around this I wrapped `handleChildDisconnect`'s state in a `setTimeout`.

My questions: Is this something Skate can/should handle differently?

**Comment by treshugart** [comment]
Definitely seems like an edge case that can be worked around. Your `setTimeout` is one way (or to batch disconnecting events, which will have the same effect).

I have another suggestion but it depends on the concrete use case needed for the disconnected event. Generally you wouldn't execute code like this that happens as the result of a render. That's like setting state during render which is generally an anti-pattern because of infinite loops. Anything affecting the render should be the result of state checks. In this scenario, you know when the child is being disconnected already, so the event doesn't really make sense. That said, I feel like this is showing the problem in simplified form of a grander use-case?

**Comment by deini** [comment]
> Generally you wouldn't execute code like this that happens as the result of a render.

I agree 100%


> That said, I feel like this is showing the problem in simplified form of a grander use-case?

Yeah, tried to come up with a real-world simple use case but couldn't think of any.

I was playing with the idea of doing a tabs/tab component with an API similar to:
```html
<x-tabs id="tabs">
  <x-tab id="tab1" label="tab1" active>Content of Tab 1</x-tab>
  <x-tab id="tab2" label="tab2">Content of Tab 2</x-tab>
</x-tabs>
```

The idea was that a tab can be dynamically added and tabs will then "register" it and display the label while the tab itself displays its content.

Its hard for me to explain it but here is some working code: https://codesandbox.io/s/ypmwl7kr6z

I honestly don't like it that much... I'm passing references in events all over the place which I'm guessing its not a good practice. Feedback would be appreciated 💃 

Update on the actual issue: Currently don't have access to the code but I couldn't reproduce it from memory. I'm quite sure its just my render doing side effects. Will report back when I get a chance to 🔎 at it again.

**Comment by treshugart** [comment]
> I was playing with the idea of doing a tabs/tab component with an API similar to:

In that scenario, though, you're not rendering those items, the consumer of your component is. If you use the `withChildren()` mixin (included in the `withComponent()`) mixin by default, then you'd update your state in that callback.

**Comment by deini** [comment]
TIL about `withChildren()` way simpler https://codesandbox.io/s/kk6ry26q6o
