### ISSUE TITLE
Ability to define coerce, serialize, deserialize (etc) in class definitions.

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1396]
Continuing from what I was thinking in #1385, would it be convenient to allow `coerce`, `serialize`, and `deserialize` (I think they can be handy) to be defined on class prototypes?

For example:

```js
import { withComponent, props } from 'skatejs'

class MyEl withComponent(HTMLElement) {
  static props = {
    foo: props.array
  }

  // we can use `this` in any of these methods, which can be convenient
  get foo() { ... }
  set foo(val) { ... }
  ['coerce foo'](val) { ... }
  ['serialize foo'](val) { ... }
  ['deserialize foo'](val) { ... }
}
```

**Comment by trusktr** [comment]
@treshugart What I think is nice about having coerce, serialize, deserialize, regardless if they are on the class prototype or not, is that they make a clear path otwards doing what people need to do anyways: parse strings to objects during deserialization, and so by removing all those features in the `v6` branch, it's removing some of the main functionality that attracts me to Skate. Otherwise, I could parse attributes myself then call manually re-render React/Vue/etc. I really like the idea of structurizing and conventionalizing how serialization/deserialization happens so that defining it is easy and generic.

**Comment by treshugart** [comment]
Interesting. I think that syntax would be hard to swallow for many. There's also the repeated name of the prop, where it feels more closely organised in the `static props`. That said, subclassing becomes inherent. On the other hand, inheritance of props being explicit (instead of implicit like this) might be a good thing.

**Comment by trusktr** [comment]
I don't see `changed`, I think you've already removed it.

But yeah, I really like the idea of `this` referring to the prop definition, and `elem` being passed in, because this makes it even more flexible than just `this` referring to the element. 👍

**Comment by trusktr** [comment]
> I want props to be WYSIWYG sans deserialize. Types can help here.

I disagree with that because I want anyone to be able to use my elements and have specific guarantees on the data types (useful errors otherwise), even if they don't use TypeScript or Flow, just plain JS.

It'd be really great if it was easy to opt-in/out to either: a TypeScript library author can decide not to use the features, and leave it up to the typing, while another library author could decide to use the features.

In React, we can use TypeScript, but we can also use a [runtime PropTypes system](https://reactjs.org/docs/typechecking-with-proptypes.html). We have the ability to choose either, or both.

**Comment by trusktr** [comment]
Oh, I see `changed` was turned into `get`/`set`. I think I like the new `get`/`set`. Still looking at it...

**Comment by treshugart** [comment]
If at some point there's compelling evidence that doing this style of prop definitions is something we should do, then we can consider it. However, as of right now, it doesn't seem as nice as using `props` and I want there to be *one* way. 

I think the other concerns have been covered, so I'm going to close this.
