### ISSUE TITLE
skatejs.netlify.com crashes

### ISSUE THREAD

**Issue by mnemanja** [skatejs/skatejs#1399]
When trying to use the documentation, the browser tab crashes.

Try clicking through the first level links, it usually brakes on the "Renderes" page.
For example going from "Migrate" to "Renderes".

**Comment by treshugart** [comment]
Interesting. Which browser are you using? I've tried Chrome, Firefox, Safari (both Mac and iOS). Is this an Edge / IE11 thing?

**Comment by mnemanja** [comment]
Sorry for the lack of initial information.
It's been Chrome on Ubuntu. 
I can confirm that it works on Windows Chrome. I do see this when navigating to Mixins > Children. Not sure if it's related.
![image](https://user-images.githubusercontent.com/1423218/36943321-b32067f2-1f87-11e8-8e0b-de2f411fd527.png)

**Comment by treshugart** [comment]
Oh, yeah, that's a bug in the `withChildren()` mixin. I stumbled across that the other day but couldn't log it. Let's track that here.

**Comment by sambigelow** [comment]
We are experiencing this quite a bit. I think this should be taken seriously because I am considering using Skate for a project but this makes me nervous

**Comment by treshugart** [comment]
@sambigelow contributions welcome.

**Comment by treshugart** [comment]
So it looks like this was already fixed at the package level, the site just didn't redeploy. Will do that later.
