### ISSUE TITLE
Webcomponent not connected when using insertAdjacentHTML

### ISSUE THREAD

**Issue by cndev123** [skatejs/skatejs#1425]
## Bug report

A skate web component is not correctly connected when using insertAdjacentHTML to add the html. 

* Skate version: _5.1.1_
  
* Affected browsers (and versions): _Chrome_

### Current behaviour

If you use the following code, mySkateComponent is not connected, i.e. the custom tag is not connected to the web component javascript. 
`document.body.insertAdjacentHTML('beforeend', '<mySkateComponent></mySkateComponent>');`

However, if I do it like this, everything works as expected:
`document.body.insertAdjacentHTML('beforeend', '<div id="myDiv"></div>');
document.querySelector('#myDiv').innerHTML= '<mySkateComponent></mySkateComponent>';`

### Expected behaviour

Adding a web component via  insertAdjacentHTML should also work.

**Comment by treshugart** [comment]
This sounds like a bug in Chrome as Skate doesn't do anything with the native methods. Does `innerHTML` work?

**Comment by cndev123** [comment]
Thank you for the investigation. Yes, innerHTML does work.

**Comment by treshugart** [comment]
Yeah, I think it's probably a bug in the shadow DOM polyfill. Best to probably raise an issue over there :)
