### ISSUE TITLE
await rendering / rendered

### ISSUE THREAD

**Issue by cinatic** [skatejs/skatejs#1427]
This is more a question rather then a bug. Why did you decide not to await for rendering and rendered function?

```
        this.rendering && this.rendering();
        this.renderer(this.renderRoot, function () {
          return _this2.render && _this2.render(_this2);
        });
        this.rendered && this.rendered();
```

best regards

**Comment by cinatic** [comment]
I do not use react or litHTML. The idea is to load data in rendering which then can be used in the render function.

Right now i load data (loaddata()) in rendering(), render empty construct in render() and as soon as the data has been loaded in loaddata() i do a triggerupdate(). To avoid reloading data i set a flag dataloaded = true.

```
import {withComponent, props} from 'skatejs5';

const Component = withComponent();


class RowExplorer extends Component {
  /***** properties & constructor *****/

  static get props() {
    return {
      dataId: props.integer
    };
  }

  constructor() {
    super();
    this._data = null;
    this._initialized = false;
  }

  /***** skate overrides *****/
  rendering() {
    if (!this.dataId || this._initialized) {
      return;
    }

    this._loadData();
  }

  render() {
    return tpl({data: this._data, isInitialized: this._initialized});
  }

  /**** private methods ****/

  async _loadData() {
    const apiData = await model.loadApiData(this.dataId);

    if (!apiData || !apiData.length) {
      this._initialized = true;
      this.triggerUpdate();
      return;
    }

    this._data = apiData;
    this._initialized = true;
    this.triggerUpdate();
  }
}

customElements.define('row-explorer', RowExplorer);
```

with async functionality i do not have to call triggerUpdate() because the data is guaranteed to be there in render

**Comment by trusktr** [comment]
Hi @cinatic, if you store your data inside `state`, then you just modify your state and which should automatically trigger update and re-render, and you don't have to do it manually. Have you tried that?

See `withUpdate` docs: http://skatejs.netlify.com/mixins/with-update

**Comment by trusktr** [comment]
That being said, async rendering might be something else entirely. It may be possible that the render result itself is asynchronous.

In the case of all the supported SkateJS renderers, they all render sync, but I _have_ seen libraries that render using async before. It may be interesting to find one of those and try it in Skate.

**Comment by cinatic** [comment]
In my opinion we have some different use cases here 

1. dynamic and frequently changing content -> use state or property observer 
2. more or less static content loaded from an api

I can use the state or an observer to avoid to write triggerupdate manually, but at the end i still have the same behaviour an it walks trough render two times. 

It's bugging me that as shwon in my example you have to walk first time trough render without knowing if you have data, so you need to add flags like hasInitialized or isDataLoaded and when you have data walk through render again.

An await in the rendering/prerender function would guarantee that the data is there, i think this can provide just some more flexibility to skatejs

**Comment by cinatic** [comment]
Yep I think you are right in the most cases you want to show something to the user.

Thanks for your opinion

**Comment by treshugart** [comment]
Cheers and thanks for your question, as well.
