### ISSUE TITLE
Constructor-as-tag-name and auto-defining

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1437]
## Feature request

Add constructor-as-tag-name support to renderer-preact. It would look something like https://twitter.com/_developit/status/991428489843650560, but we'd need to do it only for a particular render tree as we wouldn't want to affect everyone.

This can probably be done by defining the `vnode` option right before rendering and then restoring it to the previous value right after.

Open questions:

1. Do we need to call back to the original if it exists?
2. Should we auto-define the custom element if it doesn't exist? This would make it so you don't have to define at all.

### Use case(s)

```js
// Import standard custom element
import MyCustomElement from 'my-custom-element';

// Preact
<MyCustomElement />
```

**Comment by sghoweri** [comment]
👍🏼👍🏼👍🏼

**Comment by treshugart** [comment]
This is now in master. It's super convenient but I'm holding off on releasing it for now as I play around with it. Feedback welcome.
