### ISSUE TITLE
skatejs/dist/skate.min.js empty

### ISSUE THREAD

**Issue by maikeldaloo** [skatejs/skatejs#144]
Hey guys,

Just a quick note to say that the dist/skate.min.js file is empty. Please check your build and make sure that the minified script is being rendered.

**Comment by treshugart** [comment]
I'll have a look tomorrow. @wbinnssmith seems that came from your recent PR. I normally don't check dist on non releases. @maikeldaloo is this blocking you? Are you able to generate the dist yourself?

**Comment by maikeldaloo** [comment]
@treshugart it's not blocking me yet. I'm planning to use it soonish though. But I just wanted to make you aware :smile:

**Comment by treshugart** [comment]
Thanks again. It's safe to use tags and we should have another release out
within the next couple weeks.

**Comment by maikeldaloo** [comment]
Awesome. Great work though.
Since I discovered Skate, I've been trying to find any excuse to use it.

**Comment by wbinnssmith** [comment]
Thanks @maikeldaloo. This was indeed an oversight on my part (yay streams), and there's a PR open to address it.

**Comment by treshugart** [comment]
PR merged. Should be all good now. Let us know if you have any other issues.
