### ISSUE TITLE
Browser bundle transpiles classes

### ISSUE THREAD

**Issue by timwis** [skatejs/skatejs#1442]
## Bug report

* Skate version: _5.1.2_
  
* Affected browsers (and versions): _Chrome 68_

### Current behaviour

Using a [very basic setup with lit-html](https://gist.github.com/timwis/e540d89aee77421f502b51bbd1ca1421), I get a console error on `node_modules/@skatejs/renderer-lit-html/dist/es/index.js`:

```
Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
```

If I remove lit-html I get the same error on `node_modules/skatejs/dist/es/with-renderer.js`. Inspecting those files, it looks like the issue is that they're transpiled down to ES5, which involves removing ES6 classes. And classes are necessary for web components to work (unless you get that special polyfill).

I fixed this by adding the following to my webpack config:

```javascript
  resolve: {
    mainFields: ["esnext", "browser", "module", "main"]
  }
```
This tells webpack to use the bundle specified in skatejs's `package.json`'s `esnext` field first, if it's available. In that bundle, classes are not transpiled away.

Is this intended behaviour?

**Comment by treshugart** [comment]
Unfortunately, yeah, that is intended. The spec got rehashed awhile back and they decided to use native classes to extend HTMLElement, which isn't possible in ES5 without lots of hacks. I'm sure you've already come to this conclusion and it's why we decided to expose the `esnext` source.

I'm not sure which browsers you're targeting, but if you need to transpile to es5 you'll have to include the shim (or polyfills, not both in any given browser lifecycle). You have to ensure all of your code is es5 or es2015 classes, but no mixture of the two otherwise you get this error.

Unfortunately, there's nothing Skate can do about this and is widely-known to be one of the most painful parts (failing?) of the web component specs. 

Looks like you've solved your issue, but let me know if you have any more trouble and we can reopen. Thanks!

**Comment by timwis** [comment]
@treshugart thanks, but I wasn't trying to transpile to ES5. Are you saying that, if I had transpiled my source to ES5, it would have worked with the `browser` bundle? And that, if I don't want to transpile my source to ES5, I have to manually tell webpack to use the `esnext` bundle?

**Comment by Viniter** [comment]
@treshugart Hi, you might consider adding a mention of this to docs (or the Getting Started guide I guess). It's quite a pain having to figure out that there are multiple builds, which build do you need depending on whether or not are you compiling down to es5, and how to make webpack bundle the right build.

`mainFields` worked for me, but it's not the best first impression, if you can't get the library working without digging through node_modules and github issues.

**Comment by treshugart** [comment]
Oh my, @timwis, apologies for not seeing your response sooner. I just applied your gist to a codesandbox, but altered it slightly to get it working with native support: https://codesandbox.io/s/l42nwrz7kz.

You'll have to adjust the babelrc to your liking, but the key is to prevent classes from being transpiled and use the `esnext` versions from the library dists.

In v6 we'll be attempting to make consumption a bit more streamlined.

**Comment by treshugart** [comment]
> @treshugart Hi, you might consider adding a mention of this to docs (or the Getting Started guide I guess). It's quite a pain having to figure out that there are multiple builds, which build do you need depending on whether or not are you compiling down to es5, and how to make webpack bundle the right build.

> mainFields worked for me, but it's not the best first impression, if you can't get the library working without digging through node_modules and github issues.

Totally fair. We're working on streamlining the consumption model in v6, so we'll definitely update docs to reflect this better. I've raised #1521 to address this.

**Comment by FDiskas** [comment]
Thanks for `@skatejs/renderer-lit-html/dist/esnext`

**Comment by treshugart** [comment]
@FDiskas if you're still having trouble, could you raise a separate issue describing the problem in more detail? Thanks :)
