### ISSUE TITLE
Do not set props.children in renderer

### ISSUE THREAD

**Issue by blikblum** [skatejs/skatejs#1443]
___This is in preview in the v6-trey branch.___

---

### Current behavior

All renderers, be default, set a children property to props

### Expected behavior

No children property should be set to props

### Use case(s)

Reasons to remove:
 - props.children in skatejs components has a different meaning than, e.g., Preact, Snabbdom or React. In former is just a slot element, in later, the children vnodes. This can:
   * cause confusion when, e.g., developing a component in Preact and then in skatejs (with renderer-preact)
   * lead to not expected dom structure (in skatejs component will have at least an extra slot element, not counting named slots) 
 - using slot elements directly are easy and open the doors the more advanced features like named slots 
 - it requires run extra code, with creation of a temporary vnode (not used in most cases) and a extra shallow copy of props, increasing pressure on garbage collection
 - when not using shadow dom as rootEl the props.children will not work which is not evident for those not familiar with the implementation
 - It's already removed in v6 branch

**Comment by treshugart** [comment]
Yeah, I'm happy for this to be removed. It lowers the surface area of the components. I'll leave this open and flag as v6.

**Comment by josgraha** [comment]
How would children be rendered with nested custom elements react without the slot?

**Comment by blikblum** [comment]
> How would children be rendered with nested custom elements react without the slot?

Just render an `<slot/>` element. this is the only way to do it with web components. The props.children is just syntactical sugar on top of it and has a different meaning than React `children`

**Comment by treshugart** [comment]
The idea before was that you can just spread props onto the react element and it will render a `<slot>` wherever it renders `{this.props.children}`. I'm torn because this was pretty nice to have but maybe not necessary. Do we have a PR for this yet?

**Comment by blikblum** [comment]
> The idea before was that you can just spread props onto the react element and it will render a <slot> wherever it renders {this.props.children}

I did not tested but even this will not work out of the box because this.props will only return keys that are defined in static props. Related to #1480 

> Do we have a PR for this yet?

Not yet. It was postponed to v6

**Comment by treshugart** [comment]
This is no longer done.
