### ISSUE TITLE
Skatejs/ssr fails due to dispatchEvent

### ISSUE THREAD

**Issue by DiiLord** [skatejs/skatejs#1454]
## Bug report

* Skate version: _5.1.5_
* Skate ssr version: _0.19.5_
* Affected browsers (and versions): _Node 9.4.0_

### Current behaviour

When running the demo in the skate/ssr README, node throws an error:
`TypeError: parentNode.dispatchEvent is not a function`

### Expected behaviour

It should not throw an error.

**Comment by treshugart** [comment]
Fixed in a3ded28e5b63f6735a34e5a427df052a2544bb1e and released in 0.19.6. Thanks for the report!
