### ISSUE TITLE
sk_marked strips first char of each line

### ISSUE THREAD

**Issue by blikblum** [skatejs/skatejs#1457]
## Bug report

* Skate version: _5.2.1_ (`npm info skatejs version`)
* Affected browsers (and versions): all
* Running on windows

### Current behavior

sk_marked strips first char of each line. 

### Expected behavior

Should not strip first char

I've got this error when building the site under a windows environment. Since windows handles new lines differently the bug is not visible on linux

Consider the following sk_market [code](https://github.com/skatejs/skatejs/blob/master/packages/sk-marked/src/index.js#L11):
```
 src = src.replace(/"/g, '&quot;');

  // Remove leading newlines.
  src = src.split('\n');

  // Get the initial indent so we can remove it from subsequent lines.
  const indent = src[1] ? src[1].match(/^\s*/)[0].length : 0;
```
at this point src is an array so `src[1]` matches the second line and not first char. Probably the bug is only apparent because on windows `src[1]` points to an empty line (when parsing skatejs README)

I did not tried a fix because i don't get the reason of this procedure. It's supposed to check the first text char and than if the char is blank, remove the some number of chars for each line. But what if next lines does not have the same indentation?

**Comment by treshugart** [comment]
It's supposed to find the baseline indentation. We could probably use https://github.com/sindresorhus/detect-indent instead.

**Comment by blikblum** [comment]
> We could probably use https://github.com/sindresorhus/detect-indent instead.

It will not work because it not detects the baseline indentation but the most used indentation, which would lead to stripping actual content

**Comment by treshugart** [comment]
Ahh right. Just reviewed your PR btw.

**Comment by treshugart** [comment]
> + @skatejs/sk-marked@0.0.1

Released!
