### ISSUE TITLE
withChildren: Children may not be upgraded when childrenUpdated() is called.

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1459]
https://github.com/skatejs/skatejs/blob/31b776c6fd9031a2bb43e005d1ed8b93d0b1b001/packages/skatejs/src/with-children.js#L16-L24

I have some code similar to that one, calling a custom `childConnectedCallback` method inside of `connectedCallback`, but the problem with it is that `connectedCallback` can be called during parsing of the HTML page. If the custom element is already defined before parsing, then when `connectedCallback` is fired and therefore `fn()` is called, the `children` will be not-yet-upgraded if they are also custom elements. This will break code that relies on certain APIs existing on the child custom elements.

During parsing, parent elements are upgraded and their `connectedCallback` methods fired before their children are upgraded.

What I did to solve it in my case was to defer it like this:

```js
        connectedCallback() {
            super.connectedCallback && super.connectedCallback()

            // wait for children to have been upgraded
            // (in my case, children are from the same library: infamous)
            documentReady().then(() => {

                // if we're connected for the first time, we will not yet have a MutationObserver
                if (!Private(this).childObserver) {

                    const children = this.childNodes
                    for (let l=children.length, i=0; i<l; i+=1) {
                        this.childConnectedCallback(children[i])
                    }

                    // this creates a MutationObserver
                    Private(this).childObserver = observeChildren(this, this.childConnectedCallback, this.childDisconnectedCallback)
                }
            })
        }
```

In that sample `documentReady()` is a promise, so even if the document is already ready, the behavior is consistent (async).

I did this so that different orderings of loading `infamous` by script tag would always work. For example, compare the following two possibilities:

```html
<script src="infamous.js"></script>
<i-scene ...></i-scene>
```

```html
<i-scene ...></i-scene>
<script src="infamous.js"></script>
```

---

At some point, someone using `withChildren` will encounter this.

I wonder what's the best solution? Is waiting for document ready the best way to do it? What about on pages with lots of HTML to load, and the document takes long to load? Is there ever a chance to execute the callback earlier than document ready but after children are upgraded?

**Comment by trusktr** [comment]
I made a PR to show the minimal idea: https://github.com/skatejs/skatejs/pull/1460

**Comment by treshugart** [comment]
If children have a definition already loaded, during parsing, they should already be defined, IIRC. So in this instance, you could use `customElements.whenDefined()` to defer any work until after they're defined, or load the definitions before (or as dependencies of the host.

**Comment by trusktr** [comment]
> If children have a definition already loaded, during parsing, they should already be defined

Not sure exactly what you mean, but the following two fiddles show the problem. Compare the outputs in your console:

- https://jsfiddle.net/trusktr/y9vtp6dq/10
- https://jsfiddle.net/trusktr/y9vtp6dq/11

If we defer the child callback, then the end user won't have to worry about using `whenDefined` to make it work.

**Comment by trusktr** [comment]
> The only issue I have with that is that they can't opt-out of it if DOM ready is too late 

That's true, but they shouldn't really care right? If they put their logic in the child callback, then it fires when it's ready without them thinking about when the children are actually ready. Is there a case they'd _want_ to opt out?

**Comment by trusktr** [comment]
> I really lament the fact that we have to go to such lengths to deal with inconsistent behavior.

Yeaaaaaah. It would've been great for the spec to require the same order of operations in either case.

I don't remember where, but somewhere in `w3c/webcomponents` or related threads someone mentioned that the reason is because that if the order is child-first while parsing, then this means if there's a page with _tons_ of HTML to load from a (potentially slow) network, then it may take a longer time before any custom elements load.

But I'm not sure that's really a good reason. Who's using Custom Elements and loading a boatload of markup on initial payload?

The funny thing is, if we place a script tag after all the markup, then it's going to take a while until that script is parsed anyways. So that point seems moot, now that I think about it.

**Comment by treshugart** [comment]
> That's true, but they shouldn't really care right? If they put their logic in the child callback, then it fires when it's ready without them thinking about when the children are actually ready. Is there a case they'd want to opt out?

Yeah, I think we might be fine there.

**Comment by treshugart** [comment]
This will be fixed in the next major releases.
