### ISSUE TITLE
@skatejs/renderer-surplus

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1463]
I feel it coming...

See benchmarks, where Surplus beats everything: https://www.stefankrause.net/js-frameworks-benchmark7/table.html

It's missing the component system. That's where SkateJS comes in.

**Comment by treshugart** [comment]
Interesting; I've never heard of surplus. Def open to it.

**Comment by trusktr** [comment]
I'm going to do make the renderer if you don't first. It's just a matter of time before I get to needing the planned feature in my project. :D

**Comment by treshugart** [comment]
I don't have any plans to at the moment, but more than happy to have another renderer!

**Comment by treshugart** [comment]
Closing as this has been open for awhile and I don't have the time to implement a renderer for it.
