### ISSUE TITLE
`es` build doesn't work with native Custom Elements, can't call HTMLElement without `new`

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1465]
## Bug report

* Skate version: 5.2.1 (`npm info skatejs version`)
* Affected browsers (and versions): ones that have native Custom Elements

### Current behaviour

demo: https://codesandbox.io/s/vyy3pklr15

### Expected behaviour

For the transpiled code to be able to call HTMLElement classes properly.

### Solution:

Build the `es` version using @WebReflection's [`babel-plugin-transform-builtin-classes`](https://github.com/WebReflection/babel-plugin-transform-builtin-classes/). It solves the problem at build-time.

I suggest to avoid Polymer's native-shim.js, which works at runtime and introduces build complexity when you want to produce only a single bundle that works everywhere.

### Workarounds

- Use [`lowclass`](https://github.com/trusktr/lowclass/) or [`newless`](https://github.com/Mr0grog/newless/) to define classes that extend builtins. This will always work regardless of the build system.
- If you're using a tool like Webpack and a modern browser, tell it to use the `esnext` version by specifying an alias.

### TODO

- [ ] A pull request

**Comment by treshugart** [comment]
`es` is designed to be `es5` with esmodules. The `esnext` build should have native classes. For the `es` build you need the custom element shim or polyfill.
