### ISSUE TITLE
Is possible to create custom elements without registering them? 

### ISSUE THREAD

**Issue by blikblum** [skatejs/skatejs#1467]
## Question

* Skate version: 5.2.1
* Affected browsers (and versions): chrome 67

While playing with Custom Elements, i could not find a way to create a custom element directly, i.e., calling its constructor.

I tried with skatejs transpiled to es5 + custom-elements-adapter but got an error "b is not constructor": 
https://codesandbox.io/s/qvpxjj35wj

I could not get a setup with skatejs/esnext (untranspiled ES6 classes) but managed to create an example with pure custom element using native ES6 classes and i get an "TypeError: Illegal constructor" error: https://codepen.io/blikblum/pen/BPjZBr?editors=1111

Interestingly if i define the element using `customElements.define`, it starts to work

Does someone got a setup where creating a custom element through its constructor works without registering it?

**Comment by blikblum** [comment]
Tested on firefox with webcomponents flag on and the error message is more explicit: "Custom element not registered"

My conclusion is that is not possible to create custom elements without registering them, and is nothing related to skate.

In fact this makes sense because it needs a tagName to render in the DOM

**Comment by treshugart** [comment]
Yeah. You can use the preact renderer without registering tho. See https://github.com/skatejs/skatejs/blob/master/packages/renderer-preact/src/index.js#L26. Need to document this!
