### ISSUE TITLE
idea: renderer-specific context bridges

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1468]
This is just an idea and I don't think I have time to invest in this area at the moment, but I'm just putting it here because I thought it was an interesting possibility:

It'd be convenient if Skate provided a bridge in each of its renderers to wire up the specific context implementation of the underlying view lib across Skate components.

For example, for React it would somehow extend the `React.createContext` so that it creates a context who's provider is able to somehow pass a context into the React tree inside of a Skate component. (make sense? See below usage example.)

For Preact, it would bridge [`preact-context`](https://github.com/valotas/preact-context).

Some view libs don't have contexts, so nothing to do in those cases.

This would be separate from Skate-specific contexts. If we really _really_ like the declarative approach that React/Preact have with JSX, this might be worth it. Plus it would help people migrate from React/Preact components to Skate without having to figure how to re-work their existing contexts.

## basic usage:

```jsx
import {createContext} from 'react'
import {withComponent} from 'skatejs'
import withReact from '@skatejs/renderer-react'

const Context = createContext()

class FooBar extends withReact(withComponent()) {
    render() {
        return <Context.Provide value={foo: 'foo'}>
            {/* the React context will cross the Skate component boundary. */}
            <bar-baz></bar-baz>
        </Context.Provide>
    }
}

customElements.define('foo-bar', FooBar)

class BarBaz extends withReact(withComponent()) {
    render() {
        return <Context.Consumer> { ({foo}) =>
            <span>The value of foo is: {foo}</span>
        }</Context.Consumer>
    }
}

customElements.define('bar-baz', BarBaz)

document.body.innerHTML = `
    <foo-bar></foo-bar>
`
```

**Comment by treshugart** [comment]
I'd prefer to solve this at the dom context level first. Maybe once that is done, we can look at bridging context with that?

**Comment by trusktr** [comment]
I think the features would be independent of each other: both features could be used together or separately, implemented in two separate mixins.

But yeah, I think getting Skate's own contexts working first would be ideal so that there's at least one way to do it with all renderers at least for new apps.

**Comment by treshugart** [comment]
I've had some thoughts about this recently. Essentially, WC context is the bridge cause it works everywhere. You can possibly create specific integrations to frameworks but I'm not sure exactly what that would look like yet.

**Comment by trusktr** [comment]
> Essentially, WC context is the bridge cause it works everywhere.

True, but at the cost of porting from the framework format to the SkateJS format. 

The main benefit of having renderer-specific context bridges would be that porting code would be easy. For example, one would simply copy the markup from a React component `render` method and paste it into a SkateJS component `render` method, and the contexts (`<Provider>`/`<Consumer>`) that are in the markup would simply just work.

That's the really only benefit, is the user being able to simply use what they're already familiar with.

---

For example, take this React component:

```js
import * as React from 'react'
import {Consumer} from './some-context'

class Foo extends React.Component {
  render: () => <div>
    <Consumer>
      {value => /* render something based on the context value */ }
    </Consumer>
  </div>
}
```

they could simply paste this into a SkateJS component, and it would simple just work:

```js
import withReact from '@skatejs/renderer-react'
import {Consumer} from './some-context' // still a React context.

class Foo extends withReact(withComponent(HTMLElement)) {
  render: () => <div>
    <Consumer>
      {value => /* render something based on the context value */ }
    </Consumer>
  </div>
}
```

and the context bridge would automatically handle wiring it up so it works.

---

Yeah, not completely sure about the implementation, but I think it would be possible by a parent SkateJS element passing `Provider`s to child SkateJS elements, and then wrapping the child subtree with the Provider.

**Comment by treshugart** [comment]
I'd prefer to see how the context elements fare for a bit before really sinking our teeth into this. We can keep it open if you like, though.
