### ISSUE TITLE
Element is not re-rendered when a property is set prior to custom element upgrade

### ISSUE THREAD

**Issue by blikblum** [skatejs/skatejs#1469]
## Bug report

* Skate version: 5.2.1
* Affected browsers (and versions): Chrome 67

### Current behaviour

When using lit-html as renderer and updating a element property, the element is not updated / re-rendered 

### Expected behaviour

The element should rerender when a defined property is updated

### Notes

Here's one example: https://codesandbox.io/s/v67v71517y

When `value` property is set directly the component does not re-render but it re-renders when is set through attribute

This issue is related to how lit-html creates the HTML nodes:
It creates a [template element](https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/template) which is cloned, the dynamic values are set (properties, attributes etc) and than is attached to document.

The problem occurs because at the time lit-html sets the property, the custom element is not upgraded yet (the prototype is still HTMLElement and not the custom element class), so instead of calling the property setter defined in the custom element class prototype, it creates a own property in the instance. 

When the element is upgraded to the custom element class, setting the property will set the property instance and not the prototype setter

Not sure if something can be done in skatejs, since is something specific how lit-html / custom element works.

Maybe delete the props in the instance? Anyway should be something in lit-html renderer to avoid degrade perf from others

**Comment by blikblum** [comment]
I realized the issue is not lit-html specific any time a property is set before the custom element is upgraded, the property notification fails.

I created a example with the default renderer: https://codesandbox.io/s/v67v71517y

Seems that the solution is really to delete the prop if is already set at the time of construction. Polymer/LitElement are already doing it: https://github.com/Polymer/polymer/blob/master/lib/mixins/properties-changed.js#L196-L199

**Comment by treshugart** [comment]
I'm having a hard time seeing the issue in that sandbox. Are you able to create a reproduction with a minimum amount of code?

**Comment by blikblum** [comment]
I simplified here: https://codesandbox.io/s/0okv3535ow

**Comment by treshugart** [comment]
Interesting. I've messed with a few things here just to see if it would change anything. The most notable change is manually updating and manually defining getters / setters, and the setter isn't even called the second time. Did I miss anything? https://codesandbox.io/s/0xk7vqrqk0

**Comment by blikblum** [comment]
> and the setter isn't even called the second time

This is the same behavior observed when using `static props`

Basically, when setting a property, the JS engine looks into the instance if the property exists. 
If exists it modifies directly. It only look at prototype for setters when the property does not exists in intance

**Comment by treshugart** [comment]
Ah, silly me, of course. Yeah, we should store the initial value then delete.
