### ISSUE TITLE
Using Skate with Preact: Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by hguiney** [skatejs/skatejs#1477]
I have no idea if I’m actually doing this correctly, as neither the README nor the [Getting started](https://skatejs.netlify.com/guides/getting-started) guide give me any fully functional source code; just snippets. To illustrate, I copied this example from “Using Skate with Preact”:

```js
/** @jsx h */

import { props, withComponent } from 'skatejs';
import withRenderer from '@skatejs/renderer-preact';
import { h } from 'preact';

const Component = withComponent(withRenderer());

customElements.define(
  'x-hello',
  class extends Component {
    static get props() {
      return {
        name: props.string
      };
    }
    render({ name }) {
      return <span>Hello, {name}!</span>;
    }
  }
);
```

into a file `index.js`.

I created a companion `index.html` with this, a barebones setup with the example custom element:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>SkateJS Test</title>
    <script type="module" src="index.js"></script>
  </head>
  <body>
    <x-hello>Bob</x-hello>
  </body>
</html>
```
In Chrome 67 (latest stable at time of writing) on macOS Sierra, I get “Uncaught SyntaxError: Unexpected token <” on Line 18, because the JSX-style return value is obviously not valid JavaScript.

If I take off `type="module"` from the script element, then I just get “Uncaught SyntaxError: Unexpected token {” on Line 3 because the ES Module import syntax stops being recognized.

I looked at the actual source of the SkateJS website, and thought maybe throwing in `<script src="https://skatejs.netlify.com/ce-es5-shim.js"></script>` would help, but it didn’t.

**Comment by blikblum** [comment]
You have to setup a JSX transpiler normally done by babel together with webpack  or another bundler

**Comment by treshugart** [comment]
You can translate that to:

```js
import { props, withComponent } from 'skatejs';
import withRenderer from '@skatejs/renderer-preact';
import { h } from 'preact';

const Component = withComponent(withRenderer());

customElements.define(
  'x-hello',
  class extends Component {
    static get props() {
      return {
        name: props.string
      };
    }
    render({ name }) {
      return h('span', `Hello, `${name}!`);
    }
  }
);
```

**Comment by treshugart** [comment]
Here's a working sandbox: https://codesandbox.io/s/621m5m0krr. This shows it working with the JSX form and with native custom elements (unstranspiled, so we're pulling from `dist/esnext` in the Skate libs).

I'll close this for now, but happy to continue the discussion.
