### ISSUE TITLE
Importing run time components

### ISSUE THREAD

**Issue by cliren** [skatejs/skatejs#148]
How do I load a component dynamically given the following scenario:

All components are deployed to /components context and are accessible at http://example.com/components/

components/
 -- component1/
 --- main.js
-- component2/
 --- main.js

Apps are deployed to /apps context and are accessible at http://example.com/apps/

apps/
--app1
---main.js

I would like to import a component this way without using an external amd loader (like requirejs):

var component1 = require('http://example.com/components/component1/main');

The idea here is components can be released without having to release an application. This might be slightly out of skatejs topic but I would like to hear your ideas and is skatejs planning to include any such feature?

**Comment by treshugart** [comment]
There are a couple alternatives given you have a CDN in place:

1. You could load each component individually. The obvious downside here is that you load each one separately. This is not wise and does not scale.

2. You could bundle them together but then you'd have to load all of them at once incurring unnecessary overhead in most situations.

The ideal solution is to import them using a module loader in your apps where you need them and to bundle them with your apps. I don't see a downside to re-releasing your apps if streamlined.

This is pretty far out of scope for Skate to provide a solution for, though. I hope I've helped with what I can and let me know if I've mis-read your question. All the best!

**Comment by cliren** [comment]
Thanks, you laid out all the options and their pros/cons. We have a generic component which has ships frequently and needs to available to all our apps (think navigation bar with custom components). So I am leaning towards navbar a dynamic component which bundles other components using a module loader.
