### ISSUE TITLE
withChidren does not work when used with withUpdate

### ISSUE THREAD

**Issue by blikblum** [skatejs/skatejs#1480]
## Bug report

* Skate version: _5.2.1_ 
* Affected browsers (and versions): all

### Current behavior

The children property set through the default [childrenUpdated implementation](https://github.com/skatejs/skatejs/blob/master/packages/skatejs/src/with-children.js#L9-L14) has no practical effect when withUpdate is used.

This occurs because withUpdate creates a [setter for `props`](https://github.com/skatejs/skatejs/blob/master/packages/skatejs/src/with-update.js#L183-L186), which only sets the properties that are defined in `constructor.props`. So if children is not defined in static props, there's no actual property setting.

See this [example](https://codesandbox.io/s/k20wn0ln6v). It replicates the [withChildren spec](https://github.com/skatejs/skatejs/blob/master/packages/skatejs/test/unit/with-children.spec.js#L52-L63)

But what occurs if we define children in static props?

Still not works because in this case, withUpdate creates a children getter, so `this.children` will return the default value and not the actual children. Example: https://codesandbox.io/s/6l4oor3jpr

### Expected behavior

withChildren should work independent of other mixins

IMO we should not provide a default childrenUpdated callback and let the user decide what to do in its own childrenUpdated callback

**Comment by blikblum** [comment]
> I think this is related to #1466 (comment)?

No its an independent bug.

Look at the examples. They are using the default renderer  which does not overrides `props`

**Comment by blikblum** [comment]
> I'd prefer to keep it as I want to try and guide the consumer down a declarative path: declare children and handle updates in render().

Personally is a feature i will not use (skate architecture makes easy enough to skip what you not need), but i recommend creating actual examples to test it. 

There are another independent issues, not reported, like children always being empty when shadow dom is enabled or mismatch between children count due to side effect of rendering.

**Comment by treshugart** [comment]
That's fair. It'd be fairly simple to just do something like:

```js
childrenUpdated() {
  // Implemented in withUpdate().
  this.triggerUpdate();
}
```

It's removed in v6 anyways, so I'll just keep it that way. Do you think this is worth fixing in the mean time?

**Comment by blikblum** [comment]
> Do you think this is worth fixing in the mean time?

Currently, the default `childrenUpdated` callback is basically useless.
If v6 is around the corner i would not invest much on it

**Comment by treshugart** [comment]
No mixins in `@skatejs/element` so we can close this now.
