### ISSUE TITLE
The best way to define new props types?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1481]
What's the best pattern for defining new prop types? For example, suppose I want a prop type of `SomeClass`. What's the recommended pattern for defining it?

I'd like to add this to the docs.

I see the `withUpdate` implementation has a `defaultTypesMap` variable, but it isn't exported so it isn't possible to add types that way (in order to map classes to the spec for converting strings into those classes.

Should we export a function for adding to the `defaultTypesMap`? Seems like a good idea.

What are some examples of defining custom types?

**Comment by trusktr** [comment]
My use case is I want to, for example, map a prop to a Three.js `THREE.Color` object.

**Comment by trusktr** [comment]
🤔 I can easily just save the output from `prop()` to a variable, and use that, as the result is the same. 

Gonna play with ideas and see what I come up with...

**Comment by trusktr** [comment]
I really like runtime type checking, as I can't tell everyone who ever uses my lib to use TypeScript or Flow. Some people will use plain JS, but I still want to enforce contracts in those cases.

**Comment by trusktr** [comment]
Alright, so after playing, what I'm doing is just importing `props` and defining my own, then using them like this:

```js
import { Color } from 'three'
import { props } from 'skatejs'

Object.assign(props, {
    THREE: {
        Color: {
            attribute: { source: true }, // get the value from an attribute (but don't mirror it back)
            coerce: val => new Color( val ), // Color accepts integers or {r: _, g: _, b _} objects
            get default() { return new Color( Math.random(), Math.random(), Math.random() ) }, // random default color
            deserialize: val => new Color( val ), // Color accepts CSS strings
            serialize: val => new Color( val ).getStyle(), // returns CSS string like "rbg(220, 130, 50)"
        },
    },
}

export { props }
```

and the consuming class (note it is defined using [`lowclass`](https://github.com/trusktr/lowclass))

```js
import BaseMeshBehavior from './BaseMeshBehavior'
import Class from 'lowclass'
import { props } from './props'

// base class for geometry behaviors
export default
Class( 'BaseMaterialBehavior' ).extends( BaseMeshBehavior, ({ Super }) => ({

    static: {
        type: 'material',
        props: {
            color: props.THREE.Color,
            opacity: { ...props.number, default: 1 },
        },
    },

    async updated( oldProps, oldState ) {
        if (! ( await Super( this ).elementIsMesh() ) ) return

        this.updateMaterial(oldProps, 'color')

        if (this.updateMaterial(oldProps, 'opacity')) {
            this.updateMaterialNoCheck('transparent')
        }

        Super( this ).updated && Super( this ).updated( oldProps, oldState )
    },

    get transparent() {
        if ( this.opacity < 1 ) return true
        else return false
    },

    updateMaterial( oldProps, propName ) {
        if ( oldProps[ propName ] !== this[ propName ] ) {
            this.updateMaterialNoCheck(propName)
            return true
        }
        return false
    },

    updateMaterialNoCheck(propName) {
        this.element.threeObject3d.material[propName] = this[propName]
        this.element._needsToBeRendered()
    },

}))
```

**Comment by trusktr** [comment]
I think that's a good enough approach. The only thing it could possibly have better is to map constructors to types, so that instead I could write:

```js
    static: {
        type: 'material',
        props: {
            color: THREE.Color,
            opacity: { ...props.number, default: 1 },
        },
    },
```

which saves a mere 6 characters, but also it seems more like a type def.

**Comment by trusktr** [comment]
Maybe we can export a `definePropType` helper function, perhaps usage like:

```js
import { props, defineProp } from 'skatejs'

definePropType(THREE.Color, {
            attribute: { source: true }, // get the value from an attribute (but don't mirror it back)
            coerce: val => new Color( val ), // Color accepts integers or {r: _, g: _, b _} objects
            get default() { return new Color( Math.random(), Math.random(), Math.random() ) }, // random default color
            deserialize: val => new Color( val ), // Color accepts CSS strings
            serialize: val => new Color( val ).getStyle(), // returns CSS string like "rbg(220, 130, 50)"
})
```

**Comment by treshugart** [comment]
The type mapping is only for built-ins, so we probably shouldn't expose it for mutations. Also, mutating any sort of global config can be problematic, for example, if Skate is a peer dep and shared across components that you may not have control over; config could clash.

**Comment by treshugart** [comment]
To your point about assigning to `props`, I wouldn't do that for the reason mentioned above. I'd just create a custom definition that you import local to your project.

```js
import { myProp } from './my-props';

...

props = { someProp: myProp }
```

Besides the import, it's just as terse as a built-in.

**Comment by trusktr** [comment]
> Skate is a peer dep and shared across components that you may not have control over; config could clash.

Heh, sounds familiar! (custom element naming)

> about assigning to props, I wouldn't do that for the reason mentioned above

Good point though. I'll can assign Skate props onto my own object instead.

My definitions look like this now:

```js
import { props } from 'skatejs'
import { Color } from 'three'
import XYZValues from '../../core/XYZValues'
import XYZNumberValues from '../../core/XYZNumberValues'
import XYZNonNegativeValues from '../../core/XYZNonNegativeValues'
import XYZStringValues from '../../core/XYZStringValues'
import XYZSizeModeValues from '../../core/XYZSizeModeValues'

function createPropType(Type, override = {}) {
    return {
        attribute: { source: true, target: false }, // get the value from an attribute (but don't mirror it back)
        coerce: val => val instanceof Type ? val : new Type(val),
        default: new Type,
        deserialize: val => new Type(val),
        serialize: val => val.toString(),
        ...override,
    }
}

const myProps = {
    ...props,
    THREE: {
        Color: createPropType(Color, {
            get default() { return new Color( Math.random(), Math.random(), Math.random() ) },
            serialize: val => new Color( val ).getStyle(), // returns a CSS "rbg()" string
        }),
    },
    XYZValues: createPropType(XYZValues),
    XYZNumberValues: createPropType(XYZNumberValues),
    XYZNonNegativeValues: createPropType(XYZNonNegativeValues),
    XYZStringValues: createPropType(XYZStringValues),
    XYZSizeModeValues: createPropType(XYZSizeModeValues),
}

export { props }
```

But after playing with it, I kept wanting this feature: https://github.com/skatejs/skatejs/issues/1493.
