### ISSUE TITLE
[bug] `_propsNormalised` missing from constructor

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1482]
## Bug report

* Skate version: _x.x.x_ (`npm info skatejs version`)
* Affected browsers (and versions): _IE 10_

### Current behaviour

I'm not sure why yet, but I placed `withUpdate` on a base class, and am setting up `props` in a child class, and for some reason when `attributeChangedCallback` is called, `constructor. _propsNormalised` is `undefined`.

<img width="1680" alt="screen shot 2018-07-29 at 6 52 26 pm" src="https://user-images.githubusercontent.com/297678/43373809-efb60cba-9360-11e8-8468-8d687d52da52.png">

(in the highlighted line, `_propsNormalised` is undefined)

I'm investigating why this is happening. It maybe I'm making my class hierarchy in some way that is an edge case for `withUpdate`, or maybe something I'm doing wrong.

### Expected behaviour

It should work. Let's see what's going on...

**Comment by trusktr** [comment]
Aha!!! I found the bug.

If `constructor.props` is an empty object, `_propsNormalised` is never created because it is only ever created in the function of a defined prop, but none are defined.

Then, if `attributeChangedCallback` is fired and it calls the one from `withUpdate`, the logic fails because it relies on `_propsNormalised` existing.

When any code reads `observedAttributes` it fires the `defineProps` function, which has this:

```js
function defineProps(constructor) {
  if (constructor.hasOwnProperty('_propsNormalised')) return;
  const { props } = constructor;
  keys(props).forEach(name => {
    let func = props[name] || props.any;
    if (defaultTypesMap.has(func)) func = defaultTypesMap.get(func);
    if (typeof func !== 'function') func = prop((func: any));
    func({ constructor }, name);
  });
}
```

But because there's no `props`, it will not loop and will therefore not create `_propsNormalised`.

PR coming soon.

**Comment by trusktr** [comment]
As a temporary workaround, I can just define some random prop on the class that doesn't have props (which extends from a base class that uses `withUpdate`, so that things just work, although I'm not doing anything with the prop:

```
        static props = { blah: props.string } // unused prop, to ensure _propsNormalised exists
```

**Comment by trusktr** [comment]
Hmmmmm, the strange thing is, some props from a different branch of my class hierarchy are making it's way over to the other side of the hierarchy where I've only defined `blah`. See:

<img width="1680" alt="hmmmmmm" src="https://user-images.githubusercontent.com/297678/43375350-5c318c7c-9369-11e8-92ac-c9f4cbcc7ab2.png">


Still investigating. 🤔 🔍

**Comment by trusktr** [comment]
I tried to make a small reproduction on codesandbox.io, but not luck. I'm not yet sure what's the difference with my class hierarchy, which is a lot more complicated that what I tried on codesandbox. Hmmmmmm...

**Comment by treshugart** [comment]
Hmm, sounds like it *could* have something to do with how you've structured your classes. Report back once you can create the simplest possible reproduction.

**Comment by trusktr** [comment]
I noted the code where this happened in my project, but I haven't swung back around to this yet. I'll post a repro soon.

**Comment by treshugart** [comment]
I experienced this the other day, and adding a `static props` saved it. Definitely a bug, but not sure how severe. If you think it's worth fixing, then happy to merge a PR.

**Comment by trusktr** [comment]
I'll swing back around to this if `v6` still needs it.

But in all honesty, I may be stuck forked on `v5` for a while unless mixins can come back into `v6`.

**Comment by treshugart** [comment]
> I'll swing back around to this if v6 still needs it.

v6 shouldn't need it but happy for it to go into v5 if you find time.

> But in all honesty, I may be stuck forked on v5 for a while unless mixins can come back into v6.

v6 does have a mixin, but there's only one. If you're avoiding it because there might be stuff you don't want to use then:

- Remember, all of core will be under 2k.
- You won't incur any unnecessary overhead.
- Pre-optimisation is the root of many evils :)

**Comment by trusktr** [comment]
> If you're avoiding it because there might be stuff you don't want to use then:

I can't use the DOM APIs in some of my cases.

I want the things I'm building to work with or without DOM, declaratively or imperatively (respectively), so coupling everything to DOM APIs in a single `Component` class makes it difficult for my cases.

Pre-optimization is a second concern over making it work, though it is valid that if [we know some things are not best](https://www.google.com/search?num=100&ei=vXm6W7S9FIf2tAWVip2YAQ&q=animation+stutter+garbage+collector&oq=animation+stutter+garbage+collector&gs_l=psy-ab.3...2585.3399..3526...0.0..0.129.937.0j8......0....1..gws-wiz.......0i71.ApqBm7Jf_II) then we should prefer the alternative: it is a well known practice to re-use the same objects in graphics rendering (especially in JS).

**Comment by trusktr** [comment]
>  all of core will be under 2k.

That seems like an arbitrary number. IMO it should take however many bytes it takes to achieve what you want to achieve in the best way.

F.e. Three.js is more than 1mb, and people are happy using it. They can make the user experience pleasant by putting up a nice animated CSS loading graphic, for example.

**Comment by trusktr** [comment]
> You won't incur any unnecessary overhead.

Doesn't seem true at the moment, for example I don't need to observe children in many cases, yet the single-class still calls `observeChildren(this);` in `connectedCallback` regardless.

I like that with mixins I can skip this feature entirely (plus, the non-DOM cases that I have, which don't work if we always call `MutationObserver`).

**Comment by treshugart** [comment]
> I can't use the DOM APIs in some of my cases.

I want to be very clear that Skate is a web component library that is designed to work with *DOM*. Your use case here is not supported.

> Doesn't seem true at the moment, for example I don't need to observe children in many cases, yet the single-class still calls observeChildren(this); in connectedCallback regardless.

In v6 it doesn't attach an observer if you don't define the method.

> That seems like an arbitrary number.

It is not. It's what v6 is at currently. I am intentionally limiting the focus. Need more functionality? Create a separate package.

> F.e. Three.js is more than 1mb, and people are happy using it. They can make the user experience pleasant by putting up a nice animated CSS loading graphic at the beginning, for example.

I don't; see how this, in any way, is relevant here.

> I like that with mixins I can skip this feature entirely (plus, the non-DOM cases that I have, which don't work if we always call MutationObserver).

I'm happy to have mixins, but I'd prefer them to be separate packages. Core should offer the common features for common users.

---

This issue got *way* off track. Let's please keep this focused.

**Comment by treshugart** [comment]
No longer an issue in `@skatejs/element`.
