### ISSUE TITLE
[idea] computed properties with S.js

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1483]
## Feature request

We can use a getter inside of `updated` to have semi-computed properties, for example https://github.com/skatejs/skatejs/issues/1334#issuecomment-408751758.

But this doesn't handle caching values and the glue code associated with that.

If using a `render` function, we don't need much glue code, we just pass vslues into the markup (f.e. using `renderer-preact` with JSX.

However, for imperative code, glue code has to be written (f.e. above example).

Maybe we can use [`S.js`](https://github.com/adamhaile/S) in a mixin called `withComputed` or similar to make caching automatic, and so that when a user's `updated` method is called they can use the variables without worrying about checking if props have changed.

### Use case(s)

Writing less code

**Comment by treshugart** [comment]
The core, functional concept of Skate revolves around computing values in `render()` (or a possible future `getDerivedStateFromProps()`, or similar. I'd prefer if this were an independent mixin.

**Comment by trusktr** [comment]
Let's keep in mind the cost of diffing and how we can avoid it: DOM diffing was brought to the spotlight by React, but only because it was better than alternatives (f.e. handlebars with innerHTML was popular with Backbone, but slow). Direct notifications (f.e. Surplus) will always be faster. Outside of DOM, I've solved performance problems by moving data away from Redux and using light-weight EventEmitter (direct notification, but not batched).

**Comment by treshugart** [comment]
Functional data flow doesn't equate to eventual diffing. Things like LitHTML present the ability to reach into the DOM and update specific spots without the baggage of diffing and virtual DOM.
