### ISSUE TITLE
What's the purpose for static get/set props in with-update?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1484]
https://github.com/skatejs/skatejs/blob/d4fdcfa899713eff687a60477d78114743e77308/packages/skatejs/src/with-update.js#L165-L171

Why are those get/set there? Why not just an empty object?

If someone writes 

```js
static props = { foo: props.number }
```

they are overriding it.

**Comment by trusktr** [comment]
Seems like this feature is unused, and that we can delete it. Did I miss anything @treshugart?

**Comment by treshugart** [comment]
> Seems like this feature is unused, and that we can delete it. Did I miss anything @treshugart?

Probably can. IIRC there was some possible issue with it. It's gone in v6 now anyways, so we can probably just close this.
