### ISSUE TITLE
Implement declarative context API

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1486]
CodeSandbox of an initial implementation: https://codesandbox.io/s/r0vjwmm2mp.

This replaces #1485.

**Comment by trusktr** [comment]
The React Hooks API moves away from declarative contexts. 👌

**Comment by treshugart** [comment]
> The React Hooks API moves away from declarative contexts.

it doesn't, though. You can still use providers in the tree, and this is the way you should be doing it in class components as you can't use hooks in them.

This has been implemented in `@skatejs/sk-context`.
