### ISSUE TITLE
commit hook commits all unstaged changes

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1487]
I noticed that a commit hook will pick up any un-staged changes and add them to the commit I just made, which isn't normal expected git behavior. 

Example:

```
❯ git status
On branch default-value-getter
Your branch is behind 'origin/default-value-getter' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   packages/skatejs/src/with-update.js

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   packages/skatejs/src/with-update.js

❯ git commit -m "foo"
husky > npm run -s precommit (node v9.11.2)

 ✔ Running tasks for *.{js,json,md}
[default-value-getter 30c4dadc] foo
 1 file changed, 6 insertions(+), 4 deletions(-)

❯ git status
On branch default-value-getter
Your branch and 'origin/default-value-getter' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```

It'd be great if we could fix this, because it complicates command line usage, requires more commands to save unstaged changes elsewhere.

**Comment by trusktr** [comment]
If I have no unstaged changes, the output of the commit command is different:

```
skatejs+skatejs git:default-value-getter ❯ git commit -m "foo"
husky > npm run -s precommit (node v9.11.2)

 ↓ Running tasks for *.{js,json,md} [skipped]
   → No staged files match *.{js,json,md}
On branch default-value-getter
Your branch is behind 'origin/default-value-getter' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
```

**Comment by treshugart** [comment]
It ensures things meet code formatting standards. We could possibly change it so that it creates a separate commit, but I'm not sure if we can do that.

**Comment by trusktr** [comment]
> meet code formatting standards

That part is nice. It's just unexpected that when I try to commit staged changes it also commits unstaged changes.

Can we stash the unstaged changes, run the code formatting, then after all is done, pop the last stash?

**Comment by trusktr** [comment]
For now I can use `git stash -k` before every commit, so that it stashed only unstaged changes.

**Comment by treshugart** [comment]
> Can we have it stash the unstaged changes, run the code formatting, then after all is done, pop the last stash? That way after the commit is done the unstaged changes remain there.

Wouldn't that have the potential for a high conflict rate?

**Comment by trusktr** [comment]
> Wouldn't that have the potential for a high conflict rate?

It might, if we're writing drastically different code format, but so far I haven't had any problems when I do `git stash -k` first, then pop it after the commit.

Usually my changes are in different areas, not touching the same piece of code. So a conflict could happen if there's two changes in the same place with drastically different format than the standard.

Overall I think it would be better though, because it is _suuuuper_ easy to forget to do `git stash -k` and commit unwanted changes because it isn't a normal workflow.

**Comment by treshugart** [comment]
Can we leave as-is for now? This is standard for husky setups.

**Comment by trusktr** [comment]
Husky only runs the git hooks. I just looked at `lint-staged`, and it says

> This project contains a script that will run arbitrary shell tasks with a list of staged files as an argument, filtered by a specified glob pattern.

So then why is it adding unstaged files?

**Comment by treshugart** [comment]
Happy to add that for now, if you want.

**Comment by trusktr** [comment]
The latest beta version of `lint-staged` solves this problem well, so the git workflow works as one expects. So far it is working great in other projects.

**Comment by treshugart** [comment]
Would you be able to PR an update to that version?

**Comment by trusktr** [comment]
Oh niiice, 2.5 years later, lint-staged v8 is out from beta. Let me make a PR.

**Comment by trusktr** [comment]
After 2.5 years in the making, v8 is out of beta! PR: https://github.com/skatejs/skatejs/pull/1539

**Comment by treshugart** [comment]
Merged. Thanks, @trusktr!
