### ISSUE TITLE
idea: Knowing which prop has changed without diffing.

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1489]
## Feature request

It'd be `suuuuuper` sweet to be able to know which props have changed inside of `updated` without having to perform a diff.

For example, currently, one has to do this:

```js
updated(oldProps) {
  if (oldProps.foo !== this.foo) {
    // the foo prop changed
  }
}
```

The suggested API might look like this:

```js
updated(oldProps, oldState, changedProps) { // backwards-compatible signature

  // changedProps is a Set, so `.has()` is O(<n), faster than array `indexOf`.

  if (changedProps.has('foo')) {
    // the foo prop changed
  }
}
```

For values that different in equality, I could easily implement this in the `updating` method, then let `shouldUpdate` and `updated` use it.

_Buuuuut_, as usual, I have a case that doesn't fit in with the regular cases.....

### Use case(s)

It turns out, in my case, my class hierarchy has a getter/setter for the prop that is being observed. My `withUpdate` component observes changes to this value. When the value is set, it triggers an update.

However, when the value is get, it _always_ returns the same object reference.

For example:

```
element.size = [100, 100, 100] // triggers observation that my withUpdate component listens to
```

```js
element.size // returns the same object reference, f.e. { x: 100, y: 100, z: 100 }
```

which is an object who's reference never changes (for now at least).

So in my `withUpdate` component, my diff logic fails because:

```js
updated(oldProps) {
  if (oldProps.size !== this.size) {
    // we never reach this part
  }
}
```

It's not a common use case, but, I've ran into it.

If I can avoid re-writing lots of stuff in my library to accommodate this, that'd be awesome.

I think the implementation inside of `with-update.js` would actually be fairly small.

**Comment by trusktr** [comment]
I forgot to note, for now I just don't perform any check, and just run the logic all the time. This won't be ideal in large applications because it involves re-creating new WebGL geometries even though nothing has changed.

I can probably cache the value further down in the logic and diff like that (f.e. observe `this.size.x` instead of just `this.size.y`, but I think it'd be nice to simply have a feature abstracted higher up that tells me explicitly which value changed with no diffing involved.

**Comment by trusktr** [comment]
Because of performance. That's very _readable_, but it is _heavy_ and it is extra code (abstracted away behind lodash, take a look at all the stuff lodash is doing under the hood).

Direct notification is the fastest (this is why [Surplus is so fast](https://www.stefankrause.net/js-frameworks-benchmark7/table.html)).

Exposing `changedProps` would be a _direct notification system_, which would prevent the end user from having to diff data to detect what changed.

SkateJS _already knows_ what changed and `changedProps` would be a way for SkateJS to share that valuable information directly instead of requiring users to figure it out a second time.

Let's imagine someone trying to make a game declaratively: as it is now they will end up performing a bunch of diffs every 16 milliseconds, increasing the chances of causing "Jank".

---

So far, I've enjoyed how easy SkateJS makes it to define the interface of my components with `props` (interestingly on my non-custom-element element-behaviors, which I shall soon post an example of), but in the process of experimenting with it, I realized that after switching to SkateJS I now have to diff data instead of listen to events (direct notifications).

**Comment by trusktr** [comment]
To put it simply, before, the pseudocode of my logic was like this:

Before using Skate

```
on sizechange, do foo
```

After using Skate:


```
sizechanged = detectSizechange()
if sizechanged, do foo
```

More logic, less ideal. I know I can write it in short form with a single `detectSizechange` call, but the extra code is there now, and it wasn't before.

**Comment by trusktr** [comment]
This feature would be nice paired with something like https://github.com/skatejs/skatejs/issues/1493 for preventing memory churn (good for anything with real-time graphics, avoiding the infamous stutter caused by the garbage collector).

**Comment by trusktr** [comment]
PR for this: https://github.com/skatejs/skatejs/pull/1510

**Comment by treshugart** [comment]
I've ended up doing this in v6 [here](https://github.com/skatejs/skatejs/blob/v6-trey/packages/skatejs/src/component.ts#L48) and it now reports it to the callbacks [here](https://github.com/skatejs/skatejs/blob/v6-trey/packages/skatejs/src/component.ts#L238).

State was removed, as per a discussion in another issue. The only argument now is the props that changed and their old values. If you want to get the new values you have to `Object.keys(changedProps)` but this might be a good compromise for reporting old values and the changed props at the same time.

Thoughts?

**Comment by trusktr** [comment]
> I've ended up doing this in v6 here and it now reports it to the callbacks here.

Nice, I think this is on the right path, but see https://github.com/skatejs/skatejs/issues/1523 about the equality checking.

**Comment by trusktr** [comment]
> If you want to get the new values you have to Object.keys(changedProps) but this might be a good compromise for reporting old values and the changed props at the same time.

I think the array idea is better because it provides the fastest implementation (no `Object.keys`, just `for(;;)` on an `Array`), and plus because #1523.

**Comment by treshugart** [comment]
> Nice, I think this is on the right path, but see #1523 about the equality checking.

This has been fixed as noted in that issue.

> I think the array idea is better because it provides the fastest implementation (no Object.keys, just for(;;) on an Array), and plus because #1523.

But you need the old values.

**Comment by trusktr** [comment]
In the v6-trey branch currently, I see that I can tell if a prop has changed by checking if it exists in the `changedProps` arg to `updated(changedProps)`.

I do see one issue:

https://github.com/skatejs/skatejs/blob/v6-trey/packages/core/src/component.ts#L253

using props during animation means a new object is created for `this. _propsChanged` every animation tick. If we're animating dozens or hundreds of objects that have many props, this can add up.

How can we make it so that memory use is closer to constant?

If the user really wants to know an old value (so far I haven't needed to), can they just make an instance variable and store it there themselves?

Then, like in my https://github.com/skatejs/skatejs/pull/1510 idea, telling people which props changed would be a matter of setting booleans inside a constant object.

**Comment by trusktr** [comment]
In the idea in https://github.com/skatejs/skatejs/pull/1510, it uses a for loop to reset the booleans. I was thinking about this: the iteration could be long if there's lots of props, but it doesn't queue up objects for garbage collection, so in the worst case an animation framerate will be consistent rather than stuttering.

**Comment by treshugart** [comment]
Given how we're sort of going around in circles for the sake of micro-optimisations and edge-case functionality, I would prefer to remove this altogether and just let people use `propType.set` to track changes themselves if they need it.
