### ISSUE TITLE
[idea] Allowing the use of `this` in prop definitions, as well as passing in the prop name.

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1493]
I mentioned it in https://github.com/skatejs/skatejs/issues/1385, but this is a specific issue to track the idea (I will circle back to my old ones and close them or leave them open with intent for a PR).

## Feature request

After experimenting with the `props` API and defining a bunch of prop types lately, I've come to wish for and desire being able to use `this` inside the prop definition functions.

**Comment by trusktr** [comment]
### Use case(s)

In my example at https://github.com/skatejs/skatejs/issues/1481#issuecomment-410622063, I'd like to change my prop-defining function from

```js
function createPropType(Type, override = {}) {
    return {
        attribute: { source: true, target: false }, // get the value from an attribute (but don't mirror it back)
        coerce: val => val instanceof Type ? val : new Type(val),
        default: new Type,
        deserialize: val => new Type(val),
        serialize: val => val.toString(),
        ...override,
    }
}
```

to

```js
function createPropType(Type, override = {}) {
    return {
        attribute: { source: true, target: false },
        coerce(prop, val) { return val instanceof Type ? val : this[prop].from(val) }, // knowing that `this[prop]` is already an instance of Type
        default: new Type,
        deserialize(prop, val) { return this[prop].from(val) },
        serialize(prop, val) { return this[prop].toString() },
        ...override,
    }
}
```

Basically, overriding how values are cached.

I'm not sure if this is the best solution, but basically the problem I have with the former is that it can only ever create a new instance, because there's nowhere to cache it. But if I have access to `this`, I can make a custom way of caching values.

The reason I'd like to keep instances the same (besides for performance) is because other parts of the app observe the thing that is stored in `this[prop]` indefinitely (direct notifications), and I would like to avoid having to modify that part of the code (introducing diffing).

This would be a none-breaking change, as users can still return values just like before.

**Comment by trusktr** [comment]
Would it make sense to add `get` and `set` options to `props`, which do have access to `this`? This circles back to https://github.com/skatejs/skatejs/issues/1385.

Then we could leave `coerce`/`serialize`/`deserialize` as is, responsible for their job, and let `set` and `get` determine where to set/get values to/from.

I really really want to have no memory churn, so at some point I'll end up with a PR for this feature and one for https://github.com/skatejs/skatejs/issues/1489, and in the worst case I'll just keep a fork of Skate and rebase it with upstream. I really value avoiding creating new objects and avoiding diffing.

**Comment by trusktr** [comment]
PR for this: https://github.com/skatejs/skatejs/pull/1509

**Comment by treshugart** [comment]
So, personally, I've only used `coerce` a handful of times, a long time ago, and I really think that not doing any coercion is better overall. As an additional way of helping to mitigate any wrong values, a type system could be added.

**Comment by trusktr** [comment]
It's not necessarily so much about types as as it is about the API that I enable in my case.

For example, with my elements you can do this:

```
const mesh = document.querySelector('i-box')

mesh.rotation = [30, 60, 90]

// or (x, y only)
mesh.rotation = [30, 60]

// or
mesh.rotation = {x: 30, y: 60, z: 90}

// or (z only)
mesh.rotation = {z: 90}

// or
mesh.rotation.x = 30
mesh.rotation.y = 60
mesh.rotation.z = 90

// or (animated)
mesh.rotation = (x, y, z) => [x, ++y, z]

// or (animated, based on time)
mesh.rotation = (x, y, z, time) => [x, 100*Math.sin(time), z]

// or (revert to default value)
mesh.rotation = null
```

In all of those cases, the `mesh.rotation` reference needs to be the same reference, not just for performance, but for guarantees on how the API works.

This is why I've made these recent pull requests, which enable access to `this` in order to help meet my requirements.

So it's not specifically about types in my case. See what I mean?

Also, end users will not always have a Type system in place, and I still want them to benefit.

**Comment by treshugart** [comment]
The core discussion of this issue should now be possible in `@skatejs/element`.
