### ISSUE TITLE
Remove link()

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1495]
___This is in preview in the v6-trey branch.___

---

I'm proposing we remove `link()`. It's convenient, but I've never heard of anyone using it and it's pretty simple to work around and can be done as a separate library if need be.

**Comment by sghoweri** [comment]
A separate library (or heck even a `@skatejs/extras` package) would be nice but totally not a deal breaker for us.

 I will say that having these sorts of things floating around to reference has been incredibly helpful in wrapping my head around a lot of these techniques (plus giving me a TON of ideas on how to try extending and building off of SkateJS)

![](https://i.kym-cdn.com/entries/icons/original/000/008/342/ihave.jpg)

**Comment by treshugart** [comment]
@sghoweri, is this low impact for you?

**Comment by sghoweri** [comment]
Yep - I’m good with this 👍🏼

**Comment by treshugart** [comment]
This has already been done.
