### ISSUE TITLE
Combine all mixins into a single component mixin

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1497]
___This is in preview in the v6-trey branch.___

---

It's neat you can compose stuff together, but in wanting to streamline the API a bit, I've found I really only ever use `withComponent()`. The rest of the mixins are really tiny, some offering little value. Here's what I propose:

- Remove `withLifecycle()`. It doesn't really do anything except alias lifecycle names and make calling them slightly simpler.
- Remove `withContext()` in favour of creating a separate context API as a new package. This has een discussed in #1485.
- Merge `withChildren()` and `withUpdate()` together into `withComponent()` and just call it `component()`.
- Export a pre-executed version of `component()` and call it `Component`. This will be the 99% use case. The function exists to extend built-ins if you really want to, or give it a different base class but not sure why you wouldn't just extend `Component` in the latter case.
- Renderers can now be *just* functions, instead of classes and you can mix them into `Component` by just setting it as a static prop.

Speaking from my personal experience, and preference, I never liked piecing together the mixins, especially when the one's outside of `withUpdate()` were so tiny and you opted into their behaviour anyways. It feels like there's a canonical way to use Skate if they're all in one and gives us an opportunity to start creating separate packages for these things, leaving Skate as just "core".

**Comment by treshugart** [comment]
> especially after realizing (through trial and error), we really just end up using withComponent

This has been my experience all of the time.

>  Also like the idea of still shipping component() and Component — that should make upgrading us over to this super straightforward!

It's definitely intended for this purpose! Also, if people want to use customised build-ins, it's for them, too, so I don't think it's something that will be removed at any point of time. At least not soon until we know exactly what will happen with built-ins over the years.

**Comment by sghoweri** [comment]
> It's definitely intended for this purpose! Also, if people want to use customised build-ins, it's for them, too, so I don't think it's something that will be removed at any point of time. At least not soon until we know exactly what will happen with built-ins over the years.

Yeah... @_@ https://github.com/w3c/webcomponents/issues/509

![21a9d5dc-1bf8-4ed9-a08f-af459a48bdce](https://user-images.githubusercontent.com/1617209/44819463-f5266100-abba-11e8-8bc8-2ea37a4c00ee.jpeg)

**Comment by treshugart** [comment]
We ended up not shipping a way to do mixins, at least yet. Happy to reintroduce at some point but wanted to get some solid use cases submitted first before pre-optimising for that use case.
