### ISSUE TITLE
Make specifying static props opt-in, and offer simpler usage

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1498]
___This is in preview in the v6-trey branch.___

---

We currently need to have a `static props` definition so we can define properties that cause the component to re-render. This got me thinking: what if there was a way to not have to specify `props` and have detect props somehow?

The obvious solution here is [proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) but I think we should still support IE11, so we'd have to come up with a "good enough" algorithm for detecting props the consumer means to have re-render the component when updated.

The best I could come up with is in the `v6-trey` branch and goes something like:

- During the `connectedCallback` of first element to be connected
  - If the consumer has defined `static props`
    - Go through the standard prop defining algorithm.
  - Otherwise
    - Get own props on the element instance.
    - For each own prop
      - Use the value as the default value.
      - Define a prop on the prototype (and element because proto will not affect the first element) that will re-render the component based off of the constructor of the default value (if it has one - undefined / null won't).

It's important to note this is a non-breaking enhancement as `static props` is currently required and, if specified, will opt-out of any sort of default behaviour, thus not incurring any performance penalties, or edge-cases that it may present.

**Comment by blikblum** [comment]
Consider an example where a Component is created without props and is working fine (reacting to some instance prop).

Later in the project, someone adds a props definition: suddenly the Component breaks for not clear reason.

The same could happen by refactoring code to remove a property setting in constructor

**Comment by treshugart** [comment]
> Consider an example where a Component is created without props and is working fine (reacting to some instance prop).

> Later in the project, someone adds a props definition: suddenly the Component breaks for not clear reason.

I can see where you're coming from with this, but to me, this would be expected.

> The same could happen by refactoring code to remove a property setting in constructor

If you define a property in the constructor, you're initializing it. If you remove that, then there is the issue that it's no longer observed, but it's likely that you don't want it observed if you're removing it. It feels like that gap can be closed by verbose documentation.

This is definitely still in a proposal stage but I really like the idea of having a super-streamlined, minimal API. The `props` API isn't really changing, it's just that we offer a baseline, default behaviour now when it's not specified. I would hope documentation would then be clear as to what happens when you do or don't specify `props`.

**Comment by treshugart** [comment]
We ended up not doing this as it requires a lot of magic that just isn't worth it in the end.
