### ISSUE TITLE
How to do conditional rendering?

### ISSUE THREAD

**Issue by cliren** [skatejs/skatejs#150]
My component has to render two different templates conditionally. I am trying something like below but doesn't work and I realize it has to go through the lifecyle methods. How can I pass additional information to created or template functions (via constructor?) to perform conditional rendering?

```
prototype: {
    callMeLikeAnyNativeMethod: function (config) {
        if(config && config.data) {
        //use the data to render another template
         this.innerHTML = '<h1>New Template</h1>';
        }
    }
  }

```

**Comment by cliren** [comment]
I ended up doing this. This solution works but not very clean. It would be nice to allow an options object (like backbone) into the constructor. Please let me know your thoughts on this.

```
// START component

require('skate');
require('./less/styles.less');

var componentName = 'help';

var defaultMarkup = function() {
  return require('./default.handlebars')({});
};

var advancedMarkup = function() {
  return require('./advanced.handlebars')({});
};

var render = function(element) {
  if (element) {
    var config = element.hasConfig();
    element.innerHTML = config ? advancedMarkup() : defaultMarkup();
  }
};

var HelpComponent = skate(componentName, {
  prototype: {
    getConfig: function() {
      return undefined;
    }
  },
  template: function(element) {
    render(element);
  },
  type: skate.types.TAG
});

module.exports = HelpComponent;
// END component

// START client
var HelpComponent = require('./dist/help');

document.addEventListener('DOMContentLoaded', function() {

  //TODO: While this works, it would be nice to pass options into the constructor 
  HelpComponent.prototype.getConfig = function() {
    return {
      id: 1,
      name: 'foo'
    };
  };
  var help = new HelpComponent();
  $('#help-container').empty().append('<help id="help"></help>');

});
// END client
```

**Comment by treshugart** [comment]
This sounds like you should have two separate components that inherit behaviour from a base prototype, or definition.

    function handlebars (path) {
      var template = require(path + '.handlebars');
      return function (element) {
        element.innerHTML = template();
      };
    }

    var commonPrototype = {
      someMethod: function () {
        ...
      }
    };

    skate('help-basic', {
      prototype: commonPrototype,
      template: handlebars('basic')
    });

    skate('help-advanced', {
      prototype: commonPrototype,
      template: handlebars('advanced')
    });

That's what I'd do and from what I can grok, that's what the spec recommends as well. I hope this helps.
