### ISSUE TITLE
"false" values for attributes

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1511]
## Feature request

It may be nice if for `boolean` props it would be possible to write `some-attribute="false"` on the element and for it to be false.

### Use case(s)

I think it makes the declarative API nicer.

```html
<some-el some-attribute="false"></some-el>
<some-el some-attribute="true"></some-el>
```

And otherwise it'd work the same (any value other than `"false"` would be true, and when the attribute is removed it is false)

In my code before using Skate I had

```js
            this[ prop ] = attrValue === null || attrValue.trim() === 'false' ? false : true
```

A Skate user can do this in their own prop like so:

```js
static props = {
  deserialize: {
    ...props.boolean,
    deserialize: (val: string): boolean => !empty(val) && val !== 'false',
  }
}
```

**Comment by treshugart** [comment]
This sort of goes against standard HTML where the presence and absence is indicative of boolean. All HTML thinks `"false"` is, is a string.

**Comment by trusktr** [comment]
That's true, but doesn't mean people will trip over it. If the docs mention `"false"` is false, I don't think people will have issues with it.

- React has `attr={false}`
- Vue has `:attr="false"`

**Comment by treshugart** [comment]
Linters advocate doing `<div something>` as opposed to `<div something={false}>` where possible. Prettier actually will correct that for you. If you have a variable, of course it can't, but JSX inherently needs to have `false` to mean there's an absence of attribute.

Vue has a non-standard syntax, so they can make stuff up, even if it's wrong.

A-Frame is wrong.
