### ISSUE TITLE
sk-router should use es modules all the way down

### ISSUE THREAD

**Issue by lastmjs** [skatejs/skatejs#1514]
## Bug report

sk-router is not entirely implemented using es modules because one of its dependencies uses requires.

* Skate version: latest
* Affected browsers (and versions): all browsers with es module support

### Current behaviour

One of the index.js files in the Page.js dependency has requires instead of es modules.

### Expected behaviour

All source code should use es modules, including all dependencies.

### Use case(s)

It would be great to use Skate without any kind of bundling (webpack, rollup), some workflows call for it. My workflow in particular assumes all source code is written in es modules, and takes care of rewriting bare specifiers.

**Comment by lastmjs** [comment]
Is the translation unreliable? I believe examining the package.json is exactly what happens, at load time though. That's what my rewrite server Zwitterion does, and I got that functionality from Polymer's rewrite server for bare specificiers. The dependencies just need to be written with es modules, using all relative paths or bare specificiers, for me it doesn't matter.

**Comment by lastmjs** [comment]
So, perhaps we have a misunderstanding. I'm saying that Skate and all of its dependencies need to be authored with ES modules and bare specifiers. The actual source code is written with ES modules and bare specifiers, no bundling or building occurs except by the consumer on their own machine. It can then be pushed to whatever production or other environment they want.

**Comment by lastmjs** [comment]
So Page.js needs to be rewritten, or Page.js can itself be bundled with Rollup and exposed as an ES module, and then Skate can depend on it. I'll probably just use Rollup to either bundle Page.js or Skate entirely, and import it as an es module until all of Skate's dependencies are modules.

**Comment by lastmjs** [comment]
The problem is relying on webpack or another bundler. sk-router does `import page from 'page'` which is perfect, but the expectation is that the bundler will resolve the page library and transpile it to work with es modules, because it is written with requires. I don't use a system like that, my system depends upon es module source code. That's the issue I'm running into. Everything would work fine if page itself was just written with es modules, or if skate referenced an es modules or bundled version of page

**Comment by lastmjs** [comment]
The latest Page.js has an es module bundle now! Just need to update Skate with that dependency

**Comment by treshugart** [comment]
Bumped to `page` 1.9.0 in `sk-router` 0.3.1. https://unpkg.com/@skatejs/sk-router@0.3.1/dist/es/index.js

**Comment by lastmjs** [comment]
Awesome, it looks like page.js is working fine as a module, but `@skatejs/sk-router/dist/es/index.js` has a dependency on `@skatejs/val`, which is a umd build and has no es module, thus blocking me again.

**Comment by treshugart** [comment]
Bah! Will try and fix.

**Comment by treshugart** [comment]
Removed dependency on val in https://unpkg.com/@skatejs/sk-router@0.3.2/dist/es/index.js.
