### ISSUE TITLE
Contributors can add any apps freely.

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1515]
@treshugart I just wanted to let you know that SkateJS is currently configured to allow any app that I install to my account.

For example, I see this when adding a GitHub app:

![screen shot 2018-08-21 at 5 55 42 pm](https://user-images.githubusercontent.com/297678/44436742-96823700-a56b-11e8-9295-ff2de1960596.png)

You see on there that I have to "grant" or "request" access for certain orgs, which are configured with stricter settings.

So anything I install can interact with SkateJS, even if I only intend to use it for a personal project.

I just wanted to stick this note here, so you can configure that setting if you want to, so that apps that you've no idea about that contributors are using don't randomly have access to your repo.

**Comment by treshugart** [comment]
I've restricted "third-party application access policy". That should do it, I think. Thanks for flagging this!
