### ISSUE TITLE
better handling of removed attributes (default values for removed props/attributes)

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1516]
When an attribute is removed, the default value is not used.

In `withUpdate`'s `attributeChangedCallback` we have

```js
          const propertyValue = deserialize
            ? deserialize.call(this, newValue, propertyName)
            : newValue;
          this._props[propertyName] =
            propertyValue == null ? defaultValue : propertyValue;
```

And here for example is one of Skate's builtin props:

```js
const zeroOrNumber = (val: string): number => (empty(val) ? 0 : Number(val));

// ...

const number: Function = prop({
  attribute,
  default: 0,
  coerce: zeroOrNumber,
  deserialize: zeroOrNumber,
  serialize: (val: mixed): null | string =>
    empty(val) ? null : String(Number(val))
});
```

Say for example I'd like to have a `default` value of `100`:

```js
import {props} from 'skatejs'
const MyNumberProp = { ...props.number, default: 100 }
```

If the attribute doesn't exist the very first time the element is created, `100` will be used.

But later on, if someone sets the prop to `undefined` or `null` or removes the attribute with `removeAttribute`, the `default` value will be `0` instead of `100` because the call to `deserialize` always returns `0` for "empty" values.

It will never return `null` which means there's never a chance for the `default` value to be used when an attribute is removed (or prop set to null).

## Feature request

Maybe we need a generic way to handle this case so that `default` will come into play in these cases without manually having to write it in every prop definition.

For example, here's how'd we'd make it work as an end user, which makes it more verbose:

```js
    import {Color} from 'three'

    const MyColorProp = {
        // ...
        coerce: val => val instanceof Color ? val : empty(val) ? MyColorProp.default : new Color(val),
        default: new Color(120, 200, 50),
        deserialize: val => empty(val) ? MyColorProp.default : new Color(val),
        // ...
    }
```

### Use case(s)

A solution to this would simplify props definitions so they don't require manual use of the `default` value.

```js
    import {Color} from 'three'

    const MyColorProp = {
        // ...
        coerce: val => val instanceof Color ? val : new Color(val),
        default: new Color(120, 200, 50),
        deserialize: val => new Color(val),
        // ...
    }
```

**Comment by treshugart** [comment]
I think all we really need to do is check in `attributeChangedCallback` whether or not `newValue == null`, and if so, apply the default value.

**Comment by trusktr** [comment]
Another way could be to initialize the `_props` with the default value, and only ever set the default again when `set` or `deserialize` has a `null`. Hmmmm 🤔...

**Comment by treshugart** [comment]
Why can't we just return the default from `propType.get()` if the value is null internally?

**Comment by trusktr** [comment]
I just checked

https://github.com/skatejs/skatejs/blob/853a53934ac849169fcef8000884c52548ef2748/packages/core/src/props.ts#L45-L51

and I see that it still returns 0 there when values are `null`, instead of the default value defined in the propType.

Seems like somewhere around here we'd need to call `propType.default`:

https://github.com/skatejs/skatejs/blob/853a53934ac849169fcef8000884c52548ef2748/packages/core/src/component.ts#L198-L203

**Comment by treshugart** [comment]
We could just return `null` from `deserialize` and set `default` to `0`, right?

**Comment by treshugart** [comment]
The default value is now returned from the getter if the value has been removed.
