### ISSUE TITLE
[v6-trey] Pleeeease, bring back mixins in v6.

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1522]
I'm a super huge fan of the mixins. In my projects, I'm relying on the nice concept of mixins in order to use specific features of Skate.

Using v5 `withComponent` (or the combined class in v6) doesn't work in some of my cases:

I'm using only `withUpdate` to grab that specific feature set for some of my non-DOM classes. Instances of these classes of mine do not live in the DOM, so I don't need DOM APIs with these classes.

My lib that manages these classes (element-behaviors) instantiates instances of these classes, and calls their life cycle methods (`observedAttributes`, `connectedCallback`, `disconnectedCallback`) which triggers logic from SkateJS (v5) `withUpdate`, and it works great!

By combining everything into one class, I can no longer implement this architecture because it means I would have to implement `MutationObserver` and `ShadowDOM` for my non-DOM classes because In `v6` a the combined component class relies on `MutationObserver` and `ShadowDOM`.

Everything being as a single class in v6 is a _huge_ breaking change: I can't simply update to v6 and will have to stay forked from v5.

---

Is there any way I can convince you to keep mixins?

Is there something you wanted to avoid by not using mixins?

**Comment by trusktr** [comment]
This change is fine for people who currently use `withComponent`, so they can just use the new single class.

But this change is very breaking for people using only `withUpdate`, for example.

**Comment by trusktr** [comment]
See this `w3c/webcomonents` topic (https://github.com/w3c/webcomponents/issues/758), where mixins are one of the options I suggested for applying yet-to-be-released custom element features.

I linked to SkateJS there because SkateJS (v5) is a great example of opting into specific features via mixins.

**Comment by trusktr** [comment]
Pleeeease, I am on my knees begging (figuratively, I'm actually sitting at my desk): let's separate features with mixins and much as possible, so we can decide how heavy, light, or flexible our end-classes will be, and so that we can do amazing things like take advantage of `withUpdate` logic without DOM APIs being present and without having to mock or polyfill DOM APIs.

As an example, imagine someone creating a Scene Graph tree with Three.js, and using `withUpdate` on their classes, without using any DOM APIs, only WebGL. They can extend the `Object3D` class methods like `add` and `remove` to make them trigger `connectedCallback`, `disconnectedCallback`, etc, and thus trigger all the amazing functionality of `withUpdate` in a non-DOM application, just pure JS.

This Three.js user will not be able to take advantage of `withUpdate` reactivity if they now have to make DOM nodes rather than plain JS nodes.

**Comment by trusktr** [comment]
Pleeeeeeease, can we re-do v6 using mixins? 🙏

**Comment by trusktr** [comment]
In my [`lowclass`](https://github.com/trusktr/lowclass) lib, I have a tool called [`Mixin`](https://github.com/trusktr/lowclass/blob/master/src/Mixin.js), which is used to define mixins that

- are cached: an application of the same Base class to a mixin returns the same class as a previous application instead of a new one.
- work with `instanceof`:
  - for example if `withUpdate` were created with the `Mixin` tool, then the following `instanceof` check would be possible:
    ```js
    import Mixin from 'lowclass'
    const withUpdate = Mixin(Base => class extends Base { ... })
    class Foo extends withUpdate.mixin(HTMLElement) { ... }
    const foo = new Foo
    console.assert(foo instanceof withUpdate) // passes
    ```
- de-duplicate mixin applications: for example if `withUpdate` was already applied further down a class hierarchy called `SomeClassThatAlreadyHasWithUpdate`,  `withUpdate(SomeClassThatAlreadyHasWithUpdate)`, then the class is returned without a new application of the mixin.
- have default values when a `Base` value is not supplied. `Mixin(Base => class extends Base { ... }, HTMLElement)` specified the default value (f.e. works where default parameter syntax doesn't)
- can be used as plain classes.
  - For example,
    ```js
    import Mixin from 'lowclass'
    const withUpdate = Mixin(Base => class extends Base { ... }, HTMLElement)
    class Foo extends withUpdate { ... } // no mixin call
    console.assert(new Foo instanceof withUpdate) // it works
    ```

---

Mixins are powerful, and we can do cool things with them.

I am planning to add TypeScript support for `Mixin` soon.

**Comment by trusktr** [comment]
@matthewp @blikblum thoughts on keeping or not keeping mixins?

**Comment by trusktr** [comment]
Here's an article on [Typed Mixins with TypeScript](https://blog.mariusschulz.com/2017/05/26/typescript-2-2-mixin-classes), which is based on an old version of TypeScript. The abilities for typing these things is even better now.

**Comment by treshugart** [comment]
Would a compromise be separating out the part that do the application into an imperative function that you can use? Since it's invoked in `observedAttributes`, you'd pretty much have to do this anyways. I'd like to have a single DOM class as v6 is very focused in a very small subset of things now, but definitely open to sharing some of the internals that you can't get from things like lodash etc.

**Comment by trusktr** [comment]
If I can see what that might look like, then I may have an idea of it it works for my cases. I'm not yet clear exactly how it will be myself though. It's like the chicken and egg problem. 

---

Sidenote: IMO, lodash (or underscore) is great for one-off data manipulation (f.e. definitely on the server-side), but I don't recommend using it in repeated animation loop type scenarios (which is my main focus).

Similarly one should avoid doing things like `obj = {...obj, foo: 'bar'}` in animation loops because it makes a whole bunch of objects that need to be GC'd. The bigger that `obj` is, the worse it will be. Immutable patterns are not good for graphics performance, we want to avoid memory churn.

**Comment by treshugart** [comment]
Let's track this in #1524.
