### ISSUE TITLE
[v6-trey] avoid equality checking of props, leaving it to end users

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1523]
https://github.com/skatejs/skatejs/blob/4aa99272e2a4e1fd8663464340f25c1fe6ead72e/packages/skatejs/src/component.ts#L47-L50

If a prop is designed to return the same instance (there are reasons!), then this check will not work.

It would be better to add the changed props to a list when they are set, regardless of equality. Then the user can either check the list of changed props, or decide to do equality checking. It's more flexible that way.

The idea would be more like in PR https://github.com/skatejs/skatejs/pull/1510, where we give the user old values as well as a list of props that were set (even if the value is the same).

**Comment by treshugart** [comment]
Yeah, I realised that and ended up making it `set()` as it makes more sense with `get()` :)
