### ISSUE TITLE
Consider breaking skatejs/component into two mixins

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1524]
## Feature request

If we can graciously have mixins in v6, then I suggest that we can break `withUpdate` into two separate mixins:

1. one mixin that sets up the `props` system without requiring any Custom Element life cycle methods. This would be purely data oriented, and work on any type of objects even if they are not in a tree, and they do not have to be DOM nodes,
2. and a mixin that provides the life cycle features relying on connectedCallback, disconnectedCallback, attributeChangedCallback, etc. Classes using this second mixin would be tree nodes, and they too don't have to explicitly be DOM nodes, but the environment they live in has to be sure to call the lifecycle methods to make certain things work.
   - This would be great for non-DOM apps that have tree structures made with [BabylonJS](http://www.babylonjs.com/), [Three.js](http://threejs.org), [PlayCanvas](https://playcanvas.com), [Pixi.js](http://www.pixijs.com), [Two.js](https://two.js.org), etc.

### Use case(s)

The amazing thing about these mixins is that they are not limited strictly to DOM nodes, making a bunch of other use cases possible.

**Comment by treshugart** [comment]
If this is to be considered, we should have some concrete and compelling use-cases for it considering Skate's focus is custom elements and shadow DOM.

**Comment by trusktr** [comment]
In my case, I eventually want to run my lib in non-DOM places, and `withUpdate` is a super nice fit for it. All my classes extend from a `TreeNode` class, which is a non-DOM tree API similar to the DOM's Node class.

This would be nice for a few reasons:

1. For people wishing to write purely in JS and prefer imperative over declarative, this offer a performance improvement because we can avoid crossing over the HTML engine boundary and all it's extra resources.
  - f.e. people that like to write Three.js apps don't use DOM APIs, except in the case that they need to mount the Three.js `<canvas>` element somewhere. Other than that, everything is pure JS, and therefore as performant as it can be without crossing into the HTML engine.
2. In some environments, f.e. Node.js, there are ways to draw OpenGL graphics without having a DOM
  - In this case, I'd like to be able to provide a renderer that works in pure JS, as well as a scene graph tree
  - My tree nodes will have their life-cycle methods triggered by my TreeNode mixin class, instead of the DOM calling them
  - this allows the SkateJS `withUpdate` logic to be triggered without requiring DOM (or DOM polyfill).
3. Not everything object in an app is a DOM element. Sometimes we have plain data objects that we may want to use with our custom elements (data models), and we can benefit from reactivity on those objects.

**Comment by trusktr** [comment]
That last one in particular, that we might just have plain data objects and want reactivity, is a compelling one which isn't related to my 3D scene graph DOM/not-DOM stuff.

**Comment by treshugart** [comment]
Interesting. Is there a way where we can abstract the v6 stuff out into a function that augments an object? I'm not sure I am comfortable with the idea that we have a mixin that's designed to be used for custom elements but just so happens to work for not DOM objects. Even if it were explicit, I don't like placing the constraint on  a DOM class having to also work for non-DOM classes. Mixing non-DOM mixins with DOM mixins could also make the API confusing.

**Comment by treshugart** [comment]
I referenced this in #1522 so that we could look at how we could split apart this functionality in this issue.

**Comment by trusktr** [comment]
> Is there a way where we can abstract the v6 stuff out into a function that augments an object? 

Good question to think about!

Only a subset of the objects in an app are DOM objects. Imagine the convenience of defining a prop on any class and reacting to changes in `updated`.

The need for handling attributes only arrises when we're specifically talking about DOM objects, in which case attributes are a second mechanism for passing data into the object.

With this in mind, maybe it is possible to make a props-only mixin for any type of object, then an additional mixin that adds attribute support for DOM elements.

---

On related note, the new React Hooks API is React's new mechanism for grouping logic together to avoid different functionalities being blended across a class.

Mixins in v5 Skate are the equivalent for logic grouping, and in general this grouping is a nice thing.

---

Now that I mentioned React Hooks, I want to share my quick thought on it:

React Hooks has a nicer dev experience in terms of writing code, but it creates duplicate functions and closures, and triggers them eveb when nothing changes (because it needs to in order to know if anything changes, though it has some ways to trunk updates of a subtree). For stuff that needs continual updates (games or other highly-graphic apps) this can add up.

From a graphics perspective, @ngokevin of [A-Frame](https://aframe.io/examples) summarizes the performance nature of the mechanisms in React [here](https://github.com/ngokevin/aframe-react/blob/master/README.md).
