### ISSUE TITLE
[v6-trey] dash-case instead of lowercase

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1525]
https://github.com/skatejs/skatejs/blob/cceda995fd39c09f20954f20c59fd8bafff7159b/packages/core/src/props.ts#L9

IMO converting to dash case is better because it is easier to read and more inline with how people think of attribute, element, and CSS naming.

At the very least, could SkateJS supply a `dashCase` helper so users don't have to implement it?

**Comment by treshugart** [comment]
Simply using `toLowerCase()` makes it consistent with how built-ins work, at least most of them where they haven't had to deviate for prop names (`className` -> `class`, for example). It also makes the logic simpler. For those that want customisation, they can do so if they see fit.

**Comment by treshugart** [comment]
> At the very least, could SkateJS supply a dashCase helper so users don't have to implement it?

I would prefer they just install, and use, something like https://github.com/sindresorhus/decamelize. There's plenty out there.

The idea of being minimal, and as small as possible means we need to cut out as much unnecessary things as possible. A big win here is that we can be consistent with how built-ins behave (`toLowerCase()`) *and* remove the need for code like this.
