### ISSUE TITLE
[v6-trey] Where are default prop values?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1527]
https://github.com/skatejs/skatejs/blob/cceda995fd39c09f20954f20c59fd8bafff7159b/packages/core/src/props.ts#L44-L48

I see there's no more `default` helper, and in that example it is `0`. Maybe the definition can use `this` similar to your event type (`this.getEventName`), and call `this.default(elem, name)`. f.e.,

```js
const number: PropType = {
  ...any,
  deserialize: (elem, name, val): number => (val == null ? this.default(elem, name) : Number(val)),
  serialize: (elem, name, val: number) => (val == null ? null : String(Number(val)))
  default: (elem, name) => ...,
};
```

This would require passing `elem` and `name` to the other functions as well though.

Also, if we're already assuming the value is a number, then we only need `String(val)` instead of `String(Number(val))`. The user shouldn't do anything funky either way.

**Comment by trusktr** [comment]
Note, I haven't checked how `deserialize` is actually called, so my change may not be the right way to do it, but you get the idea for the needed feature.

**Comment by treshugart** [comment]
I've just reimplemented. For now, it's only called in the getter, which is really the only entry point to the property now anyways, so it should work for all use-cases without having to patch anything else.

**Comment by trusktr** [comment]
Cheers! :)
