### ISSUE TITLE
IE - document.contains doesn't exist!

### ISSUE THREAD

**Issue by maikeldaloo** [skatejs/skatejs#153]
Hi guys,

I'm developing a site using SkateJS right now and I ran into a problem on IE.
It complains that `document.contains` doesn't exist.
See https://github.com/skatejs/skatejs/blob/master/dist/skate.js#L651.

I had a look at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains), they say that `document.contains` works on IE5+.  
In the IE console, I ran `document.contains` and I got `undefined`, I tried this on all the IE versions I could emulate.

I tested this fix and all that needs to change is:
```
if (!document.contains(target)) {
    return;
}
```
to
```
if (!document.body.contains(target)) {
    return;
}
```

**Comment by treshugart** [comment]
Is it running in compatibilityor quirks mode? Usually that's why something like that doesn't work. If not I'm happy to implement something like you've suggested.

**Comment by maikeldaloo** [comment]
Whatever the default is. I haven't changed any settings on my IE. The issue is that the contains method is on the Node prototype (Node.prototype.contains), the document for a one reason isn't a Node in IE.

**Comment by treshugart** [comment]
The reason I ask is because having an invalid doctype or html can cause funny issues like this in IE. We've run our tests in IE9+, but this could have cropped up when we started using native if it's available. I'll have a look.

What version of IE and Skate are you using?

- Trey

**Comment by maikeldaloo** [comment]
I'm using the html5 doctype, nothing out of the ordinary.

Please do have a look. I'm using IE11 and emulating the older versions. I copied what you currently have in dist/skate.js to my project yesterday.

Speaking of versioning

**Comment by maikeldaloo** [comment]
Sorry, accidental click. 

Speaking of versioning, would you be able to print a header on your JS file so that it says what version it is?

**Comment by treshugart** [comment]
There is a `skate.version` property or there's the `package.json` and `bower.json` files. Is there a specific reason you need this?

**Comment by treshugart** [comment]
Just to confirm, you're right. It doesn't seem to work when testing in real IE9. It must have been introduced recently in between our testing. I'll fix 'er up for you.

**Comment by maikeldaloo** [comment]
Oh fair enough, I'm not using Bower for my project, just grabbign the file I need to placing it in my workflow.

I'm running version `0.13.0`.

**Comment by treshugart** [comment]
Oh ok. That would probably be master then as 0.13 doesn't exist yet. I had pre-bumped the version.

**Comment by maikeldaloo** [comment]
Thanks buddy. I'll update my copy when I get to work on Monday.

**Comment by maikeldaloo** [comment]
I've been grabbing it from master, I'll have a look at a tag from now on.

**Comment by treshugart** [comment]
I've fixed it in 61d4f822a70e7ac0c285bea17d6bde7283f854d7. There's still some failures in IE9 in master (haven't checked the others yet but I'll work my way up the IE ladder). That said, I'd recommend using 0.12 instead of master for the time being until I can get to fixing the rest of the failures. I need to release a new version, so 0.13 will probably land mid-week.

Thanks again for reporting it!

**Comment by treshugart** [comment]
Sorry, that was the `dist` commit. Changes here 9cb8f0846b2af5ddadb3ef8b73d9a700154f3dcf.

**Comment by maikeldaloo** [comment]
Ok, no worries. I'll use `0.12.0` until hopefully mid-week and I'll come back for the updated version :)

Nice work.
