### ISSUE TITLE
SSR/History.js - trying to modify constant variable in a loop

### ISSUE THREAD

**Issue by antonama** [skatejs/skatejs#1530]
https://github.com/skatejs/skatejs/blob/eae5f683d31ad9ef0f2e928edf491352dc12697d/packages/ssr/register/History.js#L31

**Comment by trusktr** [comment]
Good catch! Maybe that part is untested?

**Comment by treshugart** [comment]
Yeah, probably. The SSR stuff is still pretty alpha hence still being in dev releases. Would love a PR fixing it, if possible.

**Comment by treshugart** [comment]
I fixed this in the `dev` branch.
