### ISSUE TITLE
Issue with SSR within the context of a backend framework

### ISSUE THREAD

**Issue by codejet** [skatejs/skatejs#1531]
## Bug report

* Skate version: 5.2.4
* Affected browsers (and versions): all

### Current behaviour

I'm currently working on a Symfony app and am trying to get server rendered Web Components to work. I'm using https://github.com/spatie/server-side-rendering with Node as an engine. I almost got your SSR example to work, but I'm still having a few issues.

I split up the code into 3 files.

yell.js
```
class Yell extends HTMLElement {
    connectedCallback() {
        Promise.resolve().then(() => {
            const shadowRoot = this.attachShadow({ mode: 'open' });
            shadowRoot.innerHTML = '<strong><slot></slot></strong>';
        });
    }
}

customElements.define('x-yell', Yell);

module.exports.Yell = Yell;
```

hello.js
```
class Hello extends HTMLElement {
    connectedCallback() {
        const shadowRoot = this.attachShadow({ mode: 'open' });
        shadowRoot.innerHTML = '<span>Hello, <x-yell><slot></slot></x-yell>!</span>';
    }
}

customElements.define('x-hello', Hello);

module.exports.Hello = Hello;
```

server.js
```
require('@skatejs/ssr/register');
const render = require('@skatejs/ssr');
const { Hello } = require('./hello');

const hello = new Hello();
hello.textContent = 'World';

render(hello).then(console.log)
```

The result of rendering this on the server looks as follows

<img width="241" alt="markup" src="https://user-images.githubusercontent.com/802203/45411746-4d5a6a00-b675-11e8-84c3-7f4a7340625a.png">

First issue is that I get a `ReferenceError: __ssr is not defined`. And so the output is `Hello, !World` instead of `Hello, World!`.

And the second issue: there is no `rehydrate` function. But there should be one, as the default is for it to be included, no?

If I got that right, rehydration replaces the `<shadow-root />`with an actual shadow root. But I wonder how to actually take over the server-rendered custom elements on the client then? 

When I import yell.js and hello.js on the client, I always get `Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.` It looks like it is related to transpiling (see https://github.com/webcomponents/custom-elements#es5-vs-es2015) but none of the workarounds I tried fixed this. This is not really related to the issues described above, but maybe you have some insights here, too.

**Comment by trusktr** [comment]
> custom elements requiring native classes

If `__ssr` isn't there,  that doesn't seem like that problem to me. Something is missing, but I'm not sure what.

Have a reproduction?

**Comment by treshugart** [comment]
Closing this for now. We're reworking how SSR is done and it's likely you won't need to use the `@skatejs/ssr` package in production as it will be handled by renderers.
