### ISSUE TITLE
Review WCFactory template for accuracy

### ISSUE THREAD

**Issue by btopro** [skatejs/skatejs#1533]
Love skate, I don't use it in anything in production but I play w/ it a lot and follow from afar.

I've roped it into our wcfactory project that can churn out tooling and build workflow for any web component and was hoping when someone gets a chance they could review the templated skate + lit element that I'm cranking out for accuracy / make suggestions about improvements we could make to help your community get the recommended standard development method.

https://github.com/elmsln/wcfactory/tree/master/packages/generator-wcfactory/generators/init/wcfTemplates/libraries/SkateJS%2BLit

Video showing this run through in the tooling w/ Skate+Lit - https://youtu.be/CMNYuXTe1tM?t=27m57s (there's a little glitch shown in the video that I resolve in it and it's been fixed in the tooling)

**Comment by treshugart** [comment]
Hey @btopro, cheers for the links and sorry for the late reply. I'm having a look now!

I'm going to close this for now as it seems there's nothing actionable in this issue. Please reopen if I'm wrong in my assumptions.

Thanks!

**Comment by treshugart** [comment]
Assuming this is it: https://github.com/elmsln/wcfactory/blob/master/packages/generator-wcfactory/generators/start/templates/templates/libraries/SkateJS%2BLit/SkateJS.js.

**Comment by thereal54** [comment]
Yes sir. The package.json in that directory also gets put into the generated elements that are skate based

**Comment by treshugart** [comment]
That looks pretty good.

It doesn't look like you're applying a correct type for each prop using `props.*` in the `props` getter (https://github.com/elmsln/wcfactory/blob/master/packages/generator-wcfactory/generators/start/templates/templates/libraries/SkateJS%2BLit/SkateJS.js#L65). You'll get much better type handling, serialization and deseraialization using things like `props.string`. You can also just set it to the string constructor `String` (same for other native types).

In the constructor, I'm unsure why you need to do [this](https://github.com/elmsln/wcfactory/blob/master/packages/generator-wcfactory/generators/start/templates/templates/libraries/SkateJS%2BLit/SkateJS.js#L48). If you set proper `props.*` for the `props`, then you should get automatic reflection from the attribute, right?

Stoked you're doing this work and happy to continue the chat.

**Comment by btopro** [comment]
hmm I'm following but only slightly. If I post a boilerplate could you post the way you would have modified it and then I can work backwards from there to try and get the tooling to output that. Here's a basic one w/ 1 string and 1 boolean defined property:
```
/**
 * Copyright 2018 The Pennsylvania State University
 * @license Apache-2.0, see License.md for full text.
 */
import { props, withComponent } from 'skatejs';
import withLitHtml from '@skatejs/renderer-lit-html';
import { html } from 'lit-html';

// extend into class name matching library for consistency
class SkateJS extends withComponent(withLitHtml()) { }
/**
 * `skate-me`
 * `test skate`
 *
 * @microcopy - language worth noting:
 *  -
 *
 * @customElement
 * @lit-html
 * @skatejs
 * @demo demo/index.html
 */
class SkateMe extends SkateJS {
  
  // render function
  render() {
    return html`
<style>:host {
  display: block;
}

:host([hidden]) {
  display: none;
}
</style>
<slot></slot>
<div>${this.title}</div>
<div>${this.status}</div>`;
  }

  // properties available to the custom element for data binding
  static get properties() {
    return {
  "title": {
    "name": "title",
    "type": String,
    "value": "things"
  },
  "status": {
    "name": "status",
    "type": Boolean,
    "value": "true"
  }
};
  }

  /**
   * Store the tag name to make it easier to obtain directly.
   * @notice function name must be here for tooling to operate correctly
   */
  tag() {
    return "skate-me";
  }

  /**
   * life cycle
   */
  constructor() {
    super();
    
    // silly but this nets us data binding for default values
    // map our imported properties json to real props on the element
    // @notice static getter of properties is built via tooling
    // to edit modify src/SkateMe-properties.json
    let obj = SkateMe.properties;
    for (let p in obj) {
      if (obj.hasOwnProperty(p)) {
        if (this.hasAttribute(p)) {
          this[p] = this.getAttribute(p);
        }
        else {
          this[p] = obj[p].value;
        }
      }
    }
  }
  // SkateJS props function that we map our abstracted properties object over to
  static get props() {
    // map our imported properties json to real props on the element
    // @notice static getter of properties is built via tooling
    // to edit modify src/SkateMe-properties.json
    let obj = SkateMe.properties;
    let simpleProps = {};
    for (let p in obj) {
      if (obj.hasOwnProperty(p)) {
        simpleProps[p] = obj[p].value;
      }
    }
    return simpleProps;
  }
  /**
   * life cycle, element is afixed to the DOM
   */
  connected() {
    
  }

  
}
customElements.define("skate-me", SkateMe);
export { SkateMe };
```
