### ISSUE TITLE
Using withComponent(withReact()) or withReact(withComponent()) ?

### ISSUE THREAD

**Issue by zWingz** [skatejs/skatejs#1536]
It is a doc issus about `withReact`

Doc in [https://skatejs.netlify.com/renderers/with-react](https://skatejs.netlify.com/renderers/with-react)
![image](https://user-images.githubusercontent.com/13031838/47202044-8e4d4900-d3ae-11e8-9c67-c9ac2916b086.png)
or

Doc in [https://github.com/skatejs/skatejs/blob/master/packages/renderer-react/README.md](https://github.com/skatejs/skatejs/blob/master/packages/renderer-react/README.md)
![image](https://user-images.githubusercontent.com/13031838/47202055-97d6b100-d3ae-11e8-84a8-ef3d643a7adf.png)

**Comment by treshugart** [comment]
Can you elaborate on what the problem is?
