### ISSUE TITLE
skate.js.org

### ISSUE THREAD

**Issue by MattIPv4** [skatejs/skatejs#1537]
# JS.ORG CLEANUP
Hello, it seems a `js.org` subdomain that was requested to target this repository (or another on this user/organisation) no longer works.
The subdomain requested was `skate.js.org` and had the target of `skatejs.github.io`.
To keep the `js.org` subdomain you should add a page with [reasonable content](https://github.com/js-org/js.org/wiki/No-Content) within a month so the subdomain doesn't resolve to a 404 any longer.
Otherwise the requested subdomain will be removed from JS.ORGs zonefile and the list of active subdomains.

**If you are wanting to keep the `js.org` subdomain and have added [reasonable content](https://github.com/js-org/js.org/wiki/No-Content), YOU MUST reply to the [main cleanup issue](https://github.com/js-org/js.org/issues/2455) with the response format detailed at the top to keep the requested subdomain.**

**Comment by treshugart** [comment]
Thanks for the issue!

We need to use skatejs.netlify.com instead of skatejs.github.io

**Comment by MattIPv4** [comment]
@treshugart If you wish to continue to use the domain, please reply to the main cleanup issue as such at https://github.com/js-org/js.org/issues/2455 and please open a new pull request with the changes should you need to :)

**Comment by MattIPv4** [comment]
The js.org cleanup has now been completed. Please see https://github.com/js-org/js.org/pull/2545 for further information.
