### ISSUE TITLE
Consider xState

### ISSUE THREAD

**Issue by matt-erhart** [skatejs/skatejs#1538]
https://youtu.be/VSKuS2XkkZU

Basically a way to model state that's easy to visualize and easier to test endless permutations of state transitions. See especially around the 17 min mark for an interesting testing example.

**Comment by treshugart** [comment]
@matt-erhart, any reason you closed this shortly after opening it? It looks neat, but it seems like something you could layer on top of Skate?

**Comment by matt-erhart** [comment]
heh, wrong repo!
