### ISSUE TITLE
Updating SSR so it checks for shadow roots before creating them (and update example)

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1540]
At the moment, the example in the README can fail if it uses a real custom element: https://jsbin.com/jahatigagi/1/edit?html,js,output (error in console).

I suppose we should make it clear that the web components should always use "open" mode, and that they should always check for the existence of a root.

Also `__ssr` needs to check for the existence of a shadow root (because elements can be defined before they are parsed therefore their constructors can make shadow roots before `__ssr` gets a chance to do it).

---

In cases where some elements (f.e. third party ones) create closed shadow roots, maybe we can suggest to patch `attachShadow` so it always returns an open one?

**Comment by treshugart** [comment]
Yeah, SSR needs to do this, too.

**Comment by treshugart** [comment]
So what I've done, is make SSR throw an error if `attachShadow` is called multiple times. This is consistent with the spec. What consumers should do is always guard on their end. I've also added a check to core that will ensure it doesn't call `attachShadow()` if a root already exists. Unfortunately, it can only successfully perform this check if a parent class uses `{ mode: 'open' }`. We could also possibly try / catch and ignore but I'm not sure how I feel about either. At least there's a check now.
