### ISSUE TITLE
How to add a DOM node to shadow DOM?

### ISSUE THREAD

**Issue by tinca** [skatejs/skatejs#1542]
Hi,
I am trying to create a WC that uses a 3rd party lib (pixi.js). A working solution is based on renderer() where a renderRoot.appendChild() call inserts the pixi node (canvas) into shadow DOM.
This is however not the place where it should be. Constructor or even connecting()/connected() would be more appropriate, but it seems no access to shadow DOM is possible from there.

Any suggestion is appreciated!

**Comment by tinca** [comment]
This is what I could come up with:

```
class Base extends HTMLElement {
    pixiApp;

    constructor() {
        super()
        this.pixiApp = new PIXI.Application(500, 400, {
            autoResize: true,
            resolution: devicePixelRatio,
            backgroundColor: 0xfff8ff,
            antialias: true
        });
    }
}

const Component = withComponent(Base);

class GreetingComponent extends Component {

    connected() {
        // @ts-ignore
        let thz = this as Base;
        console.log(thz.pixiApp);
        thz.shadowRoot.appendChild(thz.pixiApp.view)
        this.addDrawing(50, 50, thz.pixiApp)
    }
...
```

Is there any better?

**Comment by tinca** [comment]
While waiting for your comments, here is an observation.
Above code works in Chrome, but not in Safari for which shadowRoot is undefined in GreetingComponent.

According to caniuse.com shadowDOM is supported on Safari. No wonder that webcomponents-loader.js polyfill does not help.

Any idea why it does not work in Safari?

**Comment by tinca** [comment]
Safari 12.0.1. I think I have not seen this with vanilla wcs, but I am not sure due to the numerous things I've lately experimented with.
I have seen `renderer`, but was not sure its place regarding lifecycle. What you say tells it is a one-time action (and probably obvious for a seasoned web-dev :-) just as `connected`.

No problem with waiting, my only concern is what I wrote at the other issue.
Thank you!

**Comment by treshugart** [comment]
The `renderer` method gets invoked everytime a render occurs (i.e. whenever a prop invokes an update).

**Comment by tinca** [comment]
OK, then it must be taken care of adding only once a child.

**Comment by treshugart** [comment]
Ahh yep, that's my bad. You'd obv want to do cleanup or ensure it's the only child in there somehow.
