### ISSUE TITLE
TS2305: Module '"../node_modules/skatejs/dist/es/index"' has no exported member 'withComponent'.

### ISSUE THREAD

**Issue by tinca** [skatejs/skatejs#1543]
## Bug report

* Skate version: _5.2.4_ 
using webpack.

### Current behaviour

 ERROR in xx.ts(1,9)
      TS2305: Module '"../node_modules/skatejs/dist/es/index"' has no exported member 'withComponent'.
And the code it refers to:

`import {withComponent} from 'skatejs';`

### Expected behaviour

Should compile cleanly.

This little project has no above problem when using Parcel.
Now I am trying it with webpack and get this message.
The only similar stuff I could find is:
https://github.com/winstonjs/winston-mongodb/pull/140

If it is a webpack configuration problem, can you give me a hint what to look for?
Thanks!

Ps.: is there an example skatejs project using webpack I can use for reference?

**Comment by tinca** [comment]
[ping]

**Comment by treshugart** [comment]
I really don't know what would be causing the difference. That said, TS isn't officially supported until v6 where we're rewriting everything in TS.

**Comment by treshugart** [comment]
I've just been readying the `dev` branch to start pushing dev releases for the new packages that will replace the old ones. This should be happening within the next couple of weeks.
