### ISSUE TITLE
remembering to extend parent props

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1545]
An issue that I keep running into is that when I define a new class that extends a base class, I sometimes forget to extend the parent `props` and I waste some time wondering why it isn't working.

For example, I often write

```js
        static props = {
            foo: String
        }
```

instead of

```js
        static props = {
            ...Parent.props,
            foo: String
        }
```

This made me think: what if SkateJS traversed the static prototype in search of `props` and automatically handled the inheritance (f.e. by concatenation)?

I suppose this would mean we can't opt-out of the inheritance (though I haven't wanted to do that, and I'd argue it's not a good idea to do so because subclasses blocking parents features over and over eventually results in leaf class that is entirely no longer related to the original base class).

Any thoughts on this?

**Comment by treshugart** [comment]
We used to do this, and while it can be convenient, it betrays standard convention where when you overwrite something, you still must explicitly callback to the super. It also doesn't give you any way to opt out of that behavior.

**Comment by trusktr** [comment]
True. Yeah, better to tell people to remember to inherit.
