### ISSUE TITLE
Question: SSR API docs may be inaccurate

### ISSUE THREAD

**Issue by joseph-galindo** [skatejs/skatejs#1548]
I was reading through the documentation at https://github.com/skatejs/skatejs/tree/master/packages/ssr#api to understand how the API for server-side render function works. The documentation suggests the signature should look like this:
```
const render = require('@skatejs/ssr');

render(domTree, {
   debug: false,
   rehydrate: true,
   resolver: setTimeout
});
```
But after looking through the source [here](https://github.com/skatejs/skatejs/blob/master/packages/ssr/index.js#L43-L50), I'm not sure where debug and rehydrate would be taken in. Wouldn't the render signature be more like this?
```
// setTimeout can be replaced with any custom function to resolve the promise
render(domTree, setTimeout)
```

**Comment by treshugart** [comment]
Yeah, the docs are incorrect and should have been updated.

**Comment by treshugart** [comment]
Docs have since been updated.
