### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by vogloblinsky** [skatejs/skatejs#1549]
Hi,

I have created a benchmark suite for Web Components librairies. SkateJS is implemented with lit-html & preact renderers, and you can see the raw results here : https://vogloblinsky.github.io/web-components-benchmark/

I will release soon a blog post explaining in detail that, but i want a feedback of many librairies authors before, to be sure i am not wrong in my implementations.

Source code here : https://github.com/vogloblinsky/web-components-benchmark

Can you have a look and give me some feedbacks ?

Thanks

**Comment by treshugart** [comment]
Hey, @vogloblinsky, stoked to see some work done on this. @shprink did a size comparison last year: https://wc-todo.firebaseapp.com/ and by those numbers I would expect initial load times to be different on your benchmark. That said, time could have an effect on that, but I'd still expect Skate to be a bit closer.

It appears you're also using Skate + a modified event mixin. You probably don't need that if using the new @skatejs/element, @skatejs/element-preact or @skatejs/element-lit-html packages. New Skate is about half the size of old Skate, which could also have a benefit here.

If you don't mind, I'll see if I can find some time to update your benchmark code up to the latest? Happy to have you do it and review later, if you prefer.

Thanks again for doing all this work!

**Comment by vogloblinsky** [comment]
@treshugart 
Yes i started this benchmark with a fork of @shprink repo.
I tried to update recently SkateJS examples but the documentation seems to be very light on the state + change detection side.
If i start with last example of lit-html, https://skatejs.netlify.com/docs/element-lit-html, did i just need to add a property and update it to have the render function called automatically ?
Thanks

**Comment by treshugart** [comment]
Sorry I missed this issue, @vogloblinsky. Yes, to force a re-render all you have to do is update a prop. Children changes, if using slots, will not cause a re-render (unless you are monitoring children and using them in render).

**Comment by treshugart** [comment]
In `@skatejs/element`, or renderers based off of it, you can also imperatively call `element.forceUpdate()`.
