### ISSUE TITLE
Best way to handle sub-paths?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1552]
Just curious to know if you have any thoughts on handling props like `element.rotation.x` and `element.rotation.y`.

At the moment, I have to implement some sort of wiring to make that reactive, on top of (or outside of) SkateJS.

I was thinking, if I were to switch to having something like `element.rotationX`, `element.rotationY`, and `element.rotationZ`, and similar for position, scale, etc, then it'd be easy to make those things reactive.

But having `element.rotation.x` seems to work nicely, as the sub-object encapsulates logic (f.e. they can be `THREE.Vector3` or `THREE.Quaternion` from [Three.js](http://threejs.org) and come with helpers methods for manipulating the x/y/z values in certain ways).

So I'm wondering if I should switch to `rotationX` sort of props for simplicity.

Another thing to consider is having attributes like `rotation="20 30 40"` which map the three values to `rotation.x`, `rotation.y`, and `rotation.z` (either by setting the sub-props, or by setting `rotation` to a `new THREE.Quaternion` for example), vs having attributes like `rotation-x="20" rotation-y="30" rotation-x="40"` where changing these individual props/attributes would map to sub-object in `updated` for example.

---

At the moment, I have a helper method for use with props to map props to sub objects in some cases:

```js
// map a SkateJS prop value to another target specified by getTarget
// NOTE `this` refers to the instance on which the prop exists
export const mapPropTo = (prop, getTarget) => ({
    ...prop,
    coerce(val, key) {
        const target = getTarget.call(this, this)
        const coerced = prop.coerce.call(this, val) // wraps the original coerce
        if (target) target[key] = coerced
        return coerced
    },
    deserialize(val, key) {
        const target = getTarget.call(this, this)
        const deserialized = prop.deserialize.call(this, val) // wraps the original deserialize
        if (target) target[key] = deserialized
        return deserialized
    },
})
```

and we can use it like this:

```js
static props = {
  opacity: mapPropTo(props.number, self => self.material)
}
```

where in that example any changes of the prop will not only set the prop on the instance that owns the props (`self`) but also onto a sub-object (`self.material`). Basically, the top-level instance is the outer API (an HTMLElement) while `element.material` is an object managed by the element (f.e. an instance of `THREE.Material`).

---

Do you have any thoughts on sub-props or sub-objects? Could there be a clean way to standardize it? Maybe it comes down to implementing useful helpers on top of the existing mechanism?

I'm still trying things and learning what works best. If I come up with any patterns, I'll post back.

**Comment by treshugart** [comment]
> So I'm wondering if I should switch to `rotationX` sort of props for simplicity.

I would just do this. You're welcome to implement sub-object stuff on your own, but it's seems more a stylistic choice than an objective one. Handling sub-object reactivity isn't something I see going into core.

**Comment by trusktr** [comment]
From a user perspective, I like the `rotation="10 20 30"` attribute interface.

I ended up doing something similar to that, but disguising it in something less hacky-feeling:

```js
// user runs
elem.rotation.x = 10

// then an event handler on the `rotation` object calls:
elem.updateProp('rotation') // HERE, same trick.
```

Sidenotes:

My version of `_propsChanged` (from previous PR)

- tracks booleans on a constant object (I can read values from the actual props so storing values there isn't necessarily useful)
- After every update I need to iterate on it once to set all props changed flags back to false.
- The object is not GC'd every update, it lives as long as the element does.


Your current _propsChanged version

- creates a new object after every update so that before next update it can add the changed prop values
- this queues objects to be GC'd each update.
- user code should use `propName in propsChanged` to check if a prop was set
- no iteration involved, but the GC is something I'm trying to avoid everywhere, to avoid the pause that happens every second or so when running WebGL code. I know it's just one object here, but at 60fps it can add up if it happens in other places too (not necessarily just in Skate).

**Comment by treshugart** [comment]
> no iteration involved, but the GC is something I'm trying to avoid everywhere, to avoid the pause that happens every second or so when running WebGL code. I know it's just one object here, but at 60fps it can add up if it happens in other places too (not necessarily just in Skate), and not just for one element, but imagine 100 elements: this means needing to collect 100 objects after every animation frame.

We can rectify this if it becomes a legitimate problem.
