### ISSUE TITLE
[idea] Handle initial prop values via constructor options arg.

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1554]
This is a simple feature idea. The idea is the ability to supply initial props values through a constructor `options` arg.

For example suppose we define an element:

```js
// Note, still v5 usage here
class MyElement extends withUpdate(HTMLElement) {
  props = {
    foo: Number,
    bar: String
  }

  updated() { /* ... react to the prop changes, etc ... */ }
}
```

then we instantiate it with initial values:

```js
const myEl = new MyElement({
  foo: 123,
  bar: 'blah blah'
})

console.log(myEl.foo) // 123
console.log(myEl.bar) // "blah blah"
```

Of course, this is only available when constructing elements via JS. In HTML, you obviously would use attributes, and the constructor will not receive any args when called by the engine.

My custom elements in [`infamous`](https://github.com/trusktr/infamous/) currently have this feature, but I've implemented it independently of the `props` definition, which requires more boilerplate. 

Now I'm looking to see how I can cleanly and simply automate this based on the defined `props`.

---

Using a single `object` arg is the best approach, because any `super(options)` call in the class hierarchy can handle any properties it wants.

**Comment by trusktr** [comment]
Here's a real world example. At the moment, I can do the following, using SkateJS API, with infamous:

```js
            const pointLight = new PointLight
            pointLight.props = {
                color: "white",
                position: "300 300 120",
                size: "0 0 0",
                castShadow: "true",
                intensity: "0.5",
            }
            scene.add(pointLight)
```

but it could be simplified to

```js
            const pointLight = new PointLight({
                color: "white",
                position: "300 300 120",
                size: "0 0 0",
                castShadow: "true",
                intensity: "0.5",
            })
            scene.add(pointLight)
```

**Comment by trusktr** [comment]
Plus, it gives us some more code structure options:

```js
new Scene({
    children: [
        new PointLight({
            id: "light",
            color: "white",
            position: "300 300 120",
            size: "0 0 0",
            castShadow: true,
            intensity: 0.5,
            
            children: [
                new Sphere({
                    id: "sphere",
                    size: "10",
                    has: "basic-material",
                    color: "yellow",
                })
            ],
        })
    ]
})

// move the light back and forth.
document.querySelector('#light')
    .position = (x, y, z, t) = [x, 100*Math.sin(t*0.001), z]
```

And this is good, because it means we can have such structural options in a non-DOM environment. For example, imagine a Node.js application using `infamous` with an alternative backend render hooked directly to OpenGL (not WebGL).

**Comment by treshugart** [comment]
Couldn't you just use `Object.assign()`?

```js
const elem = Object.assign(new PointLight(), props);
```

Your first example using `children` is definitely more convenient than having to call `appendChild()` but it doesn't feel like something Skate should provide especially when you can use something like [htm](https://github.com/developit/htm) or [val](https://github.com/skatejs/val) to make it more declarative. In fact, this is also a way for you to get the same functionality as the constructor arg in the first place as it's akin to attributes.

Another reason I don't really want to impose an optional props argument is that it precludes subclasses from defining their own shape for the arguments. I think either feels like an edge case that we don't need to have an opinion on.

**Comment by trusktr** [comment]
Good idea regarding `object.assign`.

I wonder how a `children` prop be defined so that it reads the native one, but accepts an array of new children. Gonna play with it...

I am planning to target also non-DOM environments (f.e. Node.js with OpenGL bindings), so I was looking to make the JS-only API convenient. :)
