### ISSUE TITLE
simpler `withChildren` implementation

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1555]
Check it out, I came up with an implementation of withChildren-like functionality using `CustomEvent`, which seems simpler than using MutationObserver:

https://codepen.io/trusktr/pen/fc793d73a2dcc208a8abdb788a0b3dae

It would need to remove the event handler in `disconnectedCallback` too.

What are you thoughts on it?

**Comment by treshugart** [comment]
> It would need to remove the event handler in disconnectedCallback too.

Probably not, actually, if it's only bound to the element itself and not any parents or children of it.

> What are you thoughts on it?

I think that mutation observers would prove to be far more performant. These events would have to bubble to inform parents of their presence and events are synchronous. This would essentially be doing a similar thing that [mutation events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events) did, and they've long been deprecated in favour of mutation observers.

Have you done any performance testing against mutation observers yet?

**Comment by trusktr** [comment]
Turns out this event-based approach is not good anyways, because it only works with custom elements that are willing to emit the event (no builtins f.e.).

**Comment by treshugart** [comment]
> Turns out this event-based approach is not good anyways, because it only works with custom elements that are willing to emit the event (no builtins f.e.).

Yep, that too. I'll reckon we should close this then.
