### ISSUE TITLE
First sentence in README.md is not correct

### ISSUE THREAD

**Issue by thundergolfer** [skatejs/skatejs#1556]
Here is the first sentence of the `README`.

> Skate is a functional reactive abstraction over the web component standards that.

It very much looks like the sentence is unfinished or something. Though it worth a heads up, as it makes it harder to understand the project quickly on arrival to the page.

**Comment by treshugart** [comment]
Must have been half brought over from the old one! Thanks!

**Comment by treshugart** [comment]
Should be fixed now! Thanks!
