### ISSUE TITLE
CLI command is actually "skatejs" not "skate"

### ISSUE THREAD

**Issue by AlexGilleran** [skatejs/skatejs#1557]
## Bug report

* Skate version: 5.2.4 - 0.1.1 is the CLI version (`npm info skatejs version`)
* Affected browsers (and versions): n/a

### Current behaviour

Tried running the cli as per the readme:

```
$ npm i -g @skatejs/cli
$ skate
-bash: skate: command not found
```

But if you run `skatejs`:
```
$ skatejs

? What are you building? (Use arrow keys)
❯ app
  lib

```

It works as you'd expect.

Another problem is that the link directly above it:
> There's a CLI to get you up and running: https://skatejs.netlify.com/packages/cli.

Doesn't go anywhere :(

**Comment by treshugart** [comment]
Oof, thanks for the report. Sorry it's taken me so long to respond. I'll update the docs. Regarding the link, I think that's because deep linking into the SPA isn't working for some reason.

**Comment by treshugart** [comment]
Updated command published and deep links now working :)
