### ISSUE TITLE
SkateJS ssr example just not working

### ISSUE THREAD

**Issue by matthewharwood** [skatejs/skatejs#1558]
## Bug report

* Skate version: 5.2.4
* Affected browsers (and versions): Chrome

### Current behaviour

`git clone https://github.com/skatejs/skatejs.git`
`yarn add global bolt`
run `bolt`
go into `cd packages/ssr/example`
run `npm install`
run `npm run start`
get error
```
{"statusCode":400,"error":"Bad Request","message":"Invalid cookie value"}
```

### Expected behaviour

should run server and serve ssr page.

### Thanks
Really would love to see this working.  Will play with it more .. it's prob me

**Comment by treshugart** [comment]
Hey, @matthewharwood, it definitely wasn't you! The example was never updated after the new APIs were released. I've since updated it. LMK if you're still having issues.
