### ISSUE TITLE
Add docs how to handle attribute update scenario

### ISSUE THREAD

**Issue by avisek1269** [skatejs/skatejs#1565]
I'm looking to get some example or documentation on how to re-render the web-components (created using preact ).  If attribute in web-component changes, it will re-render it but the states values do not change inside it, resulting in displaying previous state values. 

I guess I have to unmount and remount the component in attributeChangedCallback whenever attribute changes .

But I could not find any information regarding this. 
I would really appreciate the help.

**Comment by treshugart** [comment]
Hey @avisek1269, I'm really sorry I never saw this issue. Have you resolved it? I'm more than happy to help if you still need it. If you have a reproduction in a codesandbox, or something, that would be super helpful. Thanks!
