### ISSUE TITLE
Using `ReactDom.render` many many times is slow 

### ISSUE THREAD

**Issue by akoushke** [skatejs/skatejs#1568]
I understand that `react-element` [uses](https://github.com/skatejs/skatejs/blob/master/packages/element-react/src/index.ts#L14) `reactDom.render` to render the React component to a targeted DOM element.  wouldn't that bring down the performance for a large application using 100s of my `reacty` converted web components? if so, is there any alternatives?

**Comment by treshugart** [comment]
There are no alternatives. I haven't measured the impact (because of the lack of alternatives) but haven't noticed any noticeable performance impacts. Are there any references for the type of performance implications we should be expecting?

**Comment by treshugart** [comment]
Going to close this now as there doesn't seem to be anything actionable from it yet.
