### ISSUE TITLE
SSR: rendered Light DOM placement

### ISSUE THREAD

**Issue by drdreo** [skatejs/skatejs#1574]
## Bug report

skatejs/ssr version: 0.19.11

When the component is being rendered, the light DOM appears not in place where it should be. This is more of a technical question whether or not this is intended.

I have created a gist with the actual output of the example https://gist.github.com/drdreo/d4d8d2a62e10336ead6fe4fa20c86a6f
### Current behaviour

The light DOM ("World") is not placed in the `<slot>` where it should be rendered.

### Expected behaviour

The light DOM is being placed into the slot.

**Comment by trusktr** [comment]
@drdreo That is as expected. If you read about the ShadowDOM spec, the light DOM always appears where the user places it, then it is "distributed" to the slot at runtime. When an element is "distributed" it is not placed into a slot, it is only _rendered visually by the browser as if it were at that location in the DOM, but its actual location in the DOM will always be the original light DOM position_.

Not sure if that makes sense. I tried to explain briefly, but maybe a full "ShadowDOM tutorial" will do a better job (try Google).

**Comment by trusktr** [comment]
I closed the issue, but feel free to continue discussion.
