### ISSUE TITLE
Template happens immediately after create, not after attached – intentional?

### ISSUE THREAD

**Issue by cyberdash** [skatejs/skatejs#168]
I've noticed that templating is called during the `create` callback, which does not give me time to construct an element dynamically with javascript. For example,

```
var MyElement = skate('my-element', {
    template: template('<strong><content></content></strong>')
});

var span = document.createElement('span');
span.innerHTML = 'text should be bolded';

var myElement = new MyElement();
myElement.appendChild(span);
document.body.appendChild(myElement);
```

Doing this, the span will not be placed inside the `<strong>`, as templating happens as soon as `MyElement()` is called, which is too early.

I'd suggest doing templating on `attached` instead. Is this reasonable?

**Comment by treshugart** [comment]
I'm not sure what `template()` is. If you're using `skatejs-template-html`, you should wrap your element before calling `appendChild`

```js
skateTemplateHtml.wrap(myElement).appendChild(span);
```

Native ShadowDOM wouldn't have this problem.

**Comment by cyberdash** [comment]
Yep, should have mentioned I was using `skatejs-template-html`. This answers my question! Thanks
