### ISSUE TITLE
Add an attribute flag that tells skate to skip the template callback for the element.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#173]
This allows the developer to implement server-side rendering in their template language of choice.

**Comment by treshugart** [comment]
References #136.

**Comment by treshugart** [comment]
This could simply be a configuration option that, for now, defaults to the same name as the resolved attribute option.

**Comment by treshugart** [comment]
I'm wondering if this should be left completely up to the template callback. I have a use case where a template callback will bind extra functionality to the component element as well as template it. In this case, we'd want `template` to be invoked and the templating engine to decide whether or not it needs to template the element.

**Comment by treshugart** [comment]
@alexreardon see my comment above this one, what do you think? I see it as something hard to automate from within Skate because of all the different scenarios that we'd need to take into account.

**Comment by alexreardon** [comment]
Can you post the use case where template is templating and binding? I would have thought additional binding could be done in `attached` or just through the normal `events` object

**Comment by treshugart** [comment]
https://github.com/skatejs/shade is a good example. It returns a function that templates and binds behaviour to the web component element. That said, it's a better idea to split those functions into `.bind()` and a `.render()`.

Currently you can bypass templating by specifying a `resolved` attribute on your element. The original intention of this was to prevent FOUC by allow you to specify an `unresolved` attribute and then the adding of the `resolved` attribute would allow you to show the element via CSS. I think it makes sense to reuse this attribute.

**Comment by alexreardon** [comment]
:+1:
