### ISSUE TITLE
suspend execution of attribute.created?

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#179]
For all of the attributes I implement when using skate, I have to do checks like:

```
...
attributes: { foo: { created(el, diff) {
    if(!("shadowRoot" in el)) return;
    ...
}, }, },

created(el) {
    ... // (initialise shadow root here, etc.)
    if(el.foo) el.setFoo(el.foo);
}
```

This is because my attributes interact with the element's shadow DOM, and so `created` can't function properly if called before the element has finished being created.

Perhaps it would be better to change skate's behaviour so that `attribute.*` doesn't get run before the element's `created` function has finished, as I think there are few use cases for using these callbacks in the absence of the DOM. Is that feasible?

**Comment by treshugart** [comment]
I've had conflicting opinions about this in the past. On one hand, it's nice to have attributes all set up by the time you hit the created callback. On the other hand, sometimes you need to do something in the created callback that your attribute handler depends on. I've found the latter to be rare, but maybe still something that we should take into account.

As for what you're doing, you could probably simply fix it by putting your shadow root creation in the `template` callback. It's designed for that and it would allow you to abstract your shadow dom into a separate function:

```js
function shadowDomTemplate (shadowHtml) {
  return function (element) {
    element.createShadowRoot().innerHTML = shadowHtml;
  };
}

skate('my-component', {
  template: shadowDomTemplate('<header><content select="h2"></content></header><section><content></content></section>')
});
```

This technique is also described in the [docs templating section](https://github.com/skatejs/skatejs#templating) at the very end.

I'm interested to hear your opinion on why attribute creation should come after `created`. The more I think about it, it might not be necessary to trigger the `created` handlers before the element `created` callback. This might even make the `created` attribute handler redundant. Thoughts?

**Comment by treshugart** [comment]
Actually, the `created` handler would still be necessary, just not force triggered before the `created` lifecycle callback.

**Comment by marcoms** [comment]
wrt shadow root creation, in my case it's inside of a function that "initialises" the component with event listeners and such, in addition to creating the shadow root, which is why it went in `created`, however I should probably refactor to fit in to the skate way of things. (as long as I understand correctly that `template` gets run before `attribute.created`?)

> it's nice to have attributes all set up by the time you hit the created callback

What would you mean by "attributes all set up", besides having their values available as a string?

At any rate, with the `template` callback, my concerns are not so relevant, however my rationale for post-`created` attribute callbacks is that, the elements `created` function should be used to get the element in a finished state (or at least that's my perception), and so I would expect as a developer for attributes to be set up in a predictable and established environment. But that's just me of course.

**Comment by treshugart** [comment]
> attributes all set up

If you needed to compute any attributes based on other attribute values, those would be already set up for you. That said we can just use getters / setters on the prototype for this.

I think you're right, we should probably change the behaviour this.

> (as long as I understand correctly that template gets run before attribute.created?)

The *only* thing that happens before running the `template` callback is ensuring the prototype is all set up. Attributes and everything else is triggered after.

So what we're proposing now is to move [line 188](https://github.com/skatejs/skatejs/blob/6d0f62db5b6881073ca3617de3ad5c677c1d375e/src/lifecycle/created.js#L188) to after [line 192](https://github.com/skatejs/skatejs/blob/6d0f62db5b6881073ca3617de3ad5c677c1d375e/src/lifecycle/created.js#L192), correct?

**Comment by marcoms** [comment]
Yes I believe so. Thanks @treshugart for your support!

**Comment by treshugart** [comment]
@marcoms pr created: https://github.com/skatejs/skatejs/pull/189 just in case you want to give a quick review. I'll merge in a bit.
