### ISSUE TITLE
Expose skate as base ES6 Class 

### ISSUE THREAD

**Issue by dredzone** [skatejs/skatejs#181]
It would be nice to have skate functionality as ES6 abstract class (component) from which components could be created as ES6 classes.

**Comment by treshugart** [comment]
This is actually [in mater](https://github.com/skatejs/skatejs/blob/master/test/unit/extending.js) :). I plan on landing a 0.14 in the next week or so.

**Comment by treshugart** [comment]
Also, if what you see in the tests is different from what you're describing, please feel free to document that here. Otherwise, let me know if that solves your issue.

**Comment by treshugart** [comment]
Also, see #162.

**Comment by treshugart** [comment]
[Documented](https://github.com/skatejs/skatejs#extending-components). Closing for now. If this requires more attention please feel free to reopen.
