### ISSUE TITLE
RFC: `attribute.set` = `attribute.{created,updated}`

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#183]
Just wondering if having an additional `attribute.set` callback would be appropriate, as in my code I handle the attribute the same regardless of whether it is created or updated, which leads to duplicate code, which leads to me making a function in `prototype`, which leads to an unfortunate two ways of setting an attribute for my components -> `myEl.foo = "bar"` / `myEl.setFoo("bar")` :)

```
skate("x-foo", {
	attributes: {
		foo: {
			created(el, diff) {
				el.setFoo(diff.newValue);
			},
			
			updated(el, diff) {
				el.setFoo(diff.newValue);
			},
		},
	},
	
	prototype: {
		setFoo() {
			...
		},
	},
	
	...
});
```

To be clear, the hypothetical `attribute.set` would be run in all cases in which `attribute.created` and `attribute.updated` would be run. Perhaps this is presently possible with `attribute.fallback`, however I don't think this would work in the situation where `attribute.created` and `attribute.updated` are implemented already and with different behaviours, but if they also share some code in both events. It would be desirable in my opinion to make it explicit anyway.

**Comment by treshugart** [comment]
That's a good idea. Maybe `fallback` should just be called all of the time if it is specified. That means it would also be called when the attribute is removed, though. `fallback` might also then not be the best name for it. The reason I'm suggesting doing that is because a `set` and a `fallback` would have overlapping functionality and I'd like to keep the API from having too many options.

What do you think?

**Comment by marcoms** [comment]
Ah yes there would be some overlap... Perhaps specifying callbacks via JSON strings as keys in the attribute's object could allow the user to specify specifically what gets ran?

```
...

foo: {
    "created updated": (diff) => {
        ...
    },

    "updated": (diff) => {
        // updated-specific code
    },

    "*": (diff) => {
        // equivalent to the revised `fallback` in your comment
    },
},

...
```

Might require quite a bit of work internally however, especially to keep the API stable... However it would mean there is no need to implement `attr.set` :)

**Comment by treshugart** [comment]
Seems that you wouldn't need `'*'` because you could just specify: `'created updated removed'`.

**Comment by treshugart** [comment]
Now in master. Changes:

- `fallback` no longer supported because the same is achievable with the new syntax.
- `'*'` was not implemented. Just use a function, or bind to `'created updated removed'`.

**Comment by marcoms** [comment]
That's amazing @treshugart!

**Comment by treshugart** [comment]
Hey @marcoms I have a question for you regarding #200. I'm in the process of implementing this and once fully implemented I'm not sure there's much of a need for drilling down into the attribute lifecycle (created, updated, removed, etc). Basically, to define an attribute, you'd define a property and link it to an attribute. Your logic would go in the setter for the property. Thoughts?

**Comment by marcoms** [comment]
I myself use element properties and attributes synonymously, and I suppose distilling the API to getters and setters would be fine so long as there is some kind of object describing the change in the setter, similar to the current way of doing things.

If I understand correctly, `attributes` will go away in favour of `accessors` as implemented in x-tags? (if so, `accessors` is a technically correct name however to me it sounds a bit ambiguous, `properties` would be my preference FWIW)

**Comment by treshugart** [comment]
Though that issue labels it as `accessors`, it would be implemented as `properties`.

**Comment by marcoms** [comment]
lgtm :+1:
