### ISSUE TITLE
Initialise descendants first.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#192]
We must ensure in polyfill land that when an element is initialised (created lifecycle) that its descendants are also initialised prior to calling the created callback on the element itself. The furthest descendant should be initialised first.

Care should be take so that tree walking and initialisation do not happen more than once for a given tree. For example, when a mutation observer fires it descends into the tree and initialises each element. If this were to trigger initialisation on a component and that component then triggered initialisation there would be two tree walkers checking nodes.

**Comment by treshugart** [comment]
Fixed in master now. We should make sure that there's no tree walking happening where it doesn't need to be.

**Comment by dredzone** [comment]
Native custom elements nested parent / child lifecycle does not initializing children before parent is created at least in Chrome (version 43). It does it in sequence parent created -> child created. Could not find in the spec. document what is right order either.

**Comment by treshugart** [comment]
Interesting. In the tests I did prior to raising this it seemed to do that. I know chrome behavior changed recently in that children wouldn't even be available in the created callback. Seems there at least available now. I'll do more testing and get back to you.

**Comment by treshugart** [comment]
Yup, you're right. What had happened is that my elements had gotten initialised in the same order as the registrations because they were already in the DOM.

**Comment by treshugart** [comment]
Fixed in 345ec2cf9928b4f9a54d5ffcc6b7c08e91a2bcf6.

**Comment by antitoxic** [comment]
In what order should I register the components so that furtherest descendands are rendered first? 

It doesn't work for me when I register the containing component first. So is it order-specific?

**Comment by treshugart** [comment]
@antitoxic So, there's no real order that you can rely on, in terms of native web components. See this bin: http://jsbin.com/gezube/1/edit. The `-1` elements will be initialised in the order in which their definitions are registered because they already exist in the DOM. The `-2` elements will be initialised in DOM order because their definitions already exist.

Skate behaves the same way.

**Comment by antitoxic** [comment]
I found my mistake. I think it would be useful for the documentation. It's to do with `created` and `attached` callbacks. The latter is called every time element is moved (detached and appended somwhere else). I will fill some more details in #199/
