### ISSUE TITLE
attribute created / updated lifecycle 

### ISSUE THREAD

**Issue by dredzone** [skatejs/skatejs#193]
created method calls every time existing attribute value changing, below function calls twice when changing attr value.

'attr': function handleInsertAndUpdate (element, change) {
    console.log('handleInsertAndUpdate - ', change);
}

**Comment by treshugart** [comment]
If I'm reading the issue correctly, that's normal behaviour. I'm assuming you're doing the second example from the [attributes lifecycle section in the docs](https://github.com/skatejs/skatejs#attribute-lifecycle). Is that correct?

**Comment by dredzone** [comment]
there is still an issue, for example if I have an existing attribute on element and I change value of the attribute above function called twice (Firefox 38.x) with change.type='update' and the change.type='create'. I would expect only update call not update and create.

**Comment by treshugart** [comment]
Odd. Tests should cover that. I'll have a look tomorrow.

**Comment by treshugart** [comment]
Can you submit a separate issue if you're still having problems, please? Thanks!
