### ISSUE TITLE
Don't render initial html elements before their templates are compiled

### ISSUE THREAD

**Issue by antitoxic** [skatejs/skatejs#199]
I like that skate allows any type of template engine and I use that functionallity. I don't like shadowdom but I like the `<content select="...">` placeholders which move inner elements to specific places. (Those inner elements could be skate components too.) So I'm working on emulating  `<content select="...">` .

However skate triggers element creation before the template has moved the elements and it double-fires. 

It's a mess. How can I prevent this?

**Comment by treshugart** [comment]
See [my comment](https://github.com/skatejs/skatejs/issues/192#issuecomment-108657781) on the other issue. Unfortunately that's how native custom elements work at the moment.

I've been messing with a similar style of templating. See [Shade](https://github.com/skatejs/shade).

> and it double-fires

Could you elaborate on that, please? I'm not sure what you mean.

**Comment by antitoxic** [comment]
I'm closing this.

It would be useful if there's (*even just a tiny*) note in the documentation about `attached` and `created` callbacks. 

Basically I was emualting same thing that Shade does. (I didn't know about it btw! Thanks for sharing). I tried doing this in 2 ways:

1. rendering elements' templates fully in strings and setting it with `innerHTML` - that is a **big NO-NO** because an element is not marked as resolved until last parent is rendered (becaus tempaltes's just a string) and the template rendering is called once again for the new parent and once more and once more... A mess.
1. Entirely moving elements around with DOM - that worked well. ***Important note***: not to use event document fragments - it tends to break mutation observers (as far as my tests go)

That is my entire template function: https://github.com/obshtestvo/signali-theme/blob/master/elements/app/service/pseudo-webcomponent.skate.js#L32
