### ISSUE TITLE
attributes, setters and getters

### ISSUE THREAD

**Issue by dredzone** [skatejs/skatejs#200]
It would be nice to extend logic of custom attributes to element setters / getters similar to x-tags, for example below code would allow execute custom set / get for element.overlay and propagate change to attribute

    accessors: {
      overlay: {
        attribute: {boolean: true},        
      },
      escapeHide: {
        attribute: {
          boolean: true,
          name: 'escape-hide'
        }
      },
      overlayTapHide: {
        attribute: {
          boolean: true,
          name: 'overlay-tap-hide'
        }
      }
    }

**Comment by treshugart** [comment]
Hey @dredzone I've pushed this to master. You can find some details in the "properties" option in the massive options object that is documented near the top of the readme. It may change depending on feedback internal here at Atlassian as well as feedback from you guys, but what is there should be close to what will be in the next release.

**Comment by treshugart** [comment]
Basically to achieve what you want all you'll need to do:

```js
properties: {
  myProperty: {
    attr: true,
    type: Boolean
  }
}
```

**Comment by dredzone** [comment]
thanks for quick turnaround.
