### ISSUE TITLE
Support >>> shadow piercing combinator.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#203]
Seems `/deep/` is now `>>>`, or will be. https://hacks.mozilla.org/2015/06/the-state-of-web-components/

Should support both for the time being.

**Comment by marcoms** [comment]
Just as a heads up, shadow piercing combinators [will be removed](https://www.w3.org/wiki/Webapps/WebComponentsApril2015Meeting#Summary_of_discussion_on_Contentious_Bits) in the distant future AFAICT, so support should probably be removed when that happens

**Comment by treshugart** [comment]
Interesting. There doesn't seem to be explicit mention of that in the Mozilla blog post. Probably best to remove now before it makes its way into a release.

You originally submitted #197 and I see a need for listening events triggered from within the Shadow DOM. It seems `::content`, `::host` and `::shadow` are still being implemented AFAIK. What do you think about keeping support for those and removing `/deep/`?

**Comment by treshugart** [comment]
Removed in #207. I kept `::shadow` around for now because I couldn't tell what their stance on it was. Both `::host` and `::content` should work as normal.

**Comment by marcoms** [comment]
+1, sorry for the silence on my end.

BTW `:host` is spelt with a single colon, unless I'm mistaken?

**Comment by treshugart** [comment]
Yeah, it is. In the code it is, but I mistyped it here :)

**Comment by marcoms** [comment]
Well, it seems `::shadow` will be removed after all - just saw this in devtools:

>::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

https://www.chromestatus.com/features/6750456638341120 leads to https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/68qSZM5QMRQ/pT2YCqZSomAJ

**Comment by treshugart** [comment]
Alright, looks like we're removing Shadow support completely then. Thanks for spotting that :)

**Comment by marcoms** [comment]
It's a bit problematic though, since shadow selectors like `::shadow` will be removed to prevent hijacking from external sources, but there is no risk from inside the component itself.

I think there should be some kind of way in the skate API to deal with this, maybe a boolean at the  end of function signature or something.

**Comment by treshugart** [comment]
It should still possible to interrogate the `e.path` property to get real element that triggered the event in the Shadow DOM. I would like a way to tell Skate to match against the path instead of the target but being that there's little agreement within the working group on Shadow DOM I don't have much confidence in any solutions I could provide at the time being. I'm open to suggestions, though.

**Comment by alexreardon** [comment]
What is the recommended approach for handling shadow dom events now?

**Comment by treshugart** [comment]
Since they're removing the piercing combinator selectors, event delegation is kind of up in the air. I believe the `path` property is still an array of elements from the shadow element that triggered the event up to the host element. Of course, if they remove the selectors because of not wanting to expose the shadow root, then they might end up removing this.

Events still bubble through the Shadow DOM, they are just retargeted to look like they came from the host element.
