### ISSUE TITLE
Callbacks should use "this" instead of first argument.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#205]
Callbacks:

- `created`
- `attached`
- `detached`
- `template`

Should have the element bound to the context of the function rather than passed as the first argument.

**Comment by alexreardon** [comment]
You sure? I thought you where against `this` binding? Don't get me wrong, I am keen. It makes sense that `this` would be the current element

**Comment by treshugart** [comment]
I am against rewriting the context of a function, generally speaking. That said, everytime I go to use the API I always have to catch myself from typing "this". Against it or not in principle, I think it makes sense in this circumstance to use "this".

**Comment by alexreardon** [comment]
Agreed. Would you consider then removing the `element` parameter? I would think not given that it would break existing code

**Comment by treshugart** [comment]
That's what dev releases are for ;). I'll include it in the upgrade guide to 0.14. The whole idea of this is tightening up things for the road to 1.x.

**Comment by alexreardon** [comment]
roger

**Comment by alexreardon** [comment]
I have been using this new change for a while now. My code is much cleaner :+1:

**Comment by treshugart** [comment]
Nice!
