### ISSUE TITLE
Entry file changed from skate.js to index.js

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#210]
The `dist` entry stays the same: `dist/skate.js` and `dist/skate.min.js`.

`lib` and `src`: `skatej.js` -> `index.js`.

**Comment by alexreardon** [comment]
This would be worth mentioning in release notes (if there is release notes)

**Comment by treshugart** [comment]
Last one in list: https://github.com/skatejs/skatejs/blob/master/CHANGELOG.md#changed.
