### ISSUE TITLE
Consider removal of class name bindings.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#225]
Class name bindings exist mostly to transition away from legacy components that bind their behaviour to elements using class selectors without having to refactor any markup or break backward compatibility. By the time 2.0.0 rolls around, we should consider removing support for this.

**Comment by alexreardon** [comment]
While this may be nice from a purely web-component perspective, it might limit those who are looking to transfer from an older way of doing things.

The old skate example would no longer hold true: 

```
skate('tabs', {
  type: skate.type.CLASSNAME
  created: function (element) {
    jQuery(element).tabs();
  }
});
```

This is quite a nice feature for those who are in a transition stage.

**Comment by treshugart** [comment]
The reference above is incorrect. It has been corrected.

**Comment by treshugart** [comment]
I agree. In #226 I've split out the logic for each binding type so that if we want we can include only the spec'd way in core Skate and supply the other binding types in separate repos. This would make it so that we would have to support multiple versions of Skate on the page differently:

- We could still use a single document observer.
- There would have to be multiple registries that don't duplicate components between each other but have different binding methods applied to each.

**Comment by treshugart** [comment]
Custom binding types are in separate repos:

- https://github.com/skatejs/type-attribute
- https://github.com/skatejs/type-class

The bundled element binding supports element names without dashes. It might be worth splitting that out so that what is bundled with Skate is strictly spec material.

**Comment by treshugart** [comment]
For posterity, the rationale behind this is that these serve as a bridge to the native web component APIs from old markup patterns. The attribute binding is useful on its own in certain use-cases but using custom elements should be the default and most common use-case. It's intentional that one should have to think about, and explicitly include a separate dependency in order to use a non-standard binding type.
