### ISSUE TITLE
Make skate.init() simpler.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#238]
Currently it accepts a selector or multiple nodes, however, the use case is really to just accept one node. We should just simplify it to accept a single parameter.

A performance optimisation we should also make is to not use `elementContains()` to check to see if the document contains each element in the main element. We should simply check the element that was passed into `init()` and use that value to determine whether or not we should call attached on the descendants. If the main element is in the DOM, so are its descendants.

**Comment by alexreardon** [comment]
Related, but unrelated:

in the documentation you have this example:

```
var element = document.getElementById('my-component-id');

skate.init(element);

element.someCustomMethod();
```

If the element was already in the DOM would not `.created()` and `.attached()` have been called? Why would `init` need to be called in this circumstance?

**Comment by treshugart** [comment]
In browsers that don't support native, mutation observers are used. If you want to interact with it sync, then you've got to init sync for those browsers.

In the next release, using `skate.create()` will get around this.
