### ISSUE TITLE
Object definitions

### ISSUE THREAD

**Issue by TravisTheTechie** [skatejs/skatejs#240]
There are parameters to the callbacks for different options, but they are just named not defined. More JSDoc comments might help, but just listing of what the objects are and their definitions might help. 

[ ] element -- https://developer.mozilla.org/en-US/docs/Web/API/Element I assume
[ ] change -- described in the readme, but not super explicit
[ ] eventObject -- https://developer.mozilla.org/en-US/docs/Web/API/Event
[ ] currentTarget -- element again

Applies to the README and the usage docs.

**Comment by alexreardon** [comment]
:+1:

**Comment by treshugart** [comment]
This was done in the docs-tlc stuff. Probably won't put it in the readmes since the docs be the source of truth for this stuff soon. Closing.
