### ISSUE TITLE
skate.ready: callback not executed if document.readyState === "interactive"

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#243]
This is because `DOMContentLoaded` is fired when `document.readyState` becomes `"interactive"` (finished parsing), while the `load` event is fired when it becomes `"complete"` (finished loading sub-resources).

If, then, the current `document.readyState` is `"interactive"` and `skate.ready` is called, the `DOMContentLoaded` event has already been fired and so the callback will be waiting for an event that will never be fired again.

**Comment by treshugart** [comment]
We might need to browser check this then. @nicolasv originally fixed #219 which fixes IE > 11 setting "interactive" too early. That issue also links off to a jQuery issue relating to the same problems. It's best to be able to fire as early as possible, so I'm happy to re-implement this given we can take into account the issues IE has here.

**Comment by marcoms** [comment]
My mistake, didn't realise the history of this.

Well, If we continue to compensate for IE11+, then we should listen for the `load` event instead of `DOMContentLoaded` so that the callback won't wait for `DOMContentLoaded` indefinitely.

**Comment by nicolasv** [comment]
Yeah, we should fallback to `load` for IE <= 10 and everything else should be able to check `readyState` of `complete` or `loading`.

**Comment by treshugart** [comment]
@nicolasv do you mean `interactive` instead of `loading`?

**Comment by treshugart** [comment]
Also, related: #231.

**Comment by treshugart** [comment]
Just spoke to @nicolasv IRL and decided that instead of checking `readyState` at all, that we'll set a flag when `DOMContentLoaded` is fired. If the flag is `false`, we queue the callback to be executed when `DOMContentLoaded` is fired. If it is `true` then we'll just execute the function right away.

**Comment by marcoms** [comment]
Sounds good

**Comment by nicolasv** [comment]
> Just spoke to @nicolasv IRL and decided that instead of checking readyState at all, that we'll set a flag when DOMContentLoaded is fired. If the flag is false, we queue the callback to be executed when DOMContentLoaded is fired. If it is true then we'll just execute the function right away.

From a follow-up IRL discussion, for IE <= 10 we can't rely on `DOMContentLoaded`/`interactive` so its implementation needs to set that flag to `true` only for `complete`.

**Comment by nicolasv** [comment]
@marcoms mind reviewing #249, please?

**Comment by marcoms** [comment]
fixed by #249

>Just spoke to @nicolasv IRL and decided that instead of checking readyState at all, that we'll set a flag when DOMContentLoaded is fired. If the flag is false, we queue the callback to be executed when DOMContentLoaded is fired. If it is true then we'll just execute the function right away.

Is this still planned?
