### ISSUE TITLE
ES5 for readme.md

### ISSUE THREAD

**Issue by alexreardon** [skatejs/skatejs#245]
The `readme.md` currently uses ES6 notation to convey the skate api. I think this should be changed to ES5 for the following reasons:

- ES5 is generally better understood than ES6
- People may get the idea that the new the skate is ES6 only
- As ES6 does not run natively yet, a user of the library would not be able to `copy` `paste` the example without a transpiler

**Comment by treshugart** [comment]
+1

Once you go ES2015, it's hard to go back.

**Comment by marcoms** [comment]
Fixed by pr #274
