### ISSUE TITLE
Declaring a property with a default value throws TypeError

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#253]
With this script:

```js
skate("test-element", {
	properties: {
		prop: {
			value: "a value"
		},
	},
});
```

(see http://codepen.io/marcoms/pen/qdKxQq)

Declaring the property `prop` with a `value` leads to this error after the element is instantiated:

`Uncaught TypeError: Invalid property.  A property cannot both have accessors and be writable or have a value, #<Object>`

```js
testElementInstance instanceof HTMLUnknownElement;  // false - element is registered
testElementInstance.prop;  // undefined - default value not set
```

**Comment by marcoms** [comment]
> ~~This is particularly odd since I can only reproduce this if the component is called "calm-toast", other names or even ones with the same length are fine (is a checksum involved?)...~~

Er, never mind, An error wasn't being thrown because I updated the component definition but not the HTML, so the new component was never instantiated.

---

Basically, setting default values doesn't work.

**Comment by treshugart** [comment]
Haha, calm toast! This is actually a docs problem. I changed the name to "init" as to not clash with "value".

**Comment by marcoms** [comment]
Nice! One less name collision!
