### ISSUE TITLE
Clarifying purpose of Skate on the website

### ISSUE THREAD

**Issue by TravisTheTechie** [skatejs/skatejs#260]
Per a conversation with @treshugart...

> Skate provides an API to bind behaviours to DOM elements

And the benefits, or why one would use Skate to do this...

* Allows easy transition from selector-based behaviour binding to element binding
* Provides lifecycle hooks for elements
* Provides a superset of the custom elements spec
* Small, gzipped at 4kb (or whatever size it is)

So we can do some word smithing on this to make it a bit better, then implement it on the website. Once that's done, update the tag line on repo to match.

**Comment by antitoxic** [comment]
I would vote for this. It's hard to explain what Skate is. Especially with the name, people are asking me what is this to do with web components.

Also asking me why should they use it over `<insert name of framework here>` - like angular, polymer and so on.

Simplicity, Performance?, Size... so on.

**Comment by treshugart** [comment]
Since we should have web components in the title so that it shows up in relevant searches I was thinking about:

> Skate is a web component library that provides an API to bind behaviour to DOM elements. It's based on the W3C specification for Custom Elements.

**Comment by treshugart** [comment]
Implemented in master and 0.13.x.
