### ISSUE TITLE
Reparenting an element fires the detached + attached handlers twice in native

### ISSUE THREAD

**Issue by nicolasv** [skatejs/skatejs#261]
If you reparent an element, e.g., `newParentEl.appendChild(childEl)` where `document.body.contains(childEl)`, then the detached and attached lifecycle callbacks are called twice in native (i.e., Chrome).

This is because the call to reparent (`appendChild(…)` in this example) first synchronously triggers the detached callback and then the attached callback. Then, asynchronously, the document observer comes and processes the detached and attached mutation events (from the `appendChild(…)` call). At this point the element is back in the DOM (thanks to the natively invoked attached callback) and so the document observer proceeds in calling the detached callback and then the attached callback.

In comparison, attaching a detached element will synchronously trigger the attached callback, and then when the document observer asynchronously processes the attached mutation event, it sees that it is already attached and does a no-op.

**Comment by treshugart** [comment]
For 1.0.0 this is now up to the webcomponentsjs polyfills to fix if it is in fact an issue.
