### ISSUE TITLE
PhantomJS

### ISSUE THREAD

**Issue by alexreardon** [skatejs/skatejs#263]
I have experienced first hand that skatejs does not play well in PhantomJS. My understanding is that this is a conscious choice (/cc @treshugart ). It could be worth adding this to the documentation in the supported browser matrix section; if just to avoid others any future pain.

**Comment by treshugart** [comment]
That's a good point. What version of PhantomJS are you using? < 2 is notorious for not supporting features otherwise supported in modern browsers; running tests in IE9 is more reliable than Phantom.

**Comment by alexreardon** [comment]
I was using the one used in https://github.com/karma-runner/karma-phantomjs-launcher
Looks like it is `>=1.9` https://github.com/karma-runner/karma-phantomjs-launcher/blob/master/package.json

**Comment by treshugart** [comment]
Yeah, would be a good idea to add this to the documentation. :+1:
