### ISSUE TITLE
Properties should take existing value when overwriting properties that already exist.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#270]
For example, if you specify a `textContent` property, it overwrites the property but does not take the existing value.

~~The `properties` `init` option should take precedence over existing values.~~

Properties should actually override `init` because `init` should be default if nothing is provided. Existing values on elements then take precedence.

**Comment by treshugart** [comment]
PR'd in #303.

**Comment by alexreardon** [comment]
I was thinking that `init` should be renamed to `fallback` (`default` would be best but it is a reserved word) to more clearly indicate it's behaviour

**Comment by treshugart** [comment]
I'm going to keep this closed and raise the naming issue in #281.
