### ISSUE TITLE
Finalise property options

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#281]
Currently we have:

- `attr`
- `init` see https://github.com/skatejs/skatejs/issues/270#issuecomment-136902990
- `type`
- `get`
- `set`

Do we want to change these?

### `attr`

Maybe:

- `attribute`
- `attrLink`
- `attributeLink`
- `linkAttribute`

Remember:

- If `true` it `dash-cases` the property name and uses that as the linked attribute.
- If `falsy` it doesn't link it at all.
- If a `string` it uses the provided string as the attribute name to link.

### `init`

Maybe:

- `default` (but that's a keyword)
- `defaultValue`
- `value` (clashes with normal `defineProperty` option, but we can get around that)
- `initialValue`

Remember:

- If it's a `function` then the return value of the function becomes the initial value.
- Any other value is the exact value of the property.

### `type`

Maybe:

- `coerce`

Remember:

- It should coerce the value, but you can also do type checking here or throw errors if it's empty (required). Type checking et al can also go in `set` if you really want.

### `get`

I think this should be removed altogether. It kind of defies the rest of the options. If you want to make a readonly property, them you can probably just put a getter on the `prototype`.

### `set`

Maybe:

- `change`
- `update`
- `set` is good, but it kind of implies there's also a corresponding `get`

Remember:

- It has the same semantics as a normal property setter, but it receives two parameters:
  - `newValue`
  - `oldValue`

### One last question...

Do we want to support normal `defineProperty` options?

**Comment by treshugart** [comment]
@marcoms @alexreardon you guys probably have some opinions on this.

**Comment by marcoms** [comment]
Since ES5 reserved words are OK to use as object keys, so "default" should be fine to use.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Reserved_word_usage

>Reserved words actually only apply to Identifiers (vs. IdentifierNames) . As described in es5.github.com/#A.1, these are all IdentifierNames which do not exclude ReservedWords.

>```js
a.import
a["import"]
a = { import: "test" }.
```

Probably best to use "default" as a quoted key if it's used, though.

Also:
https://developer.mozilla.org/en-US/docs/Talk%3AJavaScript/Reference/Reserved_Words
http://stackoverflow.com/questions/7022397/using-reserved-words-as-property-names-revisited

**Comment by marcoms** [comment]
Also one possible reason to keep `get` is that it could be used to make computed properties.

```js
get() {
  return `${this.firstName} ${this.lastName}`;
}
```

Obviously less performant than just writing to the property when the others changes, but that duplicates code and isn't obvious when looking at the source of the computed property

```js
firstName: {
  set(value) {
    this.fullName = `${value || ""} ${this.lastName || ""}`;
  },
},

lastName: {
  set(value) {
    this.fullName = `${this.firstName || ""} ${value || ""}`;
  },
},

fullName: {},  // present only for documentation purposes
```

**Comment by treshugart** [comment]
For computed properties, you can put getters in on your prototype. If you want compute functionality based on dependent properties then that's a separate concern that we haven't solved yet, though, we have spiked some solutions.

**Comment by alexreardon** [comment]
My thoughts:

## property options
`init` -> `fallback`. The 'init' value is overridden by properties passed in. I think the name should reflect this.
`type` ->  (my favourite) `preprocess`, `coherse`. Currently `type` is used to convert the property into a particular value before the setter is fired. I think using the word `type` is a bit confusing as I think it implies a contract type (boolean check).
`set` -> `update` or `change`. We currently have a two phase setter: `type` on start and then `set` from that point. This is not normal `set` behaviour. I think changing it could help make this clearer. 

## type checking
It is perfectly fine to use the `preprocess` function to log a warning. I wonder if their is some way of making this common behaviour more baked into skate (eg React PropTypes). However, this would be a challenge given that if `attr:true` then everything would be a `string` before the `preprocess` function. This makes type checking difficult. Perhaps the best place is the `preprocess` function to check types. What I am looking for is for some way for a component to enforce a contract. This can be done manually in `preprocess`. I am trying to think of a way we could let `skate` help us too.

**Comment by treshugart** [comment]
In the last lifecycle update `set` has been changed `update`. I don't have any real strong opinions about changing that to `change`, but maybe `afterUpdate` is better.

`get` was also removed in that update.

I agree with most of your points here @alexreardon. I was also thinking to myself of having something like:

```js
prototype: Object.create({}, {
  prop1: skate.properties.boolean(),
  prop2: skate.properties.boolean({ attr: true })
})
```

This is far more performant than running property code on every initialisation. The only problem with this is that you can't "initialise" a property. For that, we could do something like:

```js
getInitialState: function () {
  return {
    prop1: true,
    prop2: false
  };
}
```

Of course, values initially found on the element would trump any specified in the initial state. I think this gives us the best of both worlds and is worth toying with.

**Comment by bqx** [comment]
I like the `set` -> `update` change, especially if `get` is being removed

I also agree that `type` seems to imply a type check and that `coerce` or `preprocess` would be a more descriptive name.

re: defining properties in the `prototype`: I like how the idea of having more control but I also find having the `properties` options in the object you pass to the `skate` call really easy to understand and read.

**Comment by bqx** [comment]
Now that `properties` doesn't trigger the `attributeChangedCallback`, there's no nice way of triggering the `update()` function for a property when trying to initialise it with a value. You could pull the `update()` code out into a function and call it in `created` or `ready`, but when you have a lot of properties you want to do this for it gets quite wordy.

Maybe a `created` callback that you can specify for each property, or a `updateOnInit` flag set on each property could make this easier?

**Comment by treshugart** [comment]
> Now that properties doesn't trigger the attributeChangedCallback

It does if linked: https://github.com/skatejs/skatejs/commit/6ef3d1bc189fb2dd66294aff156589e7187e5d0d.

**Comment by zephor** [comment]
## attr

I like `linkAttribute` for `attr` IMO it's far more descriptive, maybe we could go a step further and name it `linkToAttribute`. I can see `linkAttribute` confusing people as well, think "what is a 'link attribute"? Another alternative is `bindToAttribute` since what we're doing is essentially 2 way data binding?

## get and set
+1 to update and getting rid of `get`

## init
`default` or `defaultValue` get my votes, IMO they have the same semantics that @alexreardon above as being a fallback and are more in line with terminology elsewhere.

## type
I'm a fan of `coerce` or `preprocess` for the descriptiveness they bring. I think we need to have a bigger discussion of the behavior though like what happens when you bind to an attribute and it's always a string.

**Comment by treshugart** [comment]
#269 is related, but not required for this. Just mentioning to make sure you guys see it.

**Comment by marcoms** [comment]
The later comments in #304 propose that the prop.set is still to be called in cases where the property is set `null` or `undefined` (removing the corresponding attribute, if linked). I've been told that initial work has been started on this already, but I've raised this here for any potential further discussion.

**Comment by nicolasv** [comment]
Do the linked attributes follow the behaviour of the HTML spec for reflected attributes/properties?

- https://html.spec.whatwg.org/multipage/infrastructure.html#reflecting-content-attributes-in-idl-attributes
- https://html.spec.whatwg.org/multipage/infrastructure.html#enumerated-attribute

**Comment by marcoms** [comment]
The only difference I'm aware of is that the linked attribute will be removed when the property is set to `null`/`undefined`, instead of the attribute being set to `"null"`/`"undefined"`.

**Comment by treshugart** [comment]
@marcoms @nicolasv https://github.com/skatejs/skatejs/pull/334 is a WIP. It has some scope creep that I feel is necessary. See the PR for deets.

**Comment by treshugart** [comment]
> The only difference I'm aware of is that the linked attribute will be removed when the property is set to null/undefined, instead of the attribute being set to "null"/"undefined".

In that PR, this has been changed to be closer to the spec so that only `undefined` works. `null` now behaves like native. We must keep `undefined` because `delete element.property` doesn't trigger `set` in the property definition so there's no way for us to hook into that.

**Comment by nicolasv** [comment]
> In that PR, this has been changed to be closer to the spec so that only `undefined` works. `null` now behaves like native.

In the context of implementing a reflected property on an enumerated attribute (as per the spec), I can implement the majority of the logic for it in the `type` function, however, this part of the spec

> …on setting, the content attribute must be set to the specified new value.

which gives the `el.prop = null` → `prop="null"` behaviour, isn't doable since we end up calling `setAttribute` in the setter with the result of `type(value)` rather than `value` (here `type(value)` returns the invalid/missing default value).

**Comment by treshugart** [comment]
I thought about this last night @nicolasv. I think for the Skate properties that are invoked via the `skate.property()` method, that it's ok not be behave 100% to the spec. Developers will still be able to define their own property definitions.

We should take the good parts while discarding the bad parts. The only real bad part to me is that the spec allows for properties to become out of sync with attributes. This has some knock on effects that we do need to consider:

- What our API consumers see in dev tools may not be the actual representation of the element depending on where they're looking. This could lead to confusion. It certainly confused me when a checkbox's checked property didn't reflect in the attribute. The spec isn't always right in terms of easing developer friction.
- It can make DOM diffing much harder than it needs to be. If attributes and properties are always in sync, then you don't have to worry about diffing properties because what your element looks like (element name / attributes) is a correct representation of its state.

**Comment by treshugart** [comment]
Thinking that `get` should be reintroduced. For example, if you want to have a property that gets rendered as the content of a descendant that may become out of sync with the property, then you need a way to get at the source of truth. This is a use case for content editable, or things that may have other bindings applied to them that operate independently of the parent component like inputs.

```js
`<input value="${elem.prop}">`
```

When you go and get the value of the property, it will return you the internal value, but not the value that is stored in the input. If the user modifies it then it becomes out o sync. Being able to specify a getter that returns the value from the input solves this issue.

**Comment by treshugart** [comment]
I really like @marcoms suggestion about using `default`.

**Comment by treshugart** [comment]
Thinking that instead of `type` and `coerce` that we should have `serialize` and `deseriealize`. So that there is a clear path to and from attributes if linked. Otherwise, type can be used to enforce a property value.

Current functionality might look something like:

```js
properties: {
  prop: {
    attr: true,
    deserialize: Boolean
  }
}
```
