### ISSUE TITLE
Consider making attr default to true for properties.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#286]
In most cases my properties are always linked to attributes. There's some cases where you wouldn't want to do this, but I think those are the exception not the rule.

**Comment by bqx** [comment]
My gut feeling on this is that it would be better to be prescriptive about this. I think the principle of least surprise would have attr not default to true, even if you would set it in most cases.

**Comment by marcoms** [comment]
I agree with @bqx. I also have most properties bound to attributes, however I think the `properties` name would be a bit confusing, since attributes are always bound to properties (I think?) but not vice versa.

**Comment by treshugart** [comment]
Fair enough, we'll keep it as is :)
