### ISSUE TITLE
`attribute:` no longers triggers for every attribute

### ISSUE THREAD

**Issue by antitoxic** [skatejs/skatejs#288]
I observe a change in the behavior of `attribute:` property in latest skate. I only receive callbacks for `resolved` and `unresolved` attributes. I don't get a callback for `target` attribute.

**Comment by antitoxic** [comment]
It works back in 710b5c99345ac3df3c9cb3386a3e7d925b786c52 .

I use the dist/skate.js version. I don't have the ES6 stack.

**Comment by antitoxic** [comment]
I've downloaded the sources and did the setup (npm install). I have been testing commits since the one that worked.

This is the commit that broke the attribute triggering: https://github.com/skatejs/skatejs/commit/739dd8e80ec8b1423519677df522c3fcf7158957

I say broke but it might be a feature?

**Comment by antitoxic** [comment]
After setting up dev environment and running `npm run dist` on several commits I found that this is the commit that breaks tha `attribute:` triggering: 739dd8e80ec8b1423519677df522c3fcf7158957

Or is this a feature?

**Comment by antitoxic** [comment]
Seems like `triggerAttributesCreated` function was removed?

**Comment by antitoxic** [comment]
I get it that I can now do: 
```
        properties: {
            target: {
                attr: true,
                init: function (initialValue) {
                    console.log(initialValue)
                }
            }
        }
```

This however doesnt work when combined with https://github.com/skatejs/type-attribute

**Comment by antitoxic** [comment]
Specifically this doesn't work:

```js
skate('target', {
        type: attrTypeDef,
        properties: {
            target: {
                attr: true,
                set: function (newValue) {
                    console.log(newValue)
                }
            }
        })
```

**Comment by antitoxic** [comment]
Right, I'm closing this issue. It was my wrapper of `attribute:`. It took me a while. Damn.

Can I somehow subscribe to API changes? So I can receive them by mail?

**Comment by treshugart** [comment]
Hmm, I don't know much of a better way to subscribe to API updates other than to try and only use tagged versions. 0.14 will have a complete list of changes and an upgrade guide from 0.13. For the other versions you can filter GitHub issues, though that's not very convenient. It seems like you're developing off master. For that I can only recommend being across the issues and pull requests that are being published to that branch, though I don't recommend using master for this reason.

**Comment by antitoxic** [comment]
Being on master is sometimes the only way to have the fixes that affect my
current project.

Like the issue to do with Chrome not resolving. Tags/releases would
otherwise be better.

By the way, I love how the project I'm using Skate on is going. I have more
than 30-40 elements. All is well, all is clear and easy to get into.
Frontend frameworks are officially dead for me :)

I'm hugely interested in advocating/evangelising Skate on local level
Give me a shout if that's something you will also like.

**Comment by treshugart** [comment]
> Being on master is sometimes the only way to have the fixes that affect my current project.

Fair enough. If you have any suggestions to make this easier for you, feedback is welcome.

> By the way, I love how the project I'm using Skate on is going. I have more than 30-40 elements. All is well, all is clear and easy to get into.

That means a lot. Skate is very personal to me because it's the first open source project that I've done that I can say is helping *a lot* of people solve real world problems. Many thanks.

> Frontend frameworks are officially dead for me :)

I couldn't agree more. Tiny, focused modules are the future!

> I'm hugely interested in advocating/evangelising Skate on local level. Give me a shout if that's something you will also like.

I'd have to be an idiot to say no to that! Of course! Feel free to use us as a resource if you ever have any questions, too.

**Comment by antitoxic** [comment]
@treshugart My only suggestion that I can think of is opening a thread/issue that people can simply spit out information from what's going on. And ask questions. 

I know a django module (django-suit) that has a very broad ticket named "suggest packages for support" and people are shouting out names.

May be something similar to shout out changes in the API would be cool? I definitely feel the need of a discussion somewhere for best practises or at least "How do I do that with skate" kind of discussion.

**Comment by treshugart** [comment]
That's not a bad idea. Maybe creating an issue type of "discussion" for now. We have a "questions" type already where those can go.

**Comment by treshugart** [comment]
@antitoxic re:

> Can I somehow subscribe to API changes? So I can receive them by mail?

See #299.
