### ISSUE TITLE
RFC: Don't pass undefined and null values to property.type

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#293]
The function passed to the `type` property of a property object is typically used to coerce values to the desired type before giving it to the property's setter. In doing this, though, the recently added ability to pass `undefined` or `null` to a component's property to remove the corresponding attribute is lost, and JS types don't always return `undefined` when passed `undefined` (e.g. `Number(undefined) -> NaN`, `String(undefined) -> "undefined"`).

It is possible to get around this by wrapping each JS type in your own function:

```js
function type(fn) {
  return (value) => {
    if(value === undefined || value === null) return value;
    return fn(value);
  };
}

...

myProperty: {
  type: type(Number),
},
```

...However it is a bit of a hassle :)

Is there a use case for the user handling `undefined` or `null` specially (where you could otherwise use `false`)?

**Comment by treshugart** [comment]
Nice catch. I think this is something that would be handled in the setter which invokes the type function, before it invokes it. If `null` or `undefined`, then remove and return early.

**Comment by marcoms** [comment]
Sorry, not sure I understand. Do you mean manually calling `removeAttribute` in the property setter?

**Comment by treshugart** [comment]
This is where we currently are calling the `type` function: https://github.com/skatejs/skatejs/blob/master/src/lifecycle/properties.js#L59. I was thinking that it'd go somewhere above that. 

We'd have to do this to ensure that it doesn't trigger an attribute mutation: https://github.com/skatejs/skatejs/blob/master/src/lifecycle/properties.js#L76.

That function needs a little refactoring, but it shouldn't add much complexity to it.

**Comment by treshugart** [comment]
@marcoms PR'd in #304.
