### ISSUE TITLE
IE9, IE10: Object doesn't support this action

### ISSUE THREAD

**Issue by antitoxic** [skatejs/skatejs#294]
The error seems to be caused by:

```js
  function createDocumentObserver() {
    var observer = new MutationObserver(documentObserverHandler);
.....
```

Any remedies?

**Comment by antitoxic** [comment]
@treshugart this issue hits really production-readiness really bad.

**Comment by antitoxic** [comment]
`window.SkateMutationObserver` seems to be missing?

**Comment by antitoxic** [comment]
I dug into previous versions. Seems like there was a polyfill which is now missing?

**Comment by antitoxic** [comment]
The only way I am able to work in IE9 and IE10 is using https://github.com/webcomponents/webcomponentsjs/blob/master/src/MutationObserver/MutationObserver.js

**Comment by treshugart** [comment]
The mutation observer polyfill has been decoupled into https://github.com/skatejs/polyfill-mutation-observer. Seems I forgot to add that to the change log. Will raise an issue for that.

The reasoning behind thisbisbthat some people already have a polyfill orbpreferbto include their own. We recommend using the Skate one for performance but it's up to the consumer now.

This should fix your issue.

**Comment by antitoxic** [comment]
Good morning and thank you for the answer. However the Skate polyfill is not working for me:

IE9, IE10 mode say:
```
SCRIPT5002: Function expected
```

pointing to:

```js
 var batchEvents = (0, _debounce['default'])(function () {
```

**Comment by antitoxic** [comment]
The above error happens when I use the `lib/index` version.

I just tested with `dist/skatejs-polyfill-mutation-observer.js` and it's working.

I don't know why though.

**Comment by treshugart** [comment]
Interesting. I'll have a look when I get in to work. You could try using
the dist version or try recompiling the source yourself.

On 27 Aug 2015 07:55, "Anton Stoychev" <notifications@github.com> wrote:
>
> The above error happens when I use the lib/index version.
>
> I just tested with dist/skatejs-polyfill-mutation-observer.js and it's
working.

**Comment by antitoxic** [comment]
I know why now.

This:

```js
_interopRequireDefault(obj) { return obj && obj.__esModule ? obj : {
'default': obj }; }
```

I'm using webpack which is a really cool loader and build toolbthat makes
development a breeze. Ideal for a combo with Skate. It has a require
mechanism with its own mechanics which are explicit and don't include
wrapping require in a wrapper and passing argunents.

I will close this issue and open a new one for supporting webpack.

**Comment by treshugart** [comment]
I know what Webpack is; I find Galvatron much simpler FWIW. However, I don't think that's your issue. The code you pasted is actually generated by Babel. Which method are you using to include Skate? Is it `src/`, `lib/` or `dist/`?

**Comment by antitoxic** [comment]
I've tried the `lib/index`  and this is where it says `SCRIPT5002: Function expected`, pointing to
```js
_interopRequireDefault(obj) { return obj && obj.__esModule ? obj : {
'default': obj }; }
```

The `dist/` version works. 

*PS:* I didn't mean to push webpack. I'm just as excited about it as about skate. A lot for both. Webpack's ridiculously effort-taking to config. I know this. I'm only using it because I can group styling, skate templates, svgs togther and get rid of my backend asset management.

**Comment by treshugart** [comment]
> PS: I didn't mean to push webpack.

Oh, no worries at all. Webpack is cool. 

I'm interested in trying to solve why `lib/` isn't working. We're using the same tooling at work and one of the teams uses Webpack to consume the UMD source that we compile using the same technologies without a hitch. Could be the version of Babel, maybe, or that a dependency isn't properly defined somewhere (I doubt that, but possible).

**Comment by antitoxic** [comment]
Here's a full list of used packages on my setup:
http://pastebin.com/b4TPCHE5

Generated by `npm shrinkwrap`,
