### ISSUE TITLE
What is the recommended way to wait for descendant custom elements to be upgraded?

### ISSUE THREAD

**Issue by antitoxic** [skatejs/skatejs#297]
Reading the docs: 

> ready (callback)
>
>Executes callback when all components are loaded and all elements are upgraded. This comes in handy inside a component when it requires descendants to be upgraded before it uses them.

This seems to be the only way? By "all elements" is it meant all descendant elements or all elements on the page?

My usecase: I'm must take a measurement of the dimensions of an descendant custom element in order to apply some css workarounds on parent.

**Comment by treshugart** [comment]
You should be able to do that in `attached`. In fact, in order for something to have layout it must be attached so you'd need to do it there anyways.

**Comment by treshugart** [comment]
I'm assuming this related to #296 so closing. If not, feel free to reopen.

**Comment by antitoxic** [comment]
Cool, `attached` works. It wasn't related to #296 but it is now :) . I was going even to reference it here myself for future reference to other people reading.

**Comment by treshugart** [comment]
:+1:
