### ISSUE TITLE
Switch currentTarget and delegateTarget so that the event object is similar to jQuery's

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#302]
When originally naming this, I named it to be similar to jQuery, however, jQuery goes against the grain and rewrites `currentTarget` to mean what we are calling `delegateTarget`. I'd like to avoid this confusion and give it a name that's a little bit more appropriate.

**Comment by a-ignatov-parc** [comment]
Why not to use `e.currentTarget`? Most of the developers are familiar with this name and will be easier to understand what it is for without digging docs

**Comment by treshugart** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget):

> "It always refers to the element the event handler has been attached to..."

For a comparison of native vs jQuery see [this bin](http://jsbin.com/litupa/5).

> Most of the developers are familiar with this name and will be easier to understand what it is for without digging docs.

I presume what you mean by "most of the developers" are people who use jQuery. As someone who has always preferred native to jQuery, I find the fact that jQuery overwrites `currentTarget` to be the element that matched the selector odd since it contradicts what the spec says `currentTarget` should be.

**Comment by a-ignatov-parc** [comment]
Hmmm... very interesting. But jquery doc says:

> The current DOM element within the event bubbling phase.

Which is exactly (almost) what MDN says:

> Identifies the current target for the event, as the event traverses the DOM.

Also if you change delegate event handlers to normal `currentTarget` begin to work properly http://jsfiddle.net/80g1woco/1/

**Comment by a-ignatov-parc** [comment]
Ahh sorry. i misunderstood this issue.

**Comment by a-ignatov-parc** [comment]
w3c spec does not provide api to delegate events. So i think it is normal for jquery (and skatejs) to mask event delegation as direct bindings through `currentTarget`.

**Comment by treshugart** [comment]
That's actually a pretty good argument for using `currentTarget`. It's worth considering anyway.

**Comment by marcoms** [comment]
I suppose `currentTarget` could be retrieved thought `this`, no? Even so, overriding a standardised property I'm not so comfortable with. I think it could be quite confusing to those expecting standard behaviour without reading the docs.

**Comment by treshugart** [comment]
After thinking about this I think @a-ignatov-parc is probably right. I think it's a good design choice to make it so the developer doesn't have to think about whether or not they're delegating. If you want to get the host element you can use `this`.
