### ISSUE TITLE
Streamline lifecycle callbacks.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#337]
This has been created to collate all the changes that have been made around the lifecycle and to formalise the final API.

There have been several issues in the past that we have discussed and really hammered the API into what it is now. For posterity, this issue serves as the source of truth for this release and contains the rationale behind the current lifecycle operations.

## New Lifecycle

The Skate lifecycle now does the following:

1. Ensure attribute methods trigger attribute changes synchronously
2. Ensure the prototype chain is set up
3. Set up property definitions
4. Bind event listeners
5. Invoke the `created()` callback
6. Invoke the `renderer()` callback with the result of the `render()` callback
7. Invoke this entire lifecycle being described here on all descendants starting with the furthest descendant first
8. Initialise properties, ensuring setters are called now that descendant DOM has been set up
9. Invoke the `ready()` callback
10. Mark the host element as resolved
11. Invoke the `attached()` callback if the element is in the DOM

The callbacks described above are:

1. `created()` called once when the element is created
2. `renderer()` called to render the result of the `render()` callback to the element
3. `render()` returns a rendered value that is passed to `renderer()`
4. `ready()` called once on the host when all descendant DOM has been initialised

*The `attached()` and `detached()` callbacks have not been changed.*

##### Definitions in `<head>` or at the top of `<body>` (before HTML content)

If you put your component definitions at the top of the page, they will be upgraded as they are encountered by the browser's rendering engine. Meaning no matter what order you specify your component definitions a parent component will be upgraded before its descendants. For example:

```html
<x-parent>
  <x-child>
    <x-descendant></x-descendant>
  </x-child>
</x-parent>
```

In the HTML example above, `x-parent` would be upgraded, then `x-child` and finally `x-descendant`. If `x-parent` or `x-child` need something from one of their descendants they're out of luck.

##### Definitions at the end of `<body>`

You get something completely different if you put your definitions at the bottom of the page. In that case, your components are initialised in the order which your definitions are registered. Meaning if you register them in this order:

1. `x-child`
2. `x-descendant`
3. `x-parent`

Then your elements will be upgraded in that order. This is very unpredictable.

##### Assumptions

What Skate does is assume that you're properly declaring your dependencies. Meaning if `x-parent` needs `x-child` then it will somehow ensure `x-child` is registered before itself. This can easily be done with any module system (AMD, CommonJS, ES2015, etc.).

If you do this then no matter where you put your definitions Skate can descend into a DOM tree and ensure that descendants are initialised before parents. This means you can write predictable compound components without having to worry about browser semantics and inconsistencies between them.

### 1. Synchronous attribute changes

Previously in polyfill land, we were using mutation observers to listen for changes to attributes. This causes attribute changes to be triggered asynchronously which is inconsistent with native behaviour which is synchronous. When writing tests for our components, the tests would quickly become an unwieldly mess of async code that used `setTimeout()`. In order to make this consistent and easy to work with both inside tests and in consumer code, we chose to override `setAttribute()` and `removeAttribute()` to provide synchonous behaviour.

The only current drawback is that modifying `element.attributes` directly doesn't trigger updates which means it may not work in some debuggers. We have been talking about ways we could implement this, but currently it is not supported.

If your browser supports native custom elements, then everything works as normal.

### 2. Prototype chain setup

In polyfill land, there isn't a good way to extend a native DOM element with a custom DOM element. For this reason, when we are not using native custom elements, we copy the methods from the user-defined prototype to the element instance.

The prototype chain behaves normally if native custom elements are supported.

### 3. Setup property definitions

We set up property definitions early so that we can capture the values of existing properties and do any sort of setup that we need to do early on before the rest of the lifecycle is invoked.

### 4. Bind event listeners

It's ideal to bind your event listeners as early as possible so that you can respond to events as early as possible.

### 5. Invoke the `created` callback

The created callback is intended to do any sort of setup that cannot be described in any of the other options, but before the component is rendered and its descendants may be initialised.

### 6. Invoke the `renderer()` callback with the result of the `render()` callback

The `renderer()` callback exists to decouple the rendering of the component in the DOM and the actual rendering of what the template should look like. This means that you can change how your components are rendered without changing the callback that tells the renderer what it should look like.

The `render()` callback exists to provide the `renderer()` with what the component should look like given its current state. Since the state is passed in as an argument, it can be the element itself, or a raw object describing the state that you want to render. This means that you can very easily server-side render your components without invoking the rest of the element lifecycle keeping the footprint that must be supported on the server in order to render your component very minimal.

### 7. Initliase descendants starting with the furthest one first

Once we've rendered the component, we should ensure all descendants are synchronously initialised so that if the consumer is interacting with your component programmatically, they can be sure that everything has been set up. This helps to streamline the building of very complext components (e.g. page layouts) using custom elements predictable.

### 8. Initialise properties

This step consists of invoking the property setters that have been defined as `properties` with the initial value of the property. This means that if you have DOM mutations happening on your setters that doing so after descendants have been initialised that you can be 100% sure that you are working with the DOM that you expect to be working with.

### 9. Invoke the `ready()` callback

Once we have initialised properties, any setup that needs to be done *after* descendants have been initialised can be done here.

### 10. Mark the host element as resolved

In this step we removed the `unresolved` attribute from the host element (if it has been provided) and add the `resolved` attribute. This assists in building components that can minimise the amount of jank or FOUC that occurs between the time the element is not upgraded to when it is finally upgraded, if there is a delay.

**Comment by alexreardon** [comment]
Looks great @treshugart

**Comment by bqx** [comment]
Is there another copy of the lifecycle documentation kept up to date at the moment? I believe point 2 (Ensure the prototype chain is set up) was removed in #352 .

**Comment by treshugart** [comment]
@bqx updated in 51b560c.
