### ISSUE TITLE
Make `data-skate-ignore` behave consistently

### ISSUE THREAD

**Issue by joscha** [skatejs/skatejs#339]
When using `data-skate-ignore` it behaves differently depending on the target browser (it's ignore in Chrome for example). In order to provide to provide a more consistent behaviour, this should be fixed.

More information can be found here: https://bitbucket.org/atlassian/aui/pull-requests/1575/

**Comment by treshugart** [comment]
@joscha what are your thoughts regarding this if we do https://github.com/skatejs/skatejs/issues/456. Thoughts on that one welcome, too.

**Comment by joscha** [comment]
Removing sounds good - closing this then!
