### ISSUE TITLE
api/property.js still being referenced

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#346]
Tried building a project today with skate@master and it breaks trying to reference src/api/property.js (recently split into modular chunks, as I'm sure you're aware). Looks like https://github.com/skatejs/skatejs/blob/master/src/index.js#L5 is the offender.

**Comment by treshugart** [comment]
That's probably because we're using node's `require()` semantics to load the `api/property/index.js` file via `api/property`. I'll update this to load all the files directly.

**Comment by treshugart** [comment]
Fixed in 6e56e3435c42ab1519cec63a692a15e622d6f367. Let me know if this is still happening.

**Comment by marcoms** [comment]
all good :+1:
