### ISSUE TITLE
Remove sync init of descendants from a host component.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#351]
This was done in order to try and bring some semblance of order to now native custom elements behave, which is all over the place. However, if you follow some simple best-practices, it's possible to avoid it altogether so we're going to remove this and eventually form some documentation around the best way to build components using different techniques. Removing this hardly imposes any limits on the user, it just means that you can't querySelector from inside a host and expect a descendant element to be initialised yet.

**Comment by marcoms** [comment]
"querySelector from inside a host" - does this extend to all stages of the host's lifecycle? Will `skate.ready` be reintroduced?

**Comment by treshugart** [comment]
Currently, without forcing init on descendants, you can still find them and set properties / attributes on them and they will get the changes no matter what. You just can't do stuff with their eventual prototype because they may or may not have been upgraded yet. This was always the case. To this effect, not much is actually changing, though we should provide something like `skate.ready()` to call something when an element is eventually ready so that in edge-cases you can call prototyped stuff on an element.

**Comment by treshugart** [comment]
@marcoms implemented in #352.

**Comment by marcoms** [comment]
But doesn't the revised lifecycle order described in #285 push property initialisation after `created`? Components designed with this assumption might break if their property setters are called *before* `created`, no?

**Comment by treshugart** [comment]
If you're only interacting with the descendant custom element and not its
descendants (which we should never be doing, that's the responsibility of
the descendant host) then it'll work exactly as before. The prototype bug
existed before, the removal of this.
