### ISSUE TITLE
Public API for rendering / re-rendering a component.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#354]
This is useful if you are taking a more functional approach with your custom element and want to re-render when something changes. This wouldn't be very useful if you're rendering once and using setters to mutate the rendered DOM because this would just re-execute the render lifecycle on the element.

Proposed API:

```js
var hello = skate('x-hello', {
  render: function (props) {
    return `Hello, ${props.name || 'World'}!`;
  }
});

// This is already part of the API. This would create the component, set some
// props and render as part of the normal lifecycle.
// <x-hello>Hello, Wilson!</x-hello>
var hi = hello({ name: 'Wilson' });

// Sets a new value to be rendered with.
hi.name = 'Bobbo';

// This is the new API function that re-renders the element.
// <x-hello>Hello, Bobbo!</x-hello>
skate.render(elem);
```

**Comment by alexreardon** [comment]
Very cool! However, would this be confusing as the standard behaviour is that arguments to the skate constructor set's props?

**Comment by treshugart** [comment]
Yeah, that's standard behaviour. The only addition here is `skate.render()`.

**Comment by alexreardon** [comment]
is `state` = `props`?

**Comment by treshugart** [comment]
It's essentially the element instance, but the idea of the render function is to treat the incoming object as state / props (in Skate they're considered the same thing).

**Comment by alexreardon** [comment]
For consistence I think using the word `props` would be best

```
var hello = skate('x-hello', {
  render: function (props) {
    return `Hello, ${props.name || 'World'}!`;
  }
});
```

I like the idea of a new render function that takes `props` as it's arguments. When would the `render` function be fired in the lifecycle? Does it open up the possibility of being confused with `template`?

**Comment by treshugart** [comment]
@alexreardon https://github.com/skatejs/skatejs/issues/337. Added `render` and `renderer` in that. No more `template`.

**Comment by alexreardon** [comment]
:+1:

**Comment by alexreardon** [comment]
Looks very cool

**Comment by bqx** [comment]
Nice. I actually thought you could do this already. 

Is it possible to refer to the `render` function from inside another lifecycle callback? (e.g. inside an event or property handler) or would you have to use `skate.render()`? i.e.:

```
skate('x-el', {
  render: function (el) {
    ..
  },
  events: {
    click: function (e) {
      // Do I have to use skate.render() instead of this.render() here since `this` is bound to the element?
      skate.render({ prop: 'value' });  
    }
  }
}
```

**Comment by treshugart** [comment]
@bqx `skate.render()` is preferable because it is a clear and consistent API path for a consumer to re-render a component. You could theoretically use the functions from your component definition but you'd have to link `render` and `renderer` together yourself. The `renderer` is now responsible for calling `opts.render(element)` to get the rendered stuff (`opts` is passed in as the second arg instead of the `render()` function).

This does mean that you can specify a `render()`, `renderer()` or both. However, in the future, if you want to be able to render your stuff server-side with as little dependencies as possible (Skate will provide something for this), you'll have to implement a `render()` function.

**Comment by marcoms** [comment]
README.md:

    render: function (elem) {
        return '<shadow><dom>' + elem.innerHTML + '</dom></shadow>';
    },

Should this be rewritten? I'm worried that readers might be mislead by this example into thinking that shadow DOM is supported by default and would be automatically handled by skate.

**Comment by treshugart** [comment]
@marcoms yeah, that's probably a good idea.

**Comment by marcoms** [comment]
It turns out that `innerHTML`/`textContent`/... are set to empty strings when `render` is executed (assuming that's intentional), so it looks like the `render` function will instead have to be demonstrated through element properties instead.

```js
return elem.firstName + " " + elem.lastName;  // perhaps?
```

---

This is probably unrelated, but (above the `render` example in README.md):

```js
  // All properties that you define in the component definition will be
  // available on the element. This means that if you override the innerHTML
  // property that the original value of that property will be available for
  // you to use here.
```

Forgive me, I don't really understand the meaning of this paragraph... Does it have any significance to the missing `innerHTML` described above?

**Comment by treshugart** [comment]
@marcoms `innerHTML` and `textContent` should be available. Are you able to write a test case reproducing the issue?

**Comment by marcoms** [comment]
http://jsfiddle.net/r3y62zLw/ (see console output)

I thought this was supposed to happen to prevent multiple calls to `this.render` duplicating the contents of `innerHTML`

**Comment by treshugart** [comment]
@marcoms I need to investigate why it's not the expected value in `render()` without overriding it. See http://jsfiddle.net/treshugart/r3y62zLw/1/. That will give you your expected result and won't duplicate `innerHTML`.
