### ISSUE TITLE
Add change() property callback that only gets fired when the property changes.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#362]
### Use case

This is especially handy when wanting to re-render using `skate.render()` when the property changes, but not wanting to do it whenever `set` is called because `set` is called when the element is initialised and every time it is set, even if it is the same value.

```js
skate('my-element', {
  properties: {
    textContent: {
      change: skate.render
    }
  },
  render (elem) {
    return `Hello, ${elem.textContent}!`;
  }
});
```

### Signature

It should receive the same arguments as `set` and be called `change`.

### Tests

- is not called if the property has no default value, when it is set up
- is not called if the property has a default value, when it is set up
- is not called if the property has a default value and it does not change
- is not called if the property value does not change
- is called if the property has no default value and it is set
- is called if the property has a default value and it is set to a different value
- is called if the property value changes

**Comment by bqx** [comment]
It seems this is a convenience function only - nothing is stopping the user from doing the same check for `changeData.oldValue !== change.newValue` inside the the setter if they need this kind of behaviour. Is it really worth providing the convenience here?

**Comment by joscha** [comment]
why is `is not called if the property has no default value`? It is still a change, or no?

**Comment by joscha** [comment]
those two:
`is not called if the property has no default value`
and
`is not called if the property has a default value`
kinda sounds as if its never called?

**Comment by treshugart** [comment]
@joscha Reworded. I'll update the test descriptions to suit.

**Comment by treshugart** [comment]
Ended up removing the spiked callback.
