### ISSUE TITLE
Investigate why innerHTML is empty in render() when it's not overridden.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#374]
See http://jsfiddle.net/treshugart/r3y62zLw/.

**Comment by antitoxic** [comment]
btw, rawgit link is giving 404

**Comment by treshugart** [comment]
Working in http://jsfiddle.net/treshugart/r3y62zLw/2/. Similar, but versions have changed. In the previous version used, if `render` was provided it would zero out the innerHTML before calling the `render` function and using its return value.

Since then the `render` function is simply a function that mutates the element rather than one that returns a string. The old behaviour has moved into `sktate.render.html(fn)` and can be reproduced there because it does the same thing and it is still in fact a bug.

Fixing :)
