### ISSUE TITLE
Error loading skatejs after update

### ISSUE THREAD

**Issue by ilyadoroshin** [skatejs/skatejs#399]
```
ERROR in ./~/skatejs/lib/api/render/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../global/registry in /Users/idoroshin/Work/InnovationalFair2015/Aplus-webpack/node_modules/skatejs/lib/api/render
 @ ./~/skatejs/lib/api/render/index.js 3:4-74
```
88634f428aba0e07778f39c74da142e468524c53

**Comment by ilyadoroshin** [comment]
or is that my webpack config?

**Comment by ilyadoroshin** [comment]
5336c9defc8e1e25715e4a6dc724a9894733b2bd works with no error..

**Comment by treshugart** [comment]
Interesting, I'll have a look.

**Comment by treshugart** [comment]
Should be fixed in e43ac38.

We moved `src/api/render.js` to `src/api/render/index.js`. The relative path to `src/global/registry.js` stayed the same and our source tracer still picked it up. I updated the path to work for stuff picking it up from `lib/`.

Let me know if it doesn't work.

**Comment by ilyadoroshin** [comment]
@treshugart that helped! not ecab50e though, but latest d1e9e5bfad951ba3b50f64e6cffa6eb1187a3cc8
 thanks a bunch! :beers:

**Comment by treshugart** [comment]
No worries! Happy you're using Skate!
