### ISSUE TITLE
Ensure master works with other versions on the same page.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#416]
Would be nice to write a test for this since it's API.

**Comment by joscha** [comment]
:+1:

**Comment by treshugart** [comment]
Reopening because this still needs to be done. The recent change in master caused breakages on my machine (and possibly others) due to the way the test bundle creates the module hashes, so that will need to be re-implemented so that it doesn't do that.

**Comment by treshugart** [comment]
It's suggested we test against every minor dev version (0.x) and then test every major after a 1.0 is cut.

**Comment by treshugart** [comment]
Fixed in #501.
