### ISSUE TITLE
Reviewing the defaults set in skate.property.*

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#423]
A couple of the defaults set by skate.property.* stick out to me:
- `default` set by default (`false`, `0`, `""`)

I think this should be left to the developer to decide whether a property has a default value or not (if no default value is desired, then the user would have to define `default: undefined` - not practical IMO)

- `attribute: true` by default

Whilst not the same context as `skate.property.*()` are opt-in, wasn't the general understanding in #286 to have it default to `false`?

**Comment by treshugart** [comment]
1. This is standard behaviour for boolean attributes that are linked to properties. Other types might benefit from this, though. However then that makes it different from boolean properties that aren't linked to attributes. I'm not sure having the complex logic in there is better. I think if we do this we should make it enforce the type unless `undefined`.

2. Yeah, we basically just forgot to do this. We should action this as it still trips me up. Do we think it'd be worth creating corresponding `skate.attribute.*` for auto-linking? Probably not. Just thinking out loud.

**Comment by marcoms** [comment]
I hadn't thought about the fact that boolean attributes are by default false. In that case it makes sense to have the default set for linked boolean properties, however I don't think that other types should have defaults set, especially since for example, a value of 0 could definitely mean something significant in the case of a number property.

>if we do this we should make it enforce the type unless undefined

Through `type`? I thought this was done anyway...

>corresponding skate.attribute.* for auto-linking

I think it would be clearer to just have the user set `attribute: true` manually in the object passed to `skate.property.*` for such a minor difference

**Comment by treshugart** [comment]
> however I don't think that other types should have defaults set

I agree with you here. I'll mess with altering these and see what happens.

> Through type? I thought this was done anyway...

It *may* not be necessary but it's a nice hook to have for type checking and coercion. For example, if you're overriding existing properties and you want to ensure the value is compatible with the property.

> I think it would be clearer to just have the user set attribute: true manually in the object passed to skate.property.* for such a minor difference

+1

**Comment by treshugart** [comment]
I actually think it's worth considering your points for number 1 (cept on the booleans like you said). I did commit the change for attributes not being linked by default but will leave this open for the other one.

**Comment by treshugart** [comment]
Implemented @marcoms' first point in #435.
