### ISSUE TITLE
Using 'this' inside the events object.

### ISSUE THREAD

**Issue by davidbehrend** [skatejs/skatejs#432]
I've just spent my first day with skate and I'm loving it so far.
I've just hit my first ??? moment however in regards to the use of `this` inside the events object.

The docs suggest I am able to this :
```javascript
skate('my-element', {
  events: {
    click: function() {
      // Refers to the component element (according to docs)
      console.log(this); // <- undefined
    }
  }
});
```
However `this` is undefined.
I gave ~~es6~~ es2015 arrow functions a go, but the same result...
```javascript
skate('my-element', {
  events: {
    click: () => {
      console.log(this); // <- undefined
    }
  }
});
```

Can anybody point me in the right direction?

**Comment by cyberdash** [comment]
It seems like this is working on skate master: http://jsbin.com/pimusaqeno/1/edit

Which version of skate are you using?

**Comment by davidbehrend** [comment]
"skatejs": "^0.13.15"

**Comment by davidbehrend** [comment]
Using 0.13.15 your jsbin logs `Cannot read property 'textContent' of undefined`

**Comment by treshugart** [comment]
In 0.13 we pass the element as the first argument. See the `events` object in the [0.13 usage docs](https://github.com/skatejs/skatejs/tree/0.13.x#usage).

This has been overhauled to be closer to a normal event handler where you can use `this`. FWIW we'll be pushing a 0.14 release soon (maybe today or tomorrow).

**Comment by davidbehrend** [comment]
Thanks for the quick replies and a huge thanks for all the work you've done on skate. It's the first time I've actually felt like web components were something I could actually use in production.

**Comment by treshugart** [comment]
You don't know how much it means to us that you say that. Thank you! Can I quote you :) ?

Also, is it okay if we close this issue? Cheers.

**Comment by davidbehrend** [comment]
My pleasure.
Feel free to close the issue and quote me as you please. = )

The project popped up on my radar some time ago (probably from SydJS ?), but it felt a little too early to dive in. It wasn't until the recent Web Platform Podcast reminded me I should take another look.

**Comment by treshugart** [comment]
Thanks again and glad you did take another look! Feel free to leave feedback as you use it.
