### ISSUE TITLE
Review skate.properties.* definitions and make a call on their API.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#433]
Currently the `skate.properties.*` definitions are objects. They can be composed into new objects to modify their functionality:

```js
properties: {
  test: Object.assign({ attribute: true }, skate.properties.boolean)
}
```

Alternatively, we could allow composition through a function:

```js
properties: {
  test: skate.properties.boolean({ attribute: true })
}
```

This would require that we do the composition internally, but that's not necessarily a bad thing because:

- `Object.assign()` is ES2015 only and we could hide that abstraction
- It requires the user to write less code
- It ensures that our object definitions are *not* mutated, and  composed every time

However there's some downsides:

- `Object.assign()` has it's own caveats in that it only "assigns" own enumerable properties; it doesn't copy accessors. See [the docs](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) for more info.
- If they want to get around the caveats, they've got to do the same thing as we did in the first example, but they'd use the return value of the function call instead.

**Comment by marcoms** [comment]
Another issue with a the user manually invoking `Object.assign` (as a quick replacement for the former functional style) to extend the defaults is that it is impossible to overwrite a value such as `default` without cloning the object to prevent permanently tainting the skate API

```js
skate.properties.number;  // {..., default: 0}

---

Object.assign({default: 24}, skate.properties.number);  // {..., default: 0}  nope

---

Object.assign(skate.properties.number, {default: 24});  // {..., default: 24}
skate.properties.number;  // {..., default: 24}  nope

---

let clone = Object.assign({}, skate.properties.number);
Object.assign(clone, {default: 24});  // {..., default: 24}
skate.properties.number;  // {... default: 0}  phew!
```

>Object.assign() has it's own caveats in that it only "assigns" own enumerable properties; it doesn't copy accessors. See the docs for more info.

When would an accessor be used in a properties object?

**Comment by treshugart** [comment]
> When would an accessor be used in a properties object?

It's just possible with JavaScript, but not a wide use case so ignoring it.

I've made the appropriate changes and have also removed the `float` type as it does the same thing as `number`. I've also made it so that these built-in types allow `undefined` as a valid value which removes the attribute / property value if linked and makes it so that there is no default value (which they can still specify if they want).

**Comment by treshugart** [comment]
@marcoms would you mind giving the code a review?

**Comment by marcoms** [comment]
lgtm

**Comment by marcoms** [comment]
One thing to be aware of is `NaN` values for numerical properties, which would either be passed explicitly (for whatever reason) or through malformed input to `Number()`. From what I've seen, a lot of standard numerical HTML attributes just silently ignore the input when assigning the property (the attribute just coerces it to a string), however the `<meter>` element throws an exception when assigning NaN to its properties:

```js
> meter.max = NaN
VM319:2 Uncaught TypeError: Failed to set the 'max' property on 'HTMLMeterElement': The provided double value is non-finite.
```

All options of either silently ignoring, silently assigning, or throwing an exception, could be considered undesirable in many cases, so its just a matter of choosing the most predictable option :/

**Comment by treshugart** [comment]
@marcoms that's a good point. I'd say that if the user wants to throw an exception on `NaN` values, then all they need to do is something like:

```js
properties: {
  max: skate.properties.number({
    coerce: function (value) {
      if (isNaN(value)) {
        throw new Error('value is NaN');
      }
    }
  })
}
```

Alternatively maybe we think about providing a `check` hook or something that is called post `coerce` on setting the property value that is responsible for checking to make sure the value is sane.

**Comment by treshugart** [comment]
Going to merge this as is for now since whatever we do will be additive but feel free to post further comments.
