### ISSUE TITLE
Backport property fix from master

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#436]
With the 0.14 release, two elements could have their properties setter called with an element reference other than its own (see https://gist.github.com/marcoms/91f49e8047b2ed9752fc)

From testing with master, I believe this has been fixed since 0.14 in 1684cf3337aceceb754b1a306c0c141ac641575e. The bug is pretty fatal, so the fix should probably be backported as 0.14.1

**Comment by treshugart** [comment]
This was because the `assign` function was bound with an object that isn't re-created every time and thus shared. Major oversight. 0.14.1 was just released :)
