### ISSUE TITLE
Increase number of tested browsers in Sauce labs.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#457]
Probably good to go as far back as we possibly can. At the very least we could assess whether or not we should fix any failures in older browsers that may still be getting a lot of use.

**Comment by joscha** [comment]
How far back do we want to go?

**Comment by treshugart** [comment]
I'd say we should get all major mobile browsers on there as a *must*.

We should probably try to do at least the last 5 versions of FF and Chrome. It'd be nice to get the latest Opera (if Sauce has it yet) and Safari 7 (not sure how old that is off the top of my head).
