### ISSUE TITLE
Skatejs TodoMVC example dom-diff

### ISSUE THREAD

**Issue by antitoxic** [skatejs/skatejs#461]
I'm looking at the example of how to use skate with dom-diff: https://github.com/skatejs/todomvc/tree/skatejs/examples/skatejs-dom-diff

Seems like this is using React? At least the dist version mentions it.

If a developer uses React, what are the benefits of including skate?

**Comment by treshugart** [comment]
Documented in all the places where the `React` variable is used that it's not actually React, but for Babel's default transpile from JSX to `React.createElement()` calls:

- https://github.com/skatejs/todomvc/tree/skatejs/examples/skatejs-dom-diff#implementation
- https://github.com/skatejs/todomvc/blob/skatejs/examples/skatejs-dom-diff/src/todo-app.js#L110
- https://github.com/skatejs/todomvc/blob/skatejs/examples/skatejs-dom-diff/src/todo-person.js#L14

**Comment by antitoxic** [comment]
Thank you.
