### ISSUE TITLE
"events" property not working properly in IE9, with selectors having high specificity

### ISSUE THREAD

**Issue by hanhpho** [skatejs/skatejs#466]
In skatejs' ``events`` property, when using IE9, we create a clone of the element to do the selector match

```
exports['default'] = function (element, selector) {
    if (hasNativeMatchesSelectorDetattachedBug) {
        var clone = element.cloneNode();
        document.createElement('div').appendChild(clone);
        return nativeMatchesSelector.call(clone, selector);
    }
    return nativeMatchesSelector.call(element, selector);
};
```
This will work fine with:
``` 
events: {
    "click .child": foo
 }
```
... but won't with:
``` 
events: {
    "click .bar .child": foo
}
```

because the parent node of the clone will never match with ``".bar"``, so ``nativeMatchesSelector.call(clone, selector)`` will return false

**Comment by treshugart** [comment]
Closing as `events` is being removed in 1.0. The way to bind events now is by using the `on*` syntax in `render()`.
