### ISSUE TITLE
Remove ability to bind more than one component to a single element.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#475]
For legacy purposes, Skate has supported binding multiple components to a single element (because through custom types you can use class / attribute names).

There's three major reasons this should be removed so that only one component can be bound to a single element instance:

1. It deviates too far from the spec.
2. It creates ambiguity.
3. Performance

Though performance is currently good, this will make it consistently good when searching for components for a given element in polyfill land.

**Comment by jpnelson** [comment]
I take it this means that support for class and attribute bindings will be removed?

Is there an alternative way to "enhance" elements, or do you think that this is an anti-pattern?

**Comment by treshugart** [comment]
It just means that you won't have more than one component bound to an element instance. You can still have custom bindings, but core-skate is just becoming more inline with the current state of the spec.
