### ISSUE TITLE
Make event handlers have the same signature as the rest of the lifecycle callbacks.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#477]
This is so that everything is consistent across the board. The event handler signature currently maps to the native `addEventListener()` format.

The proposed format is:

```js
function (elem, data) {}
```

Where:

- `elem` used to be `this`, the element
- `data` is the event object, or `e` (no changes in argument type, just moved one position to the right)

It's either we do this, or make all the other callbacks consistent with these. This would mean that all lifecycle callbacks use `this` instead of an argument:

```js
skate('x-tag', {
  render () {
    skate.vdom.text(`Hello, ${this.name}!`);
  }
});
```

**Comment by marcoms** [comment]
Makes sense, +1

>or make all other callbacks consistent with these

To match the way we used to .bind() callbacks to the element?

**Comment by treshugart** [comment]
> To match the way we used to .bind() callbacks to the element?

Yup. However, if we did this, we may want to discuss doing what they're proposing in the custom element [contentious bits](https://github.com/w3c/webcomponents/wiki/Custom-Elements:-Contentious-Bits#symbol-named-properties-for-lifecycle-hooks).

Basically this would change to:

```js
skate('my-element', {
  prototype: {
    [skate.symbol.created] () {
      this;
    }
  }
});
```

Which kinda sucks for people using ES5 because they have to do something like:

```js
var Ctor = skate('my-element', {});
Ctor.prototype[skate.symbol.created] = function () { this; };
```

Either that or we'd fallback to using a unique string identifier like `skateCreated` or `_createdCallback`.

**Comment by treshugart** [comment]
That said, I'm not too worried about changing this right now even if it seems like they're pretty solid on doing that. Even if they change it, we just update it internally in Skate and our API doesn't change. It's unlikely that we'll ever have to worry about name conflicts for the non-prototype members on our definitions.

The best thing the user would get out of us doing that is a slightly cleaner-looking class-based component:

```js
skate('my-element', class {
  [skate.symbol.created] () {}
});
```

Instead of:

```js
skate('my-element', {
  static created (elem) {}
});
```

**Comment by treshugart** [comment]
This is not necessary if #510 is a go.

**Comment by treshugart** [comment]
Going to do #510 instead.
