### ISSUE TITLE
Incrementing the global version spec to be unique to every release defeats the purpose of sharing code.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#498]
I checked out 43e9dad2ff407313bb1def382f869e28b04965cc and ran tests and they fail on a fresh NPM install.

The culprit seems to be the `skatejs-types` need to be updated. This is kinda besides the point as this still needs to happen, but it brought to my attention the recent change to the shared vars version. 

I noticed that the shared vars version was always being incremented which is a no no if you care about performance when multiple versions are on the page. It also helps to keep Skate in better alignment with the spec as registries are shared in native, so polyfill should try and follow suit if it can. Sometimes it needs to change, but we should only change it between versions that are incompatible internally, not all of the time.

cc @jpnelson @joscha @seancurtis 

I reverted the unique version identifier in master, but I think we should write a test against the last version for every minor-dev / major version we release in the future. Meaning, if we release 0.16, we should write a compatibility test for 0.15. If we release 2, we should write a test against 1 if it is to be able to be shared on the same page.

**Comment by joscha** [comment]
Not sure about the tests in master, when I released, the tests were green. Incrementing the shared vars was a fix for the problem of having multiple Skate versions being loaded on the page that have a different way of storing whether an element had been skated. Reverting this breaks the fix that I applied to all versions from 0.12 up (the breaking change was introduced between 0.12 and 0.13). I don't think reverting is a good idea.

**Comment by treshugart** [comment]
Hey @joscha, thanks for responding.

> Not sure about the tests in master, when I released, the tests were green.

Yeah, that's not your fault; it's my bad. I wasn't calling anyone out there, I was just using saying that's how I found the version issue.

> Reverting this breaks the fix that I applied to all versions from 0.12 up (the breaking change was introduced between 0.12 and 0.13). I don't think reverting is a good idea.

it won't break because the version string in master is different from the others. That said we should either:

a) If we're going do what was recently released, we may as well not store globals for those things and modularise them. This is good because we don't have to worry about maintaining compatibility between several Skate versions on the same page.

or

b) If we want to ensure optimal performance and that polyfill-land shares a registry between all versions so that it's more like native, then we should write integration tests for each version. Not sure how we'd do this just yet.

We need to justify either change so I've added a second perf test for mutation observers in c43c1546b663c4a24330069746c3c7813e1fc9eb. This compares a single document mutation observer to two document mutation observers. It's not that much slower so maybe modularising the document observer and registries is a good idea.

Either way, we need to be aware of the caveats for either and be able to justify it. If we choose "a", we trade performance for maintainability. In "b" we do the opposite. Which is the lesser of the evils?

**Comment by joscha** [comment]
I vote for "form follows function". Currently, a 0.12 version can not co-exist with any version after, the fix might degrade performance, but at least skate behaves as expected. I think having two different skate versions on one page is an edge case anyway as it is not exactly the sane thing to do in the first place, so a performance penalty might be alright (depending the measurements are not completely out of the roof obviously). I think the globals are more confusing anyway and always carry a risk of affecting each other, so I'd be in favour of a) as well. Alternatively we can change the behaviour back to how it was before the fix, but then I'd vote for releasing a skate 1.0 to make sure people understand there are breaking changes and clearly state that 1.0 can not co-exist with any prior version.

**Comment by treshugart** [comment]
>  I'd vote for releasing a skate 1.0 to make sure people understand there are breaking changes and clearly state that 1.0 can not co-exist with any prior version.

I vote for this anyways. It's been a long time coming. Maybe instead of 0.16 we should to 16.0 :p. 

I'll go through the remaining issues and see what needs to get done before a 1.0 and flag them as such.
