### ISSUE TITLE
Raise sauce labs feature request for autodetecting platforms when using latest-n

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#519]
### MAR 16, 2016  |  09:10PM PDT 
Original message
skatejs wrote:

I was trying to use: http://sauceio.com/index.php/2016/03/new-browser-version-shortcuts/

I noticed that when using a definition with “latest-n” and not specifying a platform, Saucelabs doesn’t figure out a valid one by itself, the build just doesn’t start.
E.g.

ERROR [launcher.sauce]: Can not start safari latest-1
[init({“version”:”latest-1″,”platform”:”ANY”,”tags”:[],”name”:”Skate unit tests (master)”,”tunnel-identifier”:”karma1458098888″,”record-video”:false,”record-screenshots”:false,”device-orientation”:null,”disable-popup-handler”:true,”build”:”2520″,”public”:null,”customData”:{},”browserName”:”safari”,”base”:”SauceLabs”})] The environment you requested was unavailable.
Unsupported OS/browser/version/device combo: OS: ‘unspecified’, Browser: ‘safari’, Version: ‘8.0.’, Device: ‘unspecified’

Would be good if that can be added, otherwise the definition needs to be changed with every major release that shifts the platform.

The definition is here: https://github.com/skatejs/build/commit/8646983a1b7417531cafd81e1b22adeb7cc9041a

### MAR 16, 2016  |  02:29AM PDT 
Matt Dunn replied:
Hi,

The intention behind the latest-n browser version capability is really for browsers where we support multiple versions of a browser per OS. That’s Chrome and Firefox really and yes, you still have to specify an OS. For Safari, we support one version of Safari per OS X version.

That said, it would be a good idea to be able to just specify a browser with “latest” and have Sauce Labs work out the correct OS to run on rather than have to specify this yourself. I’m going to speak to the Product Manager who’s responsible for this area and see whether that’s on the roadmap.

I’ll let you know what I find out.

Matt

### MAR 18, 2016  |  03:01AM PDT 
Matt Dunn replied:
Hi,

I have discussed this with Product Management and they’ve asked for a feature request to be opened. Please open a request for this at https://saucelabs.ideas.aha.io/

Other users can see and comment on your feature requests, voting them up if they’d also find it useful. That portal is managed directly by our Product Management team, so they’ll see your requests and are able to ask for more information or let you know if we have plans to implement them.

We will scope the effort required to implement this but it will be useful to gauge the level of interest in this potential feature.

Many thanks,
Matt

**Comment by joscha** [comment]
Feature request is here: https://saucelabs.ideas.aha.io/ideas/SLIDEA-I-223
