### ISSUE TITLE
Sauce seems to be serving Safari 7.0 when we say we want 7.1

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#520]
### MAR 18, 2016  |  11:21PM PDT 
Dylan Lacey replied:
G’day Joscha;

That’s very odd; I couldn’t find a release ticket for Safari 7 and it would be extremely unusual for us to go back a version without some major bugs we’re working around.

You say “The last two days”; Have you been being served 7.0.6 for every test over those days? How many test have you attempted? I’m wondering if somehow there’s a stale image lurking somewhere serving janky old Safari.

Cheers,
Dylan.

### MAR 18, 2016  |  09:52PM PDT 
Original message
skatejs wrote:

Up until recently, tests asking for Safari 7 were run with:

Safari 7.1.7 (Mac OS X 10.9.5)

See: https://travis-ci.org/skatejs/skatejs/builds/115761911

Since two days ago tests seemt o be running with:

Safari 7.0.6 (Mac OS X 10.9.5)

See: https://travis-ci.org/skatejs/skatejs/builds/116769605

which now makes our builds fail. I tried enforcing Safari 7.1.7. by passing "7.1" as version string, but it wasn't recognized.

Cheers,
Joscha

### MAR 24, 2016  |  05:13PM PDT 
skatejs replied:
Yes, correct. Before that we seemed to always get the 7.1 version, then suddenly Saucelabs started providing 7.0.6 (see the Travis builds of the master branch, they are all public) and our builds broke.

### MAR 24, 2016  |  09:47AM PDT 
Matt Dunn replied:
Hi,

We updated our images recently with our new branding. When we were building a new 10.9 image, it applied the latest OS updates, which included an upgrade from Safari 7 to Safari 9. We fixed that, but I imagine that in fixing it, the Safari version probably changed from 7.1.7 to 7.0.6.

I what way is this breaking your build? Are you able to update your build to work with 7.0.6 or do you particularly need 7.1.7?

Thanks,
Matt

### MAR 28, 2016  |  03:30PM PDT 
skatejs replied:
Hi Matt,

yes, this is what is breaking our build, because there are some fixes between 7.0.6 and 7.1.7 that allow you to use Object.defineProperty on event objects. In 7.0.6 this is not possible. We couldn't find a workaround and as this is our production build that suddenly broke, we had to disable Safari 7, which is quite unfortunate. Given that 7.0.6 is from 2014 and probably not a version that is very widely spread, as security updates are available all throughout 2015, can't you add the security fixes to that image?

### MAR 29, 2016  |  03:39AM PDT 
Matt Dunn replied:
Thanks for the info. I’ve requested that we rectify this in our Safari 7 image. I’ll put this case on hold for now and get back to you once I have an update.

Regards,
Matt

**Comment by joscha** [comment]
Wrote to the support again, waiting for a response.

**Comment by joscha** [comment]
```
Matt Dunn - Mar 29, 2016 02:57AM

Thanks for the info. I’ve requested that we rectify this in our Safari 7 image. I’ll put this case on hold for now and get back to you once I have an update.


Regards,

Matt
```

**Comment by treshugart** [comment]
Closing as Sauce don't seem to want to revert this breaking change.
