### ISSUE TITLE
Skate doesn't init on IE9

### ISSUE THREAD

**Issue by PhuongXmaster** [skatejs/skatejs#536]
Please help to double check that skate is working on IE9.
I have included DOM Mutation Observer from https://github.com/megawac/MutationObserver.js
It doesn't show warning of missing DOM Mutation Observer on IE9 anymore. However, skate still cannot be initialized.

I double check in AUI component: https://docs.atlassian.com/aui/latest/docs/toggle-button.html
It doesn't work on IE9 as well.

I'm not sure skatejs alone support IE9 as in README stated.

**Comment by PhuongXmaster** [comment]
the order of MutationObserver is not correct. It works when I include the Observer before skatejs.

**Comment by treshugart** [comment]
The mutation observer must be registered prior to any definitions being registered with Skate as it lazily instantiates a mutation observer to look for new elements. Your best bet with any polyfills is to load them before any dependants.

Is everything working as expected now?

**Comment by treshugart** [comment]
Also: Hi Phuong! I just noticed that was you :)

**Comment by phuongdoan-tinypulse** [comment]
:D Nice to hear from you again. It's working now.
