### ISSUE TITLE
Merge in Kickflip to Skate proper

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#541]
This will make Skate opinionated about rendering and what it uses to do so:

- Named slots is polyfilled (possibly can use v0 shadow DOM in Blink)
- Incremental DOM is the defacto virtual DOM implementation.

Pros:

1. Skate puts less of the onus on users to decide the best way to do things.
2. You can still use any templating language you want as long as it compiles down to Incremental DOM.
3. We push for functional web components.

Cons:

1. It gets a little bigger.
2. People can no longer choose how they want to render things, but this could be alleviated by being able to choose your own templating language if it compiles down to Incremental DOM.

**Comment by joscha** [comment]
I think if it increases the consumeability of skate without taking away actual widely used features (e.g. just adding a bit of opinionated flavour) it is a good idea. Anyone wanting to get into the topic fast would use Skate+kickflip anyway, so merging them would make it easier. The only thing I am a little concerned about is the amout of polyfilling - skate currently only fills tiny amounts and I think that is actually an advantage of skate by itself.

**Comment by treshugart** [comment]
The amount of polyfilling is a temporary issue I'm willing to risk at this point for the sake of simplicity and more widespread adoption.

**Comment by treshugart** [comment]
@marcoms You'd probably have an opinion here.

@antitoxic you've been vocal in the past about Skate not having an opinionated way to render. This would fix that. Input is appreciated.

**Comment by marcoms** [comment]
I must admit I don't have experience with functional approaches like React uses. One thing I've been wary of is how animation would be possible between two different DOM states (which is why I have in the past been interacting with the DOM directly on property changes instead of re-rendering). I believe Aurelia automatically animates layout changes but something like that would probably be non-trivial and require more thought.

**Comment by treshugart** [comment]
@marcoms that's a very valid concern. There can be issues with this. For example, if 

1. a render occurs during the middle of an animation and your animation is based on changes to the `style` attribute that Incremental DOM isn't aware of, or
2. the position of the animating element changes relative to its siblings and there is no `key` defined ,it would be blown away and re-rendered

For 1, there are a couple of work arounds. Perhaps you could simply use the `render()` function to animate the style property similar to how react-motion does things:

```js
skate('my-element', {
  properties: {
    animationWidth: skate.properties.number()
  },
  render (elem) {
    <div style={ width: elem.animationWidth } />
  }
});
```

Or you could simply tell Incremental DOM not to diff the `style` attribute using the `statics` prop on an element:

```js
skate('my-element', {
  render () {
    <div statics={[ 'style' ]} />
  }
});
```

For 2, a simple approach would be to give the element that you know might be affected a `key` so that Incremental DOM knows where it is in the diff tree:

```js
skate('my-element', {
  render () {
    <div key="sibling1" />
    <div key="sibling2" />
  }
});
```

A possible future goal might be to declaratively animate a component from within the `render()` function similar to react-motion:

```js
skate('my-element', {
  render (elem) {
    <sk-animate defaultStyle={{ x: 0 }} style={{ x: spring(10) }}>
      <div />
    </sk-animate>
  }
});
```

**Comment by marcoms** [comment]
Thanks for the in-depth response. While I become acquainted with this new way of things, is it possible to emulate skate's current behaviour of rendering once and mutating the (shadow) DOM as normal (in property setters, for example) using kickflip?

**Comment by treshugart** [comment]
What you could do, if you really wanted to, is to do something like:

```js
skate('my-element', {
  properties: {
    myProp: {
      render: false,
      set () { 
        // do mutations here
      }
    }
  }
});
```

The issue here is that if you have any other properties then you need to make sure they don't re-render or you'll lose the mutations you made in the setter for `myProp`. It would just be something you'd need to do as a convention if you're mutating things.

In terms of how this actually works in practice, I can't comment for sure. Theoretically this should work, but it (obviously) deviates from the recommended way of rendering and I haven't tried it yet.
