### ISSUE TITLE
One function vs multiple functions for whether or not a render() should occur.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#545]
Once #541 is merged in, we'll have a way to prevent component rendering by specifying a `render` option to properties. They are specified on the property definitions themselves so it's a 1:1 mapping.

```js
skate('my-element', {
  properties: {
    prop1: {
      render: false
    },
    prop2: {
      render: true
    }
  }
});
```

The `render` option can also be a function:

```js
render (element, { oldValue, newValue, name })
```

The question being, should we instead create a single function on the component definition that gets called instead?

```js
skate('my-element', {
    properties: {
      prop1: {},
      prop2: {}
    },
    shouldUpdate (oldState, newState) {
      if (prop1 in newState) {
        return false
      }
      return true;
    }
});
```

My inclination is to keep the 1:1 property to render check as it seems to clean up the logic. The downside is that you call it once per property set instead of once per render queue just before rendering. I haven't ran into any issues yet, but that doesn't mean that there aren't any.

**Comment by alexreardon** [comment]
Could you give an example of the alternative? I am not totally following what the use cases are

**Comment by treshugart** [comment]
@alexreardon the current way is to specify `render` on properties. The alternative is the second code block where it shows the `shouldUpdate` function instead of granular checks.

**Comment by treshugart** [comment]
Closing this as it kind just seems like bikeshedding. If there's an overwhelming need for it in the future then we can decide then on it then.

**Comment by marcoms** [comment]
I can't really comment on the intended use case, but something like this could be useful if the user never wan't property updates to trigger a render (like me at this time). E.g.

```js
skate('x-el', {
  properties: {
    prop1: { render: false },
    prop2: { render: false },
    prop3: { render: false },
  },
});
```
 vs.

```js
skate('x-el', {
  properties: {
    prop1: {},
    prop2: {},
    prop3: {},
  },

  shouldUpdate() { return false; },
});
```

These solutions are not ideal however at least the latter one removes redundancy for property definitions.
