### ISSUE TITLE
Remove skate.render()

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#547]
Since becoming more opinionated about the rendering pipeline, there is no longer a need to imperatively render a component.

**Comment by treshugart** [comment]
That said, there may be a possibility that this would warrant use in a test where you wanted to synchronously render a component. An alternative to that would be to use the [`state()`](https://github.com/skatejs/skatejs#state-elem-state) function and force a synchronous render in that. The question then being, are there any use-cases for keeping `render()`?

**Comment by seancurtis** [comment]
I prefer the 3rd option. Adding setTimeouts is messy and could be brittle. Having to `render()` on some state changes, but not others might end up with people just calling it "in case". The third option hides the entire issue from them and should result in a lot cleaner test files.

**Comment by treshugart** [comment]
Third option implemented in #556.
