### ISSUE TITLE
Broken test

### ISSUE THREAD

**Issue by nadiam84** [skatejs/skatejs#550]
Here: test/unit/api/properties.js

There is a test that doesn't check what it suppose to check, I think. 
When we are doing `[undefined, null, false, 0, '', 'something'].forEach(` the first thing that we do is `value = JSON.stringify(value);`, which doesn't make sense for the test here because all that we check now is setting string for an attribute, not the different zero-values.

**Comment by treshugart** [comment]
This has changed slightly. We are also checking to make sure the property is the expected value. We check the attribute also to make sure there's no side effects happening. Going to close this for now. Pls reopen if you think it should be changed.
