### ISSUE TITLE
What if no Shadow DOM support is available?

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#562]
It might be best to render to the host element if no Shadow DOM support is available. This just means that composing elements that have a `render()` function into other elements will cause errors with Incremental DOM.

If we do end up doing this, we should think about warning to the console. If not, we should throw an error requiring Shadow DOM support.

**Comment by treshugart** [comment]
This has been implemented without warning, currently. If we think there should be warning support we should add this at a later point.

**Comment by jpnelson** [comment]
When you say "shadow DOM support", does that include polyfilled support?

**Comment by treshugart** [comment]
yes
