### ISSUE TITLE
Plan for migrating to Custom Elements and Shadow DOM v1 APIs?

### ISSUE THREAD

**Issue by justinfagnani** [skatejs/skatejs#563]
Hi Skate, Justin from the Polymer team here!

I'm wondering what your plans are for the v1 APIs. We're still a little bit off from v1 support, but work is picking up. I'd love to try some examples combining different web components libraries, and I'd also like to get some projects besides Polymer trying out the new polyfills when they're ready.

I know you don't use the polyfills for v0, but using the polyfills might open up interop between the various web component libraries, especially as they can simply be not included for browsers with native support to save significant download size and time. I started work a while back on the Custom Elements v1 polyfill, and will pick up the work again soon. Shadow DOM v1 should follow shortly after.

FYI, Safari Technical Preview is adding web component APIs very quickly, and Chrome should have some support landing soon. I also hear Firefox is readying commits. 😄

**Comment by justinfagnani** [comment]
Oh, and I'm really focusing on size and performance for the v1 Custom Elements polyfill. It's mostly feature complete and weighs in at 1.7k minified and gzipped.

**Comment by treshugart** [comment]
Hey @justinfagnani, thanks for getting in touch about that stuff. 

You're right, we don't use the polyfill for v0. The real reason there is performance and size as it seems you've already noticed :p . We really didn't have to write much code to support v1; the biggest issue for us was trying to make behaviour consistent between v0 and v1. For example,  the `attributeChangedCallback` being called for attributes that exist at the time of upgrade in v1 but not v0 and how that works in with our properties.

We'd totally welcome using a polyfill for v1. In fact, we've already written some code for both v1 Custom Elements and  v1 Shadow DOM. We'd be more than happy to contribute what we can from these.

In terms of Skate being compatible with other web component libraries, it should already be. Have you found this to not be the case? It should work with both v0 and v1 polyfills / native implementations without a hitch (and even if no support at all is present). It's also designed to work along-side Polymer, React et al.

I have some questions:

1. For inconsistencies between v0 and v1 custom elements, would you be detecting v0 support and making these things consistent, or is this still up to the abstraction (i.e. Skate / Polymer) to make these consistent?
2. Will v1 polyfills be designed to be compatible with v0 polyfills on the page?
3. For the Shadow DOM polyfill, we've found the most useful part of it is the DOM structure encapsulation, not CSS, at least for our purposes. What are your plans for this? All-in? Or can the encapsulation be split into JS / CSS, or to opt-in to features so a balance can be attained between performance and spec API coverage?
4. How can we help? We're more than happy to contribute our relevant code and participate in discussions as needed.

**Comment by justinfagnani** [comment]
Hi Trey, thanks for the info.

Glad to hear that Skate should work with various combinations of native and polyfills. I'll try some out soon.

As for your questions:

  1. One solution would be to write the v1 polyfill so that it can be implemented on top of the v0 API. This would mean that it works on Chrome with native v0, but not v1, and that v1 and v0 polyfills would share the same registry. Recently I've been thinking that this would optimize for a temporary situation though, and the v1 APIs are going to roll out very quickly. So now I'm concentrating on a very small, fast and correct v1-only polyfill, and when that's production-ready I'll look at making the v0 polyfill share the registry so that you at least can't double register an element, once in v0 and once in v1.
  2. see above :)
  3. The CSS encapsulation is _huge_ for us. It simplifies and improves performance of CSS so much, that it might be the main feature for some people :). So the full Shadow DOM polyfill will be all-in. It'll also probably only be necessary on IE (and Edge until they implement). In the future Polymer customer will probably opt-in to full Shadow DOM more and more... It's possibly that Polymer's Shady DOM layer, (which is much faster than the Shadow DOM polyfill, but compatible with scoped CSS, CSS custom properties and @apply mixins) might be brought out into a library. We don't have another customer for it yet, but if you're interested, let me know
  4. Trying out the polyfill when it's ready would be huge. It might actually be ready enough to try now-ish, but it's not released, so you'd have to build it yourself. I'll certainly let you know when I do another round on it. Ultimately,  a demo of Polymer+Skate on v1 APIs would be very, very cool :)

Cheers!

**Comment by treshugart** [comment]
Had a discussion with @jpnelson this morning and I think the consensus is that we should remove all internal polyfilling and support only v1 APIs requiring that polyfill for now. The issue for us is that we were just about to release a 1.0.0 and this pushes that back, but happy to do so if it means simplifying things.

Maybe it's worth supporting both `registerElement()` and `customElements.define()` and just make it known that there will be a difference in how `attributeChangedCallback()` behaves depending on which version is used. If you want consistent behaviour in Chrome, use the v1 polyfill. If it doesn't matter, don't include one. We currently do this with Shadow DOM; we can use either one. If you require v1 features, include a polyfill etc.

What do you think @jpnelson?

**Comment by justinfagnani** [comment]
If you want to release a 1.0 soon, given that our timeline for polyfills, and the browers for native implementations seems to be on the order of a few months, maybe you want to do 1.0 on the v0 APIs now and 2.0 for the v1 APIs? Just a thought. I'd love to be able to have v1 polyfills ready for you in the next few weeks, but I don't think it's feasible.

**Comment by trusktr** [comment]
Is there any Custom Elements v1 polyfill yet?

**Comment by justinfagnani** [comment]
@trusktr in a branch: https://github.com/webcomponents/webcomponentsjs/pull/514

Polymer's going to need it soon, and we want to share tests with native implementations, so work is going to pick up again soon.

**Comment by treshugart** [comment]
@justinfagnani do you have a rough timeline when it'd be stable to consume? I'm planning on cutting a 1.0 by the end of the week with what we have (which will include v1 support, at least what we can test against).

I think the safe bet for us would be to go 1.0 and do a 2.0 when the v1 one is stable, as you suggested. Going to close this now, but feel free to reopen if there's something else we should discuss.
