### ISSUE TITLE
How is composition/transclusion handled in Skate.js?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#576]
Can you give an example of how to make a custom element with Skate.js, and then how to make a second custom element with Skate.js that transcludes the first element into it's own shadow DOM?

**Comment by treshugart** [comment]
It uses v1 slots and makes `<content>` behave like `<slot>` in v0 shadow DOM. See https://jsbin.com/veyexal/1. 

Before you say anything, the global `skate.skate()` call sucks, I know. I think we're rename that to `define` or something before 1.0 goes out. It's a side effect of transpilation right now.

**Comment by trusktr** [comment]
@treshugart Thanks! Since you're using vdom there, I can guess (correct me if wrong) that both the element's content and the element's ShadowDOM are added/modified at a point in time later than when the element is created. 

This leads me to the following question: https://github.com/w3c/webcomponents/issues/508

**Comment by treshugart** [comment]
Answered in that issue: https://github.com/w3c/webcomponents/issues/508#issuecomment-222864422.

To be clear, Skate does not add any special behaviour here; it uses named slots verbatim.

**Comment by treshugart** [comment]
Closing this since hopefully it's answered on the w3c issue. Feel free to reopen if that's not clear.
