### ISSUE TITLE
How to use ES6 Classes with Skate.js?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#577]
I am trying to stick to ES6 Classes throughout my app. Currently, this is what I do with vanilla (v0) Custom Elements:

```js
class MyElement extends HTMLElement {
    createdCallback() {...}
    attachedCallback() {...}
    detachedCallback() {...}
    ...
}

// assignment is required as registerElement returns a new constructor
MyElement = document.registerElement('my-element', MyElement)

export default MyElement
```

This works because the `registerElement` options argument can accept a `prototype` property, and it may be considered coincidence that the constructor function of a class also has a `prototype` property, so I'm simply passing in the constructor for the options to `registerElement`.

About the `prototype` property to `skate()` options, the comments on skate.js.org say:

> It's notable that the element's prototype is not modified. These are added after the element is instantiated.

So, I was thinking maybe I could apply a similar pattern as I've done above, but with skate.js, f.e.:

```js
class MyElement extends HTMLElement {
    created() {...}
    attached() {...}
    detached() {...}
    ...
}

// assignment is required (v0 hack).
MyElement = skate('my-element', MyElement)
```

Would this work (note, I haven't tried Skate.js yet, but am evaluating what's out there in order to decide if I should continue with my own [WebComponent](https://github.com/infamous/infamous/blob/e052ed047d75f40c9ce797c386748b160df9cce1/src/motor-html/web-component.js) class or if I should adopt Skate.js, the latter is tempting, especially since I've been a skateboarder for 16 years).

If that *does* work, the first obvious downside is that then I will not be able to pass other options like `events`, `attributes`, etc, unless I place them onto the class constuctor function, which is a little ugly, but I could live with that.

I guess this brings up a question: have you considered an ES6 class approach? It could possibly look something like this:

```js
class MyElement extends HTMLElement {
    created() {...}
    attached() {...}
    detached() {...}
    
    events = {
        ...
    }
    attributes = {
        ...
    }
}

MyElement = skate('my-element', MyElement)
```

(The `MyElement = ` assignment is only because v0 Custom Elements API returns a new constructor function and using the original constructor doesn't work.)

In my WebComponent class, I came up with an interesting idea (but I'm not sure if it's a good idea yet): the [makeWebComponentBaseClass](https://github.com/infamous/infamous/blob/e052ed047d75f40c9ce797c386748b160df9cce1/src/motor-html/web-component.js#L19) function creates a different `WebComponent` base class to extend from depending on which type of HTMLElement one wants to extend from. The usage looks like this:
https://github.com/infamous/infamous/blob/e052ed047d75f40c9ce797c386748b160df9cce1/src/motor-html/node.js#L7-L9

WebComponent contains base functionality for all components, but currently that functionality isn't as involved as Skate.js, WebComponent is only managing stylesheets with [JSS](https://github.com/jsstyles/jss) so far.

**Comment by treshugart** [comment]
Skate will automatically extend `HTMLElement` by default if you don't do so, so you could just do the following instead:

```js
skate('my-element', {
  created () {},
  attached () {},
  detached () {}
});
```

That said, you can extend like so:

```js
const MyElement = skate('my-element', class extends HTMLElement {
  static created () {},
  static attached () {},
  static detached () {}
});
```

We've got [some tests](https://github.com/skatejs/skatejs/blob/master/test/unit/extending.js) set up for using ES2015 classes. If you can't do what you want to do, then that's a bug.

That said, even with Skate, you have to use the return value from `skate()` just like you do in v0 because Skate abstracts v0 and v1 (not full v1 support yet).

**Comment by trusktr** [comment]
The `static` usage there is a little awkward. Those functions are taken and assigned onto instances?

**Comment by treshugart** [comment]
No, the element is passed as the first and only argument. There's some reasoning behind this:

- They're lifecycle callbacks, not really part of the public API which is what the `prototype` is intended for.
- We experimented with using symbols for the names, but it's really, really awkward when not using ES2015 and still kinda awkward even when you can.
- Static avoids `prototype` conflicts.
- Rewriting the context of functions (in this case making `this` be the element in statics) can be unexpected.

We decided that not colliding and backward compatibility were more important to us than eliminating the `static` keyword when using classes.

That said, I personally dislike ES2015 classes and find other things awkward like:

```js
skate('my-element', class {
  static get props () {
    return {};
  }
});
```

Where you could simply just go:

```js
skate('my-element', {
  props: {}
});
```

With classes, you still have to merge things like `props`:

```js
import ParentComponent from './parent-component';

skate('child-component', class extends ParentComponent {
  static get props () {
    return Object.assign({}, ParentComponent.props, {
      childProp: {}
    });
  }
});
```

For instances where you're forced to use something other than `HTMLElement` as a base, then classes are more convenient than the Object.assign() route, but only ever so slightly. Since Skate automating the extending of `HTMLElement` should cover most use cases and enables a much more concise syntax.

If you have a proposal, I'd be happy to discuss it, though.

**Comment by trusktr** [comment]
> They're lifecycle callbacks, not really part of the public API which is what the prototype is intended for.

For sure, I see what you mean. That said, the actual Custom Element API has these callbacks on the prototypes, which I'm fine with, so the statics form in Skate.js seems deviated from the spec in that sense. In React we use prototype methodsfor life cycle callbacks, and people that use React simply know better than to use those method names for other purposes.

> Static avoids prototype conflicts.

The premise in React and vanilla Custom Elements is "make a class with method names X, Y, Z, and we'll automatically call those methods for you in situations X, Y, and Z", which I think is just fine. Passing `element` as an argument into the static methods is practically the same as placing the methods on the prototype and using `this` instead of `element`.

> Rewriting the context of functions (in this case making this be the element in statics) can be unexpected.

Well, that's why I'd go with prototype methods instead of statics.

> We decided that not colliding and backward compatibility were more important to us than eliminating the static keyword when using classes.

But it's your design and how you like it 😊 ! It's not a big deal if I have to use `element` instead of `this` along with the extra `static` symbol. About backwards compatibility, are you talking about how the v1 spec unnecessarily modified the callback names. They could've just ket them the same, therefore keeping backwards compatibility. I think connectedCallback/disconnectedCallback is further away from `appendChild` and `removeChild` than attachedCallback/detachedCallback. I don't see what benefit we get from renaming the methods in v1, and I see we only get the opposite of a benefit due to introduced possibility for name collision.

> That said, I personally dislike ES2015 classes and find other things awkward like:
> 
> ```js
> skate('my-element', class {
>   static get props () {
>     return {};
>   }
> });
> ```

I would write that as

```js
class MyElement {
  static get props () {
    return {};
  }
}

skate('my-element', MyElement);
```

which is closer to Custom Elements v1:

```js
class MyElement extends HTMLElement {
    ...
}

customElements.define('my-element', MyElement);
```

> If you have a proposal, I'd be happy to discuss it, though.

I'm not sure I have a proposal, but my [class-based approach](https://github.com/infamous/infamous/blob/e052ed047d75f40c9ce797c386748b160df9cce1/src/motor-html/web-component.js) solves that problem by generating the base class dynamically based on the element we want to extend. I could make the first argument to my `makeWebComponentBaseClass` function default to `HTMLElement`, but haven't done that yet.

I agree with you that with the current Skate API, passing an ES2015 class is awkward and not as nice as using the API the way it was designed by passing an Object literal. Maybe there's some way to make ES2015 classes be nice to use, a way that would be better than in both of our cases. I think I should get up and running with v1 first before I can make any proposal.

Is there an existing Custom Elements v1 polyfill, so I can experiment and perhaps make a proposal?

**Comment by trusktr** [comment]
A downside of copying stuff from the `prototype` option passed to `skate()` "during element instantiation" is that may perform less compared to just using a class prototype. This could make a difference if skate is being used to instantiate elements in a real-time game.

**Comment by treshugart** [comment]
> A downside of copying stuff from the prototype option passed to skate() "during element instantiation" is that it may perform less compared to just using a class prototype.

That only happens in the polyfill. There's no other way to do this, AFAIK.

**Comment by treshugart** [comment]
> That said, the actual Custom Element API has these callbacks on the prototypes, which I'm fine with, so the statics form in Skate.js seems deviated from the spec in that sense.

Well, Skate adds features around these callbacks for things like properties and event binding. That being the case, the function names *must* be different regardless of if they're on the `prototype` or on the `constructor`.

> In React we use prototype methods for life cycle callbacks, and people that use React simply know better than to use those method names for other purposes.

Stylistic choice, really. React doesn't have problems with DOM `prototype` collision, though, so it's easier to swallow there.

> The premise in React and vanilla Custom Elements is "make a class with method names X, Y, Z, and we'll automatically call those methods for you in situations X, Y, and Z", which I think is just fine. Passing element as an argument into the static methods is practically the same as placing the methods on the prototype and using this instead of element.

Indeed.

> Well, that's why I'd go with prototype methods instead of statics.

Personally, I'd prefer prototyped lifecycle callbacks. It's why we messed with using symbols to avoid collisions, which was an ergonomic nightmare. That said, using statics don't have any functional downsides. Maybe it's worth finding better names to put on the prototype? The problem there is ergonomic names have a higher chance of colliding. I'm open to finding a solution before 1.0, but that's very soon. Is it really that bad to use statics?

> About backwards compatibility, are you talking about how the v1 spec unnecessarily modified the callback names.

Not really, but that's only one of bikesheds and churn that has been present in the spec in the past few months. I was actually referring to the latest versions of Skate all use statics and staying backward compatible seemingly outweighs having to type `static` and use the argument. Still, I prefer prototype and am happy to discuss this for 1.0 if we can come to a quick consensus.

> I would write that as ... which is closer to Custom Elements v1.

![screen shot 2016-06-01 at 11 02 46 am](https://cloud.githubusercontent.com/assets/136556/15695510/46d848c0-27eb-11e6-9277-8b97de3cfb02.png)

Unfortunately, the reality is that right now we can't very easily do that. As you said yourself, you have to get the return value from `registerElement` (or do `window.customElements.get('my-element')`. V1 will allow that, but we aren't there yet. Skate still allows you to use classes, it just requires that you use the returned constructor instead so writing something like `skate('my-element', {})` is more ergonomic for that use case, but also allows you to use classes if you want.

Skate also uses the value of the `extends` option to generate a base class for you so you don't have to do stuff like:

```js
skate('custom-p', class extends HTMLParagraphElement { 
  static get extends () {
    return 'p';
  }
})
```

You'd just do:

```js
skate('custom-p', {
  extends: 'p'
});
```

Skate takes care of the base class, v0 passing `extends` as a "static" property and v1 where `extends` is passed as a third argument to `customElements.define()`.

It's worth noting that the spec is somewhat inconsistent with it's lifecycle. For the callbacks, they use `prototype`. But for `observedAttributes`, they use statics. Illustrating this:

```js
class MyParagraph extends HTMLParagraphElement {
  static get observedAttributes () {
    return ['some-attribute'];
  }

  attributeChangedCallback (name, oldValue, newValue) {
    // do something when "some-attribute" changes
  }
}

window.customElements.define('my-p', MyParagraph, { extends: 'p' });
```

Whereas in Skate you could just write:

```js
const MyParagraph = skate('my-p', {
  extends: 'p',
  observedAttributes: ['some-attribute'],
  attributeChanged (elem, data) {}
});
```

I wouldn't call this "divergent" from the spec. Divergent would be providing behaviour that you can't use the web component primitives to provide, such as binding behaviour to attributes and classes (which we removed).

> I'm not sure I have a proposal, but my class-based approach solves that problem by generating the base class dynamically based on the element we want to extend.

I'm not exactly sure what that means, but if it means what I think it does, isn't that very similar to what Skate does for you?

> Is there an existing Custom Elements v1 polyfill, so I can experiment and perhaps make a proposal?

I think Justin replied to you already. Be aware that we're still working on supporting v1 but feel free to raise issues.

Thanks again for all your questions and input.

**Comment by treshugart** [comment]
You also seem concerned that we don't do native prototype extension. Indeed we do, we just do it the ES5 way as you can see here: https://github.com/skatejs/skatejs/blob/a05edcc557fba8c30c9248face89ea534900c050/src/api/skate.js#L117.

Where we polyfill that is here: https://github.com/skatejs/skatejs/blob/a05edcc557fba8c30c9248face89ea534900c050/src/lifecycle/created.js#L86

**Comment by treshugart** [comment]
Feel free to reopen if this requires further discussion. Closing for now.

**Comment by trusktr** [comment]
For sure, I guess I just like ES6 class semantics, and want to write JS code that is as vanilla JS as possible in terms of defining classes, but ultimately the end result is what matter, and the result SkateJS achieves is ultimately the same thing (a way of specifying DOM classes, just not with ES syntax directly).

**Comment by treshugart** [comment]
FYI you can now:

```js
skate('my-element', class extends HTMLElement {});
```

Skate uses both the v0 and v1 polyfills and actually [now recommends](https://github.com/skatejs/skatejs#definename-definition) using classes if possible.
