### ISSUE TITLE
How does binding work?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#578]
If I use `skate.type.CLASSNAME `, and the class name matches with a bunch of different elements (divs, spans, tables, etc) what does Skate.js do? Does it register custom elements in that case?

I haven't read Skate.js source yet, but that will help. I'm just looking for a brief high-level overview.

**Comment by treshugart** [comment]
Just prefacing this with: classname and attribute bindings won't be part of 1.0 as it's too divergent with the spec. We introduced them as a stopgap for anything using 0.x versions of Skate to transition away from jQuery style plugins to custom elements without having to rewrite much. Skate 1.0 is custom elements only.

To answer your question, no it does not register custom elements. It simply just emulates the custom element behaviour to an element that has a matching class name.

**Comment by trusktr** [comment]
@treshugart I'm guessing with skate.type.ATTRIBUTE it also emulates? And with skate.type.ELEMENT it makes a Custom Element?

**Comment by treshugart** [comment]
Correct on both accounts.
