### ISSUE TITLE
created callback to ensure the element is hidden?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#579]
The docs say

> Without full web-component support, we can only emulate the created callback to ensure the element is hidden.

What does that mean?

**Comment by treshugart** [comment]
What version? That seems like it's from a very old version where we were trying to emulate the hiding of elements before they were upgraded. That's not the case anymore and I can't find it in the latest docs (master or 0.15.3).

**Comment by trusktr** [comment]
Its mentioned inhttp://skate.js.org/#component-lifecycle

**Comment by treshugart** [comment]
I really should delete those docs until we can push a new site, those are super old. Sorry about that. The README is the source of truth.
