### ISSUE TITLE
Abstract Shadow DOM V0 <content> behind Shadow DOM V1 <slot>.

### ISSUE THREAD

**Issue by nadiam84** [skatejs/skatejs#592]
In some versions of skatejs absctracting Shadow DOM V0 <content> behind Shadow DOM V1 <slot> doesn't work properly. 

The code is:
```
if (tname === 'slot') {
	    if (support.shadowDomV0) {
	      if (attrs && attrs.slot) {
	        attrs.select = '[slot="' + attrs.slot + '"]';
	        delete attrs.slot;
	      }
	      tname = 'content';
	    }
	  }
```

AtlasKit animations don't work with this and do work perfectly when this code is commented out.
This can be found in this commit: 85dfbcbf7a7bb53d709719639ca7414b37769861

**Comment by treshugart** [comment]
Interesting. I wonder if this will work in V1. Is there an isolated test case we could write for this?

**Comment by nadiam84** [comment]
No, it doesn't (not fully).
I've created a branch with included namedslots (https://github.com/skatejs/skatejs/tree/tests-with-named-slots). At least one test breaks because of this. Also wrote a test that imitates our animations structure, it's broken completely.
