### ISSUE TITLE
Get performance tests running again.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#597]
Since doing the work for 1.0, the performance tests have been neglected. It'd be nice to build something into the build module to reuse:

- https://github.com/JamieMason/karma-benchmark
- https://github.com/lazd/karma-benchmark-reporter

That said, the last commit on the karma-benchmark module was 2 years ago at the time of writing this. It'd also require the refactoring of the tests. At least we'd be reusing existing code instead of using the bespoke wrapper around Karma.

We should also check the Incremental DOM tests to see how they do it.

As part of this, we should remove all perf tests except the React tests as they're not relevant anymore because we're now using the WebComponentsJS polyfills.

EDIT

Matcha seems to be the way to go. See https://github.com/skatejs/build/issues/227.

EDIT

Matcha doesn't work without hacks in a browser environment it seems, so no go there.

**Comment by treshugart** [comment]
This will need to be done first: https://github.com/skatejs/build/issues/227

**Comment by JamieMason** [comment]
hey @treshugart, please open any issues for things you might need on karma-benchmark. I plan to revisit it but have been caught up on other projects. Thanks.

**Comment by treshugart** [comment]
Thanks, @JamieMason. I'll revisit spiking it. Matcha doesn't work in the browser without hacks anyways.

**Comment by treshugart** [comment]
Ended up just using https://github.com/treshugart/birdpoo running in karma / mocha for now. Closing but happy to revisit karma-benchmark if we get a chance.
