### ISSUE TITLE
prop.object() prop type

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#637]
```js
import { Component, prop } from 'skatejs';

export default class extends Component {
  static props = {
    myObj: prop.object()
  }
}
```

Defaults options:

- `default` should be a function that returns an object
- `deserialize` should use `JSON.parse()`
- `serialize` should use `JSON.stringify()`
- `coerce` shouldn't do anything since it's hard to infer the meaning of the input

**Comment by andreawyss** [comment]
I like it.
