### ISSUE TITLE
Reactivity

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#639]
How would you explain to someone migrating from React how to make things reactive when making SkateJS-based components? Do you have a pattern worked out for that in SkateJS yet?

**Comment by lukebatchelor** [comment]
It should be very similar to the react way of thinking. You want your `render` function to be your source of truth for everything to do with your component. You want it to be completely idempotent in that every call to `render` with the same state, should produce an identical output with no other side effects.

One key way of doing this is to let skate handle the re-rendering. If you find yourself 'working around' something by manually calling render, that's a pretty good sign there's something wrong.

Changing an elements props will automatically force a re-render and changing its state through the state function will too. One tip would be to **always** use the state function to modify state.

A common mistake is having an object as a prop, updating a value **in** the object and expecting the component to re-render. The trick is to use something like `state(elem, Object.assign({}, myProp))` to make sure you get a new reference each time.

Is that sort of what you were after/asking for?

**Comment by treshugart** [comment]
@lukebatchelor would you mind adding this to the docs somewhere?

**Comment by treshugart** [comment]
Hey @trusktr I'm just going to close this for now. Feel free to reopen if you have any more related questions.
