### ISSUE TITLE
Suggestion on coerce and deserialize

### ISSUE THREAD

**Issue by tmpfs** [skatejs/skatejs#643]
Hi,

Whilst re-reading the docs something jumped out at me about these method names. Obviously, my understanding may be wrong, feel free to correct me.

I read the intention of `coerce` as converting from an attribute string value to a native javascript type and read `deserialize` as the inverse.

From my perspective this strikes me as something of a misnomer, I would call the process of going from the string attribute value to a native data type `deserialization` and from a javascript data type to an attribute string value `serialization`.

Sorry if this is a little pedantic, but if my understanding of the intention for these functions is correct I would suggest `deserialize` is renamed to `serialize` and `coerce` to `deserialize`.

Cheers!

**Comment by treshugart** [comment]
Not sure how it happened, but the docs are just wrong. `serialize()` in fact takes the attribute from the property to the attribute and `deserialize()` is the opposite. Fixed in referenced commit.

**Comment by treshugart** [comment]
Nice catch, BTW :)
