### ISSUE TITLE
using light dom when defining a new component.

### ISSUE THREAD

**Issue by kurtis-dunn** [skatejs/skatejs#645]
When each component is created in the DOM its forced into its own shadow root...
```
<the-app>
   #shadow-root
   <the-header>
      #shadow-root
     <h1></h1>
   </the-header>
</the-app>
```

Can skate define a component without a new shadow-root for each? Like so..
```
<the-app>
   <the-header>
      <h1></h1>
   </the-header>
</the-app>
```

This is probably more of a question than an issue, but Im curious if this can be achieved. Kickflip behaved in this manner & Im unsure if the spec has changed or not. Here's the code Im using. Please let me know if I'm misunderstanding or maybe this could be a future option?

```
import skate, { define, vdom } from 'skatejs';

import Header from '../../pages/header';

export default define('the-app', {
  created (elem) {
    console.log('the-app.created()');
  },
  render (elem) {
    vdom.elementOpen(Header);
  }
});

```

**Comment by lukebatchelor** [comment]
Hiya @kurtis-dunn 

There hasn't been any change to the spec and I don't think Kickflip has ever behaved like that. Kickflip used a shadowDOM polyfill, so you wouldn't have had `#shadow-root` but would have had something like `<_shadow-root_>` with the shadow-root behaviour polyfilled rather than native.

What are you trying to achieve by not having a shadow-root exactly? I might be able to help with that.

**Comment by treshugart** [comment]
There's an idea where you can possibly pass a function to a vdom function (or via JSX) and it will allow you to do something similar. Currently you can't pass a constructor or function to `elementOpen`.

See https://github.com/skatejs/skatejs/issues/646 for more info on that. Closing for now. Please feel free to reopen if you have any more questions.

**Comment by rhythnic** [comment]
I would also be interested in this feature, if it's on the table at all.  I don't like having to import common styles into each component, as seems to be the recommended approach for shadow dom.  I'm still becoming familiar with shadow dom, but I expect that I would rather use global settings/basic element styling and something like [aphrodite](https://github.com/Khan/aphrodite) or [csjs](https://github.com/rtsao/csjs) for local styling.
