### ISSUE TITLE
Ability to pass functions as tag names

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#646]
Currently you can pass Skate element constructors as tag names (not raw web component constructors, yet), but you cannot pass a raw function.

They have different outcomes. The Skate custom element constructors convert into a string that is the custom element tag name.

Functions should get executed and passed the attrs / props and children so that they can act as templates. Essentially they become stateless, "private" custom elements that behave like templates, but are just functions and are composable.

JSX would look something like this:

```js
function List (props, chren) {
  return <ul {...props}>{chren()}</ul>;
}

function Item (props, chren) {
  return <li {...props}>{chren()}</li>;
}

<List>
  <Item>item 1</Item>
  <Item>item 2</Item>
</List>
```

This has the greatest impact to templating languages and their ability to compose in functions as tag names, but also can be used by the raw `vdom.element()` function or Incremental DOM functions as they'd be implemented at that level.

```js
vdom.elementOpen(List);
  vdom.elementOpen(Item);
    vdom.text('item 1');
  vdom.elementClose(Item);
  vdom.elementOpen(Item);
    vdom.text('item 1');
  vdom.elementClose(Item);
vdom.elementClose(List);
```

or:

```js
vdom.element(List, () => {
  vdom.element(Item, 'item 1');
  vdom.element(Item, 'item 1');
});
```

**Comment by jpnelson** [comment]
I like it. Looks like https://facebook.github.io/react/docs/reusable-components.html#stateless-functions

**Comment by treshugart** [comment]
The only possible issues with this is memory spikes. If you use this, everything between the opening and closing tag will be deferred until later. Worst-case scenario is that it brings it down to the memory usage of something like React or Virtual DOM that build and then discard large trees.
