### ISSUE TITLE
Consider passing vdom as second argument to render()

### ISSUE THREAD

**Issue by tmpfs** [skatejs/skatejs#659]
I think this would make the API cleaner and would certainly be useful for what I am working on at the moment.

So the signature would become:

```javascript
render(elem, vdom);
```

I took a look at the code to see if this were easy but I am not sure the best way to do this. I figure it's passing another argument to `pathInner` here maybe https://github.com/skatejs/skatejs/blob/master/src/lifecycle/render.js#L27 pointing to the `../api/vdom` module but not certain.

It would be even cooler if we invoked the render function in the scope of the element and just passed `vdom` but that would be a breaking change :(

**Comment by treshugart** [comment]
There's currently other ways to achieve this:

```js
// ES2015 modules
import { vdom } from 'skatejs';

// CommonJS
const { vdom } = require('skatejs');

// Global (and AMD as you'd get the `skate` var from the closure
const { vdom } = skate;
```

Does your use-case prevent this?

> It would be even cooler if we invoked the render function in the scope of the element and just passed vdom but that would be a breaking change :(

Yeah :(. I've explored this [pretty extensively](https://github.com/skatejs/skatejs/issues/510). The gist is:

- Rewriting context can be confusing
- Putting lifecycle members on the prototype has a high chance of collision for ergonomic names
- Symbols are not ergonomic
- Native custom elements has a mixture of static / instance members which is already inconsistent; I'd rather keep all non-public API members in Skate defs static for consistency

The last one is somewhat subjective, though. If you've any other ideas for that feel free to chime in.

**Comment by tmpfs** [comment]
Thanks for taking the time to explain your rationale. I guess my issue is that I don't currently know the style of the input javascript so I don't know whether to create an AST for import, require, AMD or the global variable scenario.

The easiest thing for me to do is enforce ES6 or check the `type` attribute of the `script` element for how to get a handle on the vdom.

I'll work it out ;)

Closing as not an issue.
