### ISSUE TITLE
Symbols not copied when specifying component definition as object literal

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#673]
This won't work:

``` js
const sym = Symbol();
skate.define('x-test', {
  prototype: {
    [sym]() {}
  }
});
```

But this will:

``` js
const sym = Symbol();
skate.define('x-test', class extends skate.Component {
  [sym]() {}
});
```

Workaround is to use ES6 classes when using native symbols, or instead of using a symbol, do something like: `const sym = '____uber_private';`.

A fix for this would be to use `getOwnPropertySymbols()` when copying over the prototype.

**Comment by treshugart** [comment]
Should be fixed by #760. @mcorbanini do we need to write a test for this specifically? Closing for now. Please re-open if so.

**Comment by mcorbanini** [comment]
This is a separated issue, since #760 was only to allow symbols in props not in prototype.

**Comment by treshugart** [comment]
Closing as we'll be removing object literal support in 5.0.
