### ISSUE TITLE
Remove defined attribute

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#688]
Currently we set a `defined` attribute (or customised using the `definedAttribute` option). This has two issues:

1. Can hit performance with lots of web components being initialised at once (minor concern)
2. If a parent component renders a child component, the child component will mutate itself from within the definition by adding the attribute. If the parent component re-renders and decides to remove that attribute because it doesn't know about it (any virtual DOM library could do this) then any styles used to prevent FOUC to undefined components will be reapplied to the element.

GIven the two issues with this, it's probably better to leave it up to the component authors and consumers to come up with a convention for this.

*In native custom elements, you have access to `:defined` to do this, so this really only applies to polyfill-land.*

**Comment by bradleyayers** [comment]
I expect this will be a PITA while we still live in a polyfill world, so if we want to go ahead with this we should have some examples / guides on how to avoid FOUC for _today's_ world.

**Comment by treshugart** [comment]
@bradleyayers some guidance added at https://github.com/skatejs/skatejs#preventing-fouc. We can expand on this as we encounter better workarounds.

**Comment by treshugart** [comment]
[Seems](http://jsbin.com/nivobay/1/edit) that React and Incremental DOM don't actually behave like we had thought and they keep attributes they don't know about, so long as they aren't setting them through their vdom implementations.

Let's revert this change and re-update the docs.

**Comment by bradleyayers** [comment]
Interesting. I knew that React doesn't touch attributes it doesn't know about, but I was under the impression idom did. So does idom have its own virtual DOM representation too? I assumed it traversed and queried the DOM in lock-step with idom function calls?

**Comment by treshugart** [comment]
It does lock-step, but it doesn't query for the current DOM state. Instead stored what they call "node data" on the element with what they currently about it. So in that sense it makes it the same as React. I was quite happy to figure this out about them both (and it seems most, if not all, virtual DOM implementations behave this way). It would be counterintuitive to performance for any implementation to have to query and remove attributes they don't know about. This is actually what caused me to reinvestigate the potential issue. Previously, my tests showed that they removed it, but that's because I had tested it where the vDOM impl knew about the attribute, I believe.

This is good news.

**Comment by treshugart** [comment]
@seancurtis ^. This is good news for a11y.

**Comment by treshugart** [comment]
@jpnelson ^. This may slightly change how we think about smart / dumb components.

**Comment by bradleyayers** [comment]
Cool — thanks for the explanation!

**Comment by seancurtis** [comment]
Wouldn't the attribute cease to exist if React happened to re-render an entire branch of DOM? Or would the attr end up on it again because the component would go through the lifecycle again?

**Comment by treshugart** [comment]
@seancurtis I know there's certain algorithms in IDOM (and possibly React, as well) that will remove an element and re-append it (for retaining focus in large lists, sometimes). In that scenario, it wouldn't remove anything. If any implementation re-renders an entire tree, it goes through the custom element lifecycle again, anyways.
