### ISSUE TITLE
Event listener naming convention

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#694]
Currently the naming convention is `/^on.+/`. However, that would bind a listener for `ce` for an attribute named `once`, which is not ideal as this would be super frustrating to figure debug. We should also allow both camel-cased and dash-cased names. For simplicity, we should probably just allow `/^on[A-Z\-]/` and remove the dash from the beginning of the identifer. This means the following conventions would be supported:

- `onClick` -> `addEventListener('Click')`
- `on-click` -> `addEventListener('click')`

But not:

- `onclick`

**Comment by stevemao** [comment]
just wanna leave this link here so I'm kinda -1 here :) https://w3ctag.github.io/design-principles/#casing-rules

**Comment by treshugart** [comment]
@stevemao the problem here is what do you do with names like `once`? Whitelist / blacklist (hope not)? Do you just bind a listener for `ce`?

Alternatively, if you used props for events, then attaching listeners to standard elements to listen for custom events that bubble wouldn't work. Doing this is actually inline with what other virtual DOM libraries seem to do. I'd prefer to use the DOM standard, but I'm not sure how that can be done without conflicts in a simple way.
