### ISSUE TITLE
[Question] About vs x-tag section

### ISSUE THREAD

**Issue by bigopon** [skatejs/skatejs#702]
> There's no mutating your component's DOM from property accessors which can become unweidly

How does skate differ to xtag in this?

**Comment by treshugart** [comment]
Skate is more akin to React in this sense; it has a single `render()` function. Changing of props (or attributes linked to props) trigger a re-render. Behind the scenes things are handled by [Incremental DOM](https://github.com/google/incremental-dom) so minimal DOM updates occur.

**Comment by bigopon** [comment]
Thank you. I'll close this

**Comment by treshugart** [comment]
No worries. Let us know if you have anymore questions.
