### ISSUE TITLE
Tests cause 100% cpu/loop on Android 4

### ISSUE THREAD

**Issue by bengummer** [skatejs/skatejs#714]
**Steps to reproduce:**
1. Run tests via Android 4.4 emulator using the [Android Studio](https://developer.android.com/studio/index.html).
2. Monitor CPU usage
3. Notice that CPU hits 100%
4. Attempt to use browser inside emulator, notice that it no longer responds to any interaction

This is preventing the Android tests from being run on Browserstack, since the browser seems to hang which causes a timeout/disconnection, which in turn causes the Travis build to fail.

**How to debug**

Can be investigated by opening Chrome's dev tools to link to the Android Studio emulator for debugging:

![image](https://cloud.githubusercontent.com/assets/1089897/17313455/10a07e46-589f-11e6-85af-821f43fc8277.png)

**Comment by treshugart** [comment]
Is this an issue with Skate or one of the polyfills?

**Comment by bengummer** [comment]
Good point, i'll check to see if this is caused further downstream by `skatejs-named-slots`.

**Comment by bengummer** [comment]
on Android 4.4 there are 201 failing `skatejs/named-slots` tests, but it doesn't trigger the high CPU usage seen in `skatejs/skatejs` so will keep digging

**Comment by bengummer** [comment]
Looks like the skatejs tests aren't getting past this line on Android 4.4

```javascript
it('boolean: false -> true -> false', done => {
  const elem = new Elem1();
  fixture(elem);
  afterMutations(
    () => expect(text(elem)).to.equal('closed', 'init'),
    () => props(elem, { open: true }), // <----------- this line
    () => expect(text(elem)).to.equal('open', 'false -> true'),
    () => props(elem, { open: false }),
    () => expect(text(elem)).to.equal('closed', 'true -> false'),
    done
  );
});
```

https://github.com/skatejs/skatejs/blob/1e47dbf/test/unit/vdom/properties.js#L77

**Comment by treshugart** [comment]
cc @nadiam84 I think the problem with android 4.4 is that native accessors are non-configurable. I.e. `Object.defineProperty(proto, 'childNodes', { configurable: false })`.

**Comment by nadiam84** [comment]
Yes, it's because emulators have a very old version of Chrome (less than 40). On real devices it updates like regular Chrome, so it should be fine.

**Comment by bengummer** [comment]
Thanks @nadiam84 i'll close this issue. This means for now we won't be testing Android on Browserstack.

**Comment by joscha** [comment]
I think we have to find a way to test Android. I understand if we can't test on 4.0, ideally we would use 4.4 then, but because of the property overrides that is not possible either, which leaves us with 5.0 - however that one has proxy problems: http://stackoverflow.com/questions/37907739/running-karma-test-in-browserstack-in-mobile - in the worst case we have to keep this open until 6.0 comes along on BrowserStack/Saucelabs

**Comment by bengummer** [comment]
Raised an issue with Browserstack about not being able to test on Android 4.4 because the emulator only offers Chrome 30

**Comment by bengummer** [comment]
just checked and the 100% cpu usage still happens unfortunately when running skate v1.3.1 tests on Android 4.4 emulator

**Comment by treshugart** [comment]
Looks like SauceLabs supports Android 5.1 now (since 5.0 was specified earlier, I'm assuming it wasn't at the time of creating this issue). See https://saucelabs.com/platforms#android.

**Comment by treshugart** [comment]
Closing as this is a pretty old issue that only seemed to affect us at the time.
