### ISSUE TITLE
Abbreviate prop option "attribute" to "attr" for abbreviation consistency

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#720]
Does this also mean we should change `attributeChanged` to `attrChanged`? I tentatively vote "no" because having the full name there is consistent with the spec and somewhat unrelated to `props`.

**Comment by marcoms** [comment]
I agree, `document.registerElement` compatibility is a big plus for skate IMO

**Comment by marcoms** [comment]
Is this still planned for 2.0?

**Comment by andreawyss** [comment]
We can think maybe more as alias to shorten up:

attribute: { source: true }  ->  attr: true
attribute: { target: 'foo-bar' }  -> reflect: 'foo-bar'

**Comment by marcoms** [comment]
Superceded by #975
