### ISSUE TITLE
Multiple versions of skate on a page has issues with reregistering components

### ISSUE THREAD

**Issue by lukebatchelor** [skatejs/skatejs#723]
When multiple versions of skate are on a page attempting to re-register a component will throw an error as a component of that name already exists, (likely due to one instance having registered and then the second instance not having the name in its cache).

Possible fix is when generating the new name, check that it hasnt been registered yet.

**Comment by treshugart** [comment]
For v0 you'll need to `try / catch`. It's also worth measuring performance to see if that degrades it too much.

**Comment by lukebatchelor** [comment]
Would something like this fit both use cases?

```
var isRegistered = function(name) {
  return document.createElement(name).constructor !== HTMLElement;
}
```

**Comment by treshugart** [comment]
The only thing with that is I think there are situations where an element can be an instance of `HTMLUnknownElement`.

**Comment by treshugart** [comment]
I think that wrapping a try / catch around v0 would be faster, but if not you might be able to do (or a variant of):

```js
function isCustomElement(node) {
  const ctor = node.constructor;
  return ctor !== HTMLElement && ctor !== HTMLUnknownElement;
}
```

**Comment by nadiam84** [comment]
Created a PR for this issue #729

**Comment by nadiam84** [comment]
@lukebatchelor 

> Would something like this fit both use cases?

It doesn't work. Because of the CustomElements polyfill. They are changing the HTMLElement, so this `document.createElement(name).constructor !== HTMLElement;` will never be true.

Also, this approach will fire 'create' and 'attributechange' callbacks, which is not good and breaks some tests.
