### ISSUE TITLE
Setting a property to the same value twice breaks setting the value via a linked attribute

### ISSUE THREAD

**Issue by bqx** [skatejs/skatejs#733]
It looks like setting a property to the same value twice is setting the `syncingAttribute` flag to true, but not reaching the `attributeChangedCallback` where it sets the flag to false, because the attribute value is the same.

A fix would most likely involve checking that the new property value is not the same as the old one, and not setting the flag/trying to set the attribute if that is the case.

**Comment by treshugart** [comment]
Fixed in #734. Thanks @bqx!
