### ISSUE TITLE
Document advanced ref and skip behaviour

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#735]
Should call out:
1. `ref` only being called if the reference to the callback changes
2. `ref` is not called when removed, but you can use `WeakMap` to store data without having to clean up
3. `skip: false` on initial render to stamp out a tree, then `skip: true` thereafter
4. `skip: true` plus `ref: mutateDomHere` examples
5. If you mutate the entire element (replace it, remove it, remove `skip`) on an element that has `skip: true`, you will have issues. In this case you should `skip` the parent and create a child that is mutated. This can be done via point 3 or manually creating this element and appending it in `ref` before you do something with it.

**Comment by stevemao** [comment]
Gotta be a bit careful here. Originally I did `<div skip class="contentElement">`, didn't work because

```js
const pm = new ProseMirror({
        place: contentElement, // contentElement is <div skip class="contentElement">
...
```

here prosemirror is probably changing the whole `<div skip class="contentElement">`, so it needs to be

```js
<div skip>
  <div class="contentElement">
  </div>
</div>
```

Probably not directly related to this, but could add something like "when mutating the dom, do not modify the `skip` element".

**Comment by treshugart** [comment]
Yeah, I'll amend the description to account for those types of mutations.

**Comment by thepian** [comment]
I'm very interested in skipping behaviour as I'm trying to use skate rendering on regular DOM and it clears out nested custom elements.

**Comment by treshugart** [comment]
Since we're moving to Preact in #1075, this is no longer necessary. Preact takes over at the rendering level and the consumer is subject to their behaviour, thus offloading our docs to them.
