### ISSUE TITLE
Single argument invocation of vdom.elementOpenStart() is broken.

### ISSUE THREAD

**Issue by bradleyayers** [skatejs/skatejs#740]
When invoking `vdom.elementOpenStart()` with a single parameter, the wrong parameters are incremental DOM. For example this does not work:

    skatejs.vdom.elementOpenStart('div');
    skatejs.vdom.attr('id', 'test');
    skatejs.vdom.elementOpenEnd('div');

JS bin: http://jsbin.com/haxegoraki/edit?html,js,output

**Comment by treshugart** [comment]
Looks like it gives it `b="a"` instead of `foo="bar"`, correct?

<img width="253" alt="screenshot 2016-08-24 09 39 01" src="https://cloud.githubusercontent.com/assets/136556/17913625/cb68c436-69de-11e6-9df4-1a8ceef005f3.png">

**Comment by treshugart** [comment]
In testing this, it looks like it's using the first character of the attribute value for the attribute name and the second character for the value. Doing `w="zyz"` outputs `x="y"`.
