### ISSUE TITLE
Compatibility with webreflection/document-register-element

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#742]
cc @webreflection in case you're interested

**Comment by WebReflection** [comment]
what's the current "_incompatibility_" if I might ask?

is this about using alternatively my polyfill instead of the web components one?

**Comment by treshugart** [comment]
> what's the current "incompatibility" if I might ask?

The one I've just fixed would be that Skate also uses v0 if available and had defined `createdCallback` et al in it's `Component` base class to be called in v0-land. Your fill defined this on the element that gets returned from `super()` and when I tried to call it, it was calling yours instead of mine. I've just moved the logic in to a separate function to get around it. There's some others and I'll annotate those as I go along.

> is this about using alternatively my polyfill instead of the web components one?

Quite possibly, but either way it'd be nice to support both so we can direct Skate users to polyfills that fit their needs. There's still a few things we would need to consider before including it with skatejs/web-components by default. Some things I haven't measured yet are performance and size.

**Comment by WebReflection** [comment]
>  I've just moved the logic in to a separate function to get around it. 
that part changed already locally to indeed avoid overrides when already defined.

You should've filed a bug in my repo ;-) sorry for the inconvenience.

**Comment by treshugart** [comment]
> You should've filed a bug in my repo ;-) sorry for the inconvenience.

I don't really consider it a bug with your repo, though. We should be being defensive about this anyways.

If I do find what I think are legitimate bugs, of course I'll file them with you repo.

**Comment by WebReflection** [comment]
let me know if there's anything else I can help with

**Comment by treshugart** [comment]
Sure, thing. Thanks for responding :)

**Comment by treshugart** [comment]
@WebReflection in https://github.com/WebReflection/document-register-element/pull/67#issuecomment-242031456 you mentioned FF still had some issues? I'm currently seeing some issues where the call to `nodeNames.get()` returns `undefined` at https://github.com/WebReflection/document-register-element/blob/master/src/document-register-element.js#L896. I'm still debugging the issue (could be my fault), but maybe this is something you've already seen?

**Comment by WebReflection** [comment]
please try its latest and let me know . FF Nightly breaks V0 incapable of accepting a string as second argument + other breaks. FF Desktop also has some glitch but right now I have no time to debug it.

**Comment by WebReflection** [comment]
FYI I've apparently fixed every FireFox hiccup with `1.0.7`, you can test pretty much every known browser on this page and see green light: https://webreflection.github.io/document-register-element/test/

**Comment by treshugart** [comment]
IE <= 10 compat blocked by https://github.com/WebReflection/document-register-element/issues/70. Firefox and Chrome are 100% now.

**Comment by treshugart** [comment]
Just opened https://github.com/skatejs/web-components/pull/8.

**Comment by treshugart** [comment]
Workaround for IE fixes was to include the `MutationObserver` polyfill from `webcomponents.js`.

**Comment by treshugart** [comment]
💥 IE9 compat with little work. Thanks @WebReflection!
