### ISSUE TITLE
Multiple skate versions are incompatible when idom.attributes mutation differs

### ISSUE THREAD

**Issue by bradleyayers** [skatejs/skatejs#745]
There's a fundamental problem in living up to

> It works with multiple versions of itself on the page.

due to how skate hooks into incremental-dom. incremental-dom exposes an `attributes` object which can be used to hook into the lifecycle of DOM updates, and skate leverages this to do some internal state tracking.

Unfortunately skate currently assumes that it can safely mutate `attributes.___`, but it forgot that it'll actually be stepping on other versions of itself.

This happened in practice with v1.0.0-beta12 and v1.2.3, because back in v1.0.0-beta12 we had the code:

```
// Attributes that are not handled by Incremental DOM.
attributes.key = attributes.skip = attributes.statics = function () {};
```

but in v1.2.3 we *do* need `attributes.skip` so we have:

```
// Skip handler.
incrementalDom.attributes.skip = function (elem, name, value) {
  if (value) {
    elem[$skip] = true;
  } else {
    delete elem[$skip];
  }
};
```

Unfortunately for me v1.0.0-beta12 was being executed *after* v1.2.3 and clobbering the `attributes.skip` hook.

**Comment by treshugart** [comment]
Isn't this a more fundamental issue with idom? I'm home sick at the moment
but I braided an issue about making multiple idom instances work.

**Comment by treshugart** [comment]
Raised *

**Comment by treshugart** [comment]
There's https://github.com/google/incremental-dom/issues/254. I've been biding my time with it as we haven't run into any issues until now and trying to do higher priority stuff. The gist is that iDOM needs to be updated so that attributes (and other overridables) are injected into the call to `patch()`, `patchInner()`, or `patchOuter()`.
