### ISSUE TITLE
high-level data flow (store) integration example?

### ISSUE THREAD

**Issue by 11111000000** [skatejs/skatejs#752]
redux, baobab or [Elm Architecture ](https://github.com/xgrommx/elm-architecture)
i.e. `connect` function as adapter to render cycle, and maybe `shouldComponentUpdate` analog
(Related to #660)

**Comment by treshugart** [comment]
Don't have one yet, but I really want to get one up. It wouldn't be much different to React et al.

**Comment by marcelklehr** [comment]
I'm also looking for a simple way to use redux (and especially redux-saga) with skatejs. And by the way, skatejs is quite awesome!

**Comment by treshugart** [comment]
@marcelklehr thanks! I really want to get an example up for it, but have limited time atm. Would you want to work together on something? Have you tried anything yet?

**Comment by marcelklehr** [comment]
At the moment I'm planning to extend `skate.Component` as follows:

```js
// hero.js
import * as skate from 'skatejs'
import 'skatejs-web-components'

import { createStore, applyMiddleware } from 'redux'
import createSagaMiddleware from 'redux-saga'

export const $store = Symbol()

export class Component extends skate.Component {
  constructor() {
     // Create a redux-saga store
    const sagaMiddleware = createSagaMiddleware()
    this[$store] = createStore(
      this.constructor.reducer
    , applyMiddleware(sagaMiddleware)
    )
    this[$store].subscribe(() => skate.props(this, this[$store].getState()))
    super()
    sagaMiddleware.run(this.constructor.saga.bind(null, this))
  }
}
```

This expects you to provide a static method called `reducer` and a static method called `saga` which is expected to be a saga. Inside of property setters and event listeners you can then call `el[$store].dispatch({...})`. The resulting state of the reducer will be fed to `skate.props`. I haven't actually tried this, yet, though.

**Comment by bengummer** [comment]
Something like [this gist](https://rawgit.com/bengummer/04ecccc531a35cd166da894303bdf39e/raw/skate_with_redux.html) (pasted below as well) could work.

@treshugart is there a better way than `props(elem, { ... })` to trigger a skate render in response to a Redux store update?

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Redux + skatejs example</title>
    <script src="https://unpkg.com/redux@latest/dist/redux.min.js"></script>
    <script src="https://unpkg.com/skatejs@latest/dist/index-with-deps.min.js"></script>
    <script>
      skate.define('x-redux-counter', {
        props: {
          lastUpdated: skate.prop.number() // seems to be required to trigger re-render
        },
        attached (elem) {
          // set up the Redux store
          elem.store = Redux.createStore((state, action) => {
            if (typeof state === 'undefined') {
              return 0
            }

            switch (action.type) {
              case 'INCREMENT':
                return state + 1
              default:
                return state
            }
          });

          // trigger a skate render when the store is updated.
          // i wonder if there's a better way to trigger a render..
          elem.store.subscribe(() => {
            skate.props(elem, { lastUpdated: Date.now() });
          });

          // start the timer to update the store each second
          setInterval(() => {
            elem.store.dispatch({ type: 'INCREMENT' });
          }, 1000);
        },
        render (elem) {
          const currentCount = elem.store.getState();
          return skate.h('span', currentCount);
        }
      });
    </script>
  </head>
  <body>
    <x-redux-counter>Loading...</x-redux-counter>
  </body>
</html>
```

**Comment by alinnert** [comment]
@bengummer I've got an idea about the rendering after the store updates. Instead of...

~~~javascript
// trigger a skate render when the store is updated.
// i wonder if there's a better way to trigger a render..
elem.store.subscribe(() => {
  skate.props(elem, { lastUpdated: Date.now() });
});
~~~

you could do

~~~javascript
elem.store.subscribe(() => {
  skate.props(elem, { state: elem.store.getState() });
});
~~~

This also triggers a re-render and it makes the data in the store accessible more easily:

~~~jsx
return <div>{elem.state.currentCount}</div>;
// instead of
return <div>{elem.store.getState().currentCount}</div>;
~~~

(Yes, I'm using JSX and I've made the store a little more complex. Normally it won't be a pure number.)

What do you think?

**Comment by treshugart** [comment]
@alinnert you can pass down complex data structures within Skate. Just make sure you declare it as a prop on the child and the parent will pass it down.

**Comment by TeffenEllis** [comment]
@treshugart,

I put together this helper to combine Skate and [Baobab](https://github.com/Yomguithereal/baobab) 😄 
https://gist.github.com/TeffenEllis/a5b898e94663a83fdb11ebfb6ff75cf6

Do you have any suggestions?

Cheers!

**Comment by treshugart** [comment]
Hey @TeffenEllis, that looks awesome! I've [commented](https://gist.github.com/TeffenEllis/a5b898e94663a83fdb11ebfb6ff75cf6#gistcomment-1932131) on that gist with some ideas. Thanks again :)
