### ISSUE TITLE
create a standalone typing module and flowtype module

### ISSUE THREAD

**Issue by stevemao** [skatejs/skatejs#754]
I think it's worth to create them at some point since these two are quite popular.

**Comment by treshugart** [comment]
I've had this in the back of my mind for awhile, I'm glad you brought it up :) I'm assuming this would take refactoring things into flowtype, correct? I guess we wouldn't have to do this completely up front but I haven't done that much investigation of what this would take.

**Comment by stevemao** [comment]
Oh, I'm not saying to refactor this module. I just want the consumers of this module to use this one without defining types by themselves.

**Comment by treshugart** [comment]
Ahh ok. I'd like to experiment using flowtype because it'd probably resolve #596 without having to do the checking with a library.

**Comment by bradleyayers** [comment]
I've been working on a TypeScript declaration:

```ts
declare module "skatejs" {
  export const vdom: any;

  type PropData = { [prop: string]: any };
  export const props: (elem: any, data?: PropData) => void;
  export const props: (elem: any) => PropData;

  export const emit: (elem: any, eventName: string, eventOptions = {}) => boolean;

  export function define(name: string): <C>(component: C) => C;

  export function define<Proto, Props>(name: string, definition: {
    prototype: Proto;
    props: Props;
    created?(elem: Component & Proto & Props): any;
    updated?(elem: Component & Proto & Props, prevProps: { [name: string]: any }): boolean | undefined;
    render?(elem: Component & Proto & Props): () => any | undefined;
    rendered?(elem: Component & Proto & Props): any;
    attached?(elem: Component & Proto & Props): any;
    detached?(elem: Component & Proto & Props): any;
    attributeChanged?(elem: Component & Proto & Props, data: { name: string, oldValue: any, newValue: any }): any;
    observedAttributes?: string[];
  }): { new(...args: any[]): Component & Proto & Props };

  export const symbols: {
    shadowRoot: string | symbol;
    name: string | symbol;
  };

  export const ready: (elem: HTMLElement, callback: (...args: any[]) => any) => void;

  type HOut = () => any;
  type HChildren = string | HTMLElement | null | HOut | HChildren[];
  type HBuilder = (tag: string | Component, attrs?: { [name: string]: string }, ...children: HChildren[]) => HOut;
  export const h: HBuilder;

  export const builder: (...args: string[]) => HBuilder[];

  type PropOptions = {
    attribute?: boolean | string;
    coerce?: (value: any) => any;
    default?: undefined | null | boolean | string | ((elem: any, data: { name: string }) => any);
    deserialize?: (value: string) => any;
    get?: (elem: any, data: { name: string, internalValue: any }) => any;
    initial?: undefined | null | boolean | string | ((elem: any, data: { name: string }) => any);
    serialize?: (value: any) => string;
    set?: (elem: any, data: { name: string, newValue: any, oldValue: any }) => void;
  };
  export const prop: {
    boolean(options?: PropOptions): boolean;
    number(options?: PropOptions): number;
    string(options?: PropOptions): string;
    array(options?: PropOptions): any[];
  };

  export class Component extends HTMLElement {}
}
```

A few notes:

1. In order for `props` to work correctly, the user *must* use a `prop.____()` helper for it will return the correct type. This means the pattern:

    ```ts
    props: { 
        foo: { attribute: true }
    }
    ```

     …will not work, and it would be handy instead to make type parameterised function like:

    ```ts
    props: { 
        foo: prop<any>({ attribute: true })
    }
    ```

    This would allow it to be used with arbitrarily complex types like an array of `Item`:


    ```ts
    props: { 
        foo: prop<Item[]>({ attribute: true })
    }
    ```

    The definition of this function would be quite simple:

    ```ts
    export const prop: {
        <T>(options: PropOptions): T;
        boolean(options?: PropOptions): boolean;
        number(options?: PropOptions): number;
        string(options?: PropOptions): string;
        array(options?: PropOptions): any[];
    };
    ```

2. For ES2015 classes we should use the decorator pattern for, see [this playground](https://goo.gl/YVokx9) for the background.
3. The top level API functions like `ready`, `props`, etc don't have a proper type for `elem`. It might be possible to improve this using type parameters.

**Comment by treshugart** [comment]
> It would be convenient for TypeScript if h actually had a createElement property that was just an alias to itself. This would allow simpler TypeScript configuration:

@bradleyayers I've thought about doing that:

```s
export const h = vdom.builder();
h.createElement = vdom.builder();
```

It feels React specific. I didn't read all the links in your comment, so this may sound naive, but what's keeping `h` from just working? All other Virtual DOM libraries use that.

**Comment by bradleyayers** [comment]
The last link https://github.com/Microsoft/TypeScript/issues/9582#issuecomment-250320276 is a comment from a TypeScript member saying they'd be open to adding a way to say `h`, and have it `just work`.

**Comment by bradleyayers** [comment]
I've raised a PR to do it https://github.com/Microsoft/TypeScript/pull/11267

**Comment by treshugart** [comment]
Closing this in favour of #918 and #926.
