### ISSUE TITLE
Pass vdom as arguments to render() and stateless components

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#761]
### Problem

At the moment, if you author stateless components, you must import `vdom` and use the version that's imported. If your stateless component uses a different instance of the vdom export than what the consuming component is using, the separate versions if Incremental DOM don't know about each other and can't work together, thus you get errors.

### Solution

If we were able to inject the `vdom` instance being used to the function helpers then it wouldn't matter where they were authored, they would be passed the correct instance of the virtual DOM they need to render.

For example:

```js
const Func = (props, children, vdom) => vdom.text('test');
```

### Backward compatibility

It's unclear how one would easily be able to use stateless components in versions of Skate before *and* after this is implemented. It seems they'd have to define the third argument, but fallback to the imported version.

**Comment by bradleyayers** [comment]
```
import { vdom } from 'skatejs';
const Func = (props, children, vdom=vdom) => vdom.text('test');
```

**Comment by treshugart** [comment]
@bradleyayers I'm not sure you're missing anything, was just looking for ideas, really. I think your solution is fine and in instances where that doesn't work, the developer of a stateless component can require it be passed as props, or define a function that takes vdom and returns a stateless function. 

I think you're right; all we should need to really care about is calling a function with a couple arguments. 

If we did do this, it only works for versions that don't make any breaking changes. Then there's no telling what happens.

I'll close this for now.
