### ISSUE TITLE
How to replicate skate home page

### ISSUE THREAD

**Issue by bigopon** [skatejs/skatejs#763]
A few I've notice when comparing my skate elements with skate home page elements demo:

Skate HP elements don't have `__SKATE_DATA`, `__skate_connected` .... etc
Skate HP elements don't have shadow-dom.

So, how do I make my elements in same shape with demo ?

**Comment by treshugart** [comment]
Seems to: 
<img width="514" alt="screenshot 2016-09-02 09 35 10" src="https://cloud.githubusercontent.com/assets/136556/18187865/9634546a-70f0-11e6-9dc7-6758d4f6da0c.png">

That's from the x-counter on skate.js.org. Or did I not read your issue correctly?

**Comment by bigopon** [comment]
Hmm, sorry for that but this is mine,
Please disregard this, was just my curiousity

![different](http://image.prntscr.com/image/c20a2b899fed43faa223ebd5d0fb5fd0.png)

**Comment by treshugart** [comment]
That's interesting. It must have to do with native vs polyfill.

**Comment by treshugart** [comment]
I'm going to close as it seems it's not causing any issues, but feel free to reopen if you find that it is. Thanks :)

**Comment by bigopon** [comment]
Thanks, I was concerned a bit as it may affect styling. I'll put some more in if I hit any problems

**Comment by treshugart** [comment]
It shouldn't affect styling as those are properties (as opposed to attributes).
