### ISSUE TITLE
Using superviews.js as the template library

### ISSUE THREAD

**Issue by davidjamesstone** [skatejs/skatejs#779]
Hi there,

I'm trying to use skate with [superviews.js](https://github.com/davidjamesstone/superviews.js), a template engine that compiles to idom.

Let's say I have a idom function:

```
const skate = require('skatejs')
const IncrementalDOM = require('incremental-dom'),
  elementOpen = IncrementalDOM.elementOpen,
  elementClose = IncrementalDOM.elementClose,
  elementVoid = IncrementalDOM.elementVoid,
  text = IncrementalDOM.text

window.IncrementalDOM = require('incremental-dom')

function foo (data) {
    elementVoid('input', '', [ 'type', 'text' ])
    elementOpen('div', '', null)
    if (data.someCondition) {
      text(data.name)
    }
    elementClose('div')
}
```

How do I go about getting`foo` into a skate component definition such as:

```
skate.define('x-hello', {
  props: {
    name: { attribute: true }
  },
  render (elem) {
  }
})
```

When I run the above, my `<x-hello>` element is successfully created and the `render` method is called. If I call `foo` from with the render though, idom throws an error because both `currentNode` and `currentParent` are both null.

Hope someone can shed some light.

Many thanks

**Comment by treshugart** [comment]
It's likely that you'd need to import `vdom` from `skatejs` which contains patched Incremental DOM virtual element methods. The issue would be that the `incremental-dom` versions imported by Skate would be different than the one you're importing, thus they're keeping track of internal nodes separately.

Try this:

```js
import { define, vdom } from 'skatejs';

// Make sure the functions are available for your template.
window.IncrementalDOM = vdom;
```

You have to do this when using JSX and likely with all other templating languages.

**Comment by treshugart** [comment]
Hey @davidjamesstone, just following up to see if we were able to help.

**Comment by davidjamesstone** [comment]
Sorry for the delay @treshugart. Yes I got it working following your advice.

The libraries work very well together - thanks very much.

**Comment by treshugart** [comment]
Awesome! Glad we could help.

**Comment by robhicks** [comment]
@davidjamesstone, I'm trying to use superviewjs as well. I've tried to follow the interchange between you and @treshugart but still don't understand how to add/update the dom. Do you know of an example (fiddle, etc) that I could look at?

Thanks!

**Comment by davidjamesstone** [comment]
Hi Rob

I have a working example but I'm not a home at the moment. I'll send it over later. Thanks.

**Comment by robhicks** [comment]
@davidjamesstone Awesome. Thanks!

**Comment by davidjamesstone** [comment]
Hi Rob,
 
From memory, this is what I did. It worked but I can't test it at the moment.

Basically, you need to ensure the instance if `IncrementalDOM` is the modified `skatejs` version. I did this using the following before any other code is loaded. 

`
var IncrementalDOM = skate.vdom
window.IncrementalDOM = IncrementalDOM
`

Here's the [gist](https://gist.github.com/davidjamesstone/b0fb9366bbdb40041fe7ce95324c9893).

If you are using browserify (and superviewify), I had to use browserify-shim and include the following code in my `package.json`: 

`
...
"browserify-shim": {
    "incremental-dom": "global:IncrementalDOM"
  },
  "browserify": {
    "transform": [
      "browserify-shim"
    ]
  }
` 
Any trouble please let me know and I'll make you a proper example.

Thanks, Dave.
