### ISSUE TITLE
Allow null element functions

### ISSUE THREAD

**Issue by joscha** [skatejs/skatejs#794]
Right now, one needs to do:

```js
const SomeComponent = () => null;
return (<SomeComponent />);
```

it would be great if we could do:
```js
const SomeComponent = null;
return (<SomeComponent />);
```

without vdom tripping up.

**Comment by bradleyayers** [comment]
What's the real-world use case? I suspect I've been solving these scenarios with ternary expressions:

```javascript
return maybe ? <SomeContent /> : null;
```

**Comment by joscha** [comment]
Yes, I have a component that changes it look and feel (a remove button being there or not) based on some attributes.

it's currently:
```
const Button = isRemovable ? RemoveButton : () => null;

return (<div>...<Button /></div>);
```

**Comment by bradleyayers** [comment]
An alternative syntax that works today is:

```javascript
const button = isRemovable ? <RemoveButton /> : null;

return (<div>...{button}</div>);
```

**Comment by joscha** [comment]
Yes, that's correct - I think for me it's about context and having the actual tag there makes the JSX clearer than doing the inline-JSX in the tertiary statement and then using a variable, but if I am the only one that sees this as an improvement I am happy to close the issue.

**Comment by bradleyayers** [comment]
I'd be interested in knowing if there's prior art for this, e.g. other JSX targets that support null component names gracefully. If so, it's probably worth supporting for the "least surprise" factor, else I'd probably avoid it and follow JSX conventions.

**Comment by treshugart** [comment]
I can see both sides here. In terms of impl deets, this is easy peasy, I think. However, it would be interesting to see what the [JSX spec](https://facebook.github.io/jsx/) says about this. Haven't dug in it for this yet.

**Comment by treshugart** [comment]
Looks like React doesn't handle it: http://www.webpackbin.com/4yU0M1f2-

**Comment by joscha** [comment]
I thought I had used this pattern before - seems I mixed it up with the variable one that Brad suggests. We can close this then.

**Comment by treshugart** [comment]
Yeah that's probably a good workaround. I'm not totally against it. That said, this morning, I thought about the implications of doing it and it became ambiguous as to what the behaviour is:

- do you ignore all content?
- do you just ignore the wrapping element and print all content?

The workaround is more explicit. Maybe this is why React hasn't done it yet (or never will)? Dunno.
