### ISSUE TITLE
prop `set` callback is not called when using MutationObserver custom element polyfill

### ISSUE THREAD

**Issue by bradleyayers** [skatejs/skatejs#796]
Given a component that has a prop with a `set` callback, it's not called for the initial value when a custom element polyfill (that uses MutationObserver) is used.

``` javascript
define('x-test', {
  props: {
    foo: {
      set: (elem, data) => {
      // not called
      },
    },
   },
});
```

When this element is written to the DOM using Incremental DOM and properties are set synchronously, skate doesn't have a chance to jump in with its `Object.defineProperty()` calls to register the `set` callback.

This means that the `set` callback is never called the first time a property is set in environments like Firefox.

**Comment by bradleyayers** [comment]
I've written some tests to expose this class of problem, I'd appreciate feedback on whether everyone agrees they're valid scenarios https://github.com/skatejs/skatejs/compare/master...796.

**Comment by treshugart** [comment]
I've definitely encountered https://github.com/skatejs/skatejs/compare/master...796#diff-ceb47ff514aaed213966dd46c38df36dR65 before. This exists whether or not you pass in a constructor; it just has to eventually be a custom element.

**Comment by bradleyayers** [comment]
The results of the tests are:

```
Chrome 53.0.2785 (Mac OS X 10.11.6) lifecycle/property api set() for elements initialised from the DOM is called for attribute props FAILED
	Error: Uncaught AssertionError: expected 0 to equal 1 (node_modules/chai/chai.js:206)
Firefox 48.0.0 (Mac OS X 10.11.0) lifecycle/property api set() for elements initialised from the DOM is called for a non-attribute prop when a property is synchronously set FAILED
	AssertionError: expected 0 to equal 1 (:0)
Firefox 48.0.0 (Mac OS X 10.11.0) vdom/properties should set props as properties instead of attributes on ctor references FAILED
	expected undefined to equal 'bar'
	AssertionError@node_modules/chai/chai.js:5553:18
	[3]</module.exports/Assertion.prototype.assert@node_modules/chai/chai.js:206:13
	assertEqual@node_modules/chai/chai.js:776:7
	[10]</module.exports/ctx[name]@node_modules/chai/chai.js:4192:18
	@webpack:///test/unit/vdom/properties.js:76:6 <- test/unit.js:5843:8
	patchInner<@webpack:///~/incremental-dom/dist/incremental-dom-cjs.js:595:2 <- test/unit.js:1390:4
	f@webpack:///~/incremental-dom/dist/incremental-dom-cjs.js:566:4 <- test/unit.js:1361:6
	@webpack:///test/unit/vdom/properties.js:73:4 <- test/unit.js:5840:6
```

**Comment by bradleyayers** [comment]
> This exists whether or not you pass in a constructor; it just has to eventually be a custom element. The problem with that one is that it checks prop in props, and since it hasn't been defined / upgraded in polyfill land yet, the custom element constructor can't be retrieved to check.

Yes, exactly. I feel like in this scenario since **we have** the actual Ctor (as opposed to just a tag-name) it seems plausible that we should be able to upgrade the element immediately to add `.props`, before the attributes are set?

**Comment by treshugart** [comment]
> it seems plausible that we should be able to upgrade the element immediately to add .props, before the attributes are set?

That'd work for a constructor, but not if you pass the tag name of the custom element, which would be forcing a fix for one thing where we can probably still just leave it up to the polyfill and possibly fix the issue by triggering `set()` for props that were set prior to upgrading.

**Comment by treshugart** [comment]
I think maybe [here](https://github.com/skatejs/skatejs/blob/master/src/api/define.js#L70), we could do something like:

```js
function createInitProps(Ctor) {
  const props = ensurePropertyDefinitions(Ctor);

  return (elem) => {
    if (!props) {
      return;
    }

    Object.keys(props).forEach((name) => {
      const shouldTriggerInitialSet = name in elem;
      const prop = props[name];
      prop.created(elem);

      // https://bugs.webkit.org/show_bug.cgi?id=49739
      //
      // When Webkit fixes that bug so that native property accessors can be
      // retrieved, we can move defining the property to the prototype and away
      // from having to do if for every instance as all other browsers support
      // this.
      Object.defineProperty(elem, name, prop);

      // In polyfill-land, if an element's properties are set prior to upgrading,
      // the setter will never be called.
      if (shouldTriggerInitialSet) {
        elem[name] = elem[name];
      }
    });
  };
}
```

**Comment by bradleyayers** [comment]
> but not if you pass the tag name of the custom element,

I'm happy with this behaviour. The contract would be:

> If you pass the constructor to vdom (as opposed to the tag name) you can safely pass any JavaScript object through as attributes and they will be set as properties.

**Comment by bradleyayers** [comment]
> I think maybe here, we could do something like:

This won't catch the scenario where an attribute is set but not the property:

1. Elements written using a HTML API.
2. Elements created via incremental DOM where `.props` isn't defined when attributes are being applied.

We could conceivably fix (2) in vdom if we have the Ctor reference.

**Comment by treshugart** [comment]
I'm not a big fan of making assumptions about how APIs are delivered. If someone gives you a component, but doesn't export the constructor and you want to use it, and set props, then you're broken. I think we need to fix both scenarios here.

You're right, that may not catch attributes set instead of props. This can also be handled though in the same way we just have to check if the prop has a reflected attribute or if the prop is in elem.

**Comment by treshugart** [comment]
They could get the constructor from `customElements.get(name)` but then we're making an assumption about the v1 API and we haven't removed v0 support yet.

**Comment by treshugart** [comment]
@bradleyayers we're removing support for v0 soon in #710, if that helps bump this along.

**Comment by bradleyayers** [comment]
I wouldn't have thought that would make any difference here, since this issue is fundamentally caused by the polyfill.
