### ISSUE TITLE
using Skate without Shadow DOM/Shadow Roots?

### ISSUE THREAD

**Issue by priley86** [skatejs/skatejs#802]
@treshugart thanks for contributing this library, it's a wonderful implementation.

My only question is are there any plans to optionally render custom elements without shadow DOM/shadow Roots? This would open up this library to potentially many more audiences and use cases. To add some context to this, many teams who have previously developed pattern libraries in things like jquery/plain old css and have strict browser requirements will be slowly adopting new custom element strategies. Rob Dodson's [post](https://medium.com/dev-channel/the-case-for-custom-elements-part-1-65d807b4b439#.rkh1bg503) details this migration strategy well:

jquery/css  =>  CEs  => CEs + Shadow DOM (when browser support improves)

What would be nice is to be able to use this library and take advantage of Incremental DOM now (while not adopting Shadow DOM until later).

Would you potentially explore this? Or maybe a fork of this could?

**Comment by treshugart** [comment]
I need to unhide this in the docs:

> Skate will work without Shadow DOM support, but you won't be able to compose components together due to the lack of DOM encapsulation that Shadow DOM gives you.

So you *can*, you just can't add content to your components as light DOM. See http://www.webpackbin.com/NJKsxfdnW. The only issue comes when you want to add light DOM to a component; Incremental DOM will overwrite any content added to your element that isn't in `render()` because there's no shadow root to encapsulate your component.

**Comment by priley86** [comment]
@treshugart thanks for this response, this is helpful to know that Skate would remove any light DOM. After looking at your webpackbin, I suppose I should follow up with another question. 

Is there anyway to configure Skate to **not** create shadowRoots for the custom element's nested markup? While it may be feasible to style the host element, having the option to still style the nested markup/rendered vdom with external/global styles would still be a nice add (for some teams). I know the better approach is to use Shadow DOM and encapsulate CSS (and I know you've proposed using CSS modules), but for teams which have strict browser requirements and are exploring CEs for JS/HTML encapsulation only, having the option to remove shadowRoots would make Skate applicable (this way external css can still be used).

**Comment by treshugart** [comment]
I'm not sure if I'd want to add a configuration option to do it as it's a fairly fundamental benefit of using web components. That said, a way you could do this now would be to do something like:

```js
import { define } from 'skatejs';

define('x-test', {
  prototype: {
    // This should be fine for most browsers now
    attachShadow() {
      return this;
    },

    // However, in old Chrome / Opera or old polyfills
    // you might need to do this.
    createShadowRoot() {
      return this;
    }
  }
});
```

If you find yourself having to do this a lot, you can create a base class that extends `skate.Component`, or use a composable function:

```js
function noShadowDOM(opts = {}) {
  return Object.assign(opts.prototype || {}, {
    attachShadow() {
      return this;
    }
  });
}

define('x-test', noShadowRoot({
  render() {}
});
```

**Comment by priley86** [comment]
Thanks so much for this @treshugart, this is exactly what we needed to know!

**Comment by bedeoverend** [comment]
@treshugart in overriding `attachShadow` - can you see any dangers in doing that? e.g. a library talking to elements in general and expecting shadow roots?

**Comment by bedeoverend** [comment]
also would skate ever consider the option of having two render pipelines? Not sure how you'd implement that, but in the case of an element that wants to have perhaps complete control over it's light DOM based on its props, but also needs Shadow DOM?

**Comment by treshugart** [comment]
@bedeoverend 

> in overriding attachShadow - can you see any dangers in doing that? e.g. a library talking to elements in general and expecting shadow roots?

Possibly, but the library that's talking to those elements should check for a `shadowRoot` property. However, since it wouldn't exist if `{ mode: 'closed' }`, then I'm not sure there'd be a reliable way for an external library to do this unless they overrode `attachShadow`, too. That could be troublesome, for sure.

> also would skate ever consider the option of having two render pipelines? Not sure how you'd implement that, but in the case of an element that wants to have perhaps complete control over it's light DOM based on its props, but also needs Shadow DOM?

I'm probably projecting here, but could you be talking about custom form elements :p? I've definitely seen a need for that. Maybe this is a good path to that? What is your use case here? cc @bengummer

**Comment by bedeoverend** [comment]
@treshugart it's certainly an edge case, but yeah it feels a little odd overriding the `attachShadow` - not sure if it's in Skate's scope, but perhaps a toggle for where to render to? Or overriding the render function on Skate's base component class even? Interestingly - @matthewp _just_ [floated this](https://github.com/matthewp/bram/issues/18) as an idea on his Bram library.

Re: rendering to both - haha, well actually I was thinking of our Simpla elements - the elements themselves are designed to have complete control over their children based on their props / internal state, I really like Skate's render pipeline but would obviously want to render into light dom. There's also however the benefit of hiding the element's controls away inside its Shadow DOM, so being able to render into both based on prop changes would be 👌

**Comment by bengummer** [comment]
@treshugart yeah having separate `render()` functions for light + shadow DOM would allow the element to expose form elements in light DOM (so things like native form behaviour work as expected).

Once there is official support for custom elements exposing their own form values ([spec discussion](https://github.com/w3c/webcomponents/issues/187)) this dual-render functionality wouldn't be needed for forms anymore.

If native form behaviour is the only use case here then it may be better to just document the `attachShadow` workaround (i.e. inserting form elements into light DOM so the `<form>` can see them). If there are other uses cases then maybe dual-render would be worth it.

**Comment by treshugart** [comment]
Once #872 is merged, we'll officially document the `rendererCallback()` which can be used to implement a custom renderer. It'd be up to the renderer to call `renderCallback()`, so it could have an alternate render, or do whatever it wants at that point. This is still undocumented, though, as I still have questions around how to make the Incremental DOM renderer optional. This will probably happen through mixins, where you'd have a `RenderMixin()` that an `IncrementalDOM` mixin extends. The base `RenderMixin()` could just enforce that you provide it a renderer.

**Comment by matthewp** [comment]
Biggest reason I see to render to the light DOM is for styling (as ironic as that is). Until `@apply` is a real thing theming in shadow DOM is going to be hard, and for small projects without a full time designer it might be more trouble than it's worth. For components that don't need distribution, I don't see a disadvantage to rendering to light DOM.

**Comment by treshugart** [comment]
@matthewp the only issue there is hiding the shadow root template from any parent virtual DOMs that may have rendered the component with light DOM that would normally be slotted. In most implementations if you `render()` to the component as light DOM, it will be removed by the diffing algorithm. In order to do this, you'd need to fake `childNodes` and anything else the algorithm is interested in. I can see this as being implemented as a mixin or something.

**Comment by alexlafroscia** [comment]
is there a way to do this with the current (at time of writing, 4.6.6) version of Skate? I tried overriding `attachShadow` as mentioned above but it throws a JS error:

```
Uncaught TypeError: Cannot read property 'ownerDocument' of null
    at e (index-with-deps.min.js:1030)
    at Function.value (index-with-deps.min.js:1)
    at HTMLElement.value (index-with-deps.min.js:1)
    at HTMLElement.value (index-with-deps.min.js:1)
    at MutationObserver.<anonymous> (index-with-deps.min.js:1030)
```

**Comment by treshugart** [comment]
@alexlafroscia yeah, my code above wasn't exact. I've created a [working example](http://jsbin.com/warehic/8) for you that uses it like a mixin so it's easy for you to share. The code above should have taken into account both ways to access the shadow root (property and function return value).

**Comment by alexlafroscia** [comment]
Ahh, very interesting! Thanks. I've been trying to get a server-side-rendering story put together and disabling the Shadow DOM is a req for that.

**Comment by priley86** [comment]
@treshugart we may be considering Skate.js again for some of our new components after reviewing the Angular integration example here:
https://github.com/Hotell/angular-skate-talk-demo

This is quite a compelling demo. The only issue I have there is still the required use of `slot`/shadow roots for light DOM scenarios (transcluded content like the `<img>`). It works great in new browers, but we still have the need to support CEs in cases w/o Shadow DOM (the original intent of this issue). 

It looks like the working example/jsbin link above is no longer working. Can you provide this sample once more?

I've noticed when implementing things like conditional rendering/event handlers inside the light dom with JSX gets really hairy with Mutation Observers (i.e. you have to move elements with `appendChild` if actually transcluding them to maintain event listeners). It would be great to solve this problem with Skate JS and write component APIs that are very flexible to whatever the user wants in the light DOM...

ex w/ Mutation Observer (remove Secondary button fails b/c element has been moved and JSX can no longer find it):
https://stackblitz.com/edit/using-pf-tabs-in-reactjs?file=index.js

**Comment by priley86** [comment]
It looks like `real-dom` implemented here may help in conjunction w/ using a custom renderer in the render callback? 
https://github.com/skatejs/val#real-dom

**Comment by treshugart** [comment]
@priley86 you can definitely use real-dom from val, but you just won't get the DOM diff algo from Preact. If you're rendering to light DOM, it's likely you can't do this anyways because of it becoming out of sync with it's view of the world.

**Comment by treshugart** [comment]
JSBin is down for me, so I can't check that example, unfortunately.
