### ISSUE TITLE
inconsistent behaviour by setting element property via attribute

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#840]
Currently skate behaves inconsistent when property value is set within HTML via attribute and when it's set from within custom element to other nested custom element.

I've created plnkr:

https://plnkr.co/edit/flbU9Pt1nxqUFXCnPJuq?p=preview

thing is, if you set attr/prop syncing via `{attribute: true}` it works consistently but that's quiet confusing

here is root component:

``` js
class Foo extends Component {
  static get is(){return 'my-foo'}
  static get props(){
    return {
      label: prop.string({
        // attribute:true
      }),
      done: prop.boolean({
        // attribute:true
      })
    }
  }
  static render(elem){
    const {label,done} = props(elem);
    return <main>
      <div>
        hello <b>{label}</b>.
        <br/>
        <i>I am {done ? 'DONE':'NOT FINISHED'}</i>
      </div>
      <div>
        <iron-icon icon="boom"></iron-icon>
        <Icon icon="moom"/>
        </div>
      </main>
  }
}
```

here is nested component

``` js
class Icon extends Component {
  static get css(){
    return `
      :host{
        display: block;
      }
    `
  }
  static get is(){ return 'iron-icon'}
  static get props(){
    return {
      icon: prop.string({
        // attribute:true
      })
    }
  }
  static render(elem){
    const {icon} = props(elem);
    return [
      <style>{Icon.css}</style>,
      <i>{icon}</i>
    ]
  }
}
```

so if I use root component like this:

``` html
<my-foo label="World" done></my-foo>
```

properties are not set correctly and have default value (`done===false; label===""`).
One has to explicitly set those prop definitions to `{attribute:true}` to make it work, which makes sense right ? ( attr/prop sync )

What is not ok is that when you use that `Icon` component within `Foo` it works without setting  `{attribute:true}`

``` jsx
        <iron-icon icon="boom"></iron-icon>
        <Icon icon="moom"/>
```

**Comment by treshugart** [comment]
If this is the same issue I'm experiencing, then it will fail in polyfill-land even if you use `Icon` with `Foo`.

cc @bengummer

**Comment by bengummer** [comment]
i've just written a test to demonstrate this behaviour (code at  https://github.com/skatejs/skatejs/commit/a63d8f1b3cef4b11a9ea02b99530eb2ca8ce73a6 and travis build [here](https://travis-ci.org/skatejs/skatejs/builds/166635121))

it looks like when we generate an element inside `render() { ... }` the generated element's attributes are actually set by vdom as props. This would be ok if the generated props got sync'd to attributes, but that doesn't happen if the prop/attr isn't linked.

cc @treshugart

**Comment by treshugart** [comment]
When you go through `render()`, it prefers properties if available. This is why you're seeing this behaviour, I think. Nonetheless, this is intentional, so I think I'm going to close this. What might change in the future is that props may end up automatically syncing from attributes (auto-linked) but that's still under discussion in #838.
