### ISSUE TITLE
FOUC when nesting components

### ISSUE THREAD

**Issue by bradleyayers** [skatejs/skatejs#846]
When rendering a skate component *within* another skate component, the nested component is vulnerable to a FOUC.

This can occur when the nested component has a prop that directly affects the way the component is rendered. Consider the following:

```js
define('x-parent', {
  render(elem) {
    return h('x-child', { active: true });
  }
});

define('x-child', {
  render(elem) {
    return h('p', { class: elem.active ? 'active' : '' });
  },
  
  props: {
    active: {}
  }
});
```

The problem occurs when rendering `<x-parent />`.

Sequence of events:

1. `<x-parent />` is added to the DOM, and its `connectedCallback` synchronously causes `render()` to be invoked.
2. `<x-child />` is synchronously added to the DOM via incremental-dom, (but importantly *without* an `active` attribute).
3. `x-child`'s `render()` function is synchronously invoked (again via `connectedCallback`) causing `<p class=""></p>` (at this time `active` is `false`) to be added to the DOM.
4. Incremental DOM now applies `active=true` attribute to `x-child`, which uses skate's overridden behaviour to actually apply the attribute as property (`node.active = true`).
5. The `active` property setter is invoked, [which schedules a `render()` *on the next tick*](https://github.com/skatejs/skatejs/blob/master/src/lifecycle/props-init.js#L73).
6. *One tick passes.*
7. `x-child`'s `render()` function is invoked, and adds `active` to the `<p>` element.

Here's a demo: http://www.webpackbin.com/N1Rm2yEAZ

There's a simple way to solve this — don't debounce `render()` when a property changes. However this would introduce a performance problem when setting multiple properties, as it would cause multiple renders:

```js
elem.foo = true;  // triggers render()
elem.bar = true;  // triggers render()
…
```

The whole point of the debouncing is ensure only *one* invocation of `render()` occurs regardless of the number of properties that are set.

**Comment by bradleyayers** [comment]
I have a proposal which I think is reasonable:

1. Setting a property or attribute that corresponds to a prop causes an immediate synchronous render of the component.
2. When setting multiple properties, it's possible to avoid intermediate (between property mutations) renders by using the `props` utility.
3. Update the incremental-dom integration to utilise the same underlying mechanics as `props`.

In the original example in this issue, this proposal would change the sequence of events to:

1. `<x-parent />` is added to the DOM, and its `connectedCallback` synchronously causes `render()` to be invoked.
2. `<x-child />` is synchronously added to the DOM via incremental-dom, (but importantly *without* an `active` attribute).
3. `x-child`'s `render()` function is synchronously invoked (again via `connectedCallback`) causing `<p class=""></p>` (at this time `active` is `false`) to be added to the DOM.
4. Incremental DOM enters the phase were it sets attributes on `x-child`, but first sets a flag via `beginPropsTransaction()`. (**new**)
5. Incremental DOM now applies `active=true` attribute to `x-child`, which uses skate's overridden behaviour to actually apply the attribute as property (`node.active = true`).
6. The `active` property setter is invoked, but observes that it's currently within a prop transaction, and so **does not** schedule a `render()`. (**changed**)
7. Incremental DOM finishes its setting-attributes phase, and clears the flag via `endPropsTransaction()`. (**new**).
8. During `endPropsTransaction()`, `x-child`'s `render()` is synchronously invoked, which adds `active` to the <p> element.

A further optimisation could be made to remove the initial `render()` during `connectedCallback`, by having special integration with incremental-dom, but that is not the target of this issue.

**Comment by treshugart** [comment]
> Concretely we need to update react-integration to do this.

react-integration can't cater to any specific library / framework. To it, things are just vanilla web components.

**Comment by bradleyayers** [comment]
> react-integration can't cater to any specific library / framework. To it, things are just vanilla web components.

Ah good point. If performance is an issue, we can always go down the path of a skatejs-react layer that knows about skatejs specifics (i.e. `props`) to do more efficient rendering.

**Comment by treshugart** [comment]
> Ah good point. If performance is an issue, we can always go down the path of a skatejs-react layer that knows about skatejs specifics (i.e. props) to do more efficient rendering.

And also, as discussed IRL, the browser should only do a single repaint / reflow anyways. It's just that when using a component outside of Skate (raw web component), `render()` will get called for every single one, and Incremental DOM patches will occur, but if there's no reads in between of props / attrs that cause reflow / repaint, then the browser should only do it once. The main overhead here is Skate / iDOM runtime.
