### ISSUE TITLE
attribute linked properties reflect state after 2nd mutation in browsers with native shadow DOM ( Chrome,Safari)

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#847]
When defining component property linked to DOM attribute via `{attribute:true}`, **it doesn't do anything on first mutation via `setAttribute`.**

Looks like this issue is only in browser which have native shadow dom v1 ( chrome, safari 10 )

**Chrome:**

![skate-linked-attribute-chrome-bug](https://cloud.githubusercontent.com/assets/1223799/19242383/25242f3e-8f13-11e6-9529-57fecb1e485e.gif)

**Safari:**

![skate-linked-attribute-chrome-bug_sa](https://cloud.githubusercontent.com/assets/1223799/19242390/2e205e78-8f13-11e6-8b9a-a2f7de69f240.gif)

**Firefox ( works as expected ):**

![skate-linked-attribute-chrome-bug_ff](https://cloud.githubusercontent.com/assets/1223799/19242394/340da4d0-8f13-11e6-86c0-007047509d6e.gif)

Example:

https://plnkr.co/edit/UNZYkOQ0EeUrGHeo85Iy?p=preview

maybe this is unrelated but why does `skatejs-web-components` add deprecated `registerElement` do `document` instead of polyfilling just actual v1 spec? "thanks to that" [both flags(customElement)](https://github.com/skatejs/skatejs/blob/master/src/util/support.js#L4-L5) are always true

**Comment by treshugart** [comment]
> aybe this is unrelated but why does skatejs-web-components add deprecated registerElement do document instead of polyfilling just actual v1 spec? "thanks to that" both flags(customElement) are always true

That's a side-effect of [`document-register-element`](https://github.com/webreflection/document-register-element) that it brings in.

**Comment by treshugart** [comment]
I think this is either an issue with [`document-register-element`](https://github.com/webreflection/document-register-element) not reflecting the change properly, or the internal flags that we keep being out of sync. We keep flags so that recursion doesn't happen when reflection attrs / props. I think we'll probably implement #838 as proposed which will remove the need for the flags and make reflection simpler.

**Comment by Hotell** [comment]
I've switched from `document-register-element` to [custom-elements](https://github.com/webcomponents/custom-elements). Issue still remains.

https://plnkr.co/edit/yF83goIEcZ95dGelKb8z?p=preview

So there are 2 possible reasons why is this happening:
- both polyfills have bug
- skate has damaged tail or nose, so we can't ollie properly :)

**Comment by Hotell** [comment]
I did further investigation/debugging

**Results:**

[`Component.prototype.attributeChangedCallback`](https://github.com/skatejs/skatejs/blob/master/src/api/component.js#L178) is called **once** in Chrome/Safari and **twice** in Firefox on attribute Mutation. 

This resolves in behaviour that in FF, internal `__SKATE_DATA` for `greet` property, which has both flags after attaching to DOM set to true( **IMO that's the issue** ),
```
{
  settingAttribute: true
  syncingAttribute: true
}
```
is toggling the  `syncingAttribute` to `false` so the second call of `attributeChangedCallback` will allow it to go to `else` branch
```
 if (propData.syncingAttribute) {
          propData.syncingAttribute = false;
        } else {
          // Sync up the property.
```
and set the property correctly.

After the attrs/props are synced both flags are set to **`false`**
```
{
  settingAttribute: false
  syncingAttribute: false
}
```
so after that everything works as expected.


So I think to fix this issue, we need to properly resolve the flags after the element is attached to the DOM to `false`

**Comment by treshugart** [comment]
Do you know if this is still an issue in latest?

**Comment by Hotell** [comment]
Will retry with latest skate+polyfills later on today and will get back to you with results. thanks

**Comment by Hotell** [comment]
unfortunately, issue is still valid 
https://plnkr.co/edit/UNZYkOQ0EeUrGHeo85Iy?p=preview

**Comment by camwest** [comment]
For what it's worth this bug breaks compatibility with Angular 1.x which uses setAttribute when interpolating:

```
<x-button label="{{app.myLabel}}"></x-button>
```

When app.myLabel is resolved it calls setAttribute once but due to this bug it does not re-render the component.

**Comment by camwest** [comment]
Here is the workaround that resolves the issue for me:

```
import {props, Component} from 'skatejs';

class Button extends Component {
  // ...props
  static attributeChanged(elem, {name, newValue}) {
    props(elem, {[name]: newValue});
  }
 // ... render
}
```

**Comment by Hotell** [comment]
@camwest workaround === hack IMHO, I really hate hacks :) as previously discussed, issue is in how skate resolves "flaging" toggles for props lifecycle

**Comment by treshugart** [comment]
Definitely, but it's at least a way to get around it. I've been wanting to fix this but am strapped for time ATM. Is one of you able to submit a PR?

**Comment by andreawyss** [comment]
This issue is resolved.
