### ISSUE TITLE
Comparison to riot.js?

### ISSUE THREAD

**Issue by micahscopes** [skatejs/skatejs#856]
I've been using riot, and am feeling that it's become a little more complicated than I'd hoped for.  Maybe you could include a comparison of skatejs to riot in your documentation?  I'd be curious to read some developer perspective.

**Comment by treshugart** [comment]
Hey @micahscopes, good point, probably should do that with others like Vue and Choo, too.

To address your question here, off the top of my head, the biggest differences are:

- Skate leverages the platform. What you build is consumable without the consumer having Skate, or even knowing about it. They're just web components. REAL web components.
- Skate will get smaller as the platform evolves.
- Skate leverages Incremental DOM (but we're spiking making this configurable)

Please let us know if you have any feedback or more questions. I've raised an issue in #857 so I'll close this for now. Thanks :)

**Comment by micahscopes** [comment]
Thanks for the perspective.  I'm really feeling the simplicity.  I find
myself digging and digging for modular javascript.  Slowly but surely I
have accumulated a collection of favorite libraries that work together well!

I'm seeing a ton of potential with combinations like skate+kefir+handlebars
or skate+d3.  Yeah... can't wait to try skate with d3...
