### ISSUE TITLE
WebComponents basics

### ISSUE THREAD

**Issue by micahscopes** [skatejs/skatejs#859]
I'm pretty new to skatejs and the web components spec.

I want to create a custom element that interacts with and augments whatever you put into it.  For example:

```html
<washing-machine>
  <img/>
  <img/>
</washing-machine>
```
I want the `washing-machine` element to start spinning those images around and playing with their positions and sizes.  

I also want to create some bubble and water effects with a `canvas` or `svg` or something in the shadow dom.  But at the same time, I don't want to interfere with someone adding another piece of laundry to the `washing-machine`, or maybe a `sudsy-soap` element.  If I've written my `washing-machine` component well, it will recognize that a `sudsy-soap` element deserves special treatment.  It might even "dissolve" it after a while.  

I found this helpful quote [here](https://webkit.org/blog/4096/introducing-shadow-dom-api/):
> Conceptually, slots are holes in a shadow DOM that will be filled by children of its host element.

I see stuff about the `slot` element, and feel that my question probably has something to do with this, but am not sure where to turn to learn more.  As an uninitiated web components newbie, I'm having trouble sorting through to understand what my basic legos are and how they snap together.

Is there a repository of examples somewhere on how to do this sort of thing? Maybe a hidden stash of jsbin, plunker or gist examples somewhere?

The documentation could use some fleshing out in this area.  Introducing basic web components concepts from the skatejs point of view.

**Comment by micahscopes** [comment]
Okay, I think I'm figuring this out.

Here's a tag called `whats-the-magic-word`:
```html
<whats-the-magic-word>
broccoli salad
</whats-the-magic-word>
```

Needless to say, if you guess the magic word you will be rewarded!
https://jsbin.com/wababu/63/edit?html,output

**Comment by treshugart** [comment]
In this case, it's acceptable to travers your children and spin each one.

```js
function spinItem(item) {
  // spin item
}

function spinItems (e) {
  const slot = e.target;
  const items = slot.assignedNodes();
  [...items].forEach(spinItem);
}

define('washing-machine', {
  render() {
    return h('slot', { onSlotchange: spinItems });
  }
});
```

You can even separate different items into different slots:

```js
<washing-machine>
  <item-clothing />
  <item-sudsysoap slot="soap" />
</washing-machine>
```

And then you'd have different slots for each one, each with a different `onSlotchange` handler.

```js
function spinItem(item) {
  // spin item
}

function spinItems (e) {
  const slot = e.target;
  const items = slot.assignedNodes();
  [...items].forEach(spinItem);
}

function dissolveItems (e) {
  // do something similar to spinItems here
}

define('washing-machine', {
  render() {
    return [
      h('slot', { onSlotchange: spinItems }),
      h('slot', { name: 'soap', onSlotchange: dissolveItems });
    ];
  }
});
```

**Comment by treshugart** [comment]
Haha! Yeah, you've got the hang of it with that, pretty much. I think it would be a good idea to add docs about what slots are; specs aren't the most accessible things for people to digest. I'll close this now, but feel free to reopen if you have any more questions. Thanks!

**Comment by micahscopes** [comment]
@treshugart this is really great, thanks!
