### ISSUE TITLE
Add slot() prop type

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#863]
### Problem

As a developer, I want a prop to update whenever a slot is assigned nodes so that my component is re-rendered. This prop should contain all of the assigned nodes as an array for the corresponding slot.

Slots have a `slotchange` event that fires when elements are slotted, but it doesn't seem to fire on initial slotting, for example if you render your shadow root with slots _after_ the host element contains children.
### Solution

We have a few options:
1. add a ref with a `setTimeout()` - because you cant trigger a re-render in `render()` - to init the slotted nodes
2. create a custom function helper for a slot that does the above
3. create a custom prop that uses a `MutationObserver` to listen for changes on the host and updates the prop when it changes

Options 1 and 2 are not ideal because they use `setTimeout()` and all the baggage that comes with it. Option 3 isn't perfect because it doesn't use `slotchange` at all. It completely subverts it and uses a `MutationObserver` instead (which _does_ have the same timing).

Option 3 could be altered to not use mutation observers, but then you'd have to declare a `slot()` prop along with a `slotchange` handler. This means declaring code in two separate spots. I did try doing this, but it's more to manage and worry about over just declaring a slot prop and being done with it.
### Spike

The slot prop accepts a `slot` option that corresponds to the `name` of the `<slot />` element the prop should represent. If not given, it defaults to `null` which means it should be used for the default slot.
### Potential issues

Performance with several mutation observers. However, they don't pose a performance issue if you are not modifying anything that they're not supposed to be listening to. The logic within them should also have little overhead. The only consideration here is filtering the array of `children`, but that's quick unless you're doing hundreds of thousands of them.
### Todo if accepted

If this solution is accepted, we should notify the W3C of our workaround and why `slotchange` didn't work for us.

**Comment by bradleyayers** [comment]
> As a developer, I want a prop to update whenever a slot is assigned nodes so that my component is re-rendered. This prop should contain all of the assigned nodes as an array for the corresponding slot.

Can you go into more detail about:

- whether you really want a prop to update, or you want the component to re-render
- the use-case for wanting the prop to contain all the assigned nodes as an array?

**Comment by treshugart** [comment]
> whether you really want a prop to update, or you want the component to re-render

You'd want both because you want to use the value in `render()`.

> the use-case for wanting the prop to contain all the assigned nodes as an array?

This might be a better question to answer before the first one. If we don't want / need this then the answer to the first question would be we only want it to render so that we can get the information. It's more than likely you'll want this in array format if your using functional / declarative style templates like JSX.

**Comment by treshugart** [comment]
Closing this for now as we've lived without it for this long and #995 will affect how this is implemented, and possibly change it. Probably better to start with a fresh mind once that puzzle piece is solved.
