### ISSUE TITLE
Closer to the platform

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#872]
Skate components should be definable via `customElements.define()` and `skate.define()` should become a syntactic sugar for anonymising components, and that's all. This piggy backs off #867 which implements #710.

**Comment by zzarcon** [comment]
This means that we will deprecated `skate.define` at some point and encourage the users to just pass skate components to `customElements.define`?

**Comment by treshugart** [comment]
@zzarcon we'll see. I need to spike how we could do unique tag names without `define()`.

**Comment by treshugart** [comment]
So it turns out `define()` won't be deprecated. It gives you the ability to anonymise components, or use Webpack's HMR.
