### ISSUE TITLE
slotchange event isn't fired with innerHTML text changes (in Chromium)

### ISSUE THREAD

**Issue by micahscopes** [skatejs/skatejs#877]
I realize this might go beyond skatejs.

I'd like to detect when an element's innerHTML changes.  I'm making an element that parses custom text input (a math expression to be used in mathjax).  If someone updates the contents (with text), I'd like to get a `slotchange` event.  Well, while HTML changes trigger `slotchange` events just fine, text changes are not triggering `slotchange` events.  I'm using Chromium 53.0.2785.143.

Here's an illustration of what I'm talking about:
https://jsbin.com/xivunad/edit?js,console

**Comment by micahscopes** [comment]
So I guess this is a bug in Chromium.  https://github.com/w3c/webcomponents/issues/592

I'm going to file an issue in the Webcomponents polyfill and for Chromium.

**Comment by treshugart** [comment]
> I'm going to file an issue in the Webcomponents polyfill and for Chromium.

Awesome, thank you :). I'll close this for now then as I don't think there's anything we can do here.
