### ISSUE TITLE
skate depends on skatejs-build

### ISSUE THREAD

**Issue by jpnelson** [skatejs/skatejs#896]
I understand that his was necessary in https://github.com/skatejs/skatejs/commit/7052894307ea24298b236142ebcc8d9389309a33#commitcomment-19644052 ? Is there another way?

It's a bit problematic because it means that anything depending on skate will also pull in all of the skatejs-build dependencies.

**Comment by treshugart** [comment]
Haven't got around to reverting because I was going to see if there was a
way to get JSDOM working.

**Comment by jpnelson** [comment]
But it would be reverted in future? If so I might turn this into a task

**Comment by treshugart** [comment]
For posterity, a `yarn add --save-dev` was done instead of `yarn add --dev`, I think.
