### ISSUE TITLE
Improve docs examples: simple to complex

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#903]
A comment on hacker news pointed out that the docs should start out a little bit simpler and go to more complex. Currently, there's a couple examples but they are very similar. Coming from web components and seeing Skate, one might not know what `render()` means right off the bat and may need some explanation. While we don't want to detract those coming from a React (i.e. `render()` world, examples starting simple and employing some of the spec'd stuff before introducing it might fare better.

More info: https://news.ycombinator.com/item?id=12862025

**Comment by Hotell** [comment]
As I've suggested by person in London 😉  I think it would be very nice to port docs to gitbook and have similar experience like "readers" of [redux](http://redux.js.org/) or [ngMetadata](https://hotell.gitbooks.io/ng-metadata/content/) have. I'm here to help with this. just lemme know if you think it's good idea and wanna proceed.

**Comment by treshugart** [comment]
Yeah, more than happy to do that. I think it would be simpler than maintaining a website, though, the website is a great as a suite of example components. But dev speed > website IMO, so go for it!

**Comment by haoxins** [comment]
Personally, I'd like to add an example of `rxjs and skatejs (stateless components)`.

**Comment by treshugart** [comment]
@haoxins that's a great idea. I haven't had a chance to use RXJS yet, but if anyone has, I'd be really interested how this might work out.

**Comment by pyros2097** [comment]
I think integrations with redux, mobx or even relay(v2) might help new users to use skatejs as a complete frontend solution as a replacement to react or angular.

**Comment by jeznag** [comment]
Would be great to add docs on the toolchain required. I can't figure out how to get this example going: https://hackernoon.com/building-a-custom-tag-input-with-skate-js-fbd4cdf744f#.5pmuikday

I get this error:
![image](https://cloud.githubusercontent.com/assets/1034890/22001424/373a301e-dc99-11e6-827d-efc742475f96.png)

There's probably some obvious webpack/babel plugin to use. Is it just the JSX loader?

**Comment by treshugart** [comment]
@jeznag replied via Twitter. See https://skatejs.gitbooks.io/skatejs/content/docs/api/#jsx. You don't need any special tools if you're doing raw JS. If you want to use JSX, you have to enable it.
