### ISSUE TITLE
A simple way to work with ShadowDOM encapsulated style

### ISSUE THREAD

**Issue by coderhaoxin** [skatejs/skatejs#907]
* Is it acceptable to give a simple way to work with ShadowDOM encapsulated style?

Maybe looks like:

```jsx
define('x-app', {
  props: {
    ...
  },

  style() {
    return `
      :host { ... }
    `
  }

  render(elem) {
    return (
      <div>
        ...
      </div>
    )
  }
})
```

**Comment by treshugart** [comment]
@haoxins are you asking if this looks reasonable for a custom base class, or for something to go into the base `Component` class in Skate itself?

**Comment by haoxins** [comment]
Sorry for the ambiguity. >_<

I think skatejs should support such features.

**Comment by treshugart** [comment]
I'm thinking in the near future that we can split out `Component` into mixins and compose them together (or just use the `Component` class, which would contain allthethings):

```js
import { StyleableComponent } from 'skatejs';
class MyComponent extends StyleableComponent(HTMLElement) {
  static get style () {
    return `:host { ... }`;
  }
}
```

This behaviour is already supported, you'd just have to build your own mixin as of right now.

I'll leave this open so we can continue to discuss the impl details and see if it's something we'd want to add to the core.

**Comment by justinfagnani** [comment]
In Polymer we just include a style tag in the template, which by being rendered into the shadow root does the right thing. Is there any downside to writing out a style tag in `render()`?

**Comment by treshugart** [comment]
> In Polymer we just include a style tag in the template, which by being rendered into the shadow root does the right thing. Is there any downside to writing out a style tag in render()?

I think doing it that way is fine, but it's repeated ceremony, so I see value in abstracting it away if it can be done cleanly. At the very least, it'd be neat to start using mixins, so I'll leave this open for now to get some more feedback.

**Comment by Hotell** [comment]
@justinfagnani 
> In Polymer we just include a style tag in the template, which by being rendered into the shadow root does the right thing. Is there any downside to writing out a style tag in render()?

you can do "the same" in Skate 

```typescript
import { Component } from 'skatejs';

class MyComponent extends Component {
  render(){
    return [
     <style>
    `
      :host {}
    `
    </style>,
     <div>I have shadow dom Css baby</div>
    ]
  }
}
```

or even smarter with webpack css-loader
```typescript
import { Component } from 'skatejs';
import styles from './my.css';

class MyComponent extends Component {
  render(){
    return [
     <style>{styles}</style>,
     <div>I have shadow dom Css baby</div>
    ]
  }
}
```

**Comment by marcoms** [comment]
@Hotell I wonder if you can link to the docs that specify the `[]` syntax for JSX? I didn't know it was possible to invoke JSX in that way without a wrapper `<div>` element, which wasn't ideal.

**Comment by Hotell** [comment]
arrays are ofc possible, I think that's just React constraint that everything has to have root wrapper ( this will change with Fiber ). Also Preact supports arrays.

here is link to docs https://github.com/skatejs/skatejs#styling-components

just note that 

```js
skate.define('x-component', {
  render() {
    return [
      skate.h('style', '.my-class { display: block; }'),
      skate.h('div', { class: 'my-class' }),
    ];
  }
});
```

is the same as ( with proper jsx pragma or `const React = { createElement: h };` )

```js
skate.define('x-component', {
  render() {
    return [
      <style>'.my-class { display: block; }'</style>,
      <div class='my-class'/>,
    ];
  }
});
```

**Comment by freeman** [comment]
I am not sure PReact really supports returning multiple element from render (our tests with SkateJS 5 seems to confirm it does not) (see https://github.com/developit/preact/issues/45)

**Comment by Hotell** [comment]
whops! this can be a deal breaker :-/ for styling and shadyCSS decorator/mixin for sure

**Comment by treshugart** [comment]
Hmm, I'm not sure this is a deal breaker. You can just put the ShadyCSS decorator inside an owner element. React will support this with Fiber and I'm not sure if Preact has changed its stance on this. I pinged Jason in that issue to see if it has.

Again, this isn't a deal breaker as I'm sure we can find a simple way to work around it. @Hotell can you post the code that's broken in 5.x? Maybe it's worth raising a separate issue for this?

**Comment by Hotell** [comment]
Right sorry my reaction was exaggerated.

It's though one of "secret" breaking changes that is not obvious to everyone though, that you cannot use arrays anymore.

Where it can create possible problems ( or refactoring needed ) is when you are styling via `:host` and do some particular display logic on children ( but that's rather an edge case ).

as of shady CSS decorator it monkey patches `renderCallback` by prepending `style` with transformed styles to shadow root. With having restriction of single root with `Preact` I think this wont be so easily doable https://github.com/wc-catalogue/blaze-elements/blob/master/packages/common/decorators.ts#L188

actually it should be straightforward change, something like this right?

```diff
      renderCallback: {
        value( ...args: any[] ) {
-          return [ h( 'style', this.shadyCss ) ].concat( originalRenderCallback.apply( this, args ) );
+          return h( 'div', null, [ 
+             h('style', this.shadyCss), 
+             originalRenderCallback.apply( this, args ) 
+          ]);
        }
      }

```

**Comment by treshugart** [comment]
There's some reasonable solutions in #1027. I'll keep this open until we land the docs or a possible base class in a non-core repo.
