### ISSUE TITLE
Simplify event syntax by adding an event() property

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#910]
I'm proposing adding an `event()` property. The use case for it is, currently, we have heuristics around event binding in the virtual DOM (`/^on[A-Z]/` basically). To simplify this, and to move away from needing heuristics at all, we can simply use properties to handle event listeners:

```js
import { Component } from 'skatejs';
class MyComponent extends Component {
  set onsomeevent (handler) {
    this.addEventListener('someevent', handler);
  }
}
```

That may be a little verbose if having to do it for every single event, though. There's a couple options here. We could expose a `prop.event()`:

```js
import { Component } from 'skatejs';
class MyComponent extends Component {
  static get props () {
    return {
      onsomeevent: prop.event()
    }
  }
}
```

And this could be augmented by a mixin to remove that boilerplate and conventionalise it:

```js
// This enforces a convention that all events are simply prefixed with "on".
function makeEventProps (props) {
  return events.reduce((eventsObj, name) => {
    // This convention is just an example.
    eventsObj[`on${name}`] = prop.event({ name });
  }, {});
}

function eventable (Ctor) {
  return class extends Ctor {
    static get props () {
      // Props explicitly override events as they're more explicit and should
      // "win" in a conflict.
      return Object.assign({}, makeEventProps(super.events), super.props);
    }
  };
}

class MyComponent extends eventable(Component) {
  // The `events` prop is intentionally `static` as it is similar to `props`
  // and `observedAttributes`.
  static get events () {
    // Gets translated to:
    //
    // ```js
    // props: {
    //   onsomeevent: event({ name: 'someevent' })
    // }
    // ```
    return ['someevent'];
  }
}
```

The result is something that is 100% backward compatible as props are preferred over our event naming convention. This allows it to implemented now, while deprecating the old method and removing in a future release.

Related discussion: https://github.com/facebook/react/issues/7901#issuecomment-259814104.

**Comment by caridy** [comment]
`makeEventProps()` is confusing, probably need some changes.

**Comment by treshugart** [comment]
@caridy, happy to change it; just trying to show both `prop.event()` raw, and used in a mixin.

**Comment by matthewp** [comment]
What problem are you having with the on- heuristic? Too many false-positives?

**Comment by treshugart** [comment]
@matthewp it just massively simplifies the virtual DOM logic. It does put the onus on the component developer to expose them, but it also is a way to make both event properties and addEventListener() work well. In React you already have to do this by way of function props. The explicit nature isn't too bad, IMO.

**Comment by andreawyss** [comment]
I think that events should be declared as part of the **static props** and possibly also enforce that these property names start with **on**.
```
 static get props () {
    return {
      onsomeevent: prop.event({
          bubbles: false, //default is false
          cancelable: false, //default is false
      });
    }
  }
```
Optimize for any use case where a callback function can be set as the value for these 'event' properties.
### Lifecycle
1) The Web Component will create a custom event object.
2) If a callback function was set: this is called passing in the custom event object as argument.
3) Else no callback function was set: then the custom event is actually dispatched.

This should not only play well with frameworks like React and Angular 1 but also avoid the overhead associated with dispatching events, adding and removing event listeners where not necessary.

**Comment by marcoms** [comment]
Would this solution work with assigning listeners for existing events such as `click`, without redefining the events themselves?

**Comment by andreawyss** [comment]
Good point. 
To avoid collision with existing DOM handler 'onclick', 'onchange', .... we could enforce these event property names to be camel case and maybe start with 'evt' or some other prefix. 
```
static get props () {
    return {
      evtSomeEvent: prop.event();
    }
  }
```

**Comment by treshugart** [comment]
I've been playing around with alternative approaches to this [over here](https://github.com/skatejs/dom-diff#hname-props-childrenortext). I much prefer, now, having special props for `attributes` and `events` (and possibly `aria` and `data` like in those docs). It removes the need for any heuristics at all and is quite straight forward. It also gives the developer using Skate and consuming DOM / custom elements / etc power over what they're trying to do rather than hit at the internals at what they hope / want it to do.

I'm not a fan anymore of `on*` prefixing anymore because there are edge cases with `once` and formatting that cost cpu cycles and maintenance effort.

I'm going to close this because it only offers a benefit to those that are *consuming Skate components*. It requires extra effort for the component developer and doesn't help integration with vanilla / etc custom elements because they may not do the same thing. By building this into `h`, it allows Skate to integrate with anything. This is also being considered [for react](https://github.com/facebook/react/issues/7901).
