### ISSUE TITLE
More fit to es2015 class style coding

### ISSUE THREAD

**Issue by vvakame** [skatejs/skatejs#912]
SkateJS have a [Using ES2015 classes](https://github.com/skatejs/skatejs#using-es2015-classes) section in README.md.
but, SkateJS is using `static` method and `elem` argument.
I think It is not It is not a natural object-oriented programming way.

If you already have a good method, please let me know.

**Expected**

I would like to write the following code.

```
"use strict";
const skate = require("skatejs");
exports default skate.define("x-es2015-count-up", class CountUpComponent extends skate.Component {
    constructor() {
        super();
    }
    click() {
        this.count += 1;
    }
    render() {
        return (
            <div>
                <p>{this.count}</p>
                <button onClick={e => this.click()}>Count up</button>
            </div>
        );
    }
    static get props() {
        return {
            count: skate.prop.number(),
        };
    }
});
```

**Actual**

Now, we are writing following code style.

```
"use strict";
const skate = require("skatejs");
exports default skate.define("x-es2015-count-up", class CountUpComponent extends skate.Component {
    constructor() {
        super();
    }
    click() {
        this.count += 1;
    }
    render() {
        return (
            <div>
                <p>{this.count}</p>
                <button onClick={e => this.click()}>Count up</button>
            </div>
        );
    }
    static get props() {
        return {
            count: skate.prop.number(),
        };
    }
    // !!! HERE !!!
    static render(elem) {
        return elem.render();
    }
});
```

and others

```
  static created(elem) {}
  static attached(elem) {}
  static detached(elem) {}
```

---

off topic
I tried to write TypeScript definition file in [here](https://github.com/vvakame/til/blob/master/skatejs-definitions/definitions/skatejs/index.d.ts).
This repository has [index.d.ts](https://github.com/skatejs/skatejs/blob/master/src/index.d.ts) already.
but both definition has a lot of `any` types.
It is evil for statically typings.
I think this Issue will help solve this problem.

**Comment by treshugart** [comment]
The plan is to support a prototype lifecycle where it makes sense in #872. Both will be supported, the static methods just will be deprecated where they have a prototyped counterpart.

**Comment by treshugart** [comment]
The convention will be to suffix lifecycles with `Callback`, so `renderCallback()`.

**Comment by treshugart** [comment]
Since there's already #872, I'm going to close this. Feel free to reopen if you have anymore questions.

**Comment by vvakame** [comment]
super cool! thank you for your advice. I'll try it this night.
