### ISSUE TITLE
How to pass objects to child components?

### ISSUE THREAD

**Issue by alinnert** [skatejs/skatejs#915]
I'm trying to find out how I can pass objects to child components. According to https://github.com/skatejs/skatejs/issues/752#issuecomment-260475004 it should work somehow.

The readme mentions `serialize` and `deserialize` in conjunction with attributes. Is there a way without serializing the object?
The readme also doesn't say much about defining properties. And unfortunately there's no `skate.prop.object()`.

There are basically two questions:

## How to define the property?

~~~javascript
props: { myProp: skate.prop.create({created() {}}) }
~~~

The docs don't mention the `created` method. But it seems to be necessary. Chrome throws an error without it. But this way the property is `undefined`.

---

~~~javascript
props: { myProp: null }
~~~

This is mentioned in the readme, but always throws an error: `Cannot read property 'attribute' of null`

---

~~~javascript
props: { myProp: {} }
~~~

this way my property is null.

## How to pass the property (in JSX)?

I've tried two approaches

~~~javascript
render(element) {
  return <child-el my-prop={element.data}></child-el>
}
~~~

and

~~~javascript
render(element) {
  const childEl = <child-el></child-el>;
  childEl.myProp = element.data;
  return childEl;
}
~~~

They both give the same result though.

**Comment by alinnert** [comment]
Okay, I've got it. It works like this:

Passing the object:

~~~javascript
render(element) {
  return <child-el myProp={element.data}></child-el>
}
~~~

defining the property:

~~~javascript
props: {
  myProp: {}
}
~~~

---

The properties must match **exactly**. If you want to write `<x-el my-property={obj}>` then the property must be defined like this:

~~~javascript
props: {
  'my-property': {}
}
~~~

It's different from what I'm used to ‒ Angular e. g. ‒ but understandable.

`skate.prop.create({ created() {} })` makes the property read-only for some reason. (Why?)

I think this should be documented somewhere.

**Comment by treshugart** [comment]
In terms of matching exactly, Skate doesn't do any automatic attribute to property naming convention mapping unless you pass `{ attribute: true }` to the property. By default it then dash-cases the name you gave the prop and uses that as the attribute name. If you want to enable passing complex data types from attributes to properties, you have to handle the serialisation if there isn't already a prop for it built into our API. This more closely maps to how HTML elements work, generally speaking.

I think it's making it a readonly prop because you're possibly overriding the `created()` method that is being called when the props are set up. It's not actually part of the API. What are you trying to do there?

**Comment by alinnert** [comment]
Yes, now I totally understand the attribute vs. property issue. I didn't want to use attributes to pass data if I can do it in another way. I was just about to figure out how it works.
My second comment basically contains the answer to my question but I couldn't find this in the readme. So I wrote it down for others and to point out what I was missing.

About the `{created() {}}`: If I just write `skate.prop.create({})` I get an error that the method `created` can't be found or is not a method. It actually has no purpose otherwise. But since `myProp: {}` works it doesn't really matter.

**Comment by treshugart** [comment]
Oh, I see. prop.create() returns a function that returns a prop definition
rather than just a prop definition. It's how the built in prop functions
are created.

**Comment by treshugart** [comment]
@alinnert were you able to get `prop.create()` working? You can't pass the result of it directly to a prop, you have to call it like a function first. For example:

```js
const myString = prop.create({ coerce: v => v.toString() });
define('my-element', class extends Component {
  static get props () {
    return {
      someString: myString({ attribute: true })
    };
  }
});
```

**Comment by treshugart** [comment]
Closing this. If you are still having issues feel free to reopen.

**Comment by alinnert** [comment]
Oh I see, that's how it works. I can't currently test it but I'll keep it in mind. Thank you.
