### ISSUE TITLE
Access Denied in IE11 because of WeakMap polyfill (web-components, named-slots)

### ISSUE THREAD

**Issue by alinnert** [skatejs/skatejs#917]
I've noticed my project doesn't complete running in IE11 because it throws an error "Access Denied". (It initially loads and displays my "loading data..." text but stops there somewhere.)

This error is thrown because of the WeakMap polyfill used by `skatejs-named-slots` (which is used by `skatejs-web-components`).

`es6-shims` (which is used by `core-js`) also had this error but they fixed it with version 0.31.3.
(issue: https://github.com/paulmillr/es6-shim/issues/333)

On the other hand: `skatejs-named-slots` says it's deprecated. Does this also make `skatejs-web-components` deprecated or should it be updated to using the `shadydom` polyfill instead?

The `polymer-fill` branch of `skatejs-web-components` uses `shadydom`. Is it meant to be used in production now or in the future? I wonder because its `package.json` pulls dependencies directly from GitHub.

Should I include `shadydom` etc. directly for now?
If so: how? (`shadydom` is not available on npm and doesn't provide install/usage information...)

---

Update:
I've managed it to include ShadyDOM. But the error stays the same.
If I remove `skatejs-web-components` I get the error "Skate requires native custom element support or a polyfill.". Is that supposed to happen?

**Comment by treshugart** [comment]
There's work in skatejs-web-components to move to the Polymer fills. Making
the custom element fill simple to use for The consumer is hard, but almost
there.

I'd recommend including the Polymer fills piecemeal until then.

**Comment by treshugart** [comment]
That said, I've never seen that error before with the weakmap fill. Tests
have been passing for named-slots. Is this something new?

**Comment by alinnert** [comment]
I've looked into it a little further. It happens when the page contains an iFrame. It doesn't need to be related to the SkateJS code. The polyfill tries to do `Object.getOwnPropertyNames(window)` with the iFrame's `window` object. I don't know why though. The stack trace is empty.
In my example the iFrame is an embedded YouTube video using JW Player. According to the linked issue this happens if there's a cross domain iFrame anywhere on the page.

https://jsfiddle.net/tm0bsbt1/9/
This is a simple fiddle where it happens too.

**Comment by treshugart** [comment]
I think for this you should use the webcomponents/* polyfills directly until skatejs-web-components makes that simpler. I'd prefer not to fix bugs due to dependencies in a deprecated polyfill, if that's okay with you. I'll close this for now, but feel free to reopen if there's something that you think Skate can do. Thanks :)

**Comment by alinnert** [comment]
It's fine with me. And all questions have been answered. Thank you :)
