### ISSUE TITLE
"static get props" should be called only once per class 

### ISSUE THREAD

**Issue by andreawyss** [skatejs/skatejs#919]
static get props returns props definitions that are constructed using Prop.create()
static get props is accessed multiple times during component livecycle.
Each time static get props is accessed a new set of props definitions get reconstructed!

To solve this issue, create a static getPropDefs() that caches the props definitions for a given class and then refactor the code to use static getPropDefs() instead of directly accessing static get props.

implementation would be something like this:

static getPropDefs() {
    if (!this.hasOwnProperty('_propDefs') ) {
        this._propDefs = this.props;
    }
    return this._propDefs;
}

Note: getPropDefs is static therefore "this" refers to the Constructor and this.props if not found on the current constructor will be looked up in an ancestor Constructor that the component is extending.

**Comment by treshugart** [comment]
That's a great idea. PRs welcome :)

**Comment by andreawyss** [comment]
This will be solved once PR #932 will be approved and merged.

**Comment by andreawyss** [comment]
This is resolved.
