### ISSUE TITLE
Required props

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#923]
```js
import { Component, prop } from 'skatejs';

class MyElement extends Component {
  static props = {
    myProp: {
      // We should ensure this works as expected (i.e. does not coerce).
      // We should still keep the default coercions.
      coerce: null,

      // Value is applied prior to validation.
      default: 'test'

      // Similar should be implemented for all built-in props.
      // If coercion is on, then this still checks, but will likely pass.
      // If coercion is off, it still validates.
      validate: v => typeof v === 'string',

      // Should throw in dev if `prop == null`.
      // Default value is `false`.
      required: true
    }
  }
```

**Comment by thepian** [comment]
When should it throw an exceptions. While I think that required is an important feature, I don't see the point at which you can currently assert required to be true.

**Comment by andreawyss** [comment]
First we need to provide nullable types. Currently all built in prop have a default value that is different then null. 
Then in updatedCallback if any required prop is missing we would return false and therefore not render until all required props are present.

**Comment by thepian** [comment]
Makes sense, but the comment above refers to throwing in dev mode

**Comment by treshugart** [comment]
If we do https://github.com/skatejs/skatejs/issues/991 then everything becomes nullable, but can still have a default that isn't null, it just doesn't reset to the default value when nulled.

Is preventing rendering the best idea? It could be possible to throw if required props aren't present by the time rendering occurs if it wasn't rendered sync, but debounced in a microtask. I think that would be more expected if it's possible.

**Comment by treshugart** [comment]
There hasn't really been a need for this yet and you can get a similar effect with Flow or TypeScript, so closing.
