### ISSUE TITLE
Separate things into mixins

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#927]
It'd be good to separate parts of the Component class out into mixins that compose that class but can also be used piecemeal.

One aspect of this is the IncrementalDOM renderer. It should definitely be split out into it's own mixin, but still be the default one that `Component` uses for now.

Mixins should look like:

```js
/* @jsx h */
import { MixinIncrementalDOM, h } from 'skatejs';

class MyComponent extends MixinIncrementalDOM(HTMLElement) {
  renderCallback () {
    return <div />;
  }
}

customElements.define('my-component', MyComponent);
```

That would mixin the incremental DOM renderer, which might extend something like a base renderer component class which provides the `rendererCallback()` or something.

We should consider if we can move Incremental DOM to a peer / optional dependency.

**Comment by Hotell** [comment]
this looks awesome!
