### ISSUE TITLE
Router?

### ISSUE THREAD

**Issue by pyros2097** [skatejs/skatejs#929]
Anyone know how to build a router using skatejs like react-router? Or if it is possible I would like to do it server side like nextjs?
Btw it be awesome if people could share their skatejs components somehow. Maybe if the the library is mature enough we can create a awesome-skatejs project or something?

**Comment by treshugart** [comment]
@bengummer?

**Comment by treshugart** [comment]
On the website, there is a declarative router implemented:

- Declaring routes, with code splitting: https://github.com/skatejs/skatejs.github.io/blob/master/src/app/index.js#L43-L60
- The `<Route />` component: https://github.com/skatejs/skatejs.github.io/blob/master/src/route.js

**Comment by treshugart** [comment]
I'd definitely be interested in starting to author and release "official" components under the SkateJS org. If this is something you'd be interested in helping with @pyros2097 I'd be happy to add you as a contributor.

**Comment by pyros2097** [comment]
whoaa... What happened? It seems there was a major refactor and the api kinda changed. Anyways.
I started porting a side menu react component and I am facing some issues. It seems render is being called twice and even after the prop is updated the style doesn't seem to change.
```js
var styles = {
  navigation: {
    fontSize: '15px',
    width: '20em',
    height: '100%',
    color: 'white',
    background: `rgba(0, 0, 0, 1)`,
    position: 'fixed',
    top: '0',
    right: '0',
    bottom: '0',
    zIndex: '2000',
    transition: 'right 0.3s ease-in-out 0s',
  },
}

class SideMenu extends skate.Component {

  static get props() {
    return {
      isOpen: skate.prop.boolean({ attribute: true  })
    }
  }

  hideMenu = () => {
    console.log("Hideing", this.isOpen)
    console.log(this)
    this.isOpen = false
  }

  renderCallback() {
    console.log("Render", this.isOpen)
    if (this.isOpen === true) {
      styles.navigation.right = '0'
    } else {
      styles.navigation.right = '-20em'
    }
    console.log(styles.navigation.right)
    return (
      skate.h('div', {  style: styles.navigation },
        skate.h('button', { onclick: this.hideMenu }, 'Hello:ww::ww')
      )
    )
  }
}

customElements.define('skate-sidemenu', SideMenu)
```
PS: I was trying to integrate glamor and it seems that is not also working: https://github.com/threepointone/glamor/issues/123

Anyways I was just thinking of porting some small components I have like sidemenu, switch, select, radio, table, card. I don't know if these are suitable for official components but yeah I can make them. Currently I'm planning on porting a hobby react+relay project which I currently finished and try to see how it turns up in skatejs and if I like it I'm planning on sticking to skatejs.
And my end goal is to make something like next on skatejs with server side rendering.

**Comment by treshugart** [comment]
I never saw your last response. Major apologies.

Your `style` isn't changing most likely because it's a reference to the same object literal you have in the containing module scope. If you do something like the following, it should update.

```js
<div style={{ ...style.navigation, { right: newValue }} />
```

I answered the question about Glamor on that [issue](https://github.com/threepointone/glamor/issues/123#issuecomment-273658371) you linked to.

Happy to take a look at the components once you've converted them. It would be nice to have an official UI library. I think that's something that'd be good to have an overall plan for alongside incoming components.

I'm going to close this now but if you're still having issues, please feel free to reopen.

**Comment by pyros2097** [comment]
Sure no problem.. Thanks I think this and glamor was a show stopper for me will try it again though. Still like the idea of small runtime and no dependency on huge system like react (babel or webpack).
Yeah a UI library will do wonders. Thats one of the main reasons people adopted react very quickly there are so many react-bootstrap, react material-lite things like that. Quick prototyping.
