### ISSUE TITLE
Missing typings for Component class

### ISSUE THREAD

**Issue by hopkins-tk** [skatejs/skatejs#940]
**Component** just extends **HTMLElement** but has no methods (callbacks) declared.

**Comment by bradleyayers** [comment]
From a consumer perspective, why is this a problem?

**Comment by Hotell** [comment]
@bradleyayers better intellisense and calling `super` without errors. 

Native methods `connectedCallback`,`disconnectedCallback`,`attributeChangedCallback` can be removed once they will be defined within Typescript [`HTMLElement`](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L4562)

without:
![skatejs-without-typed-component](https://cloud.githubusercontent.com/assets/1223799/20641591/7e7216de-b3fb-11e6-81ff-2b6a74a75e67.gif)


with:
![skatejs-with-typed-component](https://cloud.githubusercontent.com/assets/1223799/20641610/ce85d836-b3fb-11e6-84b7-2a2c5195b20a.gif)

**Comment by treshugart** [comment]
cc @andreawyss

**Comment by vvakame** [comment]
FYI, I'm writing fully rewrote type definitions is [here](https://github.com/vvakame/skatejs-todo/tree/master/definitions/skatejs).
This definitions supports TSX writing.
I have not finished polishing yet, but I think it will take shape this week.

**Comment by andreawyss** [comment]
@vvakame @hopkins-tk try maybe something along this idea:
define ICustomElementV1 interface 
ISkateLifecycle extends ICustomElementV1
Component extends HTMLElement implements ISkateLifecycle

also: 
attributeChangedCallback(name: string, oldValue: **null | string**, newValue: **null | string**): void; 
and 
where a prop name is expected name: **string | symbol**

**Comment by Hotell** [comment]
@vvakame I'm closely following your progress. IMHO you should introduce that directly to skate as PR, so we can join forces and work on that stuff together. wdyt? I'm ok with using `typescript@next` until 2.1 stable is released ( because `jsxFactory` support )

**Comment by treshugart** [comment]
Agree with @Hotell here. If this is worrisome, then maybe we can keep all the TS stuff in a feature branch until TS releases it.

**Comment by treshugart** [comment]
Branch here https://github.com/skatejs/skatejs/tree/typescript

**Comment by vvakame** [comment]
@Hotell @treshugart sounds good. I think that it will change to my own way because it is not stable yet, is it OK?

@treshugart type definitions can generate from TypeScript code. hand made `.d.ts` is alternative for JavaScript base project.
If you decided to use TypeScript in this project. my `index.d.ts` is not required. but `jsx.d.ts` is required. I'll send `jsx.d.ts` only.

**Comment by Hotell** [comment]
until everything is migrated to TS we will ship `index.d.ts` created by hand. I would also love to start shipping jsx definitions asap. Once everything is ts-ified, we can delete manually created `index.d.ts` and enable `{declaration:true}` within `tsconfig.json`

**Comment by andreawyss** [comment]
This issue is resolved.
