### ISSUE TITLE
Example code fails in Chrome 54/56

### ISSUE THREAD

**Issue by tony19** [skatejs/skatejs#943]
I just tried the [example code](https://github.com/skatejs/skatejs#examples) in [Codepen](http://codepen.io/tony19/pen/QGMKXm?editors=1010) on Chrome 54 and 56. They both fail with:

    component.js?235b:134 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

which points to:
![screen shot 2016-11-26 at 7 47 11 am](https://cloud.githubusercontent.com/assets/26580/20640741/92db70e2-b3ac-11e6-961e-d03f6e5ba245.png)

The error looks similar to the one seen in #813, but I'm not sure if they're related. Am I missing a step?

**Comment by Hotell** [comment]
Hey, so you have to do following things to make it work:

- you need to transpile the code to es5, doesn't work with native ES6 yet ( why @treshugart  ? ) 
- you have to provide polyfills (skatejs-web-component) which is a bummer ( forcing user to download all polyfills in browser which has everything natively is a big no no. I think it is related to extending native HTMLElement causing problems  )

Here it's your working demo: 
http://codepen.io/Hotell/pen/woqozy

**Comment by tony19** [comment]
Ok, I see. Thanks!

**Comment by Hotell** [comment]
yw!, 
I'm going to work on docs rewrite to gitbook + live examples so this issues wont be created in the future :)

**Comment by tony19** [comment]
I had skimmed the README and only saw the [Installing](https://github.com/skatejs/skatejs#installing) section with the `<script>` tag. If I had continued reading the next section on  [Dependencies](https://github.com/skatejs/skatejs#dependencies), I would've seen the actual `<script>` tags I needed in my Codepen. I don't see any mention of the ES5 requirement though, so that would've been nice in the README.

**Comment by treshugart** [comment]
@Hotell, @tony19 if you use ES5 custom elements (skate dist, basically) in a native browser, you need a shim. The latest `skatejs-web-components` includes a modded native shim in [`src/native-shim.js`](https://unpkg.com/skatejs-web-components@5.0.0/src/native-shim.js) that you can include in any browser (even if they don't support ES5). There is a pretty big hack to make that doable, but I haven't found a better way as of yet.

**Comment by treshugart** [comment]
@Hotell

> you need to transpile the code to es5, doesn't work with native ES6 yet ( why @treshugart ? )

Skate? I think all you'd need to do is concatenate the source files and remove the import / export declarations somehow. Is that what you're referring to?

> you have to provide polyfills (skatejs-web-component) which is a bummer ( forcing user to download all polyfills in browser which has everything natively is a big no no. I think it is related to extending native HTMLElement causing problems )

It sucks, but In my previous comment I noted that you can include only the native-shim.

**Comment by Hotell** [comment]
@treshugart 
> you need to transpile the code to es5, doesn't work with native ES6 yet ( why @treshugart ? )

> Skate? I think all you'd need to do is concatenate the source files and remove the import / export declarations somehow. Is that what you're referring to? I'm not sure how many people are doing this yet, so not sure it's worth the effort.

Partially, I was merely referring to that you cannot use raw es6 code, to make it work ( there needs to be compilation to es5 for classes for instance ), but for sure it's not worth the error IMHO. thanks!
