### ISSUE TITLE
documentation: Minor inaccuracy regarding Symbols

### ISSUE THREAD

**Issue by tony19** [skatejs/skatejs#944]
In the README, the [Private Members](https://github.com/skatejs/skatejs#private-members) section contains:

> However, if you're using ES2015 you can use symbols. Using this pattern, your members are completely private and only available if you have access to the symbol:
>
>```javascript
>const sym = Symbol();
>
>customElements.define('my-component', class extends skate.Component {
>  constructor () {
>    super();
>    this[sym]();
>  }
>  [sym]() {
>
>  }
>});
>```

But the symbols aren't actually "completely private", as they're available via [`Object.getOwnPropertySymbols(skateElement)`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertySymbols):

```javascript
// x-counter is a skate element
const ctr = document.querySelector('x-counter');
Object.getOwnPropertySymbols(ctr).forEach(x => {
  ctr[x] = '2';
  console.log(x, ctr[x]);
});
```

[codepen](http://codepen.io/tony19/pen/vyJgOj)

**Comment by treshugart** [comment]
This is true, and I noticed this (but didn't address it yet). Are you able to raise a PR rectifying this? Thanks!

**Comment by tony19** [comment]
@treshugart Ok #946

**Comment by treshugart** [comment]
Thanks!
