### ISSUE TITLE
refactor docs to gitbook

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#947]
current `Readme.md` is very huge and hard to maintain ( search for things etc )

As previously discussed with @treshugart, we are going to migrate the docs to maintainable format ( gitbook ) + add links to real working online code examples ( via Codepen or so )

feel free to discuss on this topic.

**Comment by treshugart** [comment]
@Hotell I added you as a writer for the skatejs org on Gitbook. Can you confirm if you're able to create a book?

**Comment by Hotell** [comment]
yup!

look how beatifull it is so far ! :D

![skate-gitbook-wip](https://cloud.githubusercontent.com/assets/1223799/20733920/6542308e-b696-11e6-99ef-4d353cf6b2de.gif)

**Comment by treshugart** [comment]
This is awesome!
