### ISSUE TITLE
Incremental DOM class property doesn't apply css classes properly in IE 11

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#950]
When user wants css classes for styling, it doesn't work as expected in old ie 11 ( by using `class` attribute within VDOM ).

More particulary, just first css class from the whole string is applied  
```
const className = `c-button ${Button.modes[mode]}`
```
in our case just **c-button**

It looks like this:

### IE11 vs Edge
![image](https://cloud.githubusercontent.com/assets/1223799/20726692/f0749266-b676-11e6-8bf0-4bd6f3c14e79.png)

#### skateJS versions
skate 4.1
skate-web-components 5.0

#### live example:
https://jsfiddle.net/hotell/sbthhvk6/

#### code:
```js
class Button extends Component {
  static get is(){ return 'bl-button'}
  static get style(){
  	return `
        .c-button {
          border: 1px solid transparent;
          background-color: #96a8b2;
          color: #fff;
          display: inline;
          max-width: 100%;
          // and so on.....
         }
    `
  }
  
  static get props(){
  	return {
    	  mode: prop.string({attribute:true})
       }
  }
  static modes = {
    brand: 'c-button--brand',
    info: 'c-button--info',
    warning: 'c-button--warning',
    error: 'c-button--error',
    success: 'c-button--success' 
  }
  renderCallback(){
    const {mode} = this;
    const className = `c-button ${Button.modes[mode]}`
    return [
    	<style>{Button.style}</style>,
    	<button class={className}><slot/></button>,
        <pre>class applied: {className}</pre>
    ]
  }
}
```

If we switch to "react" pattern and use `className` instead, it magically works everywhere.
 
### IE 11 works!
![image](https://cloud.githubusercontent.com/assets/1223799/20726810/5de27426-b677-11e6-83fe-7edca20c3199.png)

I don't know if this is skate or incremental dom or wc polyfills bug. 

Any suggestions @treshugart ? thanks

**Comment by treshugart** [comment]
What if you remove the shadycss and shadydom fills and force render to the host as light DOM?

**Comment by Hotell** [comment]
If I remove shady dom+css and use just [customElements polyfill](https://raw.githubusercontent.com/webcomponents/custom-elements/master/custom-elements.min.js) it doesn't work anywhere, with old good error 
```
component.js?235b:134 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function
```

**Comment by Hotell** [comment]
ok I got that working just with CE but apparently skate needs shadow dom 

https://github.com/skatejs/skatejs/blob/master/src/api/component.js#L397-L401 
```
// static renderer
if (!elem.shadowRoot) {
  elem.attachShadow({ mode: 'open' });
}
```
so how can I render ( you mentioned force render ) without needing shadow dom polyfill ?

**Comment by Hotell** [comment]
ha! works! withoud shadyCss woot 
https://jsfiddle.net/hotell/9c8trgLk/

**Comment by treshugart** [comment]
@Hotell can you report this to the [shadycss](https://github.com/webcomponents/shadycss/issues) repo and close, please? Thanks!

**Comment by treshugart** [comment]
As a side note, using https://github.com/zeit/styled-jsx looks like a promising way to not have to use the shadycss polyfill once https://github.com/zeit/styled-jsx/issues/12 is fixed.

**Comment by Hotell** [comment]
Also why are we shipping shadyCSS with skate-web-components ? it doesn't make sense as it doesn't do anything, because shadyCss works only with `<template></template>`

**Comment by treshugart** [comment]
The plan was to make it work automatically via a function call or statless helper. Maybe you're right, though.

**Comment by Hotell** [comment]
yeah I know, I mean, we tried to used it, but it's so buggy and doesn't work properly... anyway closing this as we agreed

**Comment by treshugart** [comment]
@Hotell happy to accept a PR over there for splitting out each one (while still keeping the all-in), if you want.
