### ISSUE TITLE
Backward compat broken in recent refactor

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#959]
https://github.com/skatejs/skatejs/pull/955/files#diff-d3ff8469a13e890ec2a5c73b90df75abL368

The static `updated()` and `rendered()` need to be kept if any subclasses are calling out to them.

**Comment by andreawyss** [comment]
@treshugart sorry, I missed this one. 
You need to publish a new release 4.2.1

**Comment by treshugart** [comment]
@andreawyss it's all good. I restarted the build so hopefully sauce labs works this time.
