### ISSUE TITLE
jspm setup

### ISSUE THREAD

**Issue by rhythnic** [skatejs/skatejs#964]
I'm excited about getting started with statejs. I like the concept of the React paradigm using web components.  I'm having a bit of trouble getting setup in jspm.  skatejs/src/api/component.js is throwing an error, but I assume it's due to my setup.  My jspm setup is using babel as a transpiler.

### Errors:
component.js:135  Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

component.js:201Uncaught TypeError: this[rendererDebounced] is not a function

### index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>My App</title>
</head>
<body>

  <x-hello></x-hello>

  <script src="jspm_packages/github/webcomponents/custom-elements@1.0.0-alpha.3/custom-elements.min.js"></script>
  <script src="jspm_packages/github/webcomponents/shadydom@master/shadydom.min.js"></script>
  <script src="jspm_packages/github/webcomponents/shadycss@master/shadycss.min.js"></script>
  <script src="jspm_packages/system.js"></script>
  <script src="config.js"></script>
  <script>
    System.import('src/main.js');
  </script>

</body>
</html>

```

### src/main.js
```
import { Component, h, define } from 'skatejs';

class Hello extends Component {
  renderCallback () {
    //return <span>Hello, <slot />!</span>;
    return h('p', { style: { fontWeight: 'bold' } }, 'Hello!');
  }
}

define('x-hello', Hello);

```

**Comment by treshugart** [comment]
The problem is that in native custom element environments (Chrome, WebKit) you need to include the [native shim](https://github.com/webcomponents/custom-elements/blob/master/src/native-shim.js) - which doesn't work in non-native implementations. It's not a fun problem to have to solve for consumers.

Instead of including the polyfills piecmeal, you can just include `skatejs-web-components` it will take care of everything for you and you shouldn't see the problem anymore.

**Comment by rhythnic** [comment]
Thanks for your reply.  I should have read the docs better.  I found out that skatejs-web-components can't be installed by jspm because jspm doesn't support tarball deps.  I made an [issue in the web components repo](https://github.com/skatejs/web-components/issues/31)

**Comment by treshugart** [comment]
Cool thanks!
