### ISSUE TITLE
Example of React HOC using SkateJS component

### ISSUE THREAD

**Issue by idibidiart** [skatejs/skatejs#965]
Hi, 

This is not an issue or feature request, just trying to find out if it's possible for a React Higher Order Component to be composed of SkateJS components, to ease the migration from React to SkateJS or at least co-existence. If it is possible, can you reference an existing example or provide one here?

**Comment by treshugart** [comment]
Using github.com/webcomponents/react-integration you can use web components just like React components. Alternatively you can just declare your web components then use use them in your JSX just as you'd write HTML for them. I'd recommend using the react-integration if you want to set props on your web components, though, because React only sets attributes for now. Examples of composing WCs into RCs can be found in the docs for react-integration.

```js
import React, { PureComponent } from 'react';
import reactify from 'skatejs-react-integration';

class WebComponent extends HTMLElement {}
customElements.define('web-component', WebComponent);

// Using just HTML
class ReactComponent1 extends PureComponent {
  render () {
    return <web-component />;
  }
}

// Using react-integration
const ReactifiedWebComponent = reactify(WebComponent);
class ReactComponent2 extends PureComponent {
  render () {
    return <ReactifiedWebComponent />;
  }
}
```

That's a contrived example, but if you're still having issues and can provide a more concrete example, I'm happy to help you work it out.

**Comment by soneymathew** [comment]
@idibidiart Be mindful of two additional things, just so that you are prepared when you face them.

- pageweight increase brought in by the polyfills required.
    This will eventually disappear as the need for polyfills goes away as the browsers completely implement the standards, this is not a problem if that is not a concern. You are already pulling in React which is not a lightweight asset.
- instability of the polyfills 
     as the browser vendors are still iterating on the implementation this may lead to issues, try to not bundle the polyfills together with your app so that you can adapt rapidly to deliver the latest polyfills

Once these are sorted out, your webcomponents should live for a very very long time

**Comment by idibidiart** [comment]
@treshugart 

Thank you for your answer. I'll be reading about react-integration and looking to understand how events in WebComponents are registered (via "on" attribute syntax or addEventListener or both) I assume (for memory leak prevention that we also have to make sure the events are removed (via removeEventListener or passing null to the "on" event attribute...? 

@soneymathew 

Thanks for your notes!

I recently came across this project: https://github.com/babel/babel-preset-env "Babel preset that automatically determines the the Babel plugins you need based on your supported environments. Uses compat-table" and I'm wondering if something similar can be done in the case of web components. In other words, it would be nice to have an easy way (e.g. via a library) to determine what web components polyfills to download for the browser in which the code is running.

**Comment by treshugart** [comment]
> I assume (for memory leak prevention that we also have to make sure the events are removed (via removeEventListener or passing null to the "on" event attribute...?

Not necessary. DOM events are cleaned up with the element.

> Or maybe a React-Integrated Web Component is a true React component with React Synthetic Events and React Lifecycle methods?

The idea is to make *vanilla* web components able to used (by a consumer) just like a React component. If you want lifecycles and synthetic events from React, then you may as well use React. You'd be coupling yourself to it anyways if you were wanting those lifecycles in a web component.

> Looking forward to some insight before I dig much further! :) and thank you in advance!! So excited about the prospect of using SkateJS!!

So cool! Thanks for the kind words.

> I recently came across this project: https://github.com/babel/babel-preset-env "Babel preset that automatically determines the the Babel plugins you need based on your supported environments. 

That is an awesome project. +1

**Comment by treshugart** [comment]
@idibidiart I'm going to close this. Happy for you to open issues as you encounter stuff.

**Comment by idibidiart** [comment]
`You'd be coupling yourself to it anyways if you were wanting those lifecycles in a web component.`

Exactly. I was hoping that you react-integration was reasonable in that it did not attempt to to turn a Web Component into a full/true React component, but just being able to use Web Components via React. 

So that's great. The event cleanup is a thing that came with a now old version of IE but I wasn't thinking about the fact that you use Incremental DOM which I assume recycles elements and in doing so it also cleans up the event handlers. I've recently built a virtual data grid that can render 2500 DOM elements as you scroll and the in-place diffing that I do can be replaced with the patch function of Google's Incremental DOM, so that's what led me to SkateJS! 

Thank you again for the insightful answers.

**Comment by treshugart** [comment]
> I was hoping that react-integration was reasonable in that it did not attempt to to turn a Web Component into a full/true React component, but just being able to use Web Components via React.

Yep. 100% it's that.

> Re: event cleanup: I guess since SkateJS uses Incremental DOM then I assume it (Incremental DOM) recycles elements (to minimize GC activity) and in doing so it must also clean up the event handlers.

Event handlers are something we have to do ourselves in the wrapper, unfortunately. But yes, these are cleaned up (and there's tests for it).

**Comment by idibidiart** [comment]
Oh right. In my current version of things I have a WeakMap that has the element to be recycled as key with the value being an array of references to its event handlers.  So when my in-place diffing engine wants to recycle an element it looks up the element in that WeakMap and removes all event listeners from it before putting it back into the recycled pool. I understand why (as SkateJS not being tightly coupled to Incremental DOM) that you have to do it in the wrapper. That should work just fine! Thanks again.
