### ISSUE TITLE
Is window-or-global worth it?

### ISSUE THREAD

**Issue by thepian** [skatejs/skatejs#968]
In vdom.js you have

import root from 'window-or-global';

When I try to use skatejs with rollupjs instead of webpack it blows up because the module is CJS not ES6. For 4 lines of code wouldn't it be easier to copy it over?

**Comment by treshugart** [comment]
Or just have it in `untl/root.js` and it'd be a oneliner. I was hoping to reuse as much code from elsewhere (where it makes sense). In skatejs-build we use both the node resolver and commonjs plugins. Might need to enable commonjs in node_modules? That said, it's probably simpler to just oneline this in a `util`.

Happy for you to do a PR for this. Thoughts?

**Comment by thepian** [comment]
Not sure. It's the sort of things that should be manageable to configure with builder plugins to override packages. I have a similar concern for the process builtin which is referenced in incremental DOM. I'll brew over it for a bit and try to come up with a PR

**Comment by treshugart** [comment]
You're getting Incremental DOM as a transitive from Skate, so it might be something to suggest over there?

**Comment by thepian** [comment]
Sure

**Comment by treshugart** [comment]
I'm hoping we can have a single build in the near future once we trial Webpack 2 and see if the bundle size is palatable.
