### ISSUE TITLE
Document slots as transclusion approach

### ISSUE THREAD

**Issue by thepian** [skatejs/skatejs#969]
I looked at another issue about slots using Shadow DOM. If that is the way to solve transclusion of initial markup within the Custom Element, I think it would be worth it to add a section about it with the references to the Slot documentation in the README. As it currently is being a beginner with the Skate approach I can't find any example/doc/directions.

* React uses this.props.children in render
* Angular uses <ng-transclude>
* Plain DOM uses this.children in constructor (I guess)

**Comment by treshugart** [comment]
The plain DOM approach is manual distribution. If you're using shadow DOM, then it's obviously slots. Happy to add a section on slotting. Any suggestions in how you might have best gotten this from the docs?

**Comment by thepian** [comment]
I imagine a section section with a lot of links perhaps in the form of a decision tree 

I could imagine something like this(will add more later)

## Learning the Components Approach

If you are getting started with Web Components and Reactive approaches, you will need to ask yourself a couple of questions about how you are going to build your solution

* How do you load shims. We recommend skatejs-web-components(link) with deps as it is tested to work with skatjs and has additional fixes(link) on top of the regular shim(link).
* ...
* Will you use regular DOM or Shadow DOM for the content of your component?
* What will you do with the initial content of your component?

### Transcluding the original content into the runtime DOM.

**Comment by thepian** [comment]
Since the gitbook is now there, I don't think this is so important
