### ISSUE TITLE
Reverse prop option validation

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#970]
You should be able to specify any option to prop configs as props may use arbitrary options internally. cc @andreawyss

**Comment by andreawyss** [comment]
Some examples on how this extra options are used in the wild?

**Comment by treshugart** [comment]
It's an edge case, but it allows things like this: https://github.com/skatejs/skatejs/pull/866/files#diff-e27b567beeb444198f148654751d1557R85

**Comment by treshugart** [comment]
It also broke some code elsewhere that were options from 1.x but they hadn't been removed. That's borderline an excuse for saying "there were breaking changes anyways", but the removal of the behaviour didn't indicate that one would have to also remove the option.

This is technically a breaking change, so I'd prefer if we can put it back in. Happy to discuss adding it in the future, but I'm not convinced of the benefit yet given how badly, and oddly it broke old code.

**Comment by andreawyss** [comment]
Review the changes I made for #838. 
I allow undocumented options but warn about it.

**Comment by andreawyss** [comment]
@treshugart if you merge #967 it will resolve this issue #970.
After you should be able to complete #866.

**Comment by treshugart** [comment]
Yes! Thank you @andreawyss!
