### ISSUE TITLE
Is it worth having render priorities?

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#971]
Just doing some reading:

- https://aerotwist.com/blog/when-everything-is-important-nothing-is/
- https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback

The browser will do a fantastic job of internal prioritisation and optimisation, but maybe there's components that are less important to render than others?

**Comment by marcoms** [comment]
This could be useful. Maybe a hypothetical API for this would preserve the children being rendered before parents (assuming appropriate `<script>` placement), or at least present it as an option, otherwise limiting the scope to sibling elements.

**Comment by treshugart** [comment]
@marcoms can you elaborate on that idea? I'm not quite sure I follow, at the moment.

**Comment by marcoms** [comment]
For example, in a normal environment these would be rendered in this order:

```html
<x-parent>  <!-- 3rd -->
  <x-child></x-child>  <!-- 1st/2nd -->
  <x-child></x-child>  <!-- 1st/2nd -->
</x-parent>
```

But if we attach priorities to them making `x-parent` be rendered first, then its no longer safe for parents to assume their children are rendered before they are:

```html
<x-parent>  <!-- 1st -->
  <x-child></x-child>  <!-- 2nd/3rd -->
  ...
```

Is that right?

**Comment by treshugart** [comment]
Parents should never assume ordering. If you load definitions async, `x-child` may be defined later than `x-parent` anyways. Custom elements should be designed to be resilient to this and not rely on upgrade order of light DOM. Shadow DOM is different, because most of the time, you are importing your dependencies for what you're using in the shadow root.

**Comment by treshugart** [comment]
The more I think about this, the more I think that it's something that should be implemented in the VDOM layer as it would have a better idea of how things should be prioritised. All Skate really does is hand off what to render to that anyways. Will close for now.
