### ISSUE TITLE
Flow vs TypeScirpt redux

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#972]
So to finally put this to bed, I say we hash out one final flow vs typescript and then move on.

After trying hard to make TypeScript work, these are the issues that came out of it:

1. JSX outside of React isn't supported
2. Inability to correctly type our props as a map where the key can be a string or symbol
3. You have to override TS' __extends with Babel's _inherits for classes to work
4. To be clean about it, it'd need to be a 100% refactor

1 and 2 are biggies. 3 isn't that big and would go away once everything is in TS.

Given the circumstances, Flow seems like a better fit, but it's definitely not as mature and has it's own suite of bugs, too.

I, personally, would prefer to stay vanilla JS or go Flow at this point. Personally, I'd prefer to fix bugs, make things faster and ship features rather than spend time adding type annotations to code, but I can also see the value in that, too, so happy with what people decide.

cc @Hotell, @andreawyss, @vvakame

**Comment by Hotell** [comment]
1. is not valid anymore
2. isn't possible also with FLOW AFAIK
3. valid
4. I don't think so, can you elaborate pls ? (there is clean gradual update)

**Comment by Hotell** [comment]
My point of view:

We should definitely use Typed Js, those type annotations are living documentation and are very nice for every contributor and maintainer as well.

Either way, we need to ship both `flow` and `ts` type definition. If "we" choose to stay vanilla then there will be much more work to manually create/maintain those type definitions. 

The main point of using typed JS is maintenence and productivity boost by great tooling support.
With flow, tooling support is really, really miserable.

Overall my opinion is clear: **BETTER SOME TYPES THEN NONE**

**Comment by treshugart** [comment]
AFAIK 1 is still an issue right?

Either way, TypeScript has proven to be hard thus far. I think if we want types and we want it now, then Flow might be the pragmatic choice (Pragmatic Programmer: adopt early / adopt often). At the very least we can strip stuff out if we eventually move to TS. It's also likely to be able to generate a TS file for us (see https://github.com/facebook/flow/issues/7). I searched for doing it the other way around and didn't come up with anything. That right there points to Flow being better as we can generate for both.

> The main point of using typed JS is maintenence and productivity boost by great tooling support.

That's if we can get it working, which we haven't yet. I use VSCode, so this would be awesome for me.

> With flow, tooling support is really, really miserable.

This is quite possibly a problem, but I don't see it being an issue for long at all. Flow has a *lot* of momentum behind it.

My vote: **Flow**, *if we move*.

**Comment by andreawyss** [comment]
I use WebStorm 2016.3.1 and it has Flow support:
![screen shot 2016-12-13 at 4 07 21 pm](https://cloud.githubusercontent.com/assets/4635265/21164594/e8e6f330-c14e-11e6-8f50-87b75cf390a4.png)

**Comment by RichOren** [comment]
+1 on Flow - I use Atom IDE with Nuclide but it also has other support as well.

![screen shot 2016-12-13 at 4 14 35 pm](https://cloud.githubusercontent.com/assets/2925044/21164709/b7019248-c14f-11e6-866d-1aa264e20ee4.png)

**Comment by andreawyss** [comment]
We have 3 options:
A) **Do nothing**. Just keep on going and review this issue in 3 Months.
B) **Use Flow now**. Minimal impact. Give it a try and review this choice in 3 Months. Easy to revert.
C) **Use TS now**. Some impact and workarounds needed. Less easy to revert.

B) Is the pragmatic, low risk choice. 
It is not committing and easy to reverse.
It can also be used as an intermediate step to TS if in a few months we decide to go there.

**Comment by treshugart** [comment]
Now that I think about it, not being able to use future ES features is a pretty big thing. You can move at the speed of TC39 as opposed to TS.

**Comment by treshugart** [comment]
<img width="555" alt="screen shot 2016-12-14 at 12 15 36 pm" src="https://cloud.githubusercontent.com/assets/136556/21166022/0bf6d126-c1f7-11e6-9b24-5ab0bd445b2c.png"> VSCode also has official support.

**Comment by treshugart** [comment]
We've given TS a try, so why don't we give Flow a try. I'm going to close this as we'll only keep it as record of the decision being made. I don't think we need to create any issues for converting things and we should probably do it over time.

**Comment by Hotell** [comment]
> Now that I think about it, not being able to use future ES features is a pretty big thing. You can move at the speed of TC39 as opposed to TS.

?? You can ofc use future features, both ts and Babel support stage 2, so this statement is falsy

**Comment by Hotell** [comment]
> I use WebStorm 2016.3.1 and it has Flow support

Haha yes it has and it sucks big time. Even with jsx, no intellisense at all,  no autoimports and the list can go on and on
