### ISSUE TITLE
Component inheritance

### ISSUE THREAD

**Issue by ab335** [skatejs/skatejs#973]
The documentation does not indicate if component inheritance can be done with Skatejs.

Is it possible for a component at definition time to inherit the default props, methods, hooks, etc from another component or to overwrite them ?

In other words, can _x-hello-plus_ extend _x-hello_ ?

```javascript
var xHello = customElements.define('x-hello', class extends skate.Component {
  static get props () {
    return {
      name: { attribute: true }
    };
  }
  renderCallback () {
    return skate.h('div', `Hello, ${this.name}`);
  }
});

customElements.define('x-hello-plus', class extends xHello {
  renderCallback () {
    return skate.h('div', `Hello Plus, ${this.name}`);
  }
});
```

Thanks for the nice repository.

**Comment by andreawyss** [comment]
Yes you can

**Comment by treshugart** [comment]
Raised a quick #974 to address this.
