### ISSUE TITLE
Consider attribute naming with new prop declaration format

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#975]
We now have the following format for declaring properties ([original comment](https://github.com/skatejs/skatejs/issues/838#issuecomment-263161428)):

```js
// boolean (my-prop)
myProp: { attribute: true }

// string (same as bool)
myProp: { attribute: 'my-prop' }

// two-way (same as string, bool)
myProp: {
  attribute: {
    // can be boolean
    source: true,

    // or string
    target: 'my-prop'
  }
}

// one-way (attr -> prop)
myProp: {
  attribute: { source: 'my-prop' }
}

// one-way (prop -> attr)
myProp: {
  attribute: { target: 'my-prop' }
}
```

In order to be consistent with the shortened `prop` option, it may be good to follow the pattern for the `attribute` option, by using the shortened form `attr` in the property declaration - i.e.

```js
myProp: {
  attr: {
    source: true,
    target: 'my-prop'
  }
}

// et al
```

@andreawyss did also propose an [alternative solution](https://github.com/skatejs/skatejs/issues/720#issuecomment-266932136) where `attr: true` would be a shorthand for typing `attribute: { source: true }`.

See also #838, #720

**Comment by marcoms** [comment]
@andreawyss - from what I understood from @treshugart's proposal, `attribute: true`  is itself a shorthand for `attribute: { source: true }`, so the benefits of the `attr` shorthand you suggested would only be a few characters shaved off no? Correct me if I'm misinterpreting. I'm hesitant about the idea of having two semantically similar/identical names (`attr`, `attribute`) meaning different things, also increasing the size of our API.

**Comment by andreawyss** [comment]
@marcoms ```attribute: true``` creates a 2-way link (source and target)
```attr: true``` will create 1-way source link (most common usecase)
```reflect: true``` will create 1-way target link
Since 2-way link should be rarely used one could think about deprecating ```attribute``` in favor of just using ```attr``` and ```reflect```.
In those few cases where a 2-way link is desired one would specify both options.

**Comment by treshugart** [comment]
I don't think it's a good idea to have `attribute: true` and `attr: true` do two different things. Having `reflect` as short-hand might be good but I'd prefer to only have one way of doing it. It's not hard to abstract and I think it'd be an edge case, anyways. I'd prefer to keep edge-cases out of the core lib moving forward.

Some ways to abstract it:

```js
import { prop } from 'skatejs';
const twpWayAttr = prop.create({ attribute: true });
const oneWayAttr = prop.create({ attribute: { source: true } });
// etc...
```

**Comment by marcoms** [comment]
I think with `prop.create()` its simple and easy enough for users to make their own convenience functions if they really want to have them. It also falls into the "one obvious way to do things" philosophy quite nicely, if that's something we want.

**Comment by vascofernandes** [comment]
Give me **one** clear way of doing things. Just one. No short cuts. 
Less framework API surface, less framework code, less confusion.

**Comment by andreawyss** [comment]
Let's just close this issue. And keep API as it is now.

**Comment by marcoms** [comment]
Well, regarding the fundamental point of renaming `attribute` to `attr`, consistent with `prop` and `skate.props`, are there any thoughts/objections on this?

(goes without saying that the rename would be pushed for 5.0, unless we make `attr` an alias of `attribute`, and deprecate `attribute`)

**Comment by andreawyss** [comment]
prop is consistent with React naming. 
attribute is consistent with DOM naming. 
I feel the current names are fine and there is no need to shorten attribute to attr. 
I let you or @treshugart close this issue.

**Comment by treshugart** [comment]
Let's just keep the API as is. I think if we had a top level `attributes` configuration, then `attrs` would make sense, but it doesn't really hurt my eyes to have `attribute` as a sub-config of `props`, especially since it is consistent with DOM naming conventions (which doesn't really have a convention for properties, as it's based on attributes mostly).
