### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by QiuKejian** [skatejs/skatejs#976]
Uncaught ReferenceError: process is not defined
    at deprecated.js:2
    at root (index.js:4)
    at index.js:5

**Comment by andreawyss** [comment]
@QiuKejian Please try version 4.4.1. Thank you

**Comment by Qiu-Kejian** [comment]
@andreawyss 
Hello. I tired 4.4.1. It seems still not working.

Uncaught ReferenceError: process is not defined
    at is-production.js:1
    at root (index.js:4)
    at index.js:5


![image](https://cloud.githubusercontent.com/assets/16420190/21209910/98660c30-c2ba-11e6-9613-2be308908e46.png)

**Comment by Qiu-Kejian** [comment]
Is this because of "use strict"?

**Comment by treshugart** [comment]
Needs to be `typeof process !== 'undefined'`.

**Comment by treshugart** [comment]
Fixed in #979.

**Comment by treshugart** [comment]
I did changed a bit in that PR. Will annotate.

**Comment by andreawyss** [comment]
@QiuKejian Please try version 4.4.2. Thank you
