### ISSUE TITLE
Deprecated warnings are not shown in the console

### ISSUE THREAD

**Issue by andreawyss** [skatejs/skatejs#981]
We need SkateJS users to become aware of all the static methods that we deprecated.
Only when using a minified bundle we can suppress these deprecated warnings. 

Currently DEBUG is only true when we run our Karma unit tests.

**Comment by treshugart** [comment]
I believe this should be resolved now? In a recent updated I've opted to use `process.env.NODE_ENV` since Webpack 2 handles that automatically, thus simplifying it for us. I've checked the `dist` bundles and this should be fixed now. If I've closed this in error, please reopen :)
