### ISSUE TITLE
Can't coerce newValue base on oldValue

### ISSUE THREAD

**Issue by Qiu-Kejian** [skatejs/skatejs#983]
Hello, every one.

In case, I am using "static get props {} " to define a property that is an object which itself include 2 or more properties.  Then it would be nice if I can do something as below.
Right?
`
static get props {
    myProp: {
        default: { a: 1, b: 1},
        coerce: (newValue, oldValue) => {
            const { a = oldValue.a, b = oldValue.b } = newValue;
            return {a, b};
        }
    }
}
`

**Comment by treshugart** [comment]
Can you provide a concrete use-case for this? It's not immediately clear to my why this would be useful. Thanks :)

**Comment by treshugart** [comment]
Ahh right, so basically you want to merge the previous value with the new value? This could potentially be unexpected for the consumer. To get around this you can do something like `elem.prop = { ...elem.prop, ...{ updated: true } }`.

I really want to keep each feature in prop definitions as simple as possible and free from side effects. Thanks for raising the issue, though :)
