### ISSUE TITLE
Depending on props in connectedCallback

### ISSUE THREAD

**Issue by thepian** [skatejs/skatejs#985]
I have one custom element 'thread' render another 'block'. Block depends on the ID attribute, so since it isn't there in the constructor, I get it in connected. That works fine for elements in the page, but not when it is rendered dynamically by 'thread'. Attribute ID is blank in connectedCallback, but is set in rendererCallback. The connectedCallback happens when the element is created and appended in elementOpen rather than in elementClose when it would be most useful.

It seems quite inefficient to have to calculate everything in renderCallback when it will not change. Might connectedCallback be delayed until properties are done being set?

**Comment by treshugart** [comment]
Can you sketch out an example of what you're trying to do with code for a reduced use-case?

**Comment by thepian** [comment]
The code below is for a block that works as part of another master custom element. It is either rendered by the master element or put in the markup for the master element as part of server-side render.

```<master-el>
  <block-el id="1234">
</master-el>```

When rendered like this on the server the `id` will be present at connect, when rendered in the browser by the master custom element it is appended before attributes are set. So `this.blockTemplate` cannot be determined in connected.

The id of a block is required and doesn't change for the lifetime of a block. In this case I have opted to implement the one-time view update in the `attributeChangedCallback` rather than `connectedCallback` where it may not be set yet. 

If I need to depend on two required properties I would have to implement the dependency in the `attributeChangedCallback` and call a common method.

I think my solution is to make a Component mixin for supporting a `requiredCallback` that fires when all properties with a required flag are present and the element is connected.

```
    get props() {
        return { id: prop.string({ attribute: true }) };
    }

    static get observedAttributes() { return ['id']; }

    attributeChangedCallback(name, oldValue, newValue) {
        super.attributeChangedCallback(name, oldValue, newValue);
        switch(name) {
            case 'id':
                if (this.blockStats.newBlock /*&& Component.isConnected(this)*/) {
                    this.blockTemplate = incrementalTemplates.get(this.id);
                    this[ticker] = setInterval(this.renderTick.bind(this),2000);
                }
                break;
        }
    }

    renderCallback() {
        if (this.blockStats.shownBlocks < this.blockTemplate.statements.length) {
            setTimeout(() => {
                this.blockStats.pendingBlock = this.blockStats.shownBlocks;
                this.constructor.renderer(this);
            },800);
        }

        return this.blockTemplate.statements.map((statement,index) => {
            return this.statementRenderer(statement, { shown: index < this.blockStats.shownBlocks, pending: index ==this.blockStats.pendingBlock });
        });
    }
```

**Comment by treshugart** [comment]
It looks like you can do all of this in `renderCallback()`:

```js
import { Component, props } from 'skatejs';

class MyComponent extends Component {
  props = {
    id: prop.string({ attribute: true })
  }
  renderCallback ({ id }) {
    if (!id) {
      return;
    }

    if (!this.blockTemplate) {
      this.blockTemplate = incrementalTemplates.get(id);
    }

    if (this.blockStats.shownBlocks < this.blockTemplate.statements.length) {
      this.blockStats.pendingBlock = this.blockStats.shownBlocks;
    }

    return this.blockTemplate.statements.map((statement, index) => {
      return this.statementRenderer(statement, {
        shown: index < this.blockStats.shownBlocks,
        pending: index === this.blockStats.pendingBlock
      });
    });
  }
}
```

Since everything is dependent on `id` then render will be called when it exists and you just need to guard its existence. You can add any other required props there and memoize anything that you only need to get once. This allows it to be resilient to `id` changes and removals, too.

**Comment by thepian** [comment]
I think I have to read the SkateJS code. I don't get this sort of behaviour where render gets called automatically. I need to implement attributeChangedCallback to get object property updates and render calls when attributes are changed.

**Comment by thepian** [comment]
Actually I just tried your example

**Comment by thepian** [comment]
The approach does bake a lot into the renderCallback and gives it side-effects. That doesn't seem nice.

**Comment by treshugart** [comment]
The side-effects are for caching purposes. You don't really need them, though, or that can be abstracted away from `renderCallback()`. I'm open to better suggestions. That said, there's no side-effects in terms of what render does to the DOM, it's only in what you're storing as properties.
