### ISSUE TITLE
consolidate dependencies

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs#986]
What I would love to see is following package.json with proper dependency resolution.

Only real "dependency" is "incremental-dom" which I think should be as peer dependency ( similar how Angular handles RxJs ). So it should be consumer responsibility to install proper version

```diff
{
...
+  "peerDependencies": {
+   "incremental-dom": "^0.4.1",
+   },
  "dependencies": {    
-  "incremental-dom": "0.4.1",
-  "rollup-plugin-replace": "^1.1.1",
-  "window-or-global": "1.0.1"
  },
  "devDependencies": {
+  "rollup-plugin-replace": "^1.1.1",
+  "window-or-global": "1.0.1"
    "birdpoo": "0.x",
    "gitbook-cli": "^2.3.0",
    "gitbook-plugin-jsfiddle": "^1.0.0",
    "react": "15.4.1",
    "react-dom": "15.4.1",
    "skatejs-build": "12.x",
    "skatejs-web-components": "5.x"
  },
...
}
```

If you're ok with that I'll submit PR @treshugart

**Comment by thepian** [comment]
To my knowledge the source depends on `window-or-global`, so your change wouldn't work.

**Comment by Hotell** [comment]
oh, right that's unfortunate, updating to 

```diff
{
...
+  "peerDependencies": {
+   "incremental-dom": "^0.4.1",
+   },
  "dependencies": {    
-  "incremental-dom": "0.4.1",
-  "rollup-plugin-replace": "^1.1.1",
    "window-or-global": "1.0.1"
  },
  "devDependencies": {
+  "rollup-plugin-replace": "^1.1.1",
+  "window-or-global": "1.0.1"
    "birdpoo": "0.x",
    "gitbook-cli": "^2.3.0",
    "gitbook-plugin-jsfiddle": "^1.0.0",
    "react": "15.4.1",
    "react-dom": "15.4.1",
    "skatejs-build": "12.x",
    "skatejs-web-components": "5.x"
  },
...
}
```

**Comment by treshugart** [comment]
Not sure why it's "unfortunate". Is there *really* a problem with this? Eventually I'd like to [decouple incremental dom](https://github.com/skatejs/skatejs/issues/927). Then, it can become an optional dependency, possibly.

**Comment by Hotell** [comment]
haha nothing really @treshugart I used probably wrong word  :)

**Comment by Hotell** [comment]
So can I proceed? this will be a BC

**Comment by treshugart** [comment]
It would be a breaking change. I'd rather do idom at the same time as decoupling. The `window-or-global` dep is like one line or something, so I don't see the value in having it as a peer dep, really. The rollup plugin should have been a dev dep from the beginning. I'm still getting used to yarn.

**Comment by Hotell** [comment]
kk, sounds good
