### ISSUE TITLE
Support common use setAttribute(.., null)

### ISSUE THREAD

**Issue by thepian** [skatejs/skatejs#987]
From the bad old days I think a lot of people learned not to use `removeAttribute`, but instead call setAttribute with null. If you do that however it will be coerced with property types. So you get `"null"` instead.

**Comment by treshugart** [comment]
We don't override `setAttribute()` so props will get the browser-coerced value, unfortunately. I don't think this is something we can - or really should - fix. Is there something in particular causing this issue for you?

**Comment by thepian** [comment]
I was not talking about overriding setAttribute. I called `setAttribute(.., null)` out of habit and got a coerced value in `attributeChangedCallback` that was "null" rather than null.

I have also noticed that when I define `attributeChangedCallback` and `observedAttributes` the props don't seem to be set on the element.

**Comment by andreawyss** [comment]
Make sure that in attributeChangedCallback you call super.attributeChangedCallback
The docs need to remind to call super when overriding a ....Callback.

**Comment by thepian** [comment]
I do call the super method, but the property doesn't seem to get set. And I do think the docs have that reminder.

**Comment by treshugart** [comment]
> I was not talking about overriding setAttribute. I called setAttribute(.., null) out of habit and got a coerced value in attributeChangedCallback that was "null" rather than null.

Yes, but in order to change native behaviour we'd need to override it. I don't think it's a good idea to change expectations here.

> I have also noticed that when I define attributeChangedCallback and observedAttributes the props don't seem to be set on the element.

`observedAttributes` need to mix with the super, if you define `props` because when you define `props` that have `{ attribute: true }` they will automatically observe the linked attribute.

Something like `return { ...super.observedAttributes, myNewObservedAttributes }` should work.

**Comment by thepian** [comment]
In the code below I have to set the `this.actionTaken` and `this.actionStarted`, as they are not set automatically by the super method. What am I doing wrong?

```
    get props() {
        return {
            blockId: prop.string({ attribute: true }),
            actionStarted: prop.string({ attribute: true }),
            actionTaken: prop.string({ attribute: true })
        };
    }

    static get observedAttributes() {
        return super.observedAttributes.concat('block-id','action-started','action-taken');
    }

    attributeChangedCallback(name, oldValue, newValue) {
        super.attributeChangedCallback(name, oldValue, newValue);
        switch(name) {
            case 'block-id':
                this.blockId = newValue; // is this automagically set?
                this.blockTemplate = incrementalTemplates.get(this.blockId);
                    // this[ticker] = setInterval(this.renderTick.bind(this),1300);
                break;
            case 'action-taken':
                this.actionTaken = newValue;
                this.constructor.renderer(this);
                break;
            case 'action-started':
                this.actionStarted = newValue;
                this.constructor.renderer(this);
                break;
        }
    }
```

**Comment by thepian** [comment]
Is the original issue perhaps an issue with the custom elements shim support for the attributeChangedCallback?

**Comment by treshugart** [comment]
You need `static get props()` (note *static*).
