### ISSUE TITLE
Native ES Classes doesn't work

### ISSUE THREAD

**Issue by mizchi** [skatejs/skatejs#988]
I use minimum babel transformers to work with chrome.

My trying code.

```js
/* flow */
import "skatejs-web-components";
import {Component, h} from "skatejs";

class Hello extends Component {
  static get props () {
    return {
      name: { attribute: true }
    };
  }
  renderCallback () {
    return h("div", `Hello, ${this.name}`);
  }
}
customElements.define("x-hello", Hello);
```

It works with this .babelrc and webpack2.

```
{
  "plugins": [
    "transform-es2015-classes"
  ]
}
```

Without it, I encounter this error

```
Uncaught TypeError: Class constructor Hello cannot be invoked without 'new'
    at HTMLElement.StandInElement (eval at <anonymous> (main.js:17), <anonymous>:130:24)
    at CustomElementRegistry.window.customElements.define (eval at <anonymous> (main.js:17), <anonymous>:144:18)
    at Object.<anonymous> (main.js:17)
    at __webpack_require__ (main.js:17)
    at main.js:17
    at main.js:17
```

**Comment by moebiusmania** [comment]
hi!
same issue, by reading the docs I was thinking that the line

```js 
import "skatejs-web-components";
```

was optional if your browser supports natively the v1 specs (latest Chrome) or if you plan to load the polyfills "globally" (by script tag).

So this is error (```Uncaught TypeError: Class constructor Hello cannot be invoked without 'new'```) is a bug or I haven't understand correctly?
tnx

**Comment by treshugart** [comment]
@mizchi the original issue you posted here is because you're consuming the transpiled source which is pointed to in the package.json's `main` field. You can consume `src/` directly, but that's not covered by our API versioning, so use at your own risk. More info on the issues around transpiled classes are explained at https://github.com/webcomponents/custom-elements#known-issues. I've updated the docs to clarify this.

**Comment by treshugart** [comment]
I created #992 so that we can offer a native class-based version to get around the native issues while still not making you worry about what other ES features we're using that you may have to transpile.

**Comment by moebiusmania** [comment]
@treshugart thanks
