### ISSUE TITLE
Component sets attribute to default prop value

### ISSUE THREAD

**Issue by zzarcon** [skatejs/skatejs#989]
Having a component like: 

```javascript
class Tags extends Component {
  static props = {
    delimiter: prop.string({attribute: true, default: ' '})
  }

  renderCallback() {
    //...  
  }
}

customElements.define('sk-tags', Tags);
```

When used as:

```html
<sk-tags />
```

It sets `delimiter` to the default value
![tags4](https://cloud.githubusercontent.com/assets/1194982/21625288/3ad30888-d20b-11e6-88a7-ba024252f598.png)

@treshugart came across this bug couple days ago and told me that was not the expected behavior, you can see it live [here](https://zzarcon.github.io/skatepark.js/?selectedKind=Tags&selectedStory=Enter%20a%20space-separated%20list%20of%20tags&full=0&down=0&left=1&panelRight=0) and the actual component code [here](https://github.com/zzarcon/skatepark.js/blob/master/packages/tags/src/index.jsx#L13).

Thanks!

**Comment by treshugart** [comment]
Skate definitely used to not set the attribute if the prop was set to the default value. This is a bug.

**Comment by zzarcon** [comment]
I think [this](https://github.com/skatejs/skatejs/blob/master/src/util/attributes-manager.js#L77) might be the cause of the issue? 

```javascript
_syncAttrValue (name, value) {
    const currAttrValue = toNullOrString(this.elem.getAttribute(name));
    if (value !== currAttrValue) {
      if (value === null) {
        this.elem.removeAttribute(name);
      } else {
        this.elem.setAttribute(name, value);
      }
    }
  }
```

We are always setting the attribute if its different than the current value, which will be always true when is the default since the user did not specified a value. Maybe just checking for that value will do the trick?

```javascript
if (currAttrValue && value !== currAttrValue) {
```

**Comment by treshugart** [comment]
I was looking into this and decided we should keep the new behaviour and release a breaking change that removes the `initial` prop. I raised #991 for this.
