### ISSUE TITLE
Create fluent interface for props

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#990]
I think we should create a fluent interface for defining props. For example:

```js
props = {
  test: prop.string().from().init('value')
}
```

Would be the same thing as:

```js
props = {
  test: prop.string({
    attribute: { source: true },
    default: 'value'
  })
}
```

**Comment by thepian** [comment]
Will that include a way to extend existing types with new attributes such as `required: <boolean>` ?

It might be more concise, but doesn't it add more code and less readability without any additional functionality?

**Comment by andreawyss** [comment]
I see this as low priority.  We should review this at a later time.

**Comment by treshugart** [comment]
@andreawyss Agree. I generally add issues as I think of them without any reservation that they will be implemented.

**Comment by Hotell** [comment]
is this still a thing since https://github.com/skatejs/skatejs/issues/1073  ?

If not we can close

**Comment by treshugart** [comment]
@Hotell it's less of a need. Could still do stuff like `isRequired` etc if we wanted to but not high priority. Will close for now.
