### ISSUE TITLE
Remove "initial" option from props

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#991]
When the attribute manager was added it seems that the `default` option broke and now *always* sets the corresponding attribute even if the incoming property value is equal to the default value. I think this is okay moving forward, but since this is the case, the `initial` property is now redundant. Moving forward if you want to set an initial prop, you can do it in the constructor.

The original behaviour was always difficult because if you have default be a function, and it returns an array, the default value will always be different, thus set as an attribute.

**Comment by Hotell** [comment]
finally this will become a thing, high 5 for TS users! :)
```ts
@prop({
  type: Number
}) count = 20;
```

**Comment by treshugart** [comment]
Done in #1098.
