### ISSUE TITLE
Offer a dist with native class support

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#992]
References #988.

If you're using native ES classes, you need a way to consume the untranspiled base `Component` class. However, since the consumer shouldn't have to worry about what ES features we're using, we should still transpile all other features we use.

- [ ] Transpile to latest stable ES spec (currently ES2015)
- [ ] Transpile to `dist/es-next`
- [ ] The `module` field in the `package.json` is the only exposed API for the `es` entry point.
- [ ] Consuming `dist/es/index.js` directly is not supported, the consumer should use `module`.
- [ ] Existing `main` should be moved to `dist/es-base`.
- [ ] Remove note in the README referencing this issue and add docs on how to consume the new file

Open questions:

- [ ] Should we still offer a minified file?

**Comment by Hotell** [comment]
consider this ( which is kind of standard nowadays )
- `bundles/skate.umd.js` - UMD bundle -> `"main":"bundles/skate.umd.js"`
- `lib/esm/index.js` - es6 ( non transpiled and not bundled ) -> `"module":"lib/esm/index.js", "jsnext:main":"lib/esm/index.js"`
- `lib/fesm/skate.js` - bundled es6 ( [Flat Ecmascript modules](https://github.com/angular/angular/blob/master/CHANGELOG.md#flat-es-modules-flat-esm--fesm) - pioneered by Angular team - top notch parse performance and smaller payload - achievable only via Rollup ) -> `"es2015":"lib/fesm/skate.js"`

**Comment by treshugart** [comment]
So, in #1075, I implemented NWB. I was having a build issue and just said f-it and it only took a few mins. On the plus side, it's removed a lot of maintenance and it added an `es` dir to the published package, which has es5 + esm files. Along side it, it also has `lib` for commonjs es5 and `umd` for, you guessed it, umd.

I think this is a good compromise for now as we get to offload the build choices to another (popular) library. Will close for now and we can raise issues to iterate on that front from there.

**Comment by Hotell** [comment]
k I left some comments in that PR
