### ISSUE TITLE
Consider adding childrenChangedCallback

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#995]
Related:

- https://github.com/w3c/webcomponents/issues/619
- https://github.com/matthewp/bram#childrenconnectedcallback
- https://twitter.com/treshugart/status/816772654174650368

Deets:

- The `MutationObserver` should be set up in the `constructor`.
- Subtrees shall *not* be observed.
- Character data should be observed, but may not need the `characterData` option (`childList` might do).

Gist of implementation at https://gist.github.com/treshugart/6bb7093a709b5cf1d52bc67a89c70709

**Comment by thepian** [comment]
On a related note how would `childContextProps` fit in as ween in React.

**Comment by thepian** [comment]
Here is a tutorial: http://reactkungfu.com/2016/01/react-context-feature-in-practice/

Context is something an ancestor sets to allow all descendants to access shared properties. It is a concept used when using React with Redux as the ancestor provides the store on the context and the descendants connects the state to the store.

You might also find this interesting to think about: https://jaysoo.ca/2015/06/09/react-contexts-and-dependency-injection/

I've been thinking about extensions to the Skate functionality lately and how to keep the codebase small. I think these sort of improvements should be mixins/addons so the core stays at essentially custom-el + s-dom + i-dom

While I'm not a huge fan of how you must currently do decorators in JavaScript, I think they are the right tool for offering additional Reactive APIs. [Redux.connect](http://stackoverflow.com/questions/32646920/whats-the-at-symbol-in-the-redux-connect-decorator) is ready for the decorator syntax, but can be used as is.

**Comment by treshugart** [comment]
Oh right, react context. I thought that was a callback or something and couldn't find anything on it. It's worth noting that [context in React is experimental and not generally recommended](https://facebook.github.io/react/docs/context.html#why-not-to-use-context).

I'd be a fan of adding `childrenChangedCallback()` and context as mixins, rather than in the core. I'm not sure it's worth creating a separate repository yet, but it could be worth considering. I'm worried less about size moving forward as Webpack 2 and Rollup do tree-shaking and am more worried about functional separation and ease of use for consumers.

**Comment by thepian** [comment]
Contexts are however very helpful if you want something like sharing a Flux/Redux store among all components of the application; Or a branch of it. Another use case is translation, where in larger bodies of translation you might want to have different translations of the same sentence.

**Comment by treshugart** [comment]
I think context is orthogonal to `childrenChangedCallback()`. Added an issue to explore context in https://github.com/skatejs/skatejs/issues/1014.

**Comment by treshugart** [comment]
https://gist.github.com/treshugart/6bb7093a709b5cf1d52bc67a89c70709

**Comment by Hotell** [comment]
This may be unrelated but how should we get projected slotted contents once after elemenent is connected - initialisation:

Demo ( Eric Bidelman Tabs ) : http://codepen.io/Hotell/pen/GWmMNm?editors=1010

I know it should be chopped down to components for tab/pane etc, just wanted to get your opinion how to do it properly
-> in the demo I have to call `setTimeout` from `connectedCallback` which feels very dirty to me, but I didn't found other way around. Also tried to use `childrenChangedCallback` but on init it wont be triggered because those projected content is already rendered so no mutation is triggered.

any ideas?

**Comment by treshugart** [comment]
In the [gist I linked to](https://gist.github.com/treshugart/6bb7093a709b5cf1d52bc67a89c70709) it calls the callback when connected, so it accounts for children already on the element when it's connected.

**Comment by Hotell** [comment]
I know, but what about my usecase ?

**Comment by treshugart** [comment]
> I know, but what about my usecase ?

I can't really tell how you codepen should be working. `childrenChangedCallback()` changes when the light DOM changes, so it has nothing to do with `renderCallback()`. What should happen, in Skate at least, `childrenChangedCallback()` should set `props` and that should trigger a render. There's a lot of code in that codepen I had to sift through to see what's happening. Can you create a simplified reproduction of your problem?

**Comment by Hotell** [comment]
this is already baked it  via `withChildren()` mixin, closing...
