### ISSUE TITLE
'DEBUG is not defined' on Chromium and 'NS_ERROR_NOT_IMPLEMENTED' on FF 50.1.0

### ISSUE THREAD

**Issue by micahscopes** [skatejs/skatejs#998]
The last time everything worked was a few months back.  I think I was on skate 4.0.2 and skate-web-components 2.x.  Those versions stopped working for Firefox 50.1, where I'm getting `NS_ERROR_NOT_IMPLEMENTED` when the polyfill tries to call customElements.

I tried upgrading to skate.js 4.5.0 and skate-web-components 5.0.0.  

I still get the same error on Firefox.  On chromium I get a whole bunch of errors like this:
```
Uncaught ReferenceError: DEBUG is not defined ...
```

Here's a branch with my examples and source: https://github.com/micahscopes/tangled-web-components/tree/buggy_skate_4_5_upgrade

Check `examples/index.html`, etc.  Building is done with `npm run transpile`.

**Comment by treshugart** [comment]
For reference, we can view the problems on https://micahscopes.github.io/tangled-web-components/examples/.

**Comment by micahscopes** [comment]
As for the 'NS_ERROR_NOT_IMPLEMENTED' on FF 50.1.0... It is completely unrelated.  And I have a minimal working example, it's the counter example from the documentation, updated to run the latest versions of skatejs and skatejs-web-components https://jsfiddle.net/eukhtw7z/1/: https://jsfiddle.net/eukhtw7z/1/

**Comment by treshugart** [comment]
Hmm, I loaded that up in Firefox and it is working.

**Comment by micahscopes** [comment]
Firefox 50.1.0?

**Comment by micahscopes** [comment]
P.s. I'm using Arch Linux Firefox 50.1.0 from the arch repo. But even on
the development version I had trouble. I think this could be a bug in how
the web-components polyfill detects customElements support, cause the error
seems to have to do with the polyfill calling customElements.define()...
But Firefox doesn't do that!

**Comment by treshugart** [comment]
Interesting. I'm going to update the web components stuff soon (ish), but maybe it's worth trying the latest polyfills (from master) to see if that resolves it for you?

**Comment by micahscopes** [comment]
@treshugart I could try that.  Here's a related ticket I opened: https://github.com/WebReflection/document-register-element/issues/94

**Comment by treshugart** [comment]
No, `skatejs-web-components` uses the canonical fill at [webcomponents/custom-elements](https://github.com/webcomponents/custom-elements).

**Comment by WebReflection** [comment]
FWIW I couldn't reproduce @micahscopes problem using same configuration (Firefox on Arch Linux)
https://github.com/WebReflection/document-register-element/issues/94#issuecomment-271160528

All green for me (or at least my test page)

**Comment by WebReflection** [comment]
Actually, I've tried the [skate test page](https://micahscopes.github.io/tangled-web-components/examples/) and indeed it has errors (although still unrelated with my poly)

**Comment by micahscopes** [comment]
Ooh... a clue!  I had webcomponents and webcomponents.customElements *both enabled* in Firefox 50.1...  When I disabled them, things started working again!

**Comment by treshugart** [comment]
Hey @micahscopes any progress on this? In a recent update, we've started using `process.env.NODE_ENV` instead of `DEBUG`, just FYI. This is internal, though, and isn't present in the `dist` builds.

**Comment by micahscopes** [comment]
I'm not experiencing either of these errors anymore, although now I'm having new problems!  I'll make new tickets for new problems :)
