### ISSUE TITLE
Can't set shadow dom css style ?

### ISSUE THREAD

**Issue by marxtseng** [skatejs/skatejs#999]
[https://jsbin.com/mupera/edit?html,css,js,output](https://jsbin.com/mupera/edit?html,css,js,output)
[https://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/](https://www.html5rocks.com/en/tutorials/webcomponents/shadowdom-201/)

> ES6 / Babel

```
customElements.define('x-hello', class extends skate.Component {
  static get props () {
    return {
      name: { attribute: true }
    };
  }
  renderCallback () {
    return [
      skate.h('style', '.message {color:red}'),
      skate.h('span', {class:'message'}, `Hello, ${this.name}`)
    ];
  }
});
```

> CSS

```
x-hello {
  padding: 9px 12px;
  border: 1px solid red;
}

x-hello::shadow .message {
  color: blue;
}

body /deep/ .message {
  color: green;
}
```

**Comment by Hotell** [comment]
Hey @marxtseng . That is old shadow Dom spec V0, which is unsupported. 

You cannot penetrate shadow boundary anymore, instead you can use css variables to do that. 

Check this beautiful article https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom#styling

**Comment by Hotell** [comment]
Feel free to ask more if something isn't clear, otherwise pls close this issue. thanks! 👍
